import type { ChapterContent } from './types';

export const chapter: ChapterContent = {
  n: 2,
  title: 'Renal circulation and glomerular filtration rate',
  thesis:
    'Filtration is governed by Starling forces, but the glomerulus is unique in sitting between two arterioles, so the kidney can change glomerular pressure and plasma flow independently. Because filtration normally runs to equilibrium, plasma flow is itself a determinant of GFR. Autoregulation and tubuloglomerular feedback keep GFR steady day to day; in effective volume depletion, angiotensin II, noradrenaline and the protective vasodilator prostaglandins take over — which is exactly where ACE inhibitors and NSAIDs cause trouble.',
  concepts: [
    {
      heading: 'A capillary bed built for filtration',
      body: [
        'The kidneys receive about a fifth of the cardiac output — per gram, four times the flow of liver or exercising muscle. Blood passes through the interlobar, arcuate and interlobular arteries to the afferent arteriole, the glomerular capillaries, the efferent arteriole, and then a second capillary bed: the peritubular capillaries around cortical tubules, or, from juxtamedullary glomeruli, the vasa recta that dive into the medulla.',
        'The circulation therefore does three jobs: it filters (GFR sets how much solute and water enters the tubule), it takes back what the cortical tubules reabsorb (peritubular Starling forces modulate proximal reabsorption), and, through the vasa recta, it supplies the medulla without washing away the concentration gradient.',
      ],
      cite: { rose: [2], evidence: 'physiology' },
      route: '/nephron',
    },
    {
      heading: 'The filtration barrier: size and charge',
      body: [
        'Filtrate crosses three layers: fenestrated endothelium, the glomerular basement membrane (a mesh of type IV collagen filled with laminin, nidogen and anionic heparan sulfate proteoglycans), and the podocytes whose foot processes are bridged by the slit diaphragm.',
        'Small solutes up to the size of inulin (MW ~5200) pass freely; myoglobin (17,000) less so; albumin (69,000, effective radius ~36 Å) hardly at all. Most pores are small (~42 Å), with a tiny population (<0.5%) of large pores that can pass IgG. Cellular layers, not the basement membrane alone, provide most of the restriction — the isolated GBM is far leakier than the intact wall, and mutations in nephrin, a slit-diaphragm protein, cause congenital nephrotic syndrome.',
        'Negative charge adds a second barrier: anionic dextrans (and albumin, a polyanion) are filtered far less than neutral molecules of the same size. The book notes that charge selectivity may matter less than once believed.',
        'In glomerular disease, the clearance of small molecules actually falls (fewer functioning pores, less surface area) while larger proteins leak through an increased number of large pores — so heavy proteinuria and a falling GFR go together. Minimal change disease shows reduced clearance at all sizes, pointing toward a charge defect.',
      ],
      points: ['Alport syndrome: abnormal type IV collagen (usually the X-linked α5 chain, COL4A5)', 'About 40% of plasma calcium is albumin-bound and therefore not filtered'],
      route: '/glomerular',
      cite: { rose: [2], evidence: 'physiology', refs: ['scott2015', 'deen2001'] },
    },
    {
      heading: 'The mesangium',
      body: [
        'Mesangial cells sit between the capillary loops. They have contractile filaments, contract in response to angiotensin II (reducing filtration surface area), make prostaglandins, and release and respond to cytokines. Circulating macrophages also move through the mesangium, clearing macromolecules that enter the capillary wall — possible because most of the mesangium is separated from the blood only by fenestrated endothelium. These properties explain mesangial proliferation and matrix expansion in immune-mediated glomerular disease.',
      ],
      cite: { rose: [2], evidence: 'physiology' },
    },
    {
      heading: 'The renin–angiotensin system and the glomerulus',
      body: [
        'Juxtaglomerular cells in the afferent arteriole make renin. Renin cleaves angiotensinogen (from the liver) to angiotensin I, which angiotensin-converting enzyme (in lung, endothelium and the kidney itself) converts to angiotensin II. Local tissue systems — in kidney, vessel wall, adrenal and brain — can make angiotensin II independently, so plasma renin can underestimate tissue activity; proximal tubular fluid angiotensin II concentrations far exceed plasma levels.',
        'Angiotensin II raises blood pressure (systemic vasoconstriction) and retains sodium (directly in the early proximal tubule via Na⁺/H⁺ exchange, and through aldosterone). AT1 receptor blockade suggests it may drive 40–50% of reabsorption in the S1 segment.',
        'At the glomerulus it constricts both arterioles, but the efferent — narrower to begin with — up to three times as much. Renal blood flow falls while glomerular pressure rises, protecting GFR when perfusion is threatened. It also contracts the mesangium (lowering filtration surface area) and sensitises the afferent arteriole to tubuloglomerular feedback. Its net effect on GFR therefore depends on the setting: GFR-preserving in renal artery stenosis, GFR-reducing in some hypertensive and heart-failure states.',
        'Angiotensin II simultaneously stimulates the glomerulus to make vasodilator prostaglandins, which cap how far renal vasoconstriction can go. Because prostaglandins act only locally (they are destroyed in the lung) while angiotensin II acts systemically, the combination raises systemic pressure while preserving renal flow.',
      ],
      chain: ['↓ Renal perfusion / ↓ macula densa Cl⁻ / ↑ sympathetic (β₁)', '↑ Renin', '↑ Angiotensin II', 'Efferent ≫ afferent constriction', '↓ RBF but ↑ Pgc: GFR preserved', '↑ Proximal Na⁺ reabsorption + ↑ aldosterone', '↑ Renal prostaglandins limit the vasoconstriction'],
      route: '/raas',
      cite: { rose: [2], evidence: 'physiology' },
    },
    {
      heading: 'Three sensors control renin',
      body: [
        'Normally sodium intake is the main determinant of renin: a high intake expands volume and suppresses it; a low intake or any fluid loss stimulates it. Three sensors carry the signal: stretch receptors in the afferent arteriole (less stretch, more renin — mediated partly by calcium entry and prostacyclin); cardiac and arterial baroreceptors acting through renal sympathetic nerves and circulating catecholamines on β₁ receptors; and the macula densa.',
        'The macula densa reads chloride, not sodium, because its NKCC2 carrier is saturated by the sodium and potassium in tubular fluid but not by chloride. Raising delivered NaCl suppresses renin (probably through adenosine); lowering it stimulates renin (through COX-2-derived PGE₂). Sodium given with bicarbonate rather than chloride therefore barely suppresses renin.',
        'Loop diuretics block NKCC2 in the macula densa itself, so they stimulate renin directly, beyond the effect of volume loss. Thiazides act further downstream and do not.',
        'In hypovolaemia all three sensors fire together. Combined indomethacin and propranolol almost abolish the renin response — showing prostaglandins and β-adrenergic signalling are its main mediators.',
      ],
      chain: ['Volume loss', '↓ Afferent stretch + ↑ sympathetic tone + ↓ Cl⁻ uptake at macula densa', '↑ Renin'],
      route: '/raas',
      cite: { rose: [2], evidence: 'physiology', refs: ['carlstrom2015'] },
    },
    {
      heading: 'Starling forces and filtration equilibrium',
      body: [
        'GFR = LpS × [(Pgc − Pbs) − σ(πgc − πbs)]. The filtrate is protein-free, so πbs is zero and σ for protein is 1: GFR = Kf × (Pgc − Pbs − πgc). Normal GFR is about 95 ± 20 mL/min in women and 120 ± 25 in men — more than a thousand times the filtration of a muscle capillary per gram, because Kf is 50–100 times higher and the glomerular capillary pressure (~45 mmHg) is far higher.',
        'Along the capillary, hydraulic pressures barely change but oncotic pressure rises (from ~23 to ~35 mmHg) as protein-free fluid leaves. The net filtration pressure, ~13 mmHg at the afferent end, falls to zero before the efferent end: filtration equilibrium. In primates this happens after about 20% of the plasma has been filtered — matching the human filtration fraction (GFR 125, RPF 625 mL/min).',
        'Equilibrium has a crucial consequence: renal plasma flow becomes a determinant of GFR. If plasma flow falls 15% with Pgc unchanged, equilibrium is still reached after filtering 20% of it — so GFR falls 15%.',
        'The filtration fraction also sets the protein concentration of blood leaving the glomerulus, and therefore the oncotic pressure in the peritubular capillaries — a link to proximal reabsorption (chapter 3).',
      ],
      equation: 'nfp',
      route: '/gfr',
      cite: { rose: [2], evidence: 'physiology', refs: ['deen1972'] },
    },
    {
      heading: 'Two arterioles, two opposite effects',
      body: [
        'Pgc depends on aortic pressure and on the two arteriolar resistances. Afferent constriction transmits less pressure to the glomerulus: Pgc, GFR and RPF all fall. Efferent constriction holds blood back in the glomerulus: Pgc rises, but total renal resistance also rises so RPF falls.',
        'The arterioles account for about 85% of renal vascular resistance. Afferent tone moves GFR and RPF in the same direction; efferent tone moves them in opposite directions, so only efferent changes alter the filtration fraction.',
        'Because RPF is an independent determinant of GFR, efferent constriction has a biphasic effect: moderate constriction raises GFR (the rise in Pgc wins); severe constriction lowers RPF so much that GFR stops rising and can fall.',
        'The other Starling terms matter mainly in disease. Kf changes little normally, and a modest fall in it does not reduce GFR while filtration still reaches equilibrium — until disease (glomerulonephritis) reduces surface area enough to prevent equilibrium. Pbs rises with ureteral or intratubular obstruction. Plasma oncotic pressure rises with haemoconcentration in vomiting or diarrhoea.',
      ],
      chain: ['Efferent constriction', '↑ Pgc and ↑ filtration fraction', '↓ RPF', 'Moderate: ↑ GFR · Severe: GFR plateaus then falls'],
      route: '/arterioles',
      cite: { rose: [2], evidence: 'physiology' },
    },
    {
      heading: 'Autoregulation',
      body: [
        'GFR and RPF stay nearly constant across a wide range of arterial pressure, even in a denervated kidney. Because both are held in parallel, the effector must be the afferent arteriole: it constricts as pressure rises, keeping Pgc and flow steady, and dilates as pressure falls.',
        'Protection runs out below a mean pressure of roughly 70 mmHg; GFR then falls with pressure and ceases at 40–50 mmHg.',
        'Three mechanisms contribute: the myogenic stretch response of the afferent arteriole (the efferent lacks it, perhaps because it lacks voltage-gated calcium channels); tubuloglomerular feedback, especially when pressure rises; and angiotensin II, whose efferent constriction supports GFR when pressure falls substantially. Blocking angiotensin II leaves autoregulation of RBF intact but that of GFR impaired.',
        'Clinical consequence: with bilateral renal artery stenosis (or stenosis to a solitary kidney), glomerular pressure depends on angiotensin II. An ACE inhibitor can reduce GFR — mildly in up to half of patients, occasionally severely — and diuretic-induced volume depletion makes this more likely. In heart failure, ACE inhibitors improve output and survival yet GFR falls in about a third, especially with low diastolic pressure and high diuretic doses.',
      ],
      route: '/autoregulation',
      cite: { rose: [2], evidence: 'physiology' },
    },
    {
      heading: 'Tubuloglomerular feedback',
      body: [
        'Raising the flow to the macula densa lowers that nephron’s GFR, to about half at maximum. The macula densa senses chloride uptake through NKCC2; the effector is afferent constriction. Adenosine (from ATP consumed by increased NaCl transport) is the favoured mediator, with contributions from thromboxane and ATP, while macula densa nitric oxide blunts the response — and resets it on a high salt intake. Angiotensin II is permissive, sensitising the afferent arteriole.',
        'Loop diuretics block the sensing step and so blunt feedback. The same adenosine signal explains how the macula densa both constricts the afferent arteriole and suppresses renin when delivery rises.',
        'The purpose is to protect the distal nephron, whose total reabsorptive capacity is small, from being overwhelmed by a sudden rise in delivery — it may be macula densa flow, rather than GFR, that is really being regulated.',
        'Two clinical corollaries: in acute tubular necrosis, impaired proximal and loop reabsorption raises macula densa delivery, and feedback may contribute to the fall in GFR; acetazolamide reduces GFR the same way. Conversely, glucosuria impairs feedback, which may contribute to the large losses in diabetic ketoacidosis and hyperosmolar states.',
      ],
      chain: ['↑ Perfusion pressure → ↑ GFR', '↑ NaCl delivery and uptake at macula densa', '↑ Adenosine', 'Afferent constriction', 'GFR back toward normal'],
      route: '/autoregulation',
      cite: { rose: [2], evidence: 'physiology', refs: ['carlstrom2015'] },
    },
    {
      heading: 'When neurohumoral control overrides autoregulation',
      body: [
        'In patients, renal perfusion usually falls because of effective volume depletion — true hypovolaemia, heart failure or cirrhosis — and that activates the sympathetic and renin–angiotensin systems. Noradrenaline constricts the afferent arteriole directly (and the efferent indirectly via angiotensin II); angiotensin II constricts mostly the efferent.',
        'The result is not autoregulatory dilation but vasoconstriction: RPF falls at rest while GFR falls less or not at all, because efferent constriction holds up Pgc. This diverts flow to the heart and brain while preserving excretory function.',
        'Renal prostaglandins (and kinins) are released in proportion to the vasoconstrictor drive and keep the ischaemia in check. NSAIDs therefore do little in a euvolaemic person but can cause acute renal failure in heart failure, cirrhosis or volume depletion — in one study GFR fell from 73 to 32 mL/min in cirrhotics with ascites given an NSAID.',
        'Volume depletion also redistributes intrarenal flow from outer to inner cortex; its significance is uncertain.',
        'Volume expansion does the reverse: less angiotensin II and noradrenaline, more dopamine (dilates both arterioles: ↑ RBF, little change in GFR) and natriuretic peptide (afferent dilation with efferent constriction: ↑ Pgc and GFR).',
      ],
      chain: ['↓ Effective arterial volume', '↑ Noradrenaline + ↑ angiotensin II', 'Afferent and (more) efferent constriction', '↓ RPF, GFR relatively preserved (↑ FF)', '↑ Vasodilator prostaglandins limit ischaemia', 'NSAID removes the brake → acute fall in RPF and GFR'],
      route: '/arterioles',
      cite: { rose: [2], evidence: 'clinical', refs: ['whelton1999'] },
    },
    {
      heading: 'Endothelin, nitric oxide and hyperfiltration',
      body: [
        'Endothelin constricts both arterioles and may contribute to the fall in GFR after ischaemic injury and with cyclosporine. Nitric oxide is released tonically and lowers renal vascular resistance.',
        'When nephrons are lost, the survivors hyperfiltrate through afferent dilation, raising their Pgc and plasma flow. That maintains total GFR in the short term but damages the remaining glomeruli in the long term — a mechanism for progression to end-stage disease, and the reason lowering intraglomerular pressure (ACE inhibition, perhaps protein restriction) slows progression, especially in diabetic nephropathy, where the hyperfiltration is primary.',
      ],
      chain: ['Nephron loss', 'Afferent dilation in survivors', '↑ Single-nephron Pgc and GFR', 'Total GFR maintained (adaptive)', 'Glomerular injury over time (maladaptive)', 'ACE inhibitor lowers Pgc via efferent dilation'],
      route: '/ckd',
      cite: { rose: [2], evidence: 'experimental', refs: ['brenner1982', 'hostetter1981'] },
    },
    {
      heading: 'Clearance and the measurement of GFR',
      body: [
        'A substance that is freely filtered, not reabsorbed, secreted, made or metabolised, and has a stable plasma level, has filtered load = excreted amount: GFR × P = U × V, so GFR = UV/P. That quantity — the volume of plasma cleared per minute — is its clearance. Inulin fits; its clearance is GFR.',
        'Creatinine, made from muscle creatine at a steady rate, is the practical marker. But it is also secreted by the proximal organic cation pathway, so its clearance normally exceeds GFR by 10–20% — historically offset by non-creatinine chromogens in the plasma assay. As GFR falls, secretion rises (up to 35% of urinary creatinine at a GFR of 40–80 mL/min), so creatinine clearance can overestimate GFR two-fold in advanced disease; it is best read as an upper limit.',
        'Check a 24-hour collection’s completeness from creatinine excretion: about 0.18–0.22 mmol/kg/day in men and 0.13–0.18 in women under 50, falling with age (the book’s estimate, converted to SI: roughly 248 − 1.8 × age µmol/kg/day for men and 194 − 1.0 × age for women).',
        'Cimetidine and trimethoprim block creatinine secretion and can raise the plasma creatinine by ~35–45 µmol/L with no change in GFR.',
      ],
      equation: 'clearance',
      route: '/clearance',
      cite: { rose: [2], evidence: 'physiology' },
    },
    {
      heading: 'Plasma creatinine: an inverse, lagging, muscle-dependent signal',
      body: [
        'In the steady state, production equals excretion ≈ GFR × Pcr, so Pcr varies inversely with GFR: halve the GFR and the creatinine doubles — once enough has accumulated for the filtered load to match production again.',
        'Three consequences. First, it takes time: if GFR drops from 120 to 12 mL/min, day 1’s creatinine is still normal and it takes 7–10 days to plateau near 880 µmol/L. Second, the hyperbola means early losses are large and quiet (88 → 133 µmol/L can mean 120 → 80 mL/min) while late changes are loud (530 → 1060 µmol/L is 20 → 10 mL/min). Third, the curve depends on muscle mass: a creatinine of 124 µmol/L is a clearance of ~100 mL/min in a heavy young man but ~20 mL/min in a small elderly woman.',
        'Creatinine can also mislead: a meat meal can raise it acutely; acetoacetate interferes with the colorimetric assay in ketoacidosis; cirrhosis and malnutrition lower production so a "normal" creatinine can hide a GFR of 20–60. Between a GFR of 120 and 60, rising secretion may keep the creatinine almost flat — so a stable creatinine below ~130 µmol/L does not prove stable disease.',
      ],
      chain: ['↓ GFR', '↓ Filtered creatinine (production unchanged)', 'Creatinine accumulates', 'Pcr rises until GFR × Pcr = production again', 'New steady state after days'],
      route: '/creatinine',
      cite: { rose: [2], evidence: 'physiology' },
    },
    {
      heading: 'Urea and the urea/creatinine ratio',
      body: [
        'Urea is also filtered and varies inversely with GFR, but two things move it independently. Production rises with protein intake, tissue breakdown, gastrointestinal bleeding, corticosteroids and tetracyclines, and falls with liver disease or a low protein intake. And 40–50% of filtered urea is passively reabsorbed as sodium and water are reabsorbed — more so in volume depletion.',
        'In SI units the urea/creatinine ratio (urea mmol/L ÷ creatinine mmol/L) is normally about 40–60 — the book’s BUN/creatinine of 10–15:1. Above ~80 (BUN/creatinine > 20:1), suspect reduced effective volume or increased urea production. Urea clearance is only 50–70% of GFR; averaging urea and creatinine clearances approximates GFR in advanced disease.',
      ],
      route: '/prerenal-atn',
      cite: { rose: [2], evidence: 'physiology' },
    },
    {
      heading: 'Measuring renal plasma flow',
      body: [
        'PAH is filtered and secreted so efficiently that most is removed in one pass, so its clearance approximates renal plasma flow (~625 mL/min); RBF = RPF ÷ (1 − Hct) ≈ 1100 mL/min. Because extraction is 85–90%, it underestimates both by 10–15%.',
      ],
      route: '/clearance',
      cite: { rose: [2], evidence: 'physiology' },
    },
  ],
  numbers: [
    { label: 'Renal blood flow', value: '≈20% of cardiac output (~1.1 L/min)' },
    { label: 'Renal plasma flow', value: '≈625 mL/min' },
    { label: 'GFR', value: '95 ± 20 (women), 120 ± 25 mL/min (men)' },
    { label: 'Filtration fraction', value: '≈0.20' },
    { label: 'Glomerular capillary pressure', value: '45–46 mmHg', note: 'primate micropuncture' },
    { label: "Bowman's space pressure", value: '≈10 mmHg' },
    { label: 'Oncotic pressure along the capillary', value: '23 → 35 mmHg' },
    { label: 'Net filtration pressure', value: '+13 mmHg afferent → 0 efferent' },
    { label: 'Arteriolar share of renal resistance', value: '≈85%' },
    { label: 'Efferent vs afferent response to angiotensin II', value: 'up to 3×' },
    { label: 'Autoregulation fails', value: 'below MAP ≈70 mmHg; filtration stops at 40–50' },
    { label: 'Creatinine secretion', value: '10–20% of excretion normally, up to 35% at GFR 40–80' },
    { label: 'Urea/creatinine ratio (SI)', value: '≈40–60 (>~80 suggests low effective volume or high urea production)', note: 'equivalent to BUN/creatinine 10–15:1 and >20:1' },
    { label: 'Normal creatinine', value: '≈70–115 µmol/L (men), 55–90 µmol/L (women)' },
    { label: 'Intrarenal flow distribution', value: 'outer cortex ~80%, inner cortex 10–15%, medulla 5–10%' },
  ],
  equations: ['nfp', 'gfrKf', 'ff', 'clearance', 'crcl24', 'cockcroft', 'ckdepi'],
  clinical: [
    'ACE inhibitors and ARBs can lower GFR when glomerular pressure is angiotensin II-dependent: bilateral renal artery stenosis, stenosis to a solitary kidney, heart failure with low pressure, or diuretic-induced volume depletion. The rise in creatinine is usually modest and reversible.',
    'NSAIDs are safe for the kidney in euvolaemic people but can cause acute kidney injury in heart failure, cirrhosis, volume depletion and CKD, where vasodilator prostaglandins are holding renal perfusion up.',
    'A normal plasma creatinine does not mean a normal GFR in small, elderly, malnourished or cirrhotic patients — estimate clearance before dosing renally excreted drugs.',
    'A stable creatinine below ~130 µmol/L does not exclude progressive disease: rising proteinuria, an active sediment or rising blood pressure may be the only clues.',
    'After an abrupt fall in GFR, creatinine rises over days. An early creatinine underestimates the severity of acute kidney injury.',
    'Trimethoprim and cimetidine raise creatinine by blocking its secretion, not by lowering GFR.',
  ],
  pathology: [
    { name: 'Renal artery stenosis + ACE inhibitor', broken: 'Angiotensin II-dependent efferent tone that was holding Pgc up', consequence: 'Efferent dilation lowers Pgc and GFR; creatinine rises', route: '/arterioles' },
    { name: 'NSAID in heart failure or cirrhosis', broken: 'Prostaglandin-mediated vasodilation opposing angiotensin II and noradrenaline', consequence: 'Unopposed afferent and efferent constriction; RPF and (flow-dependent) GFR fall', route: '/arterioles' },
    { name: 'Glomerulonephritis', broken: 'Filtration surface area (Kf) reduced enough to prevent filtration equilibrium', consequence: 'GFR falls; larger pores let protein through', route: '/gfr' },
    { name: 'Urinary obstruction', broken: "Bowman's space pressure rises", consequence: 'Net filtration pressure and GFR fall', route: '/obstruction' },
    { name: 'Haemoconcentration (vomiting, diarrhoea)', broken: 'Plasma oncotic pressure rises', consequence: 'Contributes to the fall in GFR in volume depletion', route: '/gfr' },
    { name: 'Nephron loss', broken: 'Number of filtering units', consequence: 'Compensatory single-nephron hyperfiltration: adaptive now, injurious later', route: '/ckd' },
    { name: 'Glucosuria (DKA, hyperosmolar state)', broken: 'Tubuloglomerular feedback impaired', consequence: 'GFR not reduced despite high distal delivery → larger fluid losses', route: '/hyperglycemia' },
  ],
  questions: [
    {
      q: 'Dopamine dilates both afferent and efferent arterioles. What happens to the filtration fraction?',
      options: ['It rises', 'It falls — RBF rises more than GFR', 'It is unchanged because both arterioles dilate', 'It falls to zero'],
      answer: 1,
      explanation: 'Dilating both lowers total resistance, so plasma flow rises. Pgc changes little (afferent dilation raises it, efferent dilation lowers it), so GFR rises less than RPF and GFR/RPF falls. Less concentration of plasma protein also means lower peritubular oncotic pressure.',
      route: '/arterioles',
    },
    {
      q: 'Renal plasma flow falls by 15% with no change in glomerular pressure. If filtration normally reaches equilibrium, GFR will:',
      options: ['Be unchanged', 'Fall about 15%', 'Rise, because protein is more concentrated', 'Fall about 50%'],
      answer: 1,
      explanation: 'At filtration equilibrium the rise in oncotic pressure, not the membrane, limits filtration. Equilibrium is still reached after filtering ~20% of the plasma, so GFR falls in proportion to flow.',
      route: '/gfr',
    },
    {
      q: 'A patient with hypertension and diabetic nephropathy is treated either with an ACE inhibitor or with an afferent dilator, with the same fall in blood pressure. Which lowers glomerular capillary pressure more?',
      options: ['The afferent dilator', 'The ACE inhibitor', 'They are equal', 'Neither changes Pgc'],
      answer: 1,
      explanation: 'The ACE inhibitor dilates the efferent arteriole, lowering Pgc beyond the effect of the systemic pressure. An afferent dilator lets more of the systemic pressure reach the glomerulus, partly offsetting the benefit. Lower intraglomerular pressure is thought to slow progression.',
      route: '/arterioles',
    },
    {
      q: 'GFR abruptly falls from 120 to 12 mL/min in a previously healthy 70 kg man. On day 1, the plasma creatinine is:',
      options: ['About 880 µmol/L', 'Still near normal — it rises by roughly 90–180 µmol/L per day', 'Exactly double', 'Impossible to predict'],
      answer: 1,
      explanation: 'Creatinine accumulates at the rate production exceeds excretion. With little filtration, it rises by roughly the day’s production divided by its distribution volume (~90–180 µmol/L per day) until the new steady state (~880 µmol/L) after 7–10 days. So the day-2 creatinine greatly underestimates the fall in GFR.',
      route: '/creatinine',
    },
    {
      q: 'Why do loop diuretics raise renin more than can be explained by volume loss alone?',
      options: ['They stimulate β₁ receptors', 'They block NKCC2 in the macula densa, so chloride uptake — the sensed signal — falls', 'They raise afferent arteriolar stretch', 'They inhibit ACE'],
      answer: 1,
      explanation: 'The macula densa senses chloride uptake through NKCC2. Blocking the carrier silences the signal even while delivery rises. Thiazides act downstream and do not do this.',
      route: '/raas',
    },
    {
      q: 'A 24-hour urine: creatinine 11.1 mmol/L, volume 800 mL; plasma creatinine 309 µmol/L, 80 kg man. Creatinine clearance and its meaning?',
      options: ['≈20 mL/min, an accurate GFR', '≈20 mL/min, an upper limit of the true GFR; and the collection is probably incomplete (0.11 mmol/kg/day)', '≈50 mL/min', '≈200 mL/min'],
      answer: 1,
      explanation: 'CrCl = (11.1 × 1000 × 800)/(309 × 1440) ≈ 20 mL/min. In renal failure secretion inflates creatinine clearance, so the true GFR is lower. Creatinine excretion of 8.9 mmol/day is ~0.11 mmol/kg — low for a man, raising the possibility of an incomplete collection or low muscle mass.',
      route: '/clearance',
    },
    {
      q: 'In heart failure with high angiotensin II and noradrenaline, which pattern is typical?',
      options: ['↑ RPF, ↑ GFR', '↓ RPF with GFR relatively preserved (↑ filtration fraction)', '↓ GFR with ↑ RPF', 'No change'],
      answer: 1,
      explanation: 'Neurohumoral vasoconstriction lowers renal flow, but efferent constriction by angiotensin II raises Pgc, so GFR falls less. The raised filtration fraction also raises peritubular oncotic pressure and so proximal sodium reabsorption.',
      route: '/arterioles',
    },
  ],
  updates: [
    {
      topic: 'Estimating GFR',
      text: 'Since this edition, estimating equations have replaced most timed clearances. KDIGO recommends the race-free 2021 CKD-EPI creatinine equation for initial assessment and adding cystatin C (the marker the book mentioned as preliminary) when creatinine is likely to mislead.',
      cite: { evidence: 'guideline', refs: ['inker2021ckdepi', 'kdigo2024ckd'] },
    },
    {
      topic: 'Kidney protection beyond ACE inhibition',
      text: 'SGLT2 inhibitors slow CKD progression in trials (CREDENCE, DAPA-CKD, EMPA-KIDNEY). One proposed mechanism fits this chapter’s logic: by increasing NaCl delivery to the macula densa they restore tubuloglomerular feedback and reduce hyperfiltration — a mechanistic interpretation supported by physiology studies rather than proven as the cause of the clinical benefit.',
      cite: { evidence: 'clinical', refs: ['perkovic2019', 'heerspink2020', 'empakidney2023', 'cherney2014'] },
    },
    {
      topic: 'AKI definitions',
      text: 'The book’s “acute renal failure” is now “acute kidney injury”, staged by KDIGO criteria using changes in creatinine and urine output — criteria that inherit the lag in creatinine described here.',
      cite: { evidence: 'guideline', refs: ['kellum2013aki'] },
    },
  ],
};
