import type { ChapterContent } from './types';

export const chapter: ChapterContent = {
  n: 6,
  title: 'Effects of hormones on renal function',
  thesis:
    'Hormones let the kidney regulate each solute and water separately. ADH sets free-water excretion; aldosterone sets distal Na⁺ reabsorption and K⁺/H⁺ secretion; natriuretic peptides, dopamine, prostaglandins and kinins restrain Na⁺ retention and vasoconstriction; catecholamines and angiotensin II do the opposite; PTH, calcitriol (and now FGF23) govern calcium and phosphate; erythropoietin links renal oxygen sensing to the marrow. Each acts through a defined second messenger in specific cells, and each primary excess or deficiency produces a predictable syndrome.',
  concepts: [
    {
      heading: 'Four signalling routes',
      body: [
        'Adenylyl cyclase: hormone binds a basolateral receptor, activates Gs (or Gi, which inhibits), cAMP rises, protein kinase A phosphorylates targets. Used by ADH (V2), PTH, β-adrenergic agonists; inhibited by α₂-agonists, prostaglandins and the tubular action of angiotensin II.',
        'Guanylyl cyclase: ANP’s receptor is itself a cyclase; cGMP closes inner-medullary Na⁺ channels. Nitric oxide and nitrovasodilators use soluble guanylyl cyclase.',
        'Phosphatidylinositol turnover: angiotensin II, α₁-noradrenaline and V1 vasopressin activate phospholipase C → IP₃ (calcium release, the acute effect) and diacylglycerol (protein kinase C, the sustained effect). Diacylglycerol carries arachidonic acid, which is why these vasoconstrictors also generate prostaglandins.',
        'Gene transcription: steroids — aldosterone, calcitriol, cortisol — cross the membrane, bind cytosolic receptors and induce new proteins; hence aldosterone’s ~90-minute lag.',
      ],
      cite: { rose: [6], evidence: 'physiology' },
      route: '/hormones',
    },
    {
      heading: 'ADH: actions',
      body: [
        'Made in the supraoptic and paraventricular nuclei, stored in the posterior pituitary, half-life 15–20 min (so a water diuresis peaks 90–120 min after drinking). Some reaches the circulation through the median eminence, which is why lesions below it rarely cause permanent diabetes insipidus.',
        'V2 receptors on principal cells → cAMP → aquaporin-2 vesicles fuse with the apical membrane; the water-permeable basolateral membrane (AQP3/4) lets water out. When ADH falls the channels are endocytosed. V2 receptor mutations (X-linked) and aquaporin-2 mutations (autosomal recessive) cause hereditary nephrogenic DI.',
        'ADH also stimulates cortical collecting duct Na⁺ reabsorption and K⁺ secretion — the latter prevents falls in distal flow during antidiuresis from reducing K⁺ excretion. V1 receptors constrict vessels and stimulate prostaglandins, which in turn blunt ADH’s effects; V1b (V3) receptors release ACTH. V2 receptors also release factor VIII and von Willebrand factor, the basis for desmopressin in bleeding disorders and uraemic bleeding.',
        'Cortisol inhibits CRH and ADH release, so adrenal insufficiency causes persistent ADH secretion and hyponatraemia.',
      ],
      chain: ['ADH → V2 receptor (basolateral)', 'Gs → cAMP → PKA', 'AQP2 vesicles fuse with apical membrane', 'Water enters, exits via AQP3/4', '↓ Urine volume, ↑ urine osmolality'],
      route: '/adh',
      cite: { rose: [6], evidence: 'physiology', refs: ['knepper2015', 'bockenhauer2015'] },
    },
    {
      heading: 'ADH: control of secretion',
      body: [
        'Osmoreceptors in the brain (separate from the ADH-producing cells) shrink when effective osmolality rises, opening stretch-inactivated cation channels. They respond to a 1% change in osmolality; the threshold is ~280–290 mOsm/kg, below which ADH is nearly absent and the urine maximally dilute (<100 mOsm/kg). Above it, ADH rises linearly. Plasma osmolality is held within 1–2%; >80% of a water load is excreted within 4 h.',
        'Only effective osmoles count: sodium salts do; urea does not; glucose does not in normal people (insulin lets it into the osmoreceptor) but does in uncontrolled diabetes.',
        'Thirst has a threshold a few mOsm/kg higher, is sensed as a dry mouth, and is switched off within 10–20 min of drinking by oropharyngeal receptors — before absorption — preventing overdrinking.',
        'Volume (baroreceptor) stimulation is less sensitive than osmotic: small volume losses that raise renin and noradrenaline barely change ADH; once blood pressure falls, ADH can rise far above osmotic levels. Volume depletion lowers the osmotic threshold and steepens the slope, and can keep ADH on despite hypo-osmolality — the mechanism of hyponatraemia in hypovolaemia, heart failure and cirrhosis. Chronic volume expansion (primary aldosteronism) raises the threshold slightly.',
        'Non-osmotic stimuli: nausea (up to 500-fold), pain and surgical stress (days post-operatively — dangerous with hypotonic fluids), hypoglycaemia, nicotine, morphine and many drugs. Pregnancy lowers the osmostat (Na⁺ ~5 mmol/L lower), probably via hCG/relaxin. Ethanol and phenytoin inhibit ADH.',
      ],
      chain: ['↑ Plasma effective osmolality (1%)', 'Osmoreceptor shrinks', '↑ ADH + thirst', 'Water retained and drunk', 'Osmolality restored'],
      route: '/adh',
      cite: { rose: [6, 9], evidence: 'physiology', refs: ['robertson1976'] },
    },
    {
      heading: 'Aldosterone: synthesis and actions',
      body: [
        'Aldosterone is made only in the zona glomerulosa, which alone has aldosterone synthase (the 18-hydroxylation/oxidation steps); the fasciculata lacks it, keeping aldosterone out of ACTH control. A chimeric gene joining the 11β-hydroxylase regulator to the aldosterone synthase coding region makes aldosterone ACTH-dependent: glucocorticoid-remediable aldosteronism.',
        'Aldosterone binds cytosolic mineralocorticoid receptors in the connecting segment and collecting ducts, inducing proteins (including a serine kinase) that raise the number of open apical Na⁺ channels and later Na⁺-K⁺-ATPase and K⁺ channels. The quantitatively largest effect is reduced NaCl excretion; K⁺ and H⁺ secretion rise. It acts on principal cells (Na⁺ reabsorption, K⁺ secretion), inner medullary cells (Na⁺ only) and intercalated/outer medullary cells (H⁺ secretion, directly and via the lumen-negative voltage).',
        'Cortisol binds the receptor as avidly and circulates at far higher concentrations, but 11β-hydroxysteroid dehydrogenase converts it to inactive cortisone. Inhibiting that enzyme (liquorice’s glycyrrhetinic acid) or losing it (apparent mineralocorticoid excess) makes cortisol a mineralocorticoid: hypertension, hypokalaemia, alkalosis.',
        'Aldosterone also lowers Na⁺ and raises K⁺ in sweat, saliva and colonic fluid — colonic K⁺ secretion matters in end-stage kidney disease.',
      ],
      chain: ['Aldosterone → cytosolic MR', 'Aldosterone-induced proteins (~90 min)', '↑ Open ENaC, later ↑ Na⁺-K⁺-ATPase and K⁺ channels', '↑ Na⁺ reabsorption, ↑ K⁺ and H⁺ secretion'],
      route: '/raas',
      cite: { rose: [6], evidence: 'physiology', refs: ['pearce2015', 'mune1995', 'lifton1992'] },
    },
    {
      heading: 'Aldosterone: control, and independent Na⁺ and K⁺ regulation',
      body: [
        'Two major stimuli: angiotensin II (volume) and plasma K⁺ (a rise of 0.1–0.2 mmol/L is enough; secretion rises linearly above 3.5 mmol/L). They potentiate each other, partly through an intra-adrenal renin–angiotensin system. ACTH gives only a transient rise. Hyponatraemia stimulates and hypernatraemia suppresses it, but volume usually overrides this. ANP inhibits it. Chronic sodium restriction increases aldosterone synthase ten-fold.',
        'If aldosterone raises both Na⁺ reabsorption and K⁺ secretion, how can the kidney handle them separately? Because K⁺ secretion also depends on distal Na⁺ and water delivery, and K⁺ balance itself modulates loop Na⁺ transport:',
      ],
      points: [
        'Na⁺ depletion: aldosterone ↑ but proximal reabsorption ↑ and distal delivery ↓ → Na⁺ excretion ↓, K⁺ unchanged (why untreated heart failure and cirrhosis do not waste K⁺)',
        'Na⁺ load: aldosterone ↓ but distal delivery ↑ → Na⁺ excretion ↑, K⁺ unchanged — unless aldosterone cannot fall (adenoma): then K⁺ wasting (the basis of salt-loading tests)',
        'K⁺ load: aldosterone ↑ and loop Na⁺ transport ↓ (more delivery) → K⁺ excretion ↑, Na⁺ unchanged',
        'K⁺ depletion: aldosterone ↓, distal delivery ↓ → K⁺ excretion ↓, Na⁺ unchanged',
      ],
      route: '/potassium',
      cite: { rose: [6, 12], evidence: 'physiology' },
    },
    {
      heading: 'Aldosterone escape and pressure natriuresis',
      body: [
        'Give aldosterone with ample salt and you see Na⁺ retention, weight gain (~3 kg), hypertension and K⁺ loss — then a spontaneous natriuresis returns volume toward normal. K⁺ loss continues, so this is not resistance. The escape is driven by the volume expansion itself: ANP rises 1–2 days before the natriuresis (though ANP-deficient animals still escape), and the rise in renal perfusion pressure produces a pressure natriuresis. Clamping renal artery pressure prevents escape, and fluid retention and hypertension then progress to pulmonary oedema.',
        'Clinically this is why primary aldosteronism causes hypertension and hypokalaemia but not oedema. The same volume-escape logic explains why SIADH does not produce oedema.',
      ],
      chain: ['Aldosterone excess', 'Na⁺ retention (~3 kg), BP ↑, K⁺ loss', '↑ ANP, ↑ renal perfusion pressure', 'Natriuresis in other segments (escape)', 'Na⁺ balance restored; hypertension and K⁺ loss persist'],
      route: '/sodium',
      cite: { rose: [6, 8], evidence: 'physiology' },
    },
    {
      heading: 'Natriuretic peptides',
      body: [
        'ANP (28 amino acids, from atrial myocytes) is released by atrial stretch — in any hypervolaemic state, including heart failure (with ventricular recruitment) and renal failure. It dilates vessels and causes natriuresis: through cGMP it closes Na⁺ channels in the inner medullary collecting duct, raises GFR with little change in RBF (afferent dilation plus efferent constriction), may reduce proximal reabsorption, suppresses renin and aldosterone, and blunts ADH’s effect.',
        'Its physiological importance is uncertain: infusions give only a modest diuresis (the fall in blood pressure counteracts it), renal perfusion pressure is permissive for its action, and heart failure and cirrhosis are ANP-resistant (reversed by restoring perfusion pressure). Blocking ANP reduces acute natriuresis but not the response to chronic salt loading or mineralocorticoid escape.',
        'Relatives: urodilatin (made in the kidney, not degraded by neutral endopeptidase), BNP (mainly ventricular; rises more than ANP in heart failure; implicated in cerebral salt wasting) and CNP (endothelial). ANP and BNP levels mark left ventricular dysfunction. Inhibiting neutral endopeptidase (which degrades ANP), especially with ACE inhibition, produces a sizeable natriuresis.',
      ],
      route: '/sodium',
      cite: { rose: [6], evidence: 'physiology' },
    },
    {
      heading: 'Prostaglandins',
      body: [
        'Made from arachidonic acid by cyclo-oxygenase (COX-1 constitutive; COX-2 inducible, constitutive at low levels in the kidney and essential for its development). Tubules make mostly PGE₂; glomeruli make PGE₂ and prostacyclin. They act locally — the lung destroys them.',
        'Basal production is low and so is their role. But vasoconstrictors (angiotensin II, noradrenaline, V1 vasopressin, endothelin) all stimulate glomerular prostaglandin synthesis, which then limits renal ischaemia. NSAIDs therefore cause haemodynamically mediated acute kidney injury in true volume depletion, heart failure, cirrhosis, glomerular disease and hypercalcaemia — in proportion to the intensity of vasoconstriction, and reversibly.',
        'Other consequences of blocking prostaglandins: blood pressure rises 3–5 mmHg (up to 5–10) in treated hypertensives; afterload rises in heart failure; renin falls (prostaglandins mediate baroreceptor and macula densa renin release) → hyporeninaemic hypoaldosteronism and hyperkalaemia (+0.2 mmol/L normally, +0.6 in renal insufficiency); ADH’s effect is enhanced (urine osmolality can rise, favouring hyponatraemia when ADH is non-suppressible); Na⁺ retention and diuretic resistance. Medullary prostaglandins may also protect the thick ascending limb from hypoxia by limiting its transport.',
      ],
      chain: ['↓ Effective volume', '↑ Angiotensin II, noradrenaline, ADH', '↑ Renal prostaglandins (vasodilator brake)', 'NSAID removes the brake', '↓ RBF and GFR; ↓ renin → ↑ K⁺; ↑ ADH effect; Na⁺ retention'],
      route: '/arterioles',
      cite: { rose: [6], evidence: 'clinical', refs: ['whelton1999'] },
    },
    {
      heading: 'PTH, calcitriol and calcium–phosphate balance',
      body: [
        'Calcium and phosphate absorption is incomplete (of ~25 mmol (1000 mg) dietary calcium, net absorption is only 2.5–5 mmol), so gut, bone and kidney all participate. About 40% of plasma calcium is albumin-bound, 15% complexed, 45% ionised; correct the total by +0.02 mmol/L per 1 g/L fall in albumin (below 40 g/L).',
        'PTH is secreted when the parathyroid calcium-sensing receptor detects a fall in ionised calcium. It raises plasma calcium three ways: bone resorption (with vitamin D present), calcitriol synthesis (hence gut absorption), and distal tubular calcium reabsorption. It lowers proximal phosphate reabsorption (NaPi-II), which usually outweighs its phosphate-releasing effects on bone and gut, so plasma phosphate falls.',
        'Vitamin D₃ is 25-hydroxylated in the liver (unregulated, substrate-dependent) and 1α-hydroxylated in the kidney to calcitriol, stimulated by PTH and hypophosphataemia and inhibited by hypercalcaemia and calcitriol itself. Calcitriol raises gut calcium and phosphate absorption and bone resorption, and suppresses PTH. Macrophages in sarcoidosis, tuberculosis and lymphoma make calcitriol autonomously → hypercalciuria and hypercalcaemia.',
        'Hypocalcaemia → PTH → calcitriol: calcium rises with little change in phosphate. Hypophosphataemia → more NaPi carriers and more calcitriol, PTH falls: phosphate rises with little change in calcium. PTH also helps defend against acid loads, by increasing phosphate buffer delivery and bone buffering.',
      ],
      chain: ['↓ Ionised Ca²⁺', 'Parathyroid CaSR → ↑ PTH', 'Bone resorption + distal Ca²⁺ reabsorption + ↑ calcitriol (gut absorption)', 'Phosphaturia offsets phosphate release', 'Ca²⁺ restored, phosphate ≈ unchanged'],
      route: '/minerals',
      cite: { rose: [6], evidence: 'physiology' },
    },
    {
      heading: 'Mineral metabolism in renal failure',
      body: [
        'As GFR falls, phosphate is retained and PTH rises roughly in proportion — and restricting phosphate intake prevents it. The book weighs two mechanisms: phosphate lowering ionised calcium, and phosphate reducing calcitriol synthesis (supported by low calcitriol in mild–moderate CKD, its rise with phosphate restriction, and prevention of hyperparathyroidism by calcitriol but not by calcium). Parathyroid resistance to calcitriol (fewer receptors) and a direct effect of high phosphate contribute.',
        'Initially adaptive (phosphaturia keeps phosphate near normal, fractional phosphate reabsorption falling from 80–95% to as low as 15%), hyperparathyroidism becomes maladaptive: osteitis fibrosa, and below a GFR of ~30 mL/min PTH can no longer increase phosphate excretion but still releases it from bone — hyperphosphataemia, a high calcium–phosphate product and metastatic calcification.',
        'Management principles: limit phosphate absorption (diet; binders with meals — calcium salts, sevelamer; not aluminium; never calcium citrate, which increases aluminium absorption), correct calcitriol deficiency once phosphate is controlled, correct acidosis (bone buffering), parathyroidectomy for refractory disease.',
      ],
      chain: ['↓ GFR', 'Phosphate retention', '↓ Calcitriol (+ ↓ ionised Ca²⁺, direct phosphate effect)', '↑ PTH (secondary hyperparathyroidism)', 'Phosphaturia restores phosphate — until GFR < ~30', 'Bone disease, hyperphosphataemia, vascular calcification'],
      route: '/minerals',
      cite: { rose: [6], evidence: 'clinical', refs: ['isakova2011', 'ketteler2017'], update: 'FGF23 is now recognised as the earliest hormonal response to phosphate retention in CKD, rising before PTH and suppressing calcitriol — it provides the mechanism for the calcitriol deficiency the book describes.' },
    },
    {
      heading: 'Catecholamines and dopamine',
      body: [
        'Renal sympathetic activity rises in effective volume depletion. Noradrenaline constricts renal vessels (diverting flow to heart and brain), directly stimulates proximal and loop Na⁺ transport (α₁), alters peritubular forces (raising filtration fraction) and releases renin (β₁). Coupling vasoconstriction with Na⁺ retention prevents the rise in blood pressure from causing a pressure natriuresis. α₂ receptors do the opposite: they inhibit proximal Na⁺ transport and ADH-stimulated water reabsorption (via Gi).',
        'Dopamine, made in the proximal tubule from filtered L-dopa (more in volume expansion), dilates afferent and efferent arterioles (RBF ↑ with little change in GFR) and inhibits NHE3 and Na⁺-K⁺-ATPase — a natriuretic hormone. Yet “renal-dose” dopamine did not prevent or treat acute tubular necrosis in clinical trials.',
      ],
      route: '/sodium',
      cite: { rose: [6], evidence: 'clinical', refs: ['bellomo2000'] },
    },
    {
      heading: 'Kinins, erythropoietin, endothelin and nitric oxide',
      body: [
        'Kallikrein from the distal tubule and connecting segment generates bradykinin, a vasodilator that may limit ischaemia in hypovolaemia, close inner-medullary Na⁺ channels and blunt ADH (via prostaglandins). ACE is also a kininase — one reason ACE inhibitors raise kinins.',
        'Erythropoietin is made mainly by peritubular interstitial fibroblasts in the deep cortex and outer medulla in response to reduced oxygen delivery (via hypoxia-inducible factor). Because renal oxygen consumption falls with blood flow (less filtered Na⁺ to reabsorb), hypoperfusion alone does not inappropriately stimulate it. Loss of renal mass causes the anaemia of CKD, which recombinant EPO corrects — relieving many symptoms once blamed on uraemic toxins.',
        'Endothelins are the most potent vasoconstrictors known (ETA); ETB mediates vasodilation and, in tubules, inhibition of Na⁺ and water reabsorption. Released in prolonged severe ischaemia and with nephrotoxins (cyclosporine, contrast, amphotericin); they promote fibrosis and scarring.',
        'Nitric oxide (eNOS in vessels, nNOS in macula densa and IMCD, inducible iNOS in inflammation) is a tonic renal vasodilator, promotes natriuresis (inhibits ENaC, NHE3 and the pump), blunts tubuloglomerular feedback (resetting it on a high-salt diet), and in excess — with superoxide forming peroxynitrite — injures cells.',
      ],
      route: '/ckd',
      cite: { rose: [6], evidence: 'physiology', refs: ['babitt2012'] },
    },
  ],
  numbers: [
    { label: 'ADH half-life', value: '15–20 min' },
    { label: 'ADH osmotic threshold', value: '≈280–290 mOsm/kg' },
    { label: 'Osmoreceptor sensitivity', value: '≈1% change in Posm' },
    { label: 'Water load excreted in 4 h', value: '>80%' },
    { label: 'Nausea-induced ADH rise', value: 'up to 500-fold' },
    { label: 'Pregnancy osmostat reset', value: 'plasma Na⁺ ≈5 mmol/L lower' },
    { label: 'Aldosterone latent period', value: '≈90 min' },
    { label: 'K⁺ rise that stimulates aldosterone', value: '0.1–0.2 mmol/L' },
    { label: 'Aldosterone escape weight gain', value: '≈3 kg' },
    { label: 'NSAID effect on BP in treated hypertension', value: '+3–5 (up to 10) mmHg' },
    { label: 'NSAID effect on K⁺', value: '+0.2 mmol/L (normal), +0.6 (renal insufficiency)' },
    { label: 'Plasma calcium', value: '≈40% albumin-bound, 15% complexed, 45% ionised' },
    { label: 'Net gut calcium absorption', value: '2.5–5 mmol/day (of ~25 ingested)' },
    { label: 'Fractional phosphate reabsorption in severe CKD', value: 'down to ~15%' },
  ],
  equations: ['correctedCa', 'cccr', 'fepo4'],
  clinical: [
    'Primary aldosteronism: hypokalaemia, metabolic alkalosis and hypertension without oedema (escape). Screening uses the aldosterone/renin ratio; salt loading unmasks K⁺ wasting.',
    'Hypoaldosteronism: hyperkalaemia and mild metabolic acidosis; Na⁺ wasting is modest in adults because other Na⁺-retaining systems compensate.',
    'SIADH: water retention and hyponatraemia without oedema; post-operative and nausea-related ADH make hypotonic fluids dangerous.',
    'Liquorice or apparent mineralocorticoid excess: hypertension and hypokalaemia with low renin and aldosterone.',
    'NSAIDs: AKI in volume depletion, heart failure, cirrhosis, glomerular disease and hypercalcaemia; hyperkalaemia; hyponatraemia with non-suppressible ADH; diuretic resistance; blood pressure rise.',
    'Vitamin D intoxication and granulomatous disease: hypercalciuria and hypercalcaemia.',
    'CKD mineral bone disorder and anaemia follow from loss of renal phosphate excretion, calcitriol and erythropoietin production.',
    'Desmopressin treats central DI and bleeding in haemophilia A, von Willebrand disease and uraemia.',
  ],
  pathology: [
    { name: 'Nephrogenic DI (hereditary)', broken: 'V2 receptor (X-linked) or aquaporin-2 (recessive)', consequence: 'Dilute polyuria despite high ADH', route: '/water-disorders' },
    { name: 'Glucocorticoid-remediable aldosteronism', broken: 'Chimeric 11β-hydroxylase/aldosterone synthase gene', consequence: 'ACTH-driven aldosterone: early hypertension, suppressed renin; dexamethasone corrects', route: '/inherited' },
    { name: 'Apparent mineralocorticoid excess / liquorice', broken: '11β-HSD2', consequence: 'Cortisol acts as mineralocorticoid: hypertension, hypokalaemia, alkalosis, low renin and aldosterone', route: '/inherited' },
    { name: 'Adrenal insufficiency', broken: 'Cortisol (and aldosterone)', consequence: 'Loss of cortisol’s inhibition of ADH → hyponatraemia; with aldosterone loss, hyperkalaemia and salt wasting', route: '/hyponatremia' },
    { name: 'Hypoparathyroidism', broken: 'PTH (and so calcitriol)', consequence: 'Hypocalcaemia, hyperphosphataemia, calciuria that limits correction', route: '/minerals' },
    { name: 'Secondary hyperparathyroidism of CKD', broken: 'Phosphate excretion and calcitriol synthesis', consequence: 'High PTH, bone disease, eventually hyperphosphataemia and calcification', route: '/ckd' },
    { name: 'Anaemia of CKD', broken: 'Erythropoietin-producing interstitial cells', consequence: 'Normocytic anaemia; responds to recombinant EPO', route: '/ckd' },
  ],
  questions: [
    {
      q: 'Aldosterone is high both with an adrenal adenoma and with volume depletion. Plasma renin activity is:',
      options: ['High in both', 'Low with the adenoma (volume expanded), high with volume depletion', 'Low in both', 'High with the adenoma'],
      answer: 1,
      explanation: 'Primary hyperaldosteronism expands volume and suppresses renin; secondary hyperaldosteronism is driven by renin. The distinction is the basis of the aldosterone/renin ratio.',
      route: '/raas',
    },
    {
      q: 'Patients with renal failure have a high plasma osmolality from urea but no persistent ADH release. Why?',
      options: ['Uraemia inhibits the pituitary', 'Urea is an ineffective osmole: it crosses cell membranes and does not shrink osmoreceptor cells', 'ADH is cleared faster', 'They are volume expanded'],
      answer: 1,
      explanation: 'Osmoreceptors respond to effective osmolality (tonicity). Urea equilibrates across the cell membrane, so it does not move water out of the osmoreceptor.',
      route: '/body-water',
    },
    {
      q: 'Why doesn’t switching off thirst protect against hyponatraemia the way thirst protects against hypernatraemia?',
      options: ['It does', 'Much water intake is not driven by thirst (social, habitual, fluids given IV), so abolishing thirst cannot stop it; protection depends on suppressing ADH and excreting water', 'Thirst has no threshold', 'Because of aldosterone'],
      answer: 1,
      explanation: 'Hypernatraemia is prevented by adding water when thirsty; hyponatraemia can only be prevented by excreting water, which requires ADH to be suppressible and adequate solute delivery.',
      route: '/adh',
    },
    {
      q: 'Effect on renal calcitriol synthesis of a high-phosphate diet, and of hypoparathyroidism?',
      options: ['Both increase it', 'Both decrease it', 'Phosphate increases it; hypoparathyroidism decreases it', 'No effect'],
      answer: 1,
      explanation: 'Phosphate loading suppresses 1α-hydroxylase (limiting further phosphate absorption); PTH is the main stimulus, so its absence lowers calcitriol. A high-calcium diet also lowers it (via lower PTH); phosphate restriction in CKD raises it.',
      route: '/minerals',
    },
    {
      q: 'A patient eats a large salt load (crisps) without water. Aldosterone, ANP and ADH will:',
      options: ['All rise', 'Aldosterone ↓, ANP ↑, ADH ↑ (osmolality rises)', 'All fall', 'Aldosterone ↑, ANP ↓, ADH ↓'],
      answer: 1,
      explanation: 'Salt without water raises osmolality (ADH and thirst ↑) and, as water shifts out of cells, expands extracellular volume (ANP ↑, renin and aldosterone ↓).',
      route: '/sodium',
    },
    {
      q: 'Loop diuretics cause hypercalciuria. Why don’t they cause hypocalcaemia?',
      options: ['They increase gut absorption directly', 'Any fall in plasma calcium raises PTH and calcitriol, which increase bone release, gut absorption and distal reabsorption', 'They reduce bone calcium', 'They do cause it'],
      answer: 1,
      explanation: 'The PTH–calcitriol system defends the plasma calcium; the price is the calcium mobilised to replace urinary losses.',
      route: '/minerals',
    },
    {
      q: 'Aldosterone increases Na⁺ reabsorption. Why doesn’t the plasma Na⁺ concentration rise?',
      options: ['Aldosterone also secretes Na⁺', 'Retained Na⁺ raises osmolality slightly, which stimulates ADH and thirst; water is retained with it, so volume, not concentration, increases', 'Na⁺ enters cells', 'It does rise markedly'],
      answer: 1,
      explanation: 'Sodium balance sets volume; water balance (ADH, thirst) sets concentration. At most a small rise occurs from resetting of the osmostat in chronic volume expansion.',
      route: '/body-water',
    },
    {
      q: 'In which settings is an NSAID most likely to reduce GFR?',
      options: ['High-salt diet', 'Low-salt diet, heart failure and severe vomiting', 'Untreated hypertension only', 'None'],
      answer: 1,
      explanation: 'Where angiotensin II and noradrenaline are high, prostaglandins are sustaining renal perfusion. A high-salt diet suppresses these systems, and uncomplicated hypertension does not rely on prostaglandins.',
      route: '/arterioles',
    },
  ],
  updates: [
    {
      topic: 'FGF23 and Klotho',
      text: 'The phosphate–calcitriol–PTH network now includes FGF23 (from osteocytes), which with its co-receptor Klotho causes phosphaturia and suppresses 1α-hydroxylase. In CKD, FGF23 rises early, before phosphate or PTH, and high levels are associated with mortality.',
      cite: { evidence: 'clinical', refs: ['shimada2004', 'isakova2011'] },
    },
    {
      topic: 'Hypoxia-inducible factor',
      text: 'The oxygen-sensing mechanism the book sketches is the hypoxia-inducible factor (HIF)–prolyl hydroxylase pathway. Oral HIF-prolyl hydroxylase inhibitors such as roxadustat raise endogenous erythropoietin and haemoglobin in CKD, and are used in some countries.',
      cite: { evidence: 'clinical', refs: ['babitt2012', 'chen2019roxa'] },
    },
    {
      topic: 'Neprilysin inhibition',
      text: 'The book anticipates that slowing ANP degradation with an endopeptidase inhibitor plus RAS blockade could help heart failure. In PARADIGM-HF, sacubitril–valsartan (a neprilysin inhibitor with an ARB) reduced cardiovascular death and heart-failure hospitalisation compared with enalapril in heart failure with reduced ejection fraction.',
      cite: { evidence: 'clinical', refs: ['mcmurray2014'] },
    },
  ],
};
