import type { ChapterContent } from './types';

export const chapter: ChapterContent = {
  n: 7,
  title: 'The total body water and the plasma sodium concentration',
  thesis:
    'Water crosses almost every cell membrane freely, so every body compartment has the same osmolality; what differs is which solutes each compartment holds. Sodium salts are the effective osmoles outside cells and potassium salts inside, so the plasma sodium concentration reports the ratio of exchangeable Na⁺ + K⁺ to total body water — not the amount of sodium or the size of the extracellular volume. Between plasma and interstitium the dividing forces are hydraulic and oncotic (Starling), and oedema requires those forces to overcome several safety factors.',
  concepts: [
    {
      heading: 'Osmosis and effective osmoles',
      body: [
        'When a membrane lets water through but not a solute, water moves toward the side with more solute particles until the osmolality is the same on both sides. The osmotic pressure depends on the number of particles, not their size or charge.',
        'A solute that is confined to one compartment is an effective osmole: it holds water in that compartment and can pull water across the membrane. Na⁺ salts (kept outside cells by the Na⁺-K⁺-ATPase), glucose (in the absence of insulin) and mannitol are effective extracellular osmoles; K⁺ salts are the effective intracellular osmoles.',
        'Urea crosses cell membranes and reaches the same concentration inside and outside cells. It adds to measured osmolality but moves no water — an ineffective osmole. Ethanol behaves the same way. “Tonicity” means effective osmolality.',
      ],
      chain: ['Solute added to one compartment only', 'That compartment’s osmolality rises', 'Water moves in from the other compartment', 'Both reach the same (new) osmolality'],
      cite: { rose: [7], evidence: 'physiology' },
      route: '/body-water',
    },
    {
      heading: 'Distribution of body water',
      body: [
        'Water is about 60% of lean body weight in men and 50% in women (less with obesity and age because fat holds little water). Of the total, roughly 55–60% is intracellular and 40–45% extracellular; extracellular water divides roughly 3:1 between interstitium and plasma.',
        'Because each compartment’s volume depends on how many effective osmoles it contains, the extracellular volume is set by the amount of Na⁺ in it and the intracellular volume by the amount of K⁺ — which is why sodium balance, not water balance, regulates extracellular volume.',
      ],
      points: [
        '70 kg man: TBW ≈ 42 L; ICF ≈ 25 L; ECF ≈ 17 L (interstitial ≈ 13, plasma ≈ 4)',
        'Osmolality is the same everywhere (≈280–290 mOsm/kg)',
        'ECF volume ∝ ECF Na⁺ content; ICF volume ∝ ICF K⁺ content',
      ],
      cite: { rose: [7], evidence: 'physiology' },
      route: '/body-water',
    },
    {
      heading: 'Three worked additions',
      body: [
        'Consider a 70 kg man (TBW 42 L; ICF 25, ECF 17; osmolality 280). Solve each addition in three steps: total osmoles after the addition ÷ new TBW gives the new osmolality; each compartment’s osmoles ÷ that osmolality gives its volume; plasma Na⁺ falls or rises in proportion to osmolality.',
        'Add 420 mOsm of NaCl as dry salt (the example counts it as 420 mOsm for simplicity). It stays extracellular: total solute 11,760 + 420 = 12,180 mOsm in 42 L → 290 mOsm/kg. Extracellular solute 4,760 + 420 = 5,180 → ECF 17.9 L; ICF 24.1 L. About 0.9 L of water has left the cells: both compartments become hypertonic although the salt entered only one, and plasma Na⁺ rises to ≈145. Hypertonic sodium expands the ECF at the expense of the ICF.',
        'Add 1.5 L of pure water: it distributes in proportion to the compartments (about 60% into cells), osmolality and Na⁺ fall together (≈270 and ≈135), and most of the volume ends up intracellular.',
        'Add 1.5 L of isotonic saline: osmolality is unchanged, no water moves, and the entire 1.5 L stays extracellular. This is why isotonic saline is the fluid for volume depletion and water is the fluid for hypernatraemia.',
      ],
      cite: { rose: [7], evidence: 'physiology' },
      route: '/body-water',
    },
    {
      heading: 'Plasma sodium is a concentration, not a volume',
      body: [
        'Plasma Na⁺ says how much water there is relative to solute; it says nothing direct about how much Na⁺ the body holds or how large the ECF is. Hyponatraemia can accompany low, normal or high extracellular volume, and the same is true of hypernatraemia.',
        'Volume is judged clinically (history, examination, urine Na⁺); tonicity is judged by the plasma Na⁺. The two are regulated by different systems — volume by Na⁺ excretion (renin–angiotensin, sympathetic nerves, natriuretic peptides), osmolality by water balance (ADH and thirst).',
      ],
      chain: ['Na⁺ balance', '→ extracellular volume', '(renin–angiotensin–aldosterone, SNS, ANP)', 'Water balance', '→ plasma Na⁺ / osmolality', '(ADH, thirst)'],
      cite: { rose: [7, 8, 9], evidence: 'physiology' },
      route: '/sodium',
    },
    {
      heading: 'Plasma osmolality and why it is “2 × Na⁺”',
      body: [
        'Plasma osmolality ≈ 2 × Na⁺ + glucose + urea, all in mmol/L (the book, in US units, writes glucose/18 + BUN/2.8). The factor of 2 is not simply “Na⁺ plus its anion”: NaCl is not fully dissociated (osmotic coefficient ~0.93, ≈1.75 particles), plasma is only ~93% water, and K⁺, Ca²⁺ and Mg²⁺ salts add about 0.12 × Na⁺ — the effects roughly cancel to 2.',
        'Because urea is ineffective, effective osmolality (tonicity) = 2 × Na⁺ + glucose. A patient with renal failure and a urea of 50 mmol/L has a raised measured osmolality but normal tonicity: no water leaves cells and ADH is not stimulated.',
        'A measured osmolality that exceeds the calculated value by more than ~10 mOsm/kg (the osmolal gap) means an unmeasured osmole such as ethanol, methanol, ethylene glycol or mannitol.',
      ],
      equation: 'posm',
      cite: { rose: [7], evidence: 'physiology' },
      route: '/body-water',
    },
    {
      heading: 'Edelman: sodium and potassium together set the plasma sodium',
      body: [
        'Since the ECF and ICF are in osmotic equilibrium and their main osmoles are Na⁺ and K⁺ salts, plasma Na⁺ ≈ (exchangeable Na⁺ + exchangeable K⁺) / total body water. Edelman’s isotope measurements showed plasma water Na⁺ closely tracks this ratio (with a small intercept because some Na⁺ and K⁺ is osmotically inactive, e.g. bound in bone).',
        'Implications: losing K⁺ lowers plasma Na⁺ (Na⁺ moves into cells, or water moves out of them to preserve equilibrium); giving K⁺ in hyponatraemia raises Na⁺ as effectively as giving Na⁺ — a point that matters when correcting hyponatraemia with potassium replacement, because it adds to the rate of rise.',
        'Hyponatraemia therefore means water retention relative to Na⁺ + K⁺, or loss of solute in excess of water. Almost always it reflects inability to excrete water — usually because ADH is present.',
      ],
      equation: 'edelman',
      chain: ['↓ Exchangeable K⁺ (e.g. diuretic)', 'Cell K⁺ ↓ → Na⁺ enters cells / water leaves ECF to cells', '↓ Plasma Na⁺'],
      cite: { rose: [7, 22], evidence: 'physiology', refs: ['edelman1958', 'rose1986'] },
      route: '/body-water',
    },
    {
      heading: 'Why hyponatraemia is common and hypernatraemia is not',
      body: [
        'Hyponatraemia requires water intake that exceeds excretion. The normal kidney can excrete more than 10 L/day of dilute urine, so hyponatraemia almost always involves impaired water excretion — ADH that is not suppressed, advanced renal failure or very low solute intake.',
        'Hypernatraemia is prevented by thirst: any rise in osmolality provokes it, and drinking water corrects it. Persistent hypernatraemia therefore occurs mostly in those who cannot respond to thirst — infants, and adults with impaired mental status or no access to water.',
      ],
      cite: { rose: [7, 23, 24], evidence: 'physiology' },
      route: '/water-disorders',
    },
    {
      heading: 'Capillary exchange: Starling forces',
      body: [
        'Between plasma and interstitium, the capillary wall passes water and small solutes freely, so Na⁺ salts are ineffective here. The effective osmoles are plasma proteins, and fluid movement = Lp·S·(ΔP − σ·Δπ): capillary minus interstitial hydraulic pressure, opposed by plasma minus interstitial oncotic pressure (σ is the reflection coefficient for protein).',
        'In muscle the mean net pressure only slightly favours filtration; the filtrate is returned by lymph. Organs differ: glomeruli have high hydraulic pressure and filter heavily; alveoli have low capillary pressure, which keeps them dry; hepatic sinusoids are protein-permeable, so there is no oncotic gradient and hepatic lymph flow is the defence against ascites.',
        'Plasma proteins exert more oncotic pressure than their concentration predicts (≈25–26 mmHg rather than ≈17): the Gibbs–Donnan effect of the negatively charged proteins holds extra cations in plasma.',
      ],
      equation: 'nfp',
      cite: { rose: [7], evidence: 'physiology' },
      route: '/edema',
    },
    {
      heading: 'Protection against oedema',
      body: [
        'Capillary hydraulic pressure is protected by precapillary (arteriolar) autoregulation: a rise in arterial pressure is not transmitted to the capillary. A rise in venous pressure is, which is why heart failure and venous obstruction cause oedema but hypertension does not.',
        'When fluid does begin to accumulate, three safety factors resist it: lymph flow rises; interstitial oncotic pressure falls (dilution and lymphatic removal of protein); and interstitial hydraulic pressure rises from its normally negative value. Oedema only appears when these are overwhelmed.',
      ],
      points: ['Lymph flow ↑', 'Interstitial oncotic pressure ↓', 'Interstitial hydraulic pressure ↑ (becomes positive)'],
      chain: ['↑ Venous pressure or ↓ plasma oncotic pressure', 'Filtration into interstitium ↑', 'Safety factors (lymph, oncotic, hydraulic)', 'Only when exhausted: oedema', 'Plasma volume ↓ → renal Na⁺ retention (if underfilled)'],
      cite: { rose: [7, 16], evidence: 'physiology' },
      route: '/edema',
    },
    {
      heading: 'Nephrotic oedema: underfill or overflow?',
      body: [
        'Hypoalbuminaemia lowers plasma oncotic pressure, but less albumin enters the interstitium, so interstitial oncotic pressure falls in parallel and the transcapillary gradient is largely preserved (measured before and after remission of minimal change disease). Loss of interstitial protein is itself a safety factor.',
        'In many patients oedema is therefore driven by primary renal Na⁺ retention in the collecting tubule (overflow), not by plasma volume depletion: unilateral nephrosis in animals causes Na⁺ retention only in the affected kidney.',
        'Underfill clearly operates when hypoalbuminaemia is acute (the interstitium has not had time to adapt — e.g. dilution by saline after massive bleeding, or abrupt-onset nephrotic syndrome) or very severe (albumin < ~10 g/L, when interstitial protein cannot fall further).',
      ],
      cite: { rose: [7, 16], evidence: 'physiology', refs: ['siddall2012', 'svenningsen2009'] },
      route: '/edema',
    },
  ],
  numbers: [
    { label: 'Total body water', value: '≈60% of lean weight (men), ≈50% (women)' },
    { label: 'ICF : ECF', value: '≈55–60% : 40–45% of TBW' },
    { label: 'Interstitial : plasma', value: '≈3 : 1' },
    { label: '70 kg man', value: 'TBW 42 L, ICF 25 L, ECF 17 L' },
    { label: 'Plasma osmolality', value: '≈280–290 mOsm/kg' },
    { label: 'Normal osmolal gap', value: '< ~10 mOsm/kg' },
    { label: 'Book’s US units → SI', value: 'glucose mg/dL ÷ 18; BUN mg/dL ÷ 2.8 = urea mmol/L' },
    { label: '1 mOsm/kg gradient', value: '≈19.3 mmHg osmotic pressure' },
    { label: 'Plasma oncotic pressure', value: '≈25–28 mmHg (Gibbs–Donnan raises it above ≈17 predicted)' },
    { label: 'Water excretory capacity', value: '> 10 L/day' },
    { label: 'Underfill threshold in nephrosis', value: 'albumin < ~10 g/L, or acute fall' },
  ],
  equations: ['posm', 'effosm', 'osmgap', 'edelman', 'nfp', 'glucoseNa'],
  clinical: [
    'Choose the fluid by the problem: isotonic saline for volume (stays extracellular); water (or 5% dextrose) for hypertonicity (distributes to all compartments); hypertonic saline to shift water out of swollen brain cells.',
    'Renal failure raises measured osmolality through urea without hypertonicity, so it causes no cell shrinkage and no thirst.',
    'Hyperglycaemia draws water out of cells and lowers plasma Na⁺ (translocational hyponatraemia) while the osmolality is high; the Na⁺ must be interpreted after correcting for glucose.',
    'A high osmolal gap with metabolic acidosis suggests methanol or ethylene glycol poisoning.',
    'Potassium given to a hyponatraemic patient raises plasma Na⁺ and must be counted when planning the rate of correction.',
    'Hypertension does not cause oedema (precapillary autoregulation); venous hypertension does.',
    'Nephrotic oedema is often primary renal Na⁺ retention: diuretics are usually safe, but beware acute or very severe hypoalbuminaemia where plasma volume may be genuinely low.',
  ],
  pathology: [
    { name: 'Hyponatraemia with impaired water excretion', broken: 'ADH suppression (or diluting capacity)', consequence: 'Water retained relative to Na⁺ + K⁺: plasma Na⁺ and osmolality fall, cells swell', route: '/hyponatremia' },
    { name: 'Hypernatraemia', broken: 'Thirst or access to water', consequence: 'Water deficit: cells shrink; seen in infants and the obtunded', route: '/water-disorders' },
    { name: 'Hyperglycaemia (insulin deficiency)', broken: 'Glucose entry into cells', consequence: 'Glucose becomes an effective osmole: water leaves cells, plasma Na⁺ falls despite hyperosmolality', route: '/hyperglycemia' },
    { name: 'Toxic alcohol ingestion', broken: 'None — an unmeasured osmole is added', consequence: 'Raised osmolal gap; the metabolites cause an anion gap acidosis', route: '/metabolic-acidosis' },
    { name: 'Heart failure / venous obstruction', broken: 'Venous (capillary) hydraulic pressure', consequence: 'Filtration exceeds lymph flow → oedema', route: '/edema' },
    { name: 'Nephrotic syndrome', broken: 'Glomerular albumin barrier (and collecting-duct Na⁺ handling)', consequence: 'Primary renal Na⁺ retention ± underfill → oedema', route: '/edema' },
    { name: 'Cirrhosis', broken: 'Sinusoidal pressure (portal hypertension); protein-permeable sinusoid', consequence: 'Hepatic lymph overwhelmed → ascites', route: '/edema' },
  ],
  questions: [
    {
      q: 'What does a low plasma Na⁺ tell you about the extracellular volume?',
      options: ['It is low', 'It is high', 'Nothing directly: Na⁺ concentration reflects water relative to solute; volume reflects total Na⁺ content', 'It is normal'],
      answer: 2,
      explanation: 'Hyponatraemia occurs with hypovolaemia, euvolaemia (SIADH) and hypervolaemia (heart failure). Volume must be assessed separately.',
      route: '/body-water',
    },
    {
      q: 'Glucose is added to the extracellular fluid of a person without insulin. What happens to ECF volume, ICF volume and plasma Na⁺?',
      options: ['ECF ↑, ICF ↓, Na⁺ ↓', 'ECF ↓, ICF ↑, Na⁺ ↑', 'No changes', 'ECF ↑, ICF ↑, Na⁺ unchanged'],
      answer: 0,
      explanation: 'Glucose confined to the ECF raises its osmolality, pulling water from cells. The ECF expands and its Na⁺ is diluted, while total osmolality is still raised.',
      route: '/body-water',
    },
    {
      q: 'Plasma osmolality 290 mOsm/kg, Na⁺ 125 mmol/L, urea 10 mmol/L. If glucose is the only other osmole, the glucose is about:',
      options: ['10 mmol/L', '20 mmol/L', '30 mmol/L', '50 mmol/L'],
      answer: 2,
      explanation: '290 = 2 × 125 + 10 + glucose → glucose = 30 mmol/L (the book’s problem 7-3, converted from 540 mg/dL).',
      route: '/equations',
    },
    {
      q: '1.5 L of isotonic saline is infused. Where does it go?',
      options: ['Two-thirds into cells', 'All of it stays extracellular (about 3/4 interstitial, 1/4 plasma)', 'All in plasma', 'It distributes like water'],
      answer: 1,
      explanation: 'Isotonic saline does not change osmolality, so no water crosses cell membranes; the Starling forces then share it between interstitium and plasma.',
      route: '/body-water',
    },
    {
      q: 'Which change will raise plasma volume by drawing interstitial fluid into capillaries?',
      options: ['A rise in arterial pressure', 'A fall in venous pressure', 'A fall in plasma albumin to 30 g/L', 'Venous obstruction'],
      answer: 1,
      explanation: 'Lower venous pressure lowers capillary hydraulic pressure, favouring reabsorption. Arterial pressure is buffered by arteriolar autoregulation; a modest fall in albumin is largely offset by a parallel fall in interstitial oncotic pressure.',
      route: '/edema',
    },
    {
      q: 'A patient loses 300 mmol of K⁺ with diuretics, with no change in Na⁺ or water. Plasma Na⁺:',
      options: ['Rises', 'Falls', 'Unchanged', 'Depends on aldosterone'],
      answer: 1,
      explanation: 'Plasma Na⁺ ≈ (Na⁺e + K⁺e)/TBW. Losing intracellular K⁺ lowers the numerator; Na⁺ enters cells and/or water shifts, and plasma Na⁺ falls.',
      route: '/body-water',
    },
    {
      q: 'A plasma urea of 50 mmol/L raises the measured osmolality by ~45 mOsm/kg. Does it cause cellular dehydration?',
      options: ['Yes, severe', 'No: urea equilibrates across cell membranes and is an ineffective osmole', 'Only in the brain', 'Only with low Na⁺'],
      answer: 1,
      explanation: 'Only effective osmoles move water. (Rapid removal of urea by dialysis can briefly create a gradient — the disequilibrium syndrome — but that is the reverse situation.)',
      route: '/body-water',
    },
  ],
  updates: [
    {
      topic: 'The revised Starling principle',
      text: 'Modern microvascular physiology places the semipermeable barrier at the endothelial glycocalyx, with the relevant oncotic pressure being that just beneath it rather than in the bulk interstitium. In most tissues sustained absorption at the venous end does not occur; slight filtration prevails and lymph returns it. The classical “filter at the arterial end, reabsorb at the venous end” picture is a simplification; the textbook’s safety factors remain valid.',
      cite: { refs: ['levick2010'], evidence: 'experimental' },
    },
    {
      topic: 'Non-osmotic sodium storage',
      text: 'Experimental work (mainly in rodents) suggests skin interstitium can store Na⁺ hypertonically, regulated by macrophage–VEGF-C signalling, so not all Na⁺ retained is matched by water. This challenges the assumption that total body Na⁺ is fully osmotically active, though the Edelman relation remains an excellent clinical approximation. The clinical significance in humans is still being defined.',
      cite: { refs: ['machnik2009'], evidence: 'experimental' },
    },
    {
      topic: 'Glucose correction factor',
      text: 'The classical correction (Na⁺ falls ~1.6 mmol/L per 5.5 mmol/L rise in glucose) was re-examined experimentally; a factor of ~2.4 fits better, especially above ~22 mmol/L.',
      cite: { refs: ['hillier1999'], evidence: 'experimental' },
    },
  ],
};
