import type { ChapterContent } from './types';

export const chapter: ChapterContent = {
  n: 8,
  title: 'Regulation of the effective circulating volume',
  thesis:
    'What the body defends is tissue perfusion — sensed as pressure or stretch in the carotid sinus, the cardiac chambers and the afferent arteriole — and it defends it mainly by varying urinary Na⁺ excretion. A change in Na⁺ intake is matched within 3–4 days, but only after a small change in volume that becomes the persistent signal for the new level of excretion. Multiple overlapping effectors (sympathetic nerves, angiotensin II, aldosterone, ANP, GFR and, as the final backstop, pressure natriuresis) make the system redundant. Volume regulation and osmoregulation use different sensors and different effectors, which is why “dehydration” and “volume depletion” are not synonyms.',
  concepts: [
    {
      heading: 'What “effective circulating volume” means',
      body: [
        'The effective circulating volume is the part of the ECF in the arterial tree that is actually perfusing tissues — about 700 mL in a 70 kg man. Physiologically it is best thought of as the pressure at the carotid sinus and afferent arteriole baroreceptors, since stretch rather than volume is what those receptors sense.',
        'It usually moves with ECF volume and total body Na⁺, because Na⁺ salts hold water in the ECF. But it can be dissociated: heart failure lowers it while ECF and plasma volume rise; cirrhosis lowers it despite expanded ECF, plasma volume and often raised cardiac output (splanchnic pooling, arteriovenous shunting, vasodilatation); an arteriovenous fistula raises cardiac output without changing it.',
        'It cannot be measured directly. In practice it is inferred from the kidney’s behaviour: a urine Na⁺ below ~15–20 mmol/L indicates effective volume depletion — provided there is no renal salt wasting (diuretics, renal disease) and no selective renal ischaemia (bilateral renal artery stenosis, acute glomerulonephritis).',
      ],
      points: [
        'Na⁺-depleted normal: effective volume ↓, ECF ↓, plasma volume ↓, cardiac output ↓',
        'Heart failure: effective ↓, ECF ↑, plasma ↑, cardiac output ↓',
        'AV fistula: effective normal, ECF ↑, plasma ↑, cardiac output ↑',
        'Advanced cirrhosis: effective ↓, ECF ↑, plasma ↑, cardiac output normal/↑',
      ],
      cite: { rose: [8], evidence: 'physiology', refs: ['schrier1990', 'schrier1988'] },
      route: '/sodium',
    },
    {
      heading: 'The steady state: volume is the signal',
      body: [
        'When Na⁺ intake is raised abruptly, only about half the extra Na⁺ is excreted the first day. The retained Na⁺ raises osmolality, which triggers thirst and ADH, so water is retained with it and weight and effective volume rise. Each day a larger fraction of the excess is excreted until, after 3–4 days, excretion equals intake again.',
        'The new steady state carries a slightly larger ECF, and that expansion is not a failure of regulation: it is the sustained signal that keeps aldosterone suppressed and ANP raised so that excretion stays high. Cumulative Na⁺ balance rises in proportion to intake. The same happens in reverse when intake falls.',
        'Diuretics show the same logic: with a fixed dose, virtually all the net fluid loss occurs in the first 1–2 weeks (the first dose has the largest effect); counter-regulation (renin, SNS) then brings excretion back to intake at a lower volume.',
      ],
      chain: ['↑ Na⁺ intake', 'Na⁺ retained on day 1 → osmolality ↑ → ADH, thirst', 'Water retained → ECF ↑ (weight ↑)', 'Aldosterone ↓, ANP ↑', 'Excretion rises day by day', 'Steady state at 3–4 days: excretion = intake, ECF mildly expanded'],
      cite: { rose: [8], evidence: 'physiology', refs: ['walser1985'] },
      route: '/sodium',
    },
    {
      heading: 'Normal kidneys make excess stick only when excretion is impaired',
      body: [
        'The capacity to excrete Na⁺, K⁺, HCO₃⁻ and water is so large that oedema, hyperkalaemia, metabolic alkalosis or hyponatraemia cannot persist unless renal excretion of that substance is impaired. This one idea frames most of the book’s diagnostic reasoning: for any persistent excess, ask why the kidney is not excreting it.',
      ],
      cite: { rose: [8], evidence: 'reasoning' },
      route: '/sodium',
    },
    {
      heading: 'Volume receptors',
      body: [
        'Receptors sit in the cardiopulmonary circulation (atria, pulmonary veins), the carotid sinus and aortic arch, and the afferent arteriole (with the macula densa as a lesser contributor). They sense pressure/stretch, which usually tracks volume: vomiting lowers venous return, filling pressure, cardiac output and blood pressure in sequence.',
        'Renal receptors act mainly through renin–angiotensin–aldosterone (plus endothelin and nitric oxide); extrarenal receptors mainly through the sympathetic nervous system and ANP.',
        'Head-out water immersion shifts blood from the legs to the chest: central volume and ANP rise and a brisk natriuresis follows — even in many patients with cirrhosis who otherwise excrete almost no Na⁺, showing that their Na⁺ retention reflects effective hypovolaemia.',
        'No single receptor is indispensable: cardiac or renal denervation, fixed mineralocorticoid replacement or chronic aldosterone excess still allow Na⁺ balance.',
      ],
      cite: { rose: [8], evidence: 'physiology' },
      route: '/sodium',
    },
    {
      heading: 'Effector 1: the sympathetic nervous system',
      body: [
        'MAP = cardiac output × systemic vascular resistance. A fall in effective output lowers pressure, reduces baroreceptor firing and raises sympathetic tone, which: constricts veins (≈70% of blood volume is venous) to restore venous return; raises heart rate and contractility; constricts arterioles; releases renin; and directly increases proximal Na⁺ reabsorption.',
        'Patients with autonomic failure show why this matters: removal of 500 mL of blood, trivial for a normal person, causes severe hypotension, and they have postural hypotension and cannot maximally conserve Na⁺.',
        'Sympathetic effects on Na⁺ excretion are not predictable in isolation, because the rise in perfusion pressure opposes the tubular effect. Guanethidine at non-hypotensive doses is natriuretic; at hypotensive doses it causes Na⁺ retention — the rationale for combining sympatholytics with diuretics.',
      ],
      chain: ['↓ Effective volume → ↓ baroreceptor stretch', '↑ Sympathetic tone', 'Venoconstriction, ↑ HR and contractility, arteriolar constriction', '↑ Renin → angiotensin II', '↑ Proximal Na⁺ reabsorption'],
      cite: { rose: [8], evidence: 'physiology' },
      route: '/sodium',
    },
    {
      heading: 'Effector 2: angiotensin II — and why retention may or may not restore the steady state',
      body: [
        'Angiotensin II raises pressure (direct vasoconstriction, enhancement of noradrenaline) and retains Na⁺ (directly in the proximal tubule and via aldosterone). Blocking it — or the SNS — in a hypovolaemic subject can cause marked hypotension.',
        'Vasoconstriction only buys time; restoring volume after a loss requires Na⁺ and water to be ingested and retained. In heart failure or cirrhosis the outcome depends on severity. With moderate thoracic vena caval constriction in dogs, pressure falls, renin and aldosterone rise and Na⁺ excretion collapses; plasma volume and ascites accumulate until, by day 7, venous return is restored and renin, aldosterone and Na⁺ excretion return to baseline. With severe constriction no new steady state is reached and retention persists — the analogue of compensated versus decompensated heart failure.',
      ],
      cite: { rose: [8, 16], evidence: 'experimental' },
      route: '/raas',
    },
    {
      heading: 'Where the kidney adjusts Na⁺ excretion',
      body: [
        'GFR tends to rise with expansion and fall with depletion but is not required for balance — patients with moderately reduced GFR still match excretion to intake, and glomerulotubular balance blunts the effect of GFR changes.',
        'Loop and distal tubule reabsorption are primarily flow-dependent. Neurohumoral regulation according to body needs happens mainly in the proximal tubule (angiotensin II, noradrenaline, peritubular capillary forces) and the collecting tubules (aldosterone, ANP).',
        'Mild volume depletion lowers Na⁺ excretion mainly through collecting-tubule reabsorption (aldosterone); more marked depletion recruits proximal NHE3 (and thin ascending limb) reabsorption. Expansion reverses these.',
        'Day-to-day: with GFR 160 L/day and plasma water Na⁺ 150 mmol/L the filtered load is 24,000 mmol/day; excreting 120 mmol requires FENa 0.5%, and 180 mmol only 0.67%. Aldosterone (and perhaps ANP) acting in the collecting tubule is the fine regulator.',
        'Proximal changes show up in urate handling: volume depletion (e.g. diuretics) reduces urate excretion (hyperuricaemia, gout); the volume expansion of SIADH causes urate wasting and hypouricaemia. The same proximal stimulation maintains metabolic alkalosis by increasing HCO₃⁻ reabsorption.',
      ],
      points: ['Proximal tubule 60–65%: NHE3, Na⁺-glucose, angiotensin II, noradrenaline, peritubular forces', 'Loop 25–30%: flow-dependent', 'Distal tubule ~5%: flow-dependent', 'Collecting tubules ~4%: aldosterone, ANP'],
      equation: 'fena',
      cite: { rose: [8, 3], evidence: 'physiology' },
      route: '/sodium',
    },
    {
      heading: 'Redundancy: aldosterone and ANP are important but not essential',
      body: [
        'Adrenalectomised patients on fixed mineralocorticoid replacement maintain Na⁺ balance; aldosterone excess causes only a few days of retention before escape. ANP-deficient animals fail to excrete an acute load but handle chronic salt loading; transgenic mice with ten-fold ANP still excrete only what they eat, perhaps because their blood pressure falls. Each mediator contributes; none is indispensable.',
      ],
      cite: { rose: [8, 6], evidence: 'experimental' },
      route: '/raas',
    },
    {
      heading: 'Pressure natriuresis: the backstop',
      body: [
        'A small rise in blood pressure produces a large rise in Na⁺ and water excretion, with no neural or hormonal sensor required — volume changes cardiac output and pressure directly. Reduced reabsorption occurs in the proximal tubule and loop; a proposed route is transmission of pressure through the vasa recta to the medullary interstitium, which impairs uptake of reabsorbate and pushes fluid back into the descending limb, blunting the rise in luminal Na⁺ that drives passive thin-limb NaCl exit. Prostaglandins and nitric oxide contribute.',
        'Normally it contributes little day to day: a 50-fold increase in intake raises MAP by only ~4 mmHg because angiotensin II and aldosterone fall and ANP rises. When angiotensin II cannot be varied — fixed very low or fixed very high — a larger rise in pressure is needed to excrete each increment of salt (a steeper, right-shifted pressure–natriuresis curve).',
        'This is how every form of hypertension is ultimately limited: in aldosterone escape, if renal perfusion pressure is clamped at baseline, escape fails, Na⁺ accumulates and ascites, pulmonary oedema or malignant hypertension follow; releasing the clamp triggers a natriuresis. Hypertension is the price paid to reach balance when the kidney is primed to retain Na⁺. Conversely, when angiotensin II and the SNS are both blocked in a volume-depleted person, the fall in pressure itself causes Na⁺ retention.',
        'Macula densa nitric oxide rises with NaCl delivery and blunts tubuloglomerular feedback, which may explain TGF resetting on a high-salt diet and helps keep GFR up to excrete the load.',
      ],
      chain: ['Na⁺ retained (e.g. fixed aldosterone)', 'ECF ↑ → cardiac output ↑ → MAP ↑', 'Renal perfusion pressure ↑ → medullary interstitial pressure ↑', '↓ Proximal and loop reabsorption', 'Natriuresis → balance at a higher BP'],
      cite: { rose: [8], evidence: 'experimental', refs: ['guyton1991', 'hall1984'] },
      route: '/sodium',
    },
    {
      heading: 'The cardiorenal reflex',
      body: [
        'Renal sympathetic tone can be regulated separately from the rest of the body: raised left-sided cardiac pressure reduces renal sympathetic activity. In animals, haemorrhagic hypotension (low left-sided pressures) cut renal blood flow by up to 90% and stopped urine flow, whereas similar hypotension from myocardial infarction (high left-sided pressures) reduced renal blood flow by only ~25%. This may explain why post-ischaemic ATN is common after haemorrhage, sepsis and surgery but rare with heart failure alone — though its importance in humans is uncertain.',
      ],
      cite: { rose: [8], evidence: 'experimental' },
      route: '/aki',
    },
    {
      heading: 'Volume regulation versus osmoregulation',
      body: [
        'Osmoregulation senses plasma osmolality (hypothalamic osmoreceptors) and acts on water (ADH and thirst). Volume regulation senses effective circulating volume (carotid sinus, afferent arteriole, atria) and acts mainly on Na⁺ excretion (RAAS, SNS, ANP, pressure natriuresis, and ADH). The only major overlap is the hypovolaemic stimulus to ADH.',
        'So regulating the plasma Na⁺ concentration is about water, not sodium. Worked cases: exercise in heat (sweat) → hyperosmolality and mild hypovolaemia → concentrated urine low in Na⁺; gastroenteritis with poor intake in an elderly patient → the same but more volume depleted; isotonic saline → only volume regulation acts, isosmotic natriuresis; half-isotonic saline → both hypo-osmolality and expansion, so ADH and renin fall and a dilute, Na⁺-rich urine is formed.',
        'Dehydration means water loss raising plasma Na⁺ and shrinking cells; volume depletion (hypovolaemia) means loss of ECF — Na⁺ and water. Diarrhoea with a normal plasma Na⁺ is volume depletion without dehydration.',
      ],
      points: ['Osmoregulation: sensor = osmoreceptor; effectors = ADH, thirst; affects water', 'Volume regulation: sensors = carotid sinus, afferent arteriole, atria; effectors = RAAS, SNS, ANP, pressure natriuresis, ADH; affects Na⁺ excretion'],
      cite: { rose: [8, 9], evidence: 'physiology' },
      route: '/sodium',
    },
    {
      heading: 'Plasma Na⁺ concentration and Na⁺ excretion',
      body: [
        'Hypernatraemia tends to increase and hyponatraemia to decrease Na⁺ excretion (filtered load and reabsorption), but volume dominates: SIADH is hyponatraemic yet expanded, so urine Na⁺ is high; hypernatraemia from insensible losses is volume depleted, so urine Na⁺ is low.',
      ],
      cite: { rose: [8], evidence: 'physiology' },
      route: '/hyponatremia',
    },
  ],
  numbers: [
    { label: 'Effective arterial volume', value: '≈700 mL (70 kg man)' },
    { label: 'Urine Na⁺ in effective volume depletion', value: '< 15–20 mmol/L (can reach ~1)' },
    { label: 'Urine Na⁺ with expansion', value: 'can exceed 100 mmol/L' },
    { label: 'Time to new Na⁺ steady state', value: '3–4 days' },
    { label: 'Day-1 excretion of an abrupt Na⁺ increase', value: '≈50% of the excess' },
    { label: 'Diuretic net losses', value: 'complete within 7–14 days' },
    { label: 'Filtered Na⁺ (GFR 160 L/d, Na⁺ 150)', value: '24,000 mmol/day' },
    { label: 'FENa on 120 / 180 mmol intake', value: '0.5% / 0.67%' },
    { label: 'Venous share of blood volume', value: '≈70%' },
    { label: 'MAP rise for 50-fold increase in Na⁺ intake', value: '≈4 mmHg' },
    { label: 'Urine Na⁺ in advanced cirrhosis', value: 'often < 10 mmol/day' },
  ],
  equations: ['fena', 'edelman'],
  clinical: [
    'Urine Na⁺ < 15–20 mmol/L is the practical marker of effective volume depletion — misleading with diuretics, renal salt wasting, or selective renal ischaemia (bilateral renovascular disease, acute GN).',
    'Heart failure and cirrhosis: expanded ECF but low effective volume; the kidney behaves as if hypovolaemic (high renin, noradrenaline, ADH; low urine Na⁺).',
    'Diuretics: the first dose gives the largest natriuresis; weight loss plateaus within two weeks as counter-regulation (renin, SNS, distal hypertrophy) develops — the braking phenomenon.',
    'Diuretic-induced volume contraction raises proximal reabsorption → hyperuricaemia/gout and maintenance of metabolic alkalosis.',
    'SIADH: mild volume expansion → urate wasting (hypouricaemia) and urine Na⁺ equal to intake.',
    'Autonomic failure: orthostatic hypotension and poor tolerance of blood loss.',
    'Sympatholytic antihypertensives cause Na⁺ retention when they lower BP — combine with a diuretic.',
    'Isotonic saline for volume depletion; free water (or hypotonic fluids) for dehydration.',
  ],
  pathology: [
    { name: 'Heart failure', broken: 'Cardiac output (the pump, not the volume)', consequence: 'Effective volume ↓ → RAAS, SNS, ADH → Na⁺ and water retention, oedema, hyponatraemia', route: '/edema' },
    { name: 'Cirrhosis with ascites', broken: 'Systemic (splanchnic) vascular resistance', consequence: 'Arterial underfilling despite expanded ECF → avid Na⁺ retention (urine Na⁺ < 10 mmol/day)', route: '/edema' },
    { name: 'Autonomic insufficiency', broken: 'Sympathetic effector limb', consequence: 'Postural hypotension, intolerance of blood loss, impaired Na⁺ conservation', route: '/sodium' },
    { name: 'Primary aldosteronism', broken: 'Aldosterone cannot be suppressed', consequence: 'Escape via pressure natriuresis: balance at a higher BP, no oedema, K⁺ wasting', route: '/raas' },
    { name: 'Chronic kidney disease', broken: 'Pressure natriuresis curve shifted right', consequence: 'Na⁺ balance maintained only at a higher blood pressure', route: '/ckd' },
    { name: 'Bilateral renal artery stenosis', broken: 'Renal baroreceptor sees low pressure regardless of systemic volume', consequence: 'Low urine Na⁺ without systemic hypovolaemia; angiotensin-dependent GFR', route: '/arterioles' },
  ],
  questions: [
    {
      q: 'Which gives the most accurate assessment of effective circulating volume when renal function is normal and there is no renovascular obstruction?',
      options: ['Cardiac output', 'Plasma volume', 'Systemic blood pressure', 'Urinary Na⁺ excretion'],
      answer: 3,
      explanation: 'The kidney integrates all the volume signals; low Na⁺ excretion is the best marker of effective hypovolaemia. Cardiac output and plasma volume can be high in cirrhosis; BP is defended by vasoconstriction.',
      route: '/sodium',
    },
    {
      q: 'A patient with stable hypertension takes the same diuretic dose for months. What is the relationship between Na⁺ intake and urinary Na⁺ excretion?',
      options: ['Excretion exceeds intake', 'Excretion equals intake (a new steady state at lower volume)', 'Excretion is less than intake', 'Excretion is fixed regardless of intake'],
      answer: 1,
      explanation: 'Net losses occur only in the first 1–2 weeks; thereafter counter-regulation brings excretion back to intake, with ECF smaller than before.',
      route: '/diuretics',
    },
    {
      q: 'Acute myocardial infarction lowers cardiac output. Effective circulating volume and urinary Na⁺ excretion will:',
      options: ['Both rise', 'Both fall', 'Effective volume falls, Na⁺ excretion rises', 'No change'],
      answer: 1,
      explanation: 'Lower output lowers baroreceptor pressure; the kidney retains Na⁺. ECF and plasma volume then rise as fluid is retained.',
      route: '/sodium',
    },
    {
      q: 'Diuretics raise renin secretion. How does this affect their antihypertensive effect?',
      options: ['It enhances it', 'It limits it: angiotensin II vasoconstriction and Na⁺ retention partly offset the fall in BP (why ACE inhibitors/ARBs are additive)', 'No effect', 'It reverses it'],
      answer: 1,
      explanation: 'Counter-regulation is why combining a diuretic with RAAS blockade lowers pressure more than either alone.',
      route: '/raas',
    },
    {
      q: 'Water immersion to the neck in a patient with cirrhosis who excretes almost no Na⁺ causes:',
      options: ['No change', 'A natriuresis — central volume expansion is sensed as improved effective volume', 'More Na⁺ retention', 'Hyponatraemia'],
      answer: 1,
      explanation: 'The response shows the retention reflects effective hypovolaemia, not an intrinsic tubular defect.',
      route: '/edema',
    },
    {
      q: 'Eating salty crisps without drinking. Effects on aldosterone, ANP, ADH, urine osmolality and Na⁺ excretion?',
      options: ['Aldo ↓, ANP ↑, ADH ↑; urine concentrated and Na⁺-rich', 'All ↑, urine dilute', 'Aldo ↑, ANP ↓, ADH ↓', 'No change'],
      answer: 0,
      explanation: 'Hyperosmolality stimulates ADH (concentrated urine) while volume expansion suppresses aldosterone and raises ANP (natriuresis).',
      route: '/sodium',
    },
    {
      q: 'Half-isotonic saline is infused. What urine results?',
      options: ['Concentrated, Na⁺-poor', 'Dilute (ADH suppressed by hypo-osmolality) and Na⁺-rich (volume expanded)', 'Isosmotic, Na⁺-poor', 'Unchanged'],
      answer: 1,
      explanation: 'Both regulatory systems act: osmoregulation excretes the water, volume regulation excretes the Na⁺.',
      route: '/sodium',
    },
    {
      q: 'In the angiotensin II infusion arm of the Guyton experiment, raising salt intake produces:',
      options: ['The same BP response as normal', 'A larger rise in blood pressure, because Na⁺ reabsorption cannot be lowered by suppressing angiotensin II and aldosterone', 'A fall in BP', 'No natriuresis at all'],
      answer: 1,
      explanation: 'When angiotensin II cannot vary, balance is achieved only by pressure natriuresis — at a higher BP. The same applies with angiotensin II fixed low.',
      route: '/sodium',
    },
  ],
  updates: [
    {
      topic: 'Molecular basis of pressure natriuresis',
      text: 'Work since the book’s edition shows that acute rises in renal perfusion pressure cause rapid redistribution of proximal NHE3 and NaPi2 to the base of the brush-border microvilli (NaPi2 is endocytosed), providing a cellular mechanism for the reduced proximal reabsorption described in the chapter.',
      cite: { refs: ['mcdonough2010'], evidence: 'experimental' },
    },
    {
      topic: 'Guyton’s framework',
      text: 'The pressure–natriuresis curve as the long-term set point of arterial pressure remains influential but debated; experiments on salt storage and sympathetic mechanisms have challenged the idea that renal fluid handling alone sets blood pressure. The chapter’s qualitative conclusions — pressure natriuresis limits Na⁺ retention and hypertension is its price — are unaffected.',
      cite: { refs: ['guyton1991', 'machnik2009'], evidence: 'reasoning' },
    },
  ],
};
