import type { ChapterContent } from './types';

export const chapter: ChapterContent = {
  n: 9,
  title: 'Regulation of plasma osmolality',
  thesis:
    'Plasma osmolality is held within 1–2% by two effectors that act on water, not on sodium: ADH, which sets how much water the kidney excretes, and thirst, which sets how much is drunk. Hypo-osmolality is defended by excreting water — a capacity so large (10–20 L/day) that hyponatraemia almost always means water excretion is impaired. Hyper-osmolality is defended by thirst, because a deficit can only be corrected by drinking. How much water the kidney actually adds or removes is not read off the urine osmolality: it is calculated, and for the plasma sodium it must be calculated from the urinary sodium and potassium rather than from total solute.',
  concepts: [
    {
      heading: 'Daily water balance',
      body: [
        'Intake comes from three sources: what is drunk, the water in food (meat ~70% water; some fruit and vegetables nearly 100%) and the water of oxidation. Output is urine, evaporation from skin and airway, sweat and stool.',
        'Evaporative loss is not waste: it carries 20–25% of the body’s heat, at 0.58 kcal per mL evaporated. Sweat, unlike insensible loss, is a sensible and variable loss of hypotonic fluid (Na⁺ 30–65 mmol/L) that can reach 1500 mL/h in someone exercising in the heat.',
        'The obligatory urine volume is set by solute load ÷ maximum concentrating ability: 800 mOsm/day at a maximum of 1200 mOsm/kg requires at least 670 mL. Stool normally accounts for only 100–200 mL.',
      ],
      points: [
        'Typical intake: ingested 400 (obligatory) + 1000 (elective), food 850, oxidation 350 mL/day',
        'Typical output: urine 500 (obligatory) + 1000 (elective), skin 500, respiratory 400, stool 200 mL/day',
        'Sweat can exceed 5 L/day; thirst then makes up the difference',
      ],
      cite: { rose: [9], evidence: 'physiology' },
      route: '/urine-osmolality',
    },
    {
      heading: 'The osmostat: 1–2% precision',
      body: [
        'Normal plasma osmolality is 275–290 mOsm/kg, and a change of only 1–2% triggers correction. Hypothalamic osmoreceptors drive both thirst (water intake) and ADH (water excretion).',
        'A water load suppresses ADH; the resulting diuresis peaks at 90–120 min, the time needed to clear ADH already in the circulation. Because the kidney can excrete 10–20 L/day, a water load is disposed of long before volume regulation is disturbed.',
        'A water deficit is different: ADH can only stop further loss. Replacing the deficit requires drinking. That is why thirst is the main defence against hypernatraemia, and why patients with complete central diabetes insipidus passing more than 10 L/day keep a nearly normal plasma sodium as long as thirst works and water is available.',
      ],
      chain: ['Water load', '↓ Posm sensed by osmoreceptors', 'ADH suppressed (and thirst off)', 'Dilute urine, up to 10–20 L/day', 'Posm restored'],
      cite: { rose: [9], evidence: 'physiology' },
      route: '/adh',
    },
    {
      heading: 'ADH and solute load together set urine volume',
      body: [
        'For a fixed solute load of 800 mOsm/day, urine volume varies about fifteen-fold with ADH: no ADH gives a urine of ~80 mOsm/kg and 10 L/day; maximal ADH gives 1200 mOsm/kg and 0.67 L/day; an intermediate level gives 400 mOsm/kg and 2 L/day.',
        'But volume also depends on how much solute there is to excrete, which matters most when ADH is fixed. In complete central diabetes insipidus with a maximum urine osmolality of 80 mOsm/kg, excreting 800 mOsm needs 10 L but 400 mOsm needs only 5 L. Restricting salt and protein therefore reduces the polyuria — the mainstay when the kidney cannot respond to ADH at all (nephrogenic DI).',
        'The same lever works the other way in SIADH, where ADH is fixed high: a high-salt, high-protein diet, or urea itself, raises solute excretion, increases urine output and raises the plasma sodium.',
        'So a given urine osmolality does not tell you how much water is being excreted. Urine osmolality reports the kidney’s diluting or concentrating ability; the volume of water gained or lost has to be calculated.',
      ],
      points: ['No ADH: Uosm ≈ 80, volume 10 L/day', 'Moderate ADH: Uosm ≈ 400, volume 2 L/day', 'Maximal ADH: Uosm ≈ 1200, volume 0.67 L/day'],
      cite: { rose: [9], evidence: 'physiology', refs: ['berl2008'] },
      route: '/urine-osmolality',
      equation: 'cosm',
    },
    {
      heading: 'Free-water clearance and free-water reabsorption',
      body: [
        'Split any urine into two imaginary parts: one that holds all the solute at plasma osmolality (the osmolal clearance, Cosm = Uosm × V ÷ Posm) and one of pure water. In a dilute urine the second part is water being removed from the body — free-water clearance, CH₂O = V − Cosm. In a concentrated urine the sign reverses: water is being returned to the body — free-water reabsorption, TcH₂O = Cosm − V.',
        'Worked example from the book: complete central DI passing 10 L/day at 84 mOsm/kg with a plasma osmolality of 300 gives Cosm 2.8 L and CH₂O 7.2 L — of the 10 L, 7.2 L is pure water leaving the body.',
        'Free water is generated in two steps: NaCl is reabsorbed without water in the ascending limb (and, less, in the distal nephron), and the collecting duct is then kept impermeable by the absence of ADH. Either step can fail.',
      ],
      equation: 'ch2o',
      chain: ['Fluid delivered to the loop', 'TAL reabsorbs NaCl without water → dilute fluid', 'No ADH → collecting duct stays impermeable', 'Dilute urine: free water excreted'],
      cite: { rose: [9], evidence: 'physiology' },
      route: '/free-water',
    },
    {
      heading: 'Why water excretion fails — the whole differential of hyponatraemia',
      body: [
        'Because normal excretory capacity is 10–20 L/day, water retention only causes hyponatraemia if one of the two steps is impaired (or, rarely, if intake exceeds even a normal capacity).',
        'Less free water is generated when delivery to the loop falls — renal failure (less filtered) or volume depletion (less filtered and more reabsorbed proximally). Less is generated when NaCl reabsorption is blocked, which is why thiazides, acting in the cortical diluting segment, cause hyponatraemia far more than loop diuretics. And none is excreted if ADH is present: effective volume depletion, SIADH or adrenal insufficiency.',
        'Add primary polydipsia — intake beyond capacity — and that is the entire differential diagnosis of true hyponatraemia.',
      ],
      points: [
        'Reduced delivery to the diluting segment (renal failure, volume depletion)',
        'Blocked NaCl reabsorption in the diluting segment (thiazides)',
        'ADH present (volume depletion, SIADH, adrenal insufficiency, nausea, pain, drugs)',
        'Intake exceeding a normal capacity (primary polydipsia; very low solute intake lowers that capacity)',
      ],
      cite: { rose: [9, 23], evidence: 'physiology' },
      route: '/hyponatremia',
    },
    {
      heading: 'Electrolyte-free water: the correction that matters for plasma sodium',
      body: [
        'Plasma sodium is set by exchangeable Na⁺ + K⁺ over total body water, and urea plays no part in it — urea crosses cell membranes, so losing urea in the urine lowers the blood urea but does not change the plasma sodium. Ammonium salts behave similarly.',
        'So for osmoregulation the calculation must use the urinary Na⁺ + K⁺ in place of total urine osmolality, and the plasma Na⁺ in place of plasma osmolality. Electrolyte-free water clearance = V × [1 − (UNa + UK)/PNa].',
        'The book’s example: a urine of 580 mOsm/kg looks concentrated and the classical formula suggests 1 L of water is being returned to the body — but with urine Na⁺ 5 and K⁺ 43 against a plasma Na⁺ of 144, the electrolyte-free water calculation shows 670 mL of water being lost each day. The urine is concentrated with urea, not with electrolytes.',
        'The rule of thumb that follows: if (UNa + UK) is less than the plasma Na⁺, the urine is removing free water and raising the plasma sodium, however concentrated it looks. If it exceeds the plasma Na⁺, the urine is adding free water and lowering it.',
      ],
      equation: 'efwc',
      cite: { rose: [9, 23], evidence: 'physiology', refs: ['rose1986'] },
      route: '/free-water',
    },
    {
      heading: 'A clinical example: hypernatraemia with a concentrated urine',
      body: [
        'A 78-year-old man given high-protein feeds passes 4 L/day, his blood urea rises steeply with a stable creatinine, and his plasma sodium climbs from 140 to 156 despite generous fluid. The urine is concentrated, so the classical formula suggests the kidney is adding about 2 L/day of free water.',
        'The electrolyte-free water calculation shows the opposite: the polyuria is a urea osmotic diuresis, the urine holds little Na⁺ or K⁺, and about 2.7 L of free water is being lost each day. That is the hypernatraemia explained.',
      ],
      cite: { rose: [9], evidence: 'clinical' },
      route: '/free-water',
    },
    {
      heading: 'Concentrating the urine',
      body: [
        'Water conservation needs the medullary osmotic gradient to exist and the collecting duct fluid to equilibrate with it. ADH serves both: it drives urea accumulation in the inner medulla and raises collecting-duct water permeability. The NaCl limb of the gradient, from the ascending limb, is largely ADH-independent in humans.',
        'Concentration therefore fails in three ways: no ADH (central DI), no response to it (nephrogenic DI — in adults most often lithium or hypercalcaemia), or a damaged countercurrent mechanism. In each, thirst is the protection that keeps the plasma sodium normal at the cost of polydipsia.',
      ],
      cite: { rose: [9, 24], evidence: 'physiology' },
      route: '/water-disorders',
    },
    {
      heading: 'When both systems act at once',
      body: [
        'Salt without water (a bag of crisps) raises osmolality and, once water has shifted out of cells, expands the extracellular volume. ADH and thirst rise while aldosterone falls and ANP rises: the urine ends up concentrated and rich in sodium — matching what was taken in.',
        'Isotonic saline changes no osmolality, so ADH and thirst are untouched and only volume regulation responds. Isosmotic losses (bleeding, some diarrhoea) likewise change volume without changing the plasma sodium — until the patient drinks water, when ADH driven by hypovolaemia turns the volume problem into hyponatraemia.',
      ],
      cite: { rose: [9, 8], evidence: 'physiology' },
      route: '/sodium',
    },
  ],
  numbers: [
    { label: 'Normal plasma osmolality', value: '275–290 mOsm/kg' },
    { label: 'Change that triggers correction', value: '1–2%' },
    { label: 'Minimum urine osmolality', value: '40–100 mOsm/kg' },
    { label: 'Maximum urine osmolality', value: '900–1400 mOsm/kg' },
    { label: 'Maximum water excretion', value: '10–20 L/day' },
    { label: 'Peak water diuresis after a load', value: '90–120 min' },
    { label: 'Typical solute load', value: '≈800 mOsm/day' },
    { label: 'Obligatory urine volume', value: '800 ÷ 1200 ≈ 670 mL/day' },
    { label: 'Sweat Na⁺', value: '30–65 mmol/L' },
    { label: 'Maximum sweat rate', value: '≈1500 mL/h' },
    { label: 'Heat of evaporation', value: '0.58 kcal/mL (20–25% of heat loss)' },
    { label: 'Stool water', value: '100–200 mL/day' },
  ],
  equations: ['cosm', 'ch2o', 'efwc', 'posm', 'waterdeficit'],
  clinical: [
    'Hyponatraemia almost always means impaired water excretion: look for ADH (volume depletion, SIADH, adrenal insufficiency, nausea, pain, drugs), poor delivery to the diluting segment, thiazides, or a very low solute intake.',
    'Thiazides cause hyponatraemia much more often than loop diuretics because they block the cortical diluting segment without impairing the medullary gradient.',
    'In diabetes insipidus, restricting salt and protein reduces the obligatory urine volume — the main lever when the kidney cannot respond to ADH.',
    'In SIADH, raising solute intake (salt, protein, or urea) increases urine output and raises the plasma sodium.',
    'A concentrated urine does not mean water is being retained: check (UNa + UK) against the plasma Na⁺. Urea diuresis from high-protein feeds is a classic cause of hypernatraemia with concentrated urine.',
    'Hypernatraemia in someone with intact thirst and access to water is rare — its presence suggests impaired consciousness, no access, or an osmotic diuresis.',
    'The urine osmolality answers “can the kidney dilute or concentrate?”; free-water calculations answer “how much water is being gained or lost?”.',
  ],
  pathology: [
    { name: 'Central diabetes insipidus', broken: 'ADH secretion', consequence: 'Dilute polyuria up to >10 L/day; plasma Na⁺ normal while thirst is intact', route: '/water-disorders' },
    { name: 'Nephrogenic diabetes insipidus', broken: 'Collecting-duct response to ADH (lithium, hypercalcaemia, V2/AQP2 defects)', consequence: 'Polyuria unresponsive to ADH; treated by lowering solute load and with thiazides', route: '/water-disorders' },
    { name: 'SIADH', broken: 'ADH suppression', consequence: 'Water retention, concentrated urine, hyponatraemia without oedema; urine Na⁺ + K⁺ often exceeds plasma Na⁺', route: '/hyponatremia' },
    { name: 'Thiazide hyponatraemia', broken: 'NaCl reabsorption in the cortical diluting segment', consequence: 'Free water cannot be generated: hyponatraemia, often with volume depletion and hypokalaemia', route: '/diuretics' },
    { name: 'Beer potomania / “tea and toast”', broken: 'Solute supply to the kidney', consequence: 'Very low solute excretion caps water excretion: hyponatraemia at modest water intakes', route: '/urine-osmolality' },
    { name: 'Urea osmotic diuresis', broken: 'Solute load (high-protein feeds, catabolism)', consequence: 'Polyuria with concentrated urine but loss of electrolyte-free water → hypernatraemia', route: '/free-water' },
    { name: 'Adrenal insufficiency', broken: 'Cortisol’s restraint on ADH', consequence: 'Persistent ADH → impaired water excretion → hyponatraemia', route: '/hyponatremia' },
  ],
  questions: [
    {
      q: 'A patient with complete central diabetes insipidus passes 10 L/day. Why is the plasma sodium usually normal?',
      options: ['ADH is partly preserved', 'Thirst increases water intake to match the loss', 'The kidney retains sodium', 'Urea replaces the lost water'],
      answer: 1,
      explanation: 'A water deficit can only be corrected by drinking. Thirst therefore protects the plasma sodium; hypernatraemia appears when thirst or access to water fails.',
      route: '/adh',
    },
    {
      q: 'In diabetes insipidus with a fixed maximum urine osmolality of 80 mOsm/kg, halving solute excretion from 800 to 400 mOsm/day changes urine volume from:',
      options: ['10 L to 10 L', '10 L to 5 L', '10 L to 20 L', '5 L to 10 L'],
      answer: 1,
      explanation: 'Volume = solute ÷ osmolality. When ADH is fixed, solute intake sets the urine volume — which is why restricting salt and protein helps.',
      route: '/urine-osmolality',
    },
    {
      q: 'Urine osmolality 580 mOsm/kg, urine Na⁺ 5 and K⁺ 43 mmol/L, plasma Na⁺ 144. The kidney is:',
      options: ['Adding free water to the body', 'Removing free water, despite the concentrated urine', 'In neutral water balance', 'Impossible to say without the urine volume sign'],
      answer: 1,
      explanation: 'UNa + UK = 48, well below the plasma Na⁺ of 144, so the urine is electrolyte-poor water leaving the body. The concentration is made up of urea, which does not affect the plasma sodium.',
      route: '/free-water',
    },
    {
      q: 'Someone switches to a diet of mostly beer and is then water-loaded. Compared with before, the minimum urine osmolality and the maximum free-water clearance are:',
      options: ['Both unchanged', 'Minimum osmolality unchanged; maximum free-water clearance much lower', 'Both higher', 'Minimum osmolality higher; clearance unchanged'],
      answer: 1,
      explanation: 'Diluting ability is intact, so the minimum osmolality is the same — but with almost no solute to excrete, the volume that can carry it out is small. Beer potomania causes hyponatraemia at intakes a normal diet would handle.',
      route: '/urine-osmolality',
    },
    {
      q: 'Two patients have a urine osmolality of 540 and pass 1 L/day with a plasma Na⁺ of 130 — one with SIADH (urine Na⁺ 80, K⁺ 50), one with heart failure (urine Na⁺ 10, K⁺ 50). Who is retaining more free water?',
      options: ['They are the same', 'SIADH: UNa + UK (130) equals the plasma Na⁺, so the urine adds no free water, while the heart-failure urine removes some', 'Heart failure', 'Neither retains water'],
      answer: 1,
      explanation: 'Identical urine osmolalities hide opposite effects on the plasma sodium. In SIADH the urine electrolytes are high, so almost none of the urine is electrolyte-free water, and hyponatraemia is harder to correct — the basis for giving salt or urea.',
      route: '/free-water',
    },
    {
      q: 'Two litres of isosmotic diarrhoeal fluid (all Na⁺ and K⁺ salts) are lost. The immediate effect on plasma osmolality is:',
      options: ['It falls', 'It rises', 'No direct change — volume falls without a change in tonicity', 'It depends on ADH'],
      answer: 2,
      explanation: 'Isosmotic loss removes solute and water together. Volume regulation responds (renin, aldosterone, ADH via the baroreceptors); if the patient then drinks water, that ADH turns the volume problem into hyponatraemia.',
      route: '/sodium',
    },
    {
      q: 'Why does a water diuresis peak only 90–120 minutes after drinking?',
      options: ['The water takes that long to absorb', 'Circulating ADH must first be metabolised (half-life 15–20 min)', 'Aquaporins take hours to move', 'The medullary gradient must wash out'],
      answer: 1,
      explanation: 'Secretion stops at once, but the hormone already in the circulation keeps the collecting duct permeable until it is cleared.',
      route: '/adh',
    },
  ],
  updates: [
    {
      topic: 'Copeptin in place of measuring ADH',
      text: 'Vasopressin itself is unstable and hard to assay. Copeptin, released with it in equimolar amounts, is now the practical measurement: a stimulated copeptin (after hypertonic saline or arginine) separates central diabetes insipidus from primary polydipsia far more reliably than the classical water deprivation test.',
      cite: { refs: ['fenske2018', 'winzeler2019', 'christcrain2019'], evidence: 'clinical' },
    },
    {
      topic: 'Solute loading in SIADH',
      text: 'The chapter’s reasoning — that urine output in SIADH depends on solute excretion once ADH is fixed — is the basis of oral urea, now an accepted option in chronic SIADH and endorsed in the European hyponatraemia guideline alongside fluid restriction.',
      cite: { refs: ['spasovski2014', 'decaux2008'], evidence: 'guideline' },
    },
  ],
};
