import type { ChapterContent } from './types';

export const chapter: ChapterContent = {
  n: 10,
  title: 'Acid–base physiology',
  thesis:
    'The extracellular hydrogen ion concentration is about 40 nanomol/L — a millionth of the concentration of sodium — and it is held there because hydrogen ions bind avidly to proteins and change how they work. Three lines of defence protect it: chemical buffers act at once, ventilation adjusts the PCO₂ within minutes, and the kidney sets the plasma bicarbonate over days. Bicarbonate is the buffer that matters clinically, not because its pK is well placed (it is 1.3 units away) but because the lungs can hold or lower the PCO₂ independently — which is what makes it an open, and therefore powerful, buffer system.',
  concepts: [
    {
      heading: 'Why hydrogen ion concentration is regulated so tightly',
      body: [
        'The normal extracellular H⁺ concentration is ≈40 nanomol/L; the range compatible with life is about 16–160 nanomol/L (pH 7.80–6.80). Hydrated H⁺ is small and strongly attracted to negatively charged groups, so it binds proteins more tightly than Na⁺ or K⁺ does. Gaining or losing H⁺ changes a protein’s charge distribution, shape and function.',
        'The effect is measurable: the rate of glycolysis varies inversely with H⁺ concentration, largely through phosphofructokinase. Acidaemia slows glycolysis; alkalaemia accelerates it (and so raises lactate).',
        'pH is simply −log[H⁺]. Within the physiological range each 0.10 fall in pH corresponds to roughly a 25% rise in H⁺: pH 7.40 = 40, 7.30 = 50, 7.20 = 63, 7.10 = 80, 7.00 = 100 nanomol/L.',
      ],
      points: ['pH 7.40 → 40 nmol/L', 'pH 7.30 → 50', 'pH 7.20 → 63', 'pH 7.10 → 80', 'pH 7.00 → 100', 'pH 6.80 → 160 (survival limit)'],
      equation: 'hplus',
      cite: { rose: [10], evidence: 'physiology' },
      route: '/acid-base',
    },
    {
      heading: 'Two classes of acid, two routes of disposal',
      body: [
        'Carbohydrate and fat metabolism generates about 15,000 mmol of CO₂ a day. CO₂ is not itself an acid, but it hydrates to carbonic acid, so it would accumulate as acid if the lungs did not excrete it.',
        'Non-carbonic acid comes mostly from protein: oxidising the sulphur-containing amino acids methionine and cysteine yields sulphuric acid. This amounts to only 50–100 mmol/day, and those H⁺ must be excreted by the kidney.',
        'The difference in scale (15,000 versus 50–100 mmol/day) is why a few minutes of apnoea threatens life while renal failure takes days to produce acidosis.',
      ],
      cite: { rose: [10, 11], evidence: 'physiology' },
      route: '/acid-base',
    },
    {
      heading: 'Buffers and the Henderson–Hasselbalch equation',
      body: [
        'A buffer is a weak acid that can take up or release H⁺, so the free H⁺ concentration barely moves. Strong acids make poor buffers at body pH because they are already fully ionised.',
        'For any weak acid, pH = pKa + log([base]/[acid]). When base and acid concentrations are equal, pH = pKa — the point of maximum buffering. A buffer works well within about ±1.0 pH unit of its pKa; outside that range small additions of acid or base swing the pH a long way.',
        'The book’s worked example: a litre containing 10 mmol each of HPO₄²⁻ and H₂PO₄⁻ sits at pH 6.80. Add 2 mmol of HCl and the ratio becomes 8:12, giving 240 nanomol/L — the H⁺ concentration has risen by only 80 nanomol/L although 2,000,000 nanomol were added. More than 99.99% was buffered; unbuffered, the pH would have been 2.70.',
      ],
      equation: 'hh',
      cite: { rose: [10], evidence: 'physiology' },
      route: '/acid-base',
    },
    {
      heading: 'The bicarbonate system: an open buffer',
      body: [
        'CO₂ dissolves in proportion to its partial pressure: [CO₂]dissolved = 0.03 × PCO₂, so 40 mmHg gives 1.2 mmol/L. Only a tiny fraction hydrates to carbonic acid — about 1 molecule for every 340 of dissolved CO₂ — and carbonic acid in turn is outnumbered ~6800:1 by bicarbonate. So the system is treated as CO₂ ⇌ H⁺ + HCO₃⁻, with an apparent pK′ of 6.10.',
        'That gives the clinical form: pH = 6.10 + log([HCO₃⁻] ÷ 0.03 × PCO₂), or equivalently [H⁺] = 24 × PCO₂ ÷ [HCO₃⁻] in nanomol/L. At 24 mmol/L and 40 mmHg this yields 40 nanomol/L, pH 7.40.',
        'A pK 1.3 units from the working pH should make bicarbonate a poor buffer. It is a powerful one because the system is open at the lung end: as H⁺ is buffered and CO₂ generated, ventilation can blow that CO₂ off instead of letting it accumulate.',
        'The book quantifies it. In a closed system, adding 1.1 mmol/L of HCl takes the H⁺ from 40 to 80 nanomol/L (PCO₂ would rise to 77 mmHg). Hold the PCO₂ at 40 by ventilating and 12 mmol/L can be added for the same change — an eleven-fold gain. Lower the PCO₂ to 20 and 18 mmol/L can be absorbed.',
        'Because of this, non-bicarbonate buffering capacity depends on the amount of buffer and the pH, whereas bicarbonate buffering capacity depends mainly on the plasma bicarbonate concentration and is relatively independent of pH.',
      ],
      equation: 'hh',
      chain: ['H⁺ added', 'HCO₃⁻ + H⁺ → H₂CO₃ → CO₂ + H₂O', 'Chemoreceptors sense the rise in H⁺', '↑ Ventilation blows off the CO₂', 'The reaction is pulled onwards: buffering continues'],
      cite: { rose: [10, 11], evidence: 'physiology' },
      route: '/acid-base',
    },
    {
      heading: 'The isohydric principle',
      body: [
        'All buffers in a solution share one H⁺ concentration, so their acid/base ratios move together. Measure one and you know what the others are doing — which is why the bicarbonate/CO₂ pair can stand for the whole system in clinical practice.',
      ],
      cite: { rose: [10], evidence: 'physiology' },
      route: '/acid-base',
    },
    {
      heading: 'Where buffering actually happens',
      body: [
        'Extracellular: bicarbonate dominates (24 mmol/L), with plasma proteins and phosphate (≈1 mmol/L) minor. Bicarbonate cannot buffer carbonic acid itself — adding H⁺ to HCO₃⁻ simply regenerates it — so respiratory acid loads must be handled inside cells.',
        'Intracellular: proteins, organic and inorganic phosphates, and haemoglobin in red cells. Bone is the third compartment, contributing perhaps 40% of the buffering of an acute acid load and more in chronic acid retention, by exchanging surface Na⁺ and K⁺ and then dissolving mineral to release carbonate and phosphate.',
        'Bone buffering is not purely physicochemical: it does not occur in dead bone, and both reduced osteoblastic and increased osteoclastic activity have been shown.',
      ],
      points: ['Plasma HCO₃⁻: immediate', 'Interstitial HCO₃⁻: ~15 min', 'Cell buffers: 2–4 h', 'Bone: hours to years'],
      cite: { rose: [10], evidence: 'physiology' },
      route: '/acid-base',
    },
    {
      heading: 'What the classical dog experiments showed',
      body: [
        'Nephrectomised dogs given about 180 mmol of HCl (mean weight 18.9 kg): if that acid had been added to 11.3 L of water the H⁺ would have been 16 mmol/L, pH 1.80. In the animals the pH fell only to 7.07, with bicarbonate down from 24 to 7 mmol/L and PCO₂ down from 40 to 25 mmHg.',
        'Accounting for the load: 43% was neutralised by extracellular bicarbonate and 57% inside cells — 36% in exchange for cellular Na⁺, 15% for K⁺ and 6% by chloride entering cells with H⁺.',
        'The K⁺ shift is the clinically important part: a severe metabolic acidaemia can move the plasma K⁺ from 4 to 6–7 mmol/L. The parallel Na⁺ shift is trivial against a plasma Na⁺ of 140.',
      ],
      cite: { rose: [10, 12], evidence: 'experimental' },
      route: '/acid-base',
    },
    {
      heading: 'Respiratory acid loads behave differently',
      body: [
        'In respiratory acidosis there is essentially no extracellular buffering. The H⁺ concentration is limited instead by a rise in plasma bicarbonate from two sources: extracellular carbonic acid dissociating, with H⁺ moving into cells and bone in exchange for Na⁺ and K⁺; and bicarbonate leaving red cells in exchange for chloride, after CO₂ has been hydrated by carbonic anhydrase and the H⁺ buffered by haemoglobin.',
        'Buffering alone raises the bicarbonate by only about 1 mmol/L per 10 mmHg rise in PCO₂ — enough to blunt but not to correct. Renal compensation is the real defence: over 4–5 days it adds about 3.5 mmol/L per 10 mmHg.',
        'So at a PCO₂ of 80 mmHg, buffering alone gives a bicarbonate of ~28 and a markedly acid pH, while buffering plus renal compensation gives ~38 mmol/L and a much better defended pH.',
      ],
      cite: { rose: [10, 20], evidence: 'physiology' },
      route: '/respiratory',
    },
    {
      heading: 'Intracellular pH is what matters, and it follows the plasma',
      body: [
        'Cytosolic pH is lower than extracellular pH and differs between tissues: about 7.06 in skeletal muscle and 7.13 in the early proximal tubule at a plasma pH of 7.40. It is also not uniform within a cell — measuring with a weak acid and with a weak base gives values about 0.5 unit apart, because each concentrates in different compartments.',
        'Extracellular changes produce parallel but smaller intracellular changes, so the measurable plasma pH remains a fair guide to what is happening inside cells, which is where protein function is at stake.',
        'How cells sense the change differs by disorder: CO₂ is lipid-soluble and crosses freely, so a respiratory change is sensed directly. A fall in plasma bicarbonate acts indirectly, by steepening the gradient for bicarbonate exit on the basolateral Na⁺-3HCO₃⁻ carrier of the proximal tubule; the resulting fall in cell pH is an important signal for increased ammonium production.',
      ],
      cite: { rose: [10, 11], evidence: 'experimental' },
      route: '/ammonium',
    },
    {
      heading: 'Naming the disturbances',
      body: [
        'Acidaemia and alkalaemia describe the blood: a high or low H⁺ concentration. Acidosis and alkalosis describe the processes that push it that way. The distinction matters in mixed disorders, where an alkalotic process can be present in a patient who is acidaemic overall.',
        'A primary change in PCO₂ (set by alveolar ventilation) gives a respiratory acidosis or alkalosis; a primary change in plasma bicarbonate gives a metabolic acidosis or alkalosis.',
      ],
      cite: { rose: [10, 17], evidence: 'physiology' },
      route: '/mixed',
    },
    {
      heading: 'Acid loads, bone and stones',
      body: [
        'Because bone buffers acid, an acid load raises calcium release from bone and urinary calcium excretion. A high protein intake raises acid production and therefore calcium excretion, lowers urinary citrate (acidaemia increases its proximal reabsorption, and citrate normally keeps calcium in a soluble complex), and lowers urine pH, which converts urate to the far less soluble uric acid that can nucleate a calcium stone.',
        'In end-stage kidney disease the same chemistry runs for years: retained acid depletes bone calcium, and buffering in skeletal muscle contributes to protein breakdown and wasting.',
      ],
      cite: { rose: [10], evidence: 'clinical' },
      route: '/ckd',
    },
  ],
  numbers: [
    { label: 'Normal arterial [H⁺]', value: '≈40 nanomol/L (pH 7.40)' },
    { label: 'Range compatible with life', value: '16–160 nanomol/L (pH 7.80–6.80)' },
    { label: 'CO₂ produced daily', value: '≈15,000 mmol' },
    { label: 'Non-carbonic acid produced daily', value: '50–100 mmol' },
    { label: 'Dissolved CO₂', value: '0.03 × PCO₂ (1.2 mmol/L at 40 mmHg)' },
    { label: 'Apparent pK′ of the CO₂/HCO₃⁻ system', value: '6.10' },
    { label: 'CO₂ : H₂CO₃', value: '≈340 : 1' },
    { label: 'HCO₃⁻ : H₂CO₃', value: '≈6800 : 1' },
    { label: 'Phosphate pKa', value: '6.80' },
    { label: 'Open-system gain in buffering', value: '≈11-fold at a fixed PCO₂ of 40' },
    { label: 'Buffering of an acid load', value: '≈43% extracellular HCO₃⁻, 57% cells and bone' },
    { label: 'Bone’s share of an acute acid load', value: 'up to ≈40%' },
    { label: 'Buffering of a respiratory acid load', value: '+1 mmol/L HCO₃⁻ per 10 mmHg PCO₂' },
    { label: 'Renal compensation, chronic', value: '+3.5 mmol/L HCO₃⁻ per 10 mmHg PCO₂ (4–5 days)' },
    { label: 'Intracellular pH', value: '≈7.06 muscle, ≈7.13 proximal tubule' },
  ],
  equations: ['hh', 'hplus', 'winters', 'respComp'],
  clinical: [
    'Severe acidaemia raises the plasma K⁺ by shifting it out of cells (4 → 6–7 mmol/L is possible); alkalaemia does the reverse.',
    'Alkalaemia accelerates glycolysis and raises lactate — a mild hyperlactataemia in a severely alkalotic patient need not mean tissue hypoxia.',
    'Bicarbonate cannot buffer carbonic acid, so hyperventilation is the only rapid defence in respiratory acidosis, and the kidney the only effective one.',
    'Chronic acid retention in kidney disease depletes bone and wastes muscle — the rationale for treating the acidosis of CKD.',
    'A high-protein diet promotes calcium stones: more calcium excreted, less citrate, a more acid urine.',
    'Interpreting a blood gas: convert pH to [H⁺] (40 at 7.40, then ±1 nanomol per 0.01 unit near normal) and check that [H⁺] = 24 × PCO₂ ÷ HCO₃⁻ — if it does not, the numbers are internally inconsistent.',
  ],
  pathology: [
    { name: 'Metabolic acidosis', broken: 'Plasma bicarbonate (consumed or lost)', consequence: 'Acidaemia, hyperventilation, K⁺ shifted out of cells, bone buffering', route: '/metabolic-acidosis' },
    { name: 'Metabolic alkalosis', broken: 'Bicarbonate excess or H⁺ loss', consequence: 'Alkalaemia, hypoventilation, K⁺ into cells, raised lactate', route: '/metabolic-alkalosis' },
    { name: 'Respiratory acidosis', broken: 'Alveolar ventilation', consequence: 'Little extracellular buffering; relies on cell buffers acutely and the kidney over 4–5 days', route: '/respiratory' },
    { name: 'Respiratory alkalosis', broken: 'Excess ventilation', consequence: 'Buffers release H⁺; chronic hypocapnia lowers bicarbonate and shifts buffering toward cells and bone', route: '/respiratory' },
    { name: 'Uraemic acidosis', broken: 'Renal acid excretion', consequence: 'Years of bone buffering: calcium loss, bone disease and muscle wasting', route: '/ckd' },
    { name: 'Acid-load hypercalciuria', broken: 'Bone buffering of a dietary acid load', consequence: 'Calcium excretion up, citrate down, urine pH down — calcium and uric acid stones', route: '/minerals' },
  ],
  questions: [
    {
      q: 'Why is bicarbonate an effective buffer at pH 7.40 despite a pK′ of 6.10?',
      options: ['Its concentration is very high', 'The system is open: ventilation removes the CO₂ generated, so the reaction keeps going', 'Its pK is actually 7.4 in vivo', 'It is not effective'],
      answer: 1,
      explanation: 'Holding the PCO₂ constant increases buffering capacity about eleven-fold; lowering it increases it further. A closed bicarbonate system would be a poor buffer at this pH.',
      route: '/acid-base',
    },
    {
      q: '180 mmol of HCl is given to a nephrectomised dog. Roughly how is it buffered?',
      options: ['Almost entirely by extracellular bicarbonate', 'About 43% by extracellular bicarbonate, 57% by cells and bone', 'Almost entirely inside cells', 'By the kidney'],
      answer: 1,
      explanation: 'Swan and Pitts: of the load, 78 mmol went on extracellular bicarbonate and 103 mmol entered cells — 65 in exchange for Na⁺, 28 for K⁺, 10 accompanied by chloride.',
      route: '/acid-base',
    },
    {
      q: 'A patient’s PCO₂ is fixed at 40 mmHg by mechanical ventilation. What determines how far the pH falls after an acid load?',
      options: ['Only the size of the load', 'The size of the load and the starting bicarbonate concentration (plus non-bicarbonate buffers)', 'The respiratory rate', 'The urine pH'],
      answer: 1,
      explanation: 'With the PCO₂ fixed, pH depends on how far the bicarbonate falls; a patient who starts with a low bicarbonate has far less reserve. This is why a superimposed acid load is so dangerous in established metabolic acidosis.',
      route: '/acid-base',
    },
    {
      q: '90 mmol of bicarbonate is given intravenously. The plasma bicarbonate rises to 32 at 10 min, then drifts down to 27 by 3 hours. Why?',
      options: ['It is excreted immediately', 'It distributes into the interstitium and then cells and bone release H⁺, consuming some of it', 'It is metabolised to CO₂ and lost', 'Measurement error'],
      answer: 1,
      explanation: 'Buffering has a time course: plasma at once, interstitium over ~15 min, cells and bone over 2–4 h. Restoring balance then needs the kidney to excrete the excess bicarbonate.',
      route: '/metabolic-alkalosis',
    },
    {
      q: 'In respiratory acidosis, why is extracellular bicarbonate not a useful buffer?',
      options: ['Its concentration falls', 'Adding H⁺ from carbonic acid to bicarbonate just regenerates carbonic acid — a buffer cannot buffer itself', 'The pK changes', 'CO₂ cannot enter the blood'],
      answer: 1,
      explanation: 'Carbonic acid must be buffered by non-bicarbonate buffers: haemoglobin, cell proteins and phosphates, and bone.',
      route: '/respiratory',
    },
    {
      q: 'Arterial pH 7.10. The hydrogen ion concentration is about:',
      options: ['20 nanomol/L', '40 nanomol/L', '80 nanomol/L', '160 nanomol/L'],
      answer: 2,
      explanation: 'Each 0.30 fall in pH doubles [H⁺]: 7.40 → 40, 7.10 → 80, 6.80 → 160.',
      route: '/equations',
    },
  ],
  updates: [
    {
      topic: 'The Stewart (physicochemical) approach',
      text: 'An alternative framework treats pH as determined by three independent variables — the strong ion difference, total weak acid (mainly albumin and phosphate) and PCO₂ — rather than by bicarbonate. It makes the same predictions as the traditional approach in most situations and is most useful where albumin is very abnormal; the book’s bicarbonate-centred method remains standard in clinical practice.',
      cite: { refs: ['figge1998', 'kraut2010'], evidence: 'reasoning' },
    },
    {
      topic: 'Treating the acidosis of chronic kidney disease',
      text: 'The chapter’s account of bone and muscle buffering predicts that correcting chronic metabolic acidosis should protect both. Trials of alkali in CKD show improved bone and nutritional markers and slower loss of GFR, and KDIGO now suggests treating a serum bicarbonate below 18–20 mmol/L, though optimal targets remain uncertain.',
      cite: { refs: ['debrito2009', 'wesson2020', 'kdigo2024ckd'], evidence: 'guideline' },
    },
  ],
};
