import type { ChapterContent } from './types';

export const chapter: ChapterContent = {
  n: 12,
  title: 'Potassium homeostasis',
  thesis:
    'Ninety-eight per cent of body potassium is inside cells, so the plasma concentration is a window onto a very small compartment: moving just 1.5–2% of cell K⁺ outwards can take the plasma level to 8 mmol/L. Two systems therefore protect it. Internal balance — the Na⁺-K⁺-ATPase, helped by insulin and β₂-catecholamines — parks a dietary load inside cells within minutes. External balance — secretion by principal cells in the distal nephron, set by aldosterone and by the plasma K⁺ itself — then removes it over hours. Distal flow and the lumen-negative voltage are permissive, and it is their opposite movements that let aldosterone regulate sodium and potassium independently.',
  concepts: [
    {
      heading: 'Why the plasma concentration is so precarious',
      body: [
        'Total body potassium is 3000–4000 mmol (50–55 mmol/kg), 98% intracellular: cell K⁺ ≈140 mmol/L against a plasma 4. The Na⁺-K⁺-ATPase maintains that gradient, pumping 3 Na⁺ out for 2 K⁺ in.',
        'The ratio of cell to extracellular K⁺ sets the resting membrane potential, which is why both hypo- and hyperkalaemia cause muscle paralysis and cardiac arrhythmias.',
        'Potassium also matters for cell metabolism — protein and glycogen synthesis — and depletion impairs urinary concentration: about a 350 mmol deficit (10% of body stores) measurably lowers maximum urine osmolality.',
        'The arithmetic of a meal makes the problem concrete: three large glasses of orange juice contain ~40 mmol of K⁺. Spread through 17 L of extracellular fluid that would raise the plasma K⁺ by 2.4 mmol/L — so it cannot be left there while the kidney works.',
      ],
      points: ['Total body K⁺ 3000–4000 mmol (50–55 mmol/kg)', '98% intracellular; cell 140 vs plasma 4 mmol/L', 'Moving 1.5–2% of cell K⁺ out → plasma 8 mmol/L', 'Na⁺-K⁺-ATPase: 3 Na⁺ out / 2 K⁺ in'],
      cite: { rose: [12], evidence: 'physiology' },
      route: '/potassium',
    },
    {
      heading: 'Internal balance: insulin and catecholamines',
      body: [
        'Insulin drives K⁺ into muscle and liver by stimulating the Na⁺-K⁺-ATPase, independently of its effect on glucose transport. Eating glucose with potassium blunts the rise in plasma K⁺; insulin deficiency raises the baseline K⁺ by 0.4–0.5 mmol/L and exaggerates the response to a load.',
        'β₂-receptors promote cellular uptake (α-receptors oppose it). Pre-treatment with propranolol makes the rise after a K⁺ load larger and longer. Endogenous adrenaline released in stress — coronary ischaemia, for example — lowers the plasma K⁺ by 0.5–0.6 mmol/L; β₂-agonists given for asthma or heart failure do the same, and in someone already hypokalaemic on a diuretic can take it below 2.8.',
        'Both hormones act permissively: a K⁺ load does not itself raise catecholamines, and the evidence that it raises insulin at physiological increments is weak. Their deficiency raises the baseline only transiently, because the kidney then excretes the excess — which is why fasting plasma K⁺ is usually normal in people on β-blockers or with type 1 diabetes.',
        'Therapeutically this is the basis of insulin with glucose for acute hyperkalaemia, and of the warning that giving potassium in a dextrose solution can transiently lower the plasma level further.',
      ],
      chain: ['K⁺-rich meal absorbed', 'Plasma K⁺ rises slightly', 'Insulin and basal β₂ tone stimulate Na⁺-K⁺-ATPase', 'K⁺ parked in muscle and liver within minutes', 'Kidney excretes the load over hours'],
      cite: { rose: [12, 28], evidence: 'physiology', refs: ['rosa1980', 'allon1989', 'defronzo1980'] },
      route: '/potassium',
    },
    {
      heading: 'Other things that move potassium across cell membranes',
      body: [
        'Plasma K⁺ itself: a rise drives K⁺ into cells and a fall draws it out, which is why the plasma concentration usually does track total body stores — with important exceptions.',
        'Exercise: K⁺ leaves muscle during depolarisation and through ATP-sensitive channels that open as ATP falls. The local rise is vasodilatory and helps match blood flow to work. Systemically it is 0.3–0.4 mmol/L with slow walking, 0.7–1.2 with moderate exercise and up to 2.0 with exhausting exercise, reversing within minutes and sometimes undershooting by 0.4–0.5. Conditioning blunts it; β-blockade exaggerates it, by 1.5 to as much as 4 mmol/L. Even clenching the fist during venepuncture can add 1–2 mmol/L to the sample.',
        'Extracellular pH: in mineral acidosis H⁺ enters cells and K⁺ and Na⁺ leave, raising plasma K⁺ by 0.2–1.7 mmol/L per 0.1 unit fall in pH — a wide and unpredictable range. Organic acidoses (lactic acidosis, ketoacidosis) raise it much less, because the anion accompanies H⁺ into the cell and perhaps because the anions stimulate insulin release. Metabolic alkalosis lowers plasma K⁺ only slightly.',
        'Hyperosmolality: plasma K⁺ rises 0.4–0.8 mmol/L per 10 mOsm/kg rise in effective osmolality. Water leaving cells concentrates cell K⁺ (favouring exit) and drags K⁺ with it. This is why hyperglycaemia in uncontrolled diabetes raises plasma K⁺ even when total body K⁺ is depleted.',
        'Cell turnover: tissue breakdown (trauma, tumour lysis) releases K⁺; rapid cell production (treating megaloblastic anaemia with B12 or folate) consumes it.',
      ],
      points: ['Acidosis (mineral): +0.2–1.7 mmol/L per 0.1 pH unit', 'Hyperosmolality: +0.4–0.8 mmol/L per 10 mOsm/kg', 'Exercise: +0.3 to +2.0 mmol/L by intensity', 'Fist clenching at venepuncture: +1–2 mmol/L (spurious)'],
      cite: { rose: [12], evidence: 'physiology' },
      route: '/hyperkalemia',
    },
    {
      heading: 'Segmental handling: excretion is distal secretion',
      body: [
        'Almost all filtered K⁺ is reabsorbed before the distal tubule — passively with water and solute in the proximal tubule, and on NKCC2 in the thick ascending limb — so less than 10% of the filtered load reaches the early distal tubule. Some of the K⁺ taken up by the loop is recycled within the medulla.',
        'What appears in the urine is therefore almost entirely what the connecting segment and the principal cells of the cortical and outer medullary collecting tubules secrete. That is what makes urinary K⁺ regulable: the kidney is not fine-tuning reabsorption of a large filtered load but adding a variable amount at the end.',
        'Secretion is opposed by K⁺ reabsorption in intercalated cells through a luminal H⁺-K⁺-ATPase, which secretes H⁺ while reabsorbing K⁺. Its activity rises in K⁺ depletion and falls with loading — a mechanism that links potassium conservation to acid secretion.',
      ],
      cite: { rose: [12, 5], evidence: 'physiology' },
      route: '/potassium',
    },
    {
      heading: 'The principal cell: three determinants of a passive step',
      body: [
        'K⁺ enters the cell basolaterally on the Na⁺-K⁺-ATPase and leaves passively through luminal K⁺ channels. Because the final step is passive, only three things govern it: the concentration gradient from cell to lumen, the electrical gradient, and the number of open channels.',
        'The cell’s total K⁺ is 140–150 mmol/L but its activity is nearer 80–90; the size of this transport pool is not fixed — it rises after a K⁺ load and falls with depletion, under the control of the plasma K⁺ and aldosterone.',
        'The electrical gradient comes from Na⁺ entering through ENaC: reabsorbing a cation leaves the lumen negative, and chloride follows only after a delay. Replace luminal Na⁺ with a non-reabsorbable cation and the voltage falls to zero; replace luminal Cl⁻ with sulphate and the voltage — and K⁺ secretion — increase.',
      ],
      chain: ['Na⁺-K⁺-ATPase loads the cell with K⁺', 'ENaC lets Na⁺ in: lumen becomes 15–50 mV negative', 'K⁺ leaves through ROMK/BK channels down that gradient', 'Flow carries the secreted K⁺ away, keeping the gradient favourable'],
      cite: { rose: [12, 5], evidence: 'physiology' },
      route: '/distal',
    },
    {
      heading: 'Aldosterone and the plasma potassium are the regulators',
      body: [
        'Aldosterone stimulates every step: more open Na⁺ channels (the earliest change), more open K⁺ channels, and more Na⁺-K⁺-ATPase. The extra Na⁺ entry both enlarges the K⁺ transport pool and makes the lumen more negative. The 3:2 ratio of Na⁺ reabsorbed to K⁺ secreted in the cortical collecting tubule matches the pump’s stoichiometry.',
        'Amiloride shows the primacy of the sodium step: closing ENaC removes the voltage and abolishes the aldosterone-induced rise in K⁺ secretion, without any direct action on potassium.',
        'The plasma K⁺ acts independently. In adrenalectomised dogs given fixed aldosterone, K⁺ excretion rises steeply once the plasma K⁺ passes about 4.2 mmol/L. Potassium alone reproduces everything aldosterone does to the principal cell. In an intact animal both act together, which is why chronic hyperkalaemia cannot occur without a defect in K⁺ secretion.',
        'Fixed aldosterone also sets the steady-state plasma K⁺: at a constant intake, roughly 4.3 mmol/L at physiological replacement, 3.4 with hyperaldosteronism and 5.0 with hypoaldosteronism.',
        'ADH raises luminal K⁺ permeability too — not as a regulator of potassium, but so that the fall in distal flow during antidiuresis does not inadvertently reduce K⁺ excretion.',
      ],
      cite: { rose: [12, 6], evidence: 'experimental' },
      route: '/raas',
    },
    {
      heading: 'Distal flow: permissive, and the key to independence',
      body: [
        'Raising distal flow washes secreted K⁺ away and replaces it with K⁺-poor fluid, keeping the luminal concentration low and the gradient favourable. Within the physiological range the luminal K⁺ concentration stays nearly constant as flow rises, so more K⁺ is secreted without any change in concentration. Only when distal flow is very low does luminal K⁺ rise enough to limit secretion.',
        'Higher flow usually brings more Na⁺ to the secretory site as well, which adds to the voltage.',
        'This is the mechanism that lets aldosterone handle sodium and potassium separately (Table 6-3). A salt load suppresses aldosterone, which would tend to retain K⁺ — but the accompanying rise in distal flow offsets it, so K⁺ excretion is unchanged. Volume depletion raises aldosterone, which would waste K⁺ — but distal flow falls, so again K⁺ excretion is unchanged. That is why untreated heart failure and cirrhosis, with high aldosterone, are usually normokalaemic.',
        'Break the pairing and potassium moves. Give a salt load when aldosterone cannot fall (primary aldosteronism): high flow and high aldosterone together cause K⁺ wasting — the basis of salt-loading tests. Give a diuretic in heart failure: flow rises while aldosterone stays high, and hypokalaemia follows. That is the principal mechanism of diuretic-induced potassium loss.',
      ],
      chain: ['Aldosterone ↑ and distal flow ↓ (volume depletion) → K⁺ excretion unchanged', 'Aldosterone ↓ and distal flow ↑ (salt load) → K⁺ excretion unchanged', 'Aldosterone ↑ and distal flow ↑ (diuretic, or aldosteronism + salt) → K⁺ wasting', 'Aldosterone ↓ and distal flow ↓ → K⁺ retention'],
      cite: { rose: [12, 6], evidence: 'physiology', refs: ['woda2001'] },
      route: '/potassium',
    },
    {
      heading: 'Non-reabsorbable anions',
      body: [
        'Sodium delivered with an anion that cannot be reabsorbed leaves less chloride to dissipate the lumen-negative voltage, so K⁺ (and H⁺) secretion rises. The effect is strongest when the person is volume depleted and avidly reabsorbing sodium.',
        'Clinical instances: bicarbonate in proximal (type 2) RTA and in vomiting; β-hydroxybutyrate and acetoacetate in ketoacidosis; high-dose penicillins such as carbenicillin, which carries 4.7 mmol of Na⁺ per gram and delivers a large non-reabsorbable anion load.',
        'These effects can override the direct tendency of acidaemia to reduce K⁺ secretion — which is why type 2 RTA and diabetic ketoacidosis cause potassium wasting despite the acidosis.',
      ],
      cite: { rose: [12, 11], evidence: 'physiology' },
      route: '/hypokalemia',
    },
    {
      heading: 'Potassium adaptation',
      body: [
        'Intake can be raised from 60–80 to 500 mmol/day and balance still maintained. Given acutely that load could be lethal; given gradually it is handled — potassium adaptation.',
        'In humans loaded with 400 mmol/day, plasma K⁺ rose from 3.8 to 4.8 mmol/L and aldosterone 2.5-fold in the first two days; by day 20 both had fallen back toward baseline (K⁺ 4.2) while excretion stayed high. The efficiency of secretion itself had increased, through raised Na⁺-K⁺-ATPase activity and proliferation of basolateral membrane in the distal nephron. At any given plasma K⁺, adapted animals secrete two to four times more.',
        'Adaptation also has extrarenal limbs: greater uptake into cells, and colonic secretion — which can account for 30–50% of dietary potassium in end-stage kidney disease.',
        'The clinical case is chronic kidney disease: fewer nephrons, the same intake, so excretion per nephron must rise. Balance is held until late, provided intake is not excessive, urine flow is adequate and aldosterone can respond. Tellingly, the rise in distal Na⁺-K⁺-ATPase only appears when intake is not restricted — the adaptation is driven by need, not by nephron loss itself.',
      ],
      cite: { rose: [12], evidence: 'experimental' },
      route: '/ckd',
    },
    {
      heading: 'Potassium depletion',
      body: [
        'Excretion falls, at first because aldosterone release falls (a direct effect of K⁺ on the zona glomerulosa), then because the distal cell K⁺ concentration falls — at which point giving aldosterone no longer restores secretion.',
        'Active reabsorption adds to it: the H⁺-K⁺-ATPase of intercalated cells is stimulated by depletion, reabsorbing K⁺ while secreting H⁺ (part of why K⁺ depletion sustains a metabolic alkalosis).',
        'The kidney is nevertheless an imperfect conserver: excretion falls only to 15–25 mmol/day with a deficit of 50–150 mmol, and to 5–15 mmol/day with larger losses — partly because K⁺ leaks passively through a non-selective channel in the inner medullary collecting duct.',
      ],
      cite: { rose: [12, 27], evidence: 'physiology' },
      route: '/hypokalemia',
    },
  ],
  numbers: [
    { label: 'Total body K⁺', value: '3000–4000 mmol (50–55 mmol/kg)' },
    { label: 'Fraction intracellular', value: '98%' },
    { label: 'Cell vs plasma K⁺', value: '≈140 vs 4 mmol/L' },
    { label: 'Normal intake', value: '40–120 mmol/day' },
    { label: 'Stool and sweat losses', value: '5–10 and 0–10 mmol/day' },
    { label: 'K⁺ reaching the early distal tubule', value: '< 10% of the filtered load' },
    { label: 'Lumen-negative voltage (CCT)', value: '−15 to −50 mV' },
    { label: 'Na⁺ reabsorbed : K⁺ secreted', value: '3 : 2' },
    { label: 'Plasma K⁺ at which excretion climbs steeply', value: '≈4.2 mmol/L' },
    { label: 'Steady-state K⁺ by aldosterone (dog)', value: '4.3 normal, 3.4 excess, 5.0 deficiency' },
    { label: 'Adaptation ceiling', value: 'intake up to 500 mmol/day tolerated if gradual' },
    { label: 'Minimum urinary K⁺ in depletion', value: '15–25, then 5–15 mmol/day' },
    { label: 'Colonic secretion in ESKD', value: '30–50% of dietary K⁺' },
    { label: 'Effect of adrenaline in stress', value: '−0.5 to −0.6 mmol/L' },
  ],
  equations: ['ttkg', 'ukcr'],
  clinical: [
    'Chronic hyperkalaemia always means impaired distal K⁺ secretion — hypoaldosteronism or reduced distal flow/Na⁺ delivery — because adaptation would otherwise handle the load.',
    'Hypokalaemia from renal loss means the distal secretory process has been activated: mineralocorticoid excess with adequate flow, increased flow with adequate aldosterone (diuretics), or Na⁺ delivered with a non-reabsorbable anion.',
    'Untreated heart failure and cirrhosis are usually normokalaemic despite high aldosterone, because distal flow is low — add a diuretic and K⁺ wasting appears.',
    'Insulin with glucose lowers plasma K⁺ acutely in hyperkalaemia; β₂-agonists do the same; β-blockers oppose it.',
    'Hyperglycaemia raises plasma K⁺ through hyperosmolality even when total body K⁺ is depleted — as in diabetic ketoacidosis, where the measured K⁺ hides a large deficit.',
    'Mineral acidosis raises plasma K⁺ far more predictably than lactic acidosis or ketoacidosis.',
    'A fist clenched during venepuncture, or a delayed sample, can produce spurious hyperkalaemia.',
    'In advanced kidney disease, colonic secretion becomes a significant route — relevant when constipation or bowel disease alters it.',
  ],
  pathology: [
    { name: 'Hypoaldosteronism / type 4 RTA', broken: 'Aldosterone effect on principal cells', consequence: 'Hyperkalaemia with mild metabolic acidosis; urine K⁺ inappropriately low', route: '/hyperkalemia' },
    { name: 'Diuretic-induced hypokalaemia', broken: 'The pairing of flow and aldosterone', consequence: 'High distal flow with high aldosterone: K⁺ wasting, alkalosis', route: '/diuretics' },
    { name: 'Primary aldosteronism', broken: 'Aldosterone cannot be suppressed', consequence: 'K⁺ wasting that worsens with a salt load (high flow and high aldosterone together)', route: '/raas' },
    { name: 'Digitalis overdose', broken: 'Na⁺-K⁺-ATPase', consequence: 'K⁺ cannot enter cells: plasma K⁺ up to 13.5 mmol/L', route: '/hyperkalemia' },
    { name: 'Diabetic ketoacidosis', broken: 'Insulin (uptake) plus hyperosmolality and non-reabsorbable anions', consequence: 'Measured K⁺ normal or high despite a large total body deficit; falls precipitously with insulin', route: '/hyperglycemia' },
    { name: 'Tumour lysis / crush injury', broken: 'Cell integrity', consequence: 'K⁺ released faster than cells and kidney can take it up', route: '/hyperkalemia' },
    { name: 'K⁺ depletion', broken: 'Distal cell K⁺ pool; H⁺-K⁺-ATPase activated', consequence: 'Urinary K⁺ falls to 5–25 mmol/day; concentrating defect; alkalosis maintained', route: '/hypokalemia' },
  ],
  questions: [
    {
      q: 'Why are untreated patients with heart failure and high aldosterone usually normokalaemic?',
      options: ['Aldosterone is ineffective', 'Distal flow is low, offsetting the high aldosterone — the two determinants move in opposite directions', 'They eat more potassium', 'The kidney reabsorbs K⁺'],
      answer: 1,
      explanation: 'This pairing is what lets aldosterone regulate Na⁺ and K⁺ independently. Give a loop diuretic and flow rises while aldosterone stays high — then K⁺ wasting appears.',
      route: '/potassium',
    },
    {
      q: 'A patient with an aldosterone-producing adenoma is given a sodium load. Urinary K⁺ excretion:',
      options: ['Falls', 'Rises — high distal flow now combines with aldosterone that cannot be suppressed', 'Is unchanged', 'Depends on the urine pH'],
      answer: 1,
      explanation: 'In a normal person a salt load suppresses aldosterone, so K⁺ excretion does not change. When aldosterone is autonomous the two stimuli add, which is the basis of salt-loading tests.',
      route: '/raas',
    },
    {
      q: 'Which of these raises the plasma K⁺?',
      options: ['An ACE inhibitor', 'A thiazide diuretic', 'An intravenous glucose infusion in a non-diabetic', 'An α-adrenergic blocker'],
      answer: 0,
      explanation: 'Less angiotensin II means less aldosterone and less distal K⁺ secretion. Thiazides and glucose (via insulin) lower it; α-blockade tends to promote cellular uptake by leaving β₂ effects unopposed.',
      route: '/hyperkalemia',
    },
    {
      q: 'How would you distinguish renal from gastrointestinal potassium loss?',
      options: ['Plasma K⁺', 'Urinary K⁺ excretion (or the urine K⁺/creatinine ratio): inappropriately high with renal loss, low with extrarenal loss', 'Urine osmolality', 'Serum aldosterone'],
      answer: 1,
      explanation: 'With extrarenal loss the kidney should conserve, taking excretion down to 15–25 mmol/day. A higher value in a hypokalaemic patient points to the kidney as the route.',
      route: '/hypokalemia',
    },
    {
      q: 'In diabetic ketoacidosis the plasma K⁺ is 5.2. What is total body potassium?',
      options: ['High', 'Normal', 'Usually substantially depleted — hyperosmolality, insulin deficiency and acidosis have shifted K⁺ out of cells while osmotic diuresis lost it', 'Unpredictable'],
      answer: 2,
      explanation: 'Treating with insulin and fluid moves K⁺ back into cells and unmasks the deficit, which is why potassium is replaced early in ketoacidosis.',
      route: '/hyperglycemia',
    },
    {
      q: 'Why does 500 mmol/day of potassium not kill someone who works up to it gradually?',
      options: ['It is not absorbed', 'Potassium adaptation: distal Na⁺-K⁺-ATPase activity and secretory capacity rise, so secretion at any given plasma K⁺ is two to four times greater', 'It is stored in bone', 'Aldosterone falls'],
      answer: 1,
      explanation: 'The same adaptation lets people with advanced kidney disease stay in balance until very late, aided by colonic secretion.',
      route: '/ckd',
    },
  ],
  updates: [
    {
      topic: 'The WNK–NCC potassium switch',
      text: 'A mechanism the book predates now explains how the distal nephron distinguishes a potassium load from volume depletion. Plasma K⁺ regulates WNK kinases in the distal convoluted tubule: a low K⁺ activates NCC (retaining Na⁺ and reducing delivery to the secretory site), a high K⁺ inhibits it (raising delivery). This provides the molecular basis for the aldosterone paradox — how the same hormone can serve Na⁺ retention in one state and K⁺ excretion in another.',
      cite: { refs: ['terker2015', 'hoorn2011wnk', 'subramanya2014'], evidence: 'experimental' },
    },
    {
      topic: 'Abandoning the TTKG',
      text: 'The transtubular potassium gradient, once used to judge distal secretion, rests on assumptions about medullary urea and water handling that do not hold. Its originators recommended abandoning it; the urine K⁺/creatinine ratio and a direct 24-hour excretion are used instead.',
      cite: { refs: ['kamel2011ttkg'], evidence: 'clinical' },
    },
    {
      topic: 'Potassium intake and outcomes',
      text: 'Beyond acute homeostasis, higher dietary potassium is associated with lower blood pressure and cardiovascular risk. In a cluster-randomised trial in rural China, a 75% NaCl / 25% KCl salt substitute reduced stroke, major cardiovascular events and death in people with previous stroke or treated hypertension. Such substitutes carry a hyperkalaemia risk in advanced kidney disease, who were not the population studied.',
      cite: { refs: ['neal2021ssass', 'palmer2015k', 'gumz2015'], evidence: 'clinical' },
    },
  ],
};
