import type { ChapterContent } from './types';

export const chapter: ChapterContent = {
  n: 14,
  title: 'Hypovolemic states',
  thesis:
    'Volume depletion means the extracellular fluid has been lost faster than it was replaced — from gut, kidney, skin or into a third space. Two things normally prevent it: intake is far above basal needs, and the kidney can reduce sodium excretion to almost nothing. Its consequences follow a hierarchy: first the compensations (sympathetic tone, angiotensin II, ADH), then postural symptoms, then hypotension and shock. Which electrolyte and acid–base disorder accompanies it depends entirely on the composition of the fluid lost — the same volume deficit can arrive with alkalosis, acidosis, hyponatraemia or hypernatraemia.',
  concepts: [
    {
      heading: 'Where the fluid goes',
      body: [
        'Gastrointestinal: 3–6 L is secreted into the gut each day and nearly all reabsorbed, with only 100–200 mL lost in stool. Vomiting or nasogastric suction removes fluid rich in H⁺ and Cl⁻ (hence metabolic alkalosis); diarrhoea, fistulas and ostomies remove alkaline intestinal, pancreatic and biliary fluid (hence metabolic acidosis). All gastrointestinal secretions contain potassium, so hypokalaemia is common. Bleeding loses plasma, so electrolytes are usually unchanged — apart from lactic acidosis in shock.',
        'Renal: diuretics, osmotic diuresis (glucose in uncontrolled diabetes), adrenal insufficiency and salt-wasting nephropathies. Because 130–180 L is filtered daily and more than 98% reabsorbed, a small fractional fall in reabsorption is a large loss.',
        'Skin and respiratory: 700–1000 mL a day of insensible loss, plus sweat (Na⁺ 30–50 mmol/L) which can exceed 1–2 L/h in someone exercising in heat. Burns and exudative lesions lose fluid of plasma-like composition.',
        'Third space: fluid sequestered where it is no longer in equilibrium with the extracellular fluid — 1500–2000 mL into the tissues around a fractured hip, or into bowel in obstruction and peritonitis. The distinction from cirrhotic ascites is speed: ascites accumulates slowly enough for renal retention to keep up, so those patients present with oedema rather than hypovolaemia.',
      ],
      points: ['Gastric loss → metabolic alkalosis, hypokalaemia', 'Intestinal/pancreatic/biliary loss → metabolic acidosis, hypokalaemia', 'Bleeding → no electrolyte change (except lactate in shock)', 'Pure water loss → hypernatraemia, mostly intracellular'],
      cite: { rose: [14], evidence: 'clinical' },
      route: '/hypovolemia',
    },
    {
      heading: 'Salt-wasting nephropathy, and why it is often self-inflicted',
      body: [
        'Most patients with a GFR under 25 mL/min cannot maximally conserve sodium if moved abruptly to a low-salt diet: an obligatory loss of 10–40 mmol/day, against a normal minimum of under 5. Severe salt wasting — over 100 mmol and 2 L a day — is uncommon and points to tubulointerstitial disease, medullary cystic disease or partial obstruction.',
        'Three mechanisms: the osmotic diuresis of increased urea excretion per surviving nephron; direct tubular damage that can impair the response to aldosterone; and, probably most important, the natriuretic adaptation that lets a reduced nephron mass excrete a normal salt intake.',
        'That last mechanism explains a striking observation: apparent salt wasters losing as much as 300 mmol/day acutely can maintain balance on 5 mmol/day if intake is reduced gradually over weeks. The wasting is persistence of an adaptation, not a fixed defect — so treatment is to find the intake that holds balance, usually above 60–80 mmol/day, rather than to assume a fixed requirement.',
        'Post-obstructive diuresis is usually not salt wasting at all: it is the appropriate excretion of fluid retained during the obstruction. Some replacement (50–75 mL/h of half-isotonic saline) is reasonable because a mild sodium-wasting and concentrating defect exists, but over-replacement simply perpetuates the diuresis.',
      ],
      cite: { rose: [14], evidence: 'clinical' },
      route: '/tubulointerstitial',
    },
    {
      heading: 'The haemodynamic sequence',
      body: [
        'First the plasma volume and venous return fall. Cardiopulmonary receptors in the atria and pulmonary veins sense it and raise sympathetic tone. With larger losses cardiac output falls, blood pressure drops, and the carotid sinus and aortic arch baroreceptors trigger a more generalised sympathetic response involving the splanchnic and renal circulations.',
        'The result is venoconstriction (70% of blood volume is venous), increased contractility and heart rate, and arteriolar constriction — preserving cerebral and coronary perfusion at the expense of skin, muscle, gut and kidney.',
        'By severity: about 10% of blood volume (a unit donated) is fully compensated apart from a faster pulse. At 16–25%, compensation maintains recumbent pressure but not upright — postural dizziness, with sympathetic responses now maximal. Beyond that, hypotension appears even lying down, and then shock.',
      ],
      chain: ['↓ Plasma volume → ↓ venous return', 'Cardiopulmonary receptors → ↑ sympathetic tone', '↓ Cardiac output → ↓ BP → arterial baroreceptors', 'Venoconstriction, tachycardia, arteriolar constriction, renin release', 'Cerebral and coronary flow preserved; skin, gut and kidney sacrificed'],
      cite: { rose: [14, 8], evidence: 'physiology' },
      route: '/hypovolemia',
    },
    {
      heading: 'Symptoms, and why pure water loss feels different',
      body: [
        'Three groups: symptoms of the loss itself (vomiting, diarrhoea, polyuria), of the hypovolaemia (lassitude, fatigue, thirst, muscle cramps, postural dizziness; then abdominal or chest pain and confusion from mesenteric, coronary and cerebral ischaemia), and of the accompanying electrolyte disorder (weakness in potassium disorders; lethargy, seizures and coma in sodium disorders and hyperglycaemia).',
        'Symptomatic hypovolaemia is mostly a feature of isosmotic salt and water loss, where the whole deficit comes from the extracellular fluid. With pure water loss the rise in osmolality pulls water out of cells, so about two-thirds of the deficit is borne by the intracellular compartment — such patients show the neurological features of hypernatraemia before they look extracellularly depleted.',
        'One symptom is nearly specific: extreme salt craving in primary adrenal insufficiency, reported by about 20% of patients — salting everything, even eating salt off the hand.',
      ],
      cite: { rose: [14, 24], evidence: 'clinical' },
      route: '/hypovolemia',
    },
    {
      heading: 'What the examination is actually worth',
      body: [
        'The physical signs are insensitive and non-specific. In severe bleeding, the findings that perform best are severe postural dizziness preventing upright measurement, and a postural pulse increment of 30 beats/min or more. For milder losses, the useful signs are a dry axilla, dry mucous membranes and reduced skin turgor — and their absence does not exclude hypovolaemia.',
        'Skin turgor is age-dependent: elasticity falls after 55–60 years, so reduced turgor means less in the elderly (assess the inner thigh or over the sternum), and obesity masks it. Normal turgor never excludes a mild deficit.',
        'Blood pressure must be read against the patient’s own baseline — 120/80 is low for someone who usually runs 180/100. With marked vasoconstriction, Korotkoff sounds and the radial pulse become faint, so cuff pressure can read falsely low; an intra-arterial line may be needed.',
        'Venous pressure is the most direct bedside estimate of filling. Examined properly (trunk at 15–30°, external jugular, occluding above after filling from below), the normal is 1–8 cmH₂O above the right atrium. Failure to see the vein is not a low venous pressure; it is an unsuccessful examination.',
      ],
      points: ['Postural pulse rise ≥ 30/min: the best single sign in blood loss', 'Dry axilla: useful positive', 'Normal skin turgor: does not exclude hypovolaemia', 'Normal JVP range: 1–8 cmH₂O'],
      cite: { rose: [14], evidence: 'clinical' },
      route: '/hypovolemia',
    },
    {
      heading: 'Laboratory findings — and their traps',
      body: [
        'Urine sodium under 25 mmol/L (sometimes as low as 1) is the expected renal response, unless sodium reabsorption is impaired: diuretics, salt-wasting disease, adrenal insufficiency, metabolic alkalosis with bicarbonaturia (measure urine chloride instead), or an osmotic diuresis.',
        'A urea/creatinine ratio above 20:1 in US units (about 80 in SI) with a normal urinalysis is pre-renal azotaemia: proximal sodium and water reabsorption rises, urea follows passively, creatinine does not. But the ratio depends on urea production as well — high with gastrointestinal bleeding or steroids, and misleadingly normal when protein intake has collapsed, as in prolonged vomiting.',
        'A normal urinalysis is itself informative: in hypovolaemia the kidney is not diseased, whereas most intrinsic causes of renal insufficiency show protein, cells or casts.',
        'The plasma sodium can be anything. Hypovolaemia stimulates ADH and thirst, so water retention causes hyponatraemia; but water lost in excess of solute — insensible loss, sweat, diabetes insipidus — causes hypernatraemia, which requires impaired thirst or no access to water.',
        'Haematocrit and albumin rise with plasma volume contraction, but so often begin abnormal (anaemia, hypoalbuminaemia) that their absence proves nothing.',
      ],
      equation: 'fena',
      cite: { rose: [14, 13], evidence: 'clinical' },
      route: '/urine-chemistry',
    },
    {
      heading: 'Choosing the replacement fluid',
      body: [
        'Mild deficits can be corrected orally — extra salt and water, or an oral rehydration solution, which works because glucose-coupled sodium absorption in the small intestine is preserved in secretory diarrhoea.',
        'Dextrose in water is physiologically the same as giving distilled water, since the glucose is metabolised: it replaces insensible loss or corrects a water deficit, and does nothing for extracellular volume because it distributes through total body water.',
        'Isotonic saline stays extracellular and is the fluid for volume repletion. Half-isotonic saline provides both salt and water — appropriate where both have been lost, as in an osmotic diuresis.',
        'The composition of what was lost should guide the replacement: potassium in gastrointestinal losses, bicarbonate (or its precursors) when alkaline fluid has been lost, chloride when gastric acid has.',
      ],
      cite: { rose: [14], evidence: 'clinical' },
      route: '/hypovolemia',
    },
  ],
  numbers: [
    { label: 'Gastrointestinal secretion per day', value: '3–6 L, of which 100–200 mL is lost in stool' },
    { label: 'Insensible loss', value: '700–1000 mL/day' },
    { label: 'Sweat Na⁺', value: '30–50 mmol/L; up to 1–2 L/h in heat' },
    { label: 'Blood loss fully compensated', value: '≈10% of blood volume' },
    { label: 'Blood loss causing postural hypotension', value: '16–25%' },
    { label: 'Postural pulse increment suggesting blood loss', value: '≥ 30 beats/min' },
    { label: 'Urine Na⁺ in hypovolaemia', value: '< 25 mmol/L (can be 1)' },
    { label: 'Urea/creatinine ratio in pre-renal azotaemia', value: '> 20:1 (US) ≈ > 80 (SI)' },
    { label: 'Obligatory Na⁺ loss with GFR < 25 mL/min', value: '10–40 mmol/day' },
    { label: 'Severe salt-wasting nephropathy', value: '> 100 mmol Na⁺ and 2 L/day' },
    { label: 'Urine output in shock', value: '< 15 mL/h' },
    { label: 'Normal jugular venous pressure', value: '1–8 cmH₂O above the right atrium' },
    { label: 'Post-obstructive replacement', value: '50–75 mL/h of half-isotonic saline' },
  ],
  equations: ['fena', 'feurea', 'nadeficit', 'waterdeficit', 'ureacr'],
  clinical: [
    'Volume depletion and dehydration are not synonyms: dehydration means a water deficit with hypernatraemia; volume depletion means loss of extracellular fluid, most often salt and water together.',
    'The plasma sodium tells you the composition of what was lost, not how much — a normal sodium in a clearly hypovolaemic patient means proportionate salt and water loss.',
    'A postural pulse rise of 30/min or severe postural dizziness is the most useful bedside finding in blood loss; skin turgor is unreliable over about 55–60 years.',
    'A low urine sodium confirms the kidney is responding; a high one does not exclude hypovolaemia — check the urine chloride, and consider diuretics, salt wasting or adrenal insufficiency.',
    'Pre-renal azotaemia raises urea out of proportion to creatinine, but so does gastrointestinal bleeding and steroid use; low protein intake hides it.',
    'Apparent salt wasting often resolves if sodium intake is reduced gradually rather than abruptly — find the intake that maintains balance.',
    'Post-obstructive diuresis is mostly appropriate excretion of retained fluid; replacing it litre for litre perpetuates it.',
    'Dextrose in water does not expand the extracellular volume — it is water. Use isotonic saline for volume.',
  ],
  pathology: [
    { name: 'Vomiting / nasogastric suction', broken: 'Loss of H⁺, Cl⁻, K⁺ and volume', consequence: 'Metabolic alkalosis, hypokalaemia, low urine Cl⁻ (urine Na⁺ may be high)', route: '/metabolic-alkalosis' },
    { name: 'Diarrhoea', broken: 'Loss of HCO₃⁻-rich intestinal fluid', consequence: 'Normal anion gap metabolic acidosis, hypokalaemia, negative urine anion gap', route: '/metabolic-acidosis' },
    { name: 'Osmotic diuresis', broken: 'Proximal reabsorption overwhelmed by non-reabsorbed solute', consequence: 'Salt and water loss, K⁺ wasting; hypernatraemia if water loss dominates', route: '/hyperglycemia' },
    { name: 'Adrenal insufficiency', broken: 'Aldosterone (and cortisol)', consequence: 'Renal salt wasting with hyperkalaemia and hyponatraemia; salt craving', route: '/hyponatremia' },
    { name: 'Salt-wasting nephropathy', broken: 'Tubular Na⁺ conservation / adaptation to nephron loss', consequence: 'Obligatory losses despite hypovolaemia; corrected by finding the right intake', route: '/tubulointerstitial' },
    { name: 'Third-space sequestration', broken: 'Fluid trapped out of equilibrium (obstruction, pancreatitis, fracture)', consequence: 'Hypovolaemia with a normal or raised total body sodium', route: '/hypovolemia' },
    { name: 'Hypovolaemic shock', broken: 'Tissue perfusion (loss ≈30% of blood volume)', consequence: 'Tachycardia, cold clammy skin, oliguria < 15 mL/h, confusion; lactic acidosis', route: '/aki' },
  ],
  questions: [
    {
      q: 'A hypovolaemic patient has a urine Na⁺ of 80 mmol/L. Which of these does NOT explain it?',
      options: ['Diuretic therapy', 'Vomiting with bicarbonaturia', 'Adrenal insufficiency', 'Diarrhoea with an intact kidney'],
      answer: 3,
      explanation: 'In diarrhoea the kidney is healthy and retains sodium avidly, so the urine sodium should be low. The other three all impair renal sodium reabsorption or force sodium out with another anion.',
      route: '/urine-chemistry',
    },
    {
      q: 'Two hypovolaemic patients: one with vomiting for a week, one with acute gastrointestinal bleeding. Whose urea/creatinine ratio is higher?',
      options: ['The vomiting patient', 'The bleeding patient — absorbed blood protein raises urea production on top of increased reabsorption', 'Identical', 'Neither is raised'],
      answer: 1,
      explanation: 'Both have increased proximal reabsorption, but bleeding adds a protein load. Prolonged vomiting can even lower protein intake enough to keep the ratio deceptively normal.',
      route: '/prerenal-atn',
    },
    {
      q: 'A patient with diabetes insipidus passes 10 L/day and has a plasma Na⁺ of 143. Are they volume depleted?',
      options: ['Yes, severely', 'Usually not much: thirst keeps up, and pure water loss is shared with the intracellular compartment', 'Yes, because urine output is high', 'Only if the urine is dilute']  ,
      answer: 1,
      explanation: 'Two-thirds of a pure water deficit comes from cells, so extracellular volume is relatively spared. Trouble comes when thirst or access to water fails.',
      route: '/water-disorders',
    },
    {
      q: 'A patient with chronic kidney disease loses 300 mmol of sodium a day when put on a low-salt diet. What should you do?',
      options: ['Accept a permanent high salt requirement', 'Reduce intake gradually over weeks — much apparent salt wasting is persistence of an adaptation, not a fixed defect', 'Give fludrocortisone', 'Stop all diuretics permanently'],
      answer: 1,
      explanation: 'Patients losing 300 mmol/day acutely have maintained balance on 5 mmol/day when the reduction was gradual. Find the intake that holds balance rather than assuming a fixed loss.',
      route: '/ckd',
    },
    {
      q: 'Which fluid expands the extracellular volume most per litre infused?',
      options: ['5% dextrose', 'Half-isotonic saline', 'Isotonic saline', 'They are equivalent'],
      answer: 2,
      explanation: 'Dextrose is metabolised and leaves water, which distributes through total body water. Isotonic saline changes no osmolality, so all of it stays extracellular.',
      route: '/body-water',
    },
  ],
  updates: [
    {
      topic: 'Balanced crystalloids',
      text: 'The book treats isotonic saline as the default resuscitation fluid. Large randomised trials since then compared it with balanced solutions (Ringer’s lactate, Plasma-Lyte), whose chloride content is closer to plasma and which avoid the hyperchloraemic acidosis that large-volume saline produces. The two largest trials disagree. SMART (15,802 patients, five ICUs at one centre, cluster-randomised) found fewer major adverse kidney events with balanced crystalloid — 14.3% vs 15.4%, odds ratio 0.91 — a difference that was statistically significant but small, and driven by the composite rather than by mortality alone. PLUS (5,037 patients, 53 ICUs in Australia and New Zealand, double-blind) found no difference in 90-day mortality (21.8% vs 22.0%) or in renal replacement therapy. The physiological argument for avoiding a large chloride load is sound, and balanced solutions have become the usual default; the size of any clinical benefit remains uncertain.',
      cite: { refs: ['semler2018', 'finfer2022plus'], evidence: 'clinical' },
    },
    {
      topic: 'Assessing volume status',
      text: 'The chapter is candid that physical signs are insensitive. Bedside ultrasound of the inferior vena cava and dynamic measures of fluid responsiveness (passive leg raise with stroke-volume measurement) are now widely used in the acutely ill, and have largely displaced central venous pressure, which predicts fluid responsiveness poorly.',
      cite: { refs: ['marik2013cvp'], evidence: 'clinical' },
    },
  ],
};
