import type { ChapterContent } from './types';

export const chapter: ChapterContent = {
  n: 16,
  title: 'Edematous states',
  thesis:
    'Oedema needs two things, not one: a change in Starling forces that pushes fluid into the interstitium, and a kidney that retains sodium. The second is what makes oedema possible on any scale — the whole plasma volume is only about 3 litres, and oedema is not visible until the interstitium has gained 2.5 to 3. In heart failure and cirrhosis that retention is an appropriate response to a circulation the kidney reads as underfilled, which is why removing the fluid can make tissue perfusion worse. In nephrotic syndrome it is usually the primary fault, and removing it costs nothing.',
  concepts: [
    {
      heading: 'Why the kidney is the whole story',
      body: [
        'Oedema is not detectable until the interstitial volume has risen by at least 2.5–3 L. The normal plasma volume is about 3 L. If oedema fluid came from plasma alone, every oedematous patient would be profoundly haemoconcentrated and in shock. They are not, because the sequence is: fluid moves into the interstitium, plasma volume falls, the kidney retains sodium and water, plasma volume is restored — and because the capillary forces are still abnormal, most of what was retained goes to the interstitium too.',
        'The net result is a large expansion of total extracellular volume with the plasma volume held near normal. The kidney is not failing to keep up; it is doing exactly what it should, and the oedema is the price.',
        'This is why the question "should I remove this fluid?" has two different answers. Where the retention is compensatory, removing it reduces the effective circulating volume. Where the retention is primary — the kidney holding on to sodium it need not — both plasma and interstitial volumes are expanded, and removing the excess costs nothing.',
      ],
      chain: [
        'Starling forces change (venous pressure up, capillary leaky, oncotic gradient lost)',
        'Fluid moves into the interstitium',
        'Plasma volume falls, tissue perfusion falls',
        'Kidney retains Na⁺ and water',
        'Plasma volume restored — but most of the retained fluid enters the interstitium',
        'Oedema, with a near-normal plasma volume',
      ],
      points: ['Oedema is invisible until +2.5–3 L of interstitial fluid', 'Plasma volume is ~3 L: the fluid cannot have come from there', 'Retention is usually appropriate, not a failure'],
      cite: { rose: [16, 8, 7], evidence: 'physiology' },
      route: '/edema',
    },
    {
      heading: 'The Starling forces, and why the numbers are not what you would guess',
      body: [
        'In a skeletal muscle capillary the two large terms are the mean capillary hydraulic pressure (about 17 mmHg), pushing fluid out, and the plasma oncotic pressure (about 28 mmHg), pulling it in. Interstitial hydraulic pressure is slightly negative (about −3) and interstitial oncotic pressure about 8. The net gradient favouring filtration is only about 0.3 mmHg, and the lymphatics return what is filtered.',
        'Different capillary beds are not alike, and the differences explain clinical patterns. Hepatic sinusoids are freely permeable to protein, so there is almost no oncotic gradient across them and the hydraulic gradient is essentially unopposed — which is why portal hypertension produces ascites so readily. Alveolar capillaries are intermediate: a low hydraulic pressure but a high interstitial oncotic pressure of about 18 mmHg, which gives the lung a much larger protective reserve against hypoalbuminaemia than muscle has.',
        'Capillary hydraulic pressure is well defended against arterial pressure — the precapillary sphincter constricts when arterial pressure rises, which is why hypertensive patients do not develop oedema. It is not defended against venous pressure, which is transmitted almost fully. That is why oedema comes from volume expansion and venous obstruction rather than from hypertension.',
      ],
      points: [
        'Muscle capillary: net filtration gradient only ~0.3 mmHg',
        'Liver sinusoid: protein-permeable, so almost no oncotic opposition',
        'Alveolus: interstitial oncotic pressure ~18 mmHg — a large reserve',
        'Arterial pressure is buffered; venous pressure is not',
      ],
      equation: 'starling',
      cite: { rose: [16, 7], evidence: 'physiology', refs: ['levick2010'] },
      route: '/edema',
    },
    {
      heading: 'The safety factors: why a small change does not cause oedema',
      body: [
        'Given a baseline gradient of 0.3 mmHg, any disturbance ought to cause oedema. In practice the gradient must rise by about 15 mmHg before oedema is detectable, and three mechanisms account for that margin.',
        'Lymph flow rises — in cirrhosis by more than tenfold as sinusoidal pressure increases. Interstitial oncotic pressure falls, both by dilution and by lymphatic removal of interstitial protein, which raises the transcapillary oncotic gradient and offsets the rise in hydraulic pressure. And as interstitial volume rises, interstitial hydraulic pressure rises: oedema cannot appear until the normally negative value has become positive.',
        'The margins are finite. In cirrhosis, once filtration exceeds what the lymphatics can carry, the rising intraperitoneal pressure becomes the limit on further ascites.',
      ],
      points: ['~15 mmHg of extra filtration gradient is needed before oedema appears', 'Lymph flow, interstitial oncotic washout, interstitial pressure'],
      cite: { rose: [16, 7], evidence: 'physiology' },
      route: '/edema',
    },
    {
      heading: 'Hypoalbuminaemia is a weaker cause than it looks',
      body: [
        'The intuition is that halving the plasma albumin halves the force holding fluid in the vessels. It does not, because interstitial oncotic pressure falls in parallel: less albumin in the plasma means less entering the interstitium. Measurements in minimal change disease show plasma and interstitial oncotic pressures falling together, with little change in the gradient between them.',
        'How large that protection is depends on where interstitial oncotic pressure starts. If it is 8 mmHg it can supply at most 8 mmHg of buffering; if the higher human estimates of 12–15 mmHg are right, the protection is roughly twice as large. Either way it is finite — the interstitial reservoir can be washed out — which is why oedema attributable to hypoalbuminaemia alone is mostly seen below a plasma albumin of about 15–20 g/L.',
        'Acute hypoalbuminaemia behaves differently. Give large volumes of saline rapidly to a hypovolaemic patient and the plasma albumin falls with no time for the interstitial concentration to follow, so the gradient really does fall and peripheral oedema can appear before filling pressures are restored.',
        'The lung is better protected still, because its interstitial oncotic pressure starts near 18 mmHg. Pulmonary oedema is not usually seen from hypoalbuminaemia alone, at albumin levels low enough to cause peripheral oedema, unless left atrial pressure is also raised.',
      ],
      cite: { rose: [16], evidence: 'experimental' },
      route: '/edema',
    },
    {
      heading: 'Nephrotic syndrome: mostly overfilling, sometimes underfilling',
      body: [
        'If hypoalbuminaemia caused nephrotic oedema by underfilling, then removing the oedema with diuretics should deplete the plasma volume and raise the creatinine. Usually it does not, unless fluid is removed excessively.',
        'The stronger evidence is what happens in remission. When corticosteroids induce remission of minimal change disease, glomerular filtration rate rises and sodium excretion increases substantially — with the oedema starting to clear — before the plasma albumin has risen at all. Whatever caused the retention was therefore the renal disease, not the low albumin. Experimental glomerular disease shows a primary increase in sodium reabsorption that appears to be in the collecting tubules; how that happens is not well understood.',
        'But the picture varies between patients, and a study of children with minimal change disease found three groups at the onset of relapse: some with a nearly normal albumin, a low fractional sodium excretion and modest volume expansion but no oedema — primary renal retention; some oedematous and nephrotic with no signs of hypovolaemia; and some oedematous with clear hypovolaemia, a markedly raised plasma renin, aldosterone and noradrenaline, and a low GFR. In one of the last group, albumin infusion transiently improved both.',
        'So the practical question is not which theory is right but which patient is in front of you. High renin and aldosterone with a low urine sodium and symptoms of hypovolaemia mean underfilling; suppressed renin with a normal plasma volume means the kidney is simply retaining.',
      ],
      points: [
        'Remission raises Na⁺ excretion before albumin rises (Rose Fig. 16-4)',
        'Overfilling: renin suppressed, plasma volume normal — diuresis is safe',
        'Underfilling: renin and aldosterone high, urine Na⁺ low, GFR falling',
      ],
      cite: { rose: [16], evidence: 'experimental' },
      route: '/edema',
    },
    {
      heading: 'Effective circulating volume is not cardiac output',
      body: [
        'Renal retention in oedematous states is usually an appropriate response to a fall in effective circulating volume — the pressure perfusing the arterial baroreceptors. Often that tracks cardiac output, so a failing heart produces retention. But not always.',
        'Create an arteriovenous fistula and cardiac output does not initially change, yet tissue perfusion falls because the blood through the fistula bypasses the capillary circulation. The kidney retains sodium, blood volume and cardiac output rise, and the new steady state has a cardiac output exceeding baseline by the flow through the fistula.',
        'Cirrhosis with ascites is the clinical version. Cardiac output is often high, and yet these patients behave as though volume-depleted: avid sodium retention, and rising renin, noradrenaline and ADH. The reason is splanchnic vasodilatation and multiple arteriovenous communications, which drop systemic vascular resistance and blood pressure. Much of that high cardiac output is circulating ineffectively, while renal and eventually musculocutaneous perfusion fall.',
      ],
      chain: ['Splanchnic vasodilatation', 'Systemic vascular resistance falls', 'Arterial pressure falls despite a high cardiac output', 'Baroreceptors read underfilling', 'Renin, noradrenaline and ADH rise; urine Na⁺ < 25 mmol/L'],
      cite: { rose: [16, 8], evidence: 'physiology' },
      route: '/edema',
    },
    {
      heading: 'The compensated state, and why renin can be normal in heart failure',
      body: [
        'Renin is often normal in patients with heart failure or cirrhosis, which seems to contradict everything above. Part of the answer is that they have reached a compensated state: the fluid retained has increased venous return, so systemic haemodynamics are stable at rest and the stimulus for further renin release has gone.',
        'The experiment is chronic thoracic inferior vena cava constriction in the dog. There is initial hypotension, activation of renin and aldosterone, and a marked fall in sodium excretion. By about day 7 a new steady state has been reached: blood pressure, renin, aldosterone and urinary sodium excretion are all back to baseline, and the plasma volume is expanded. The expansion is what restored venous return; the hormones fell because it worked.',
        'That explanation does not cover every case. Many patients with stable heart failure have a persistently reduced cardiac output and still a normal plasma renin. One possibility is that circulating renin does not reflect tissue renin–angiotensin activity: animals with heart failure show persistent hypoperfusion-driven activation of the intrarenal system with normal plasma concentrations. The chapter offers this as a possibility, not a settled account.',
      ],
      points: ['IVC constriction: new steady state by ~day 7', 'Normal renin can mean compensation, not absence of activation', 'A normal plasma renin does not exclude intrarenal activation'],
      cite: { rose: [16, 2, 8], evidence: 'experimental' },
      route: '/edema',
    },
    {
      heading: 'Three questions before reaching for a diuretic',
      body: [
        'When must oedema be treated? Pulmonary oedema is the only form that is immediately life-threatening. Everything else can be removed slowly, and in cirrhosis should be: hypokalaemia, metabolic alkalosis and rapid fluid shifts can precipitate hepatic encephalopathy or the hepatorenal syndrome.',
        'What does removing it cost? If the retention was compensatory, diuresis lowers the effective circulating volume. Cardiac output falls by an average of about 20% in heart failure, and renin, noradrenaline and ADH rise. Most patients still benefit — exercise tolerance and congestion improve — so small falls in cardiac output are tolerated. But perfusion can be impaired significantly when the baseline effective circulating volume is already low, or when diuresis is too fast. The way to tell is to watch the urea and creatinine: while they are stable, perfusion has been preserved.',
        'The awkward case is the patient who cannot be both oedema-free and have a stable creatinine — whose cardiac output is only maintained at filling pressures high enough to cause oedema. That is not overdiuresis; it is the disease. Recognising the difference decides whether to give more diuretic or to attack the underlying problem.',
        'How fast? In generalised oedema most capillary beds are involved, so 2–3 L a day or more can usually be mobilised without depleting the plasma volume. Cirrhosis with ascites but no peripheral oedema is the exception: ascitic fluid can only be recovered through the peritoneal capillaries, and direct measurement puts the safe limit near 500–750 mL/day. Patients with ascites and no oedema who were diuresed faster than that lost about a quarter of their plasma volume and became azotaemic; patients who also had peripheral oedema did not, and could safely lose more than 2 kg a day until the oedema had gone.',
      ],
      points: ['Only pulmonary oedema is an emergency', 'Watch urea and creatinine as the perfusion check', 'Ascites without peripheral oedema: ~500–750 mL/day'],
      cite: { rose: [16, 15], evidence: 'clinical', refs: ['pockros1986'] },
      route: '/edema',
    },
    {
      heading: 'Where the oedema is tells you which capillaries are abnormal',
      body: [
        'Left ventricular disease — coronary or hypertensive — raises left atrial and pulmonary capillary pressures, so these patients have pulmonary oedema without peripheral oedema. Pulmonary capillary pressure generally has to exceed 18–20 mmHg, against a normal of 5–12, before oedema forms.',
        'Cor pulmonale is right ventricular failure, giving peripheral oedema and perhaps ascites with clear lungs. Cardiomyopathies involve both ventricles and produce both.',
        'Cirrhosis raises sinusoidal pressure, so ascites dominates and the central venous pressure is normal or low. Nephrotic syndrome and primary renal retention expand the whole extracellular volume, so the distribution is generalised and the venous pressure is normal or high.',
        'Some oedema should not be treated with diuretics at all. Lymphatic obstruction, myxoedema and localised venous disease do not allow the fluid to be mobilised back into the vascular space when venous pressure falls, so a diuretic predictably produces volume depletion instead of resolving the swelling.',
      ],
      points: [
        'Pulmonary oedema, clear periphery: left-sided disease',
        'Peripheral oedema, raised JVP, clear lungs: right-sided disease',
        'Ascites with a low venous pressure: cirrhosis',
        'Lymphoedema and myxoedema: do not diurese',
      ],
      cite: { rose: [16], evidence: 'clinical' },
      route: '/edema',
    },
  ],
  numbers: [
    { label: 'Interstitial gain before oedema is detectable', value: '2.5–3 L' },
    { label: 'Normal plasma volume', value: '~3 L' },
    { label: 'Net filtration gradient, muscle capillary', value: '~0.3 mmHg' },
    { label: 'Capillary hydraulic pressure, muscle', value: '~17 mmHg' },
    { label: 'Plasma oncotic pressure', value: '~28 mmHg' },
    { label: 'Interstitial oncotic pressure, muscle', value: '8 mmHg (12–15 in some human studies)' },
    { label: 'Interstitial oncotic pressure, alveolus', value: '~18 mmHg' },
    { label: 'Gradient rise needed before oedema', value: '~15 mmHg' },
    { label: 'Pulmonary capillary pressure causing oedema', value: '> 18–20 mmHg (normal 5–12)' },
    { label: 'Albumin below which hypoalbuminaemic oedema occurs', value: '< 15–20 g/L' },
    { label: 'Urine Na⁺ in compensatory retention', value: 'often < 25 mmol/L' },
    { label: 'Fall in cardiac output with diuresis in heart failure', value: '~20% on average' },
    { label: 'Safe ascites mobilisation without peripheral oedema', value: '500–750 mL/day' },
    { label: 'Safe fluid removal in generalised oedema', value: '2–3 L/day or more' },
    { label: 'Time to a new steady state after IVC constriction', value: '~7 days' },
  ],
  equations: ['starling', 'fena'],
  clinical: [
    'Oedema requires both an altered capillary force and renal sodium retention. Ask which is which before treating.',
    'In heart failure and cirrhosis the retention is compensatory: removing the fluid lowers the effective circulating volume, and the urea and creatinine are how you find out whether it has gone too far.',
    'In primary renal sodium retention — much of nephrotic syndrome, glomerulonephritis — both plasma and interstitial volumes are expanded, and diuresis carries no such cost.',
    'A rising urea and creatinine on diuretics means one of two things: too much diuretic, or a heart that can only maintain output at oedema-forming filling pressures. They are managed differently.',
    'Ascites without peripheral oedema: limit diuresis to about 500–750 mL/day. With peripheral oedema the limit does not apply until the oedema has gone.',
    'Do not give diuretics for lymphoedema, myxoedema or localised venous disease: the fluid cannot be mobilised and the patient will simply become volume depleted.',
    'A normal plasma renin in heart failure usually means the patient is compensated, not that the system is uninvolved.',
    'Hypoalbuminaemia alone rarely causes oedema until the albumin is very low. When a hypoalbuminaemic patient is oedematous, look for the other reason.',
  ],
  pathology: [
    { name: 'Left heart failure', broken: 'Left ventricular output; pulmonary capillary pressure rises', consequence: 'Pulmonary oedema with a clear periphery', route: '/edema' },
    { name: 'Cor pulmonale', broken: 'Right ventricular output; systemic venous pressure rises', consequence: 'Peripheral oedema and ascites with clear lungs', route: '/edema' },
    { name: 'Cirrhosis with ascites', broken: 'Systemic vascular resistance (splanchnic vasodilatation) and sinusoidal pressure', consequence: 'Ascites, avid Na⁺ retention and high renin despite a high cardiac output', route: '/edema' },
    { name: 'Nephrotic syndrome (overfilling)', broken: 'Primary collecting-tubule Na⁺ reabsorption', consequence: 'Generalised oedema with renin suppressed and plasma volume defended', route: '/edema' },
    { name: 'Nephrotic syndrome (underfilling)', broken: 'Transcapillary oncotic gradient, once albumin is very low', consequence: 'Oedema with high renin, low urine Na⁺ and a falling GFR', route: '/edema' },
    { name: 'Capillary leak (burns, sepsis, IL-2)', broken: 'The reflection coefficient — protein crosses freely', consequence: 'Oedema with a falling plasma volume; haematocrit can rise to 70–80% in the idiopathic syndrome', route: '/edema' },
    { name: 'Lymphatic obstruction / myxoedema', broken: 'Return of filtered fluid and protein', consequence: 'Oedema that diuretics cannot mobilise — they cause volume depletion instead', route: '/edema' },
    { name: 'Overdiuresis', broken: 'Effective circulating volume, iatrogenically', consequence: 'Rising urea out of proportion to creatinine, urine Na⁺ < 10, concentrated urine', route: '/prerenal-atn' },
  ],
  questions: [
    {
      q: 'Why can oedema not be explained by fluid leaving the plasma alone?',
      options: [
        'It can',
        'Oedema needs 2.5–3 L of interstitial gain and the whole plasma volume is only about 3 L — the patient would be in shock',
        'Because plasma is replaced from cells',
        'Because lymphatics prevent it',
      ],
      answer: 1,
      explanation: 'The kidney supplies the volume. That is why renal sodium retention is a necessary part of every oedematous state, and why the plasma volume ends up near normal.',
      route: '/edema',
    },
    {
      q: 'A nephrotic patient has oedema, a plasma albumin of 22 g/L, a suppressed plasma renin and a normal plasma volume. What does the renin tell you?',
      options: [
        'The sample was mishandled',
        'This is overfilling — the kidney is retaining sodium primarily, so diuresis should not compromise perfusion',
        'The patient is hypovolaemic',
        'Aldosterone must be high',
      ],
      answer: 1,
      explanation:
        'Suppressed renin with a defended plasma volume is the signature of primary renal retention. Contrast the minority of nephrotic patients with a very low albumin, high renin and symptoms of hypovolaemia, in whom diuresis does carry a cost.',
      route: '/edema',
    },
    {
      q: 'Corticosteroids induce remission in minimal change disease. Sodium excretion rises and the oedema begins to clear before the plasma albumin has changed. What does that show?',
      options: [
        'Steroids are natriuretic',
        'The sodium retention was caused by the renal disease, not by the hypoalbuminaemia',
        'Albumin measurements are unreliable',
        'Nothing — the timing is coincidental',
      ],
      answer: 1,
      explanation: 'This is Rose Fig. 16-4, and it is the strongest argument that nephrotic oedema is usually an overfilling state.',
      route: '/edema',
    },
    {
      q: 'A cirrhotic patient with a high cardiac output has a urine Na⁺ of 8 mmol/L and a markedly raised renin. Why does the kidney behave as though volume-depleted?',
      options: [
        'The cardiac output measurement is wrong',
        'Splanchnic vasodilatation drops systemic vascular resistance and arterial pressure, so much of that output is circulating ineffectively',
        'Aldosterone is not being metabolised by the liver',
        'There is coexisting heart failure',
      ],
      answer: 1,
      explanation:
        'Effective circulating volume is what perfuses the baroreceptors, not cardiac output. Liver disease does also reduce aldosterone clearance, but the primary abnormality is haemodynamic.',
      route: '/edema',
    },
    {
      q: 'A cirrhotic with tense ascites and no peripheral oedema is diuresed at 1.5 L/day. Urea and creatinine rise. Why?',
      options: [
        'Hepatorenal syndrome was inevitable',
        'Ascites can only be mobilised through the peritoneal capillaries at about 500–750 mL/day, so the rest came from the plasma volume',
        'The diuretic was nephrotoxic',
        'Too little albumin was given',
      ],
      answer: 1,
      explanation:
        'Patients diuresed faster than this without peripheral oedema lost about a quarter of their plasma volume. Those who also had peripheral oedema were protected, because that fluid mobilises freely.',
      route: '/edema',
    },
    {
      q: 'After ten days of furosemide following pulmonary oedema, a man has lost 6 kg, has no oedema, a urine Na⁺ of 2 mmol/L, urine osmolality 550 mOsm/kg, urea 39 mmol/L and creatinine 400 µmol/L. What now?',
      options: [
        'Increase the diuretic',
        'Stop the diuretic and give sodium — this is volume depletion from overdiuresis',
        'Start dialysis',
        'Add an ACE inhibitor',
      ],
      answer: 1,
      explanation:
        'He started with a normal extracellular volume, a little of which had moved into the alveoli. Continued removal had to produce depletion. The avid urine, the weight loss and the disproportionate urea all point the same way; the creatinine returned to normal on a high-sodium diet.',
      route: '/prerenal-atn',
    },
  ],
  updates: [
    {
      topic: 'Heart failure treatment has moved well beyond the diuretic',
      text: 'The chapter already reports that spironolactone reduces mortality and digoxin does not. Since then, neprilysin inhibition combined with angiotensin receptor blockade reduced cardiovascular death or heart failure hospitalisation compared with enalapril, and SGLT2 inhibition reduced worsening heart failure or cardiovascular death by about a quarter (hazard ratio 0.74) with or without diabetes. Both act partly through the kidney, and both changed outcomes rather than only symptoms — which diuretics, for all their usefulness, have never been shown to do.',
      cite: { refs: ['mcmurray2014', 'mcmurray2019dapa', 'pitt1999rales'], evidence: 'clinical' },
    },
    {
      topic: 'The revised Starling principle',
      text: 'The chapter uses the classical Starling equation with filtration at the arteriolar end and reabsorption at the venular end. The revised principle holds that in most tissues there is no venular reabsorption in the steady state: the oncotic force that opposes filtration is generated across the endothelial glycocalyx, against the protein concentration in the sub-glycocalyx space rather than in the interstitium, and essentially all filtered fluid returns via the lymphatics. It changes the account of the mechanism rather than the clinical conclusions, and it strengthens the chapter’s argument that infused albumin retains less fluid in the vascular space than a simple oncotic calculation predicts.',
      cite: { refs: ['levick2010'], evidence: 'physiology', update: 'The mechanism of the oncotic opposition, not the clinical conclusions.' },
    },
  ],
  modules: ['/edema', '/diuretics', '/body-water', '/sodium'],
};
