import type { ChapterContent } from './types';

export const chapter: ChapterContent = {
  n: 24,
  title: 'Hyperosmolal states — hypernatraemia',
  thesis:
    'Hypernatraemia is a disorder of thirst, or of access to water, far more than of the kidney. Even a kidney that cannot concentrate at all leaves the plasma sodium in the high-normal range as long as the patient feels thirst and can reach water, so the sodium climbs in infants, in the confused and the intubated, and in the rare patient whose hypothalamus has lost thirst. What the kidney\'s defect decides is how much has to be drunk to keep up. The urine osmolality, before and after desmopressin, tells which defect it is.',
  concepts: [
    {
      heading: 'Thirst, not ADH, is the final defence',
      body: [
        'A rise in plasma osmolality sets off two responses from the same hypothalamic osmoreceptors. Antidiuretic hormone is released first, from an osmolality of about 275 to 285 mOsm/kg, and the kidney starts to keep water. Thirst begins a few mOsm/kg higher, and it is the thirst that settles the matter: together they hold the plasma osmolality within 1 to 2 per cent despite wide swings in what is eaten and drunk.',
        'ADH can only reduce the loss. It cannot replace water already lost through the skin and lungs, or water that a kidney unable to concentrate goes on excreting. Drinking can. A patient with complete central diabetes insipidus may pass 10 to 15 litres a day and keep a normal sodium simply by drinking it back. Conversely, maximal ADH cannot protect a patient who does not drink.',
        'So a plasma sodium above 150 mmol/L is virtually never seen in an alert adult who has a normal thirst mechanism and access to water. It occurs in infants, who are thirsty but cannot ask, in adults with an altered mental state, and in the rare patient with hypodipsia. Older people are at particular risk: osmotic thirst weakens with age even though ADH release is preserved.',
      ],
      chain: [
        'Water lost or solute gained, and plasma osmolality rises',
        'ADH is released from about 280 mOsm/kg and the urine concentrates',
        'Thirst starts a few mOsm/kg higher',
        'Intake rises to match whatever is being lost',
        'Plasma sodium returns to normal, or to high-normal if the kidney cannot concentrate',
      ],
      points: [
        'Plasma osmolality held at about 280–290 mOsm/kg',
        'Na⁺ > 150 is almost never seen in an alert adult with water to hand',
        'At risk: infants, altered mental state, hypodipsia, old age',
      ],
      cite: { rose: [24, 6], evidence: 'physiology' },
      route: '/water-disorders',
    },
    {
      heading: 'Water has to be lost in excess of sodium plus potassium',
      body: [
        'The plasma sodium follows the ratio of exchangeable sodium plus potassium to total body water. A fluid lost with the same sodium-plus-potassium concentration as plasma lowers the volume and leaves the sodium where it was. To raise the sodium, water has to be lost in excess of sodium plus potassium.',
        'Diarrhoea shows the difference. A secretory diarrhoea such as cholera is isosmotic and made almost entirely of sodium and potassium salts, so it depletes volume without changing the sodium. An osmotic diarrhoea (lactulose, sorbitol, malabsorption) is also isosmotic, but only 30 to 110 mmol/L of it is sodium plus potassium; unabsorbed solute makes up the rest, so it removes water in excess of sodium and potassium and the sodium rises. An osmotic diuresis from glucose, urea or mannitol does the same in the urine.',
        'Sodium can also be added. Hypertonic sodium bicarbonate during resuscitation, a salt emetic, or a feed made up with too much salt can raise the sodium by tens of mmol/L. These patients are volume-expanded and excrete a urine rich in sodium, the opposite of patients who lost water.',
      ],
      points: ['Isosmotic Na⁺ + K⁺ loss changes no concentration', 'Osmotic diarrhoea and osmotic diuresis lose water in excess of Na⁺ + K⁺', 'Sodium overload: volume-expanded, urine Na⁺ often > 100 mmol/L'],
      cite: { rose: [24, 22], evidence: 'physiology' },
      route: '/body-water',
    },
    {
      heading: 'How much urine a concentrating defect forces',
      body: [
        'Every day the kidney has to excrete the solute of the diet and of metabolism, normally 600 to 900 mOsm of sodium and potassium salts and urea. The least water it can do that in is the solute divided by the highest urine osmolality it can reach. That makes the concentrating defect a volume problem.',
        'The book\'s arithmetic: 800 mOsm a day needs only 800 mL of urine if the kidney can reach 1000 mOsm/kg, but 2 litres if it can reach only 400. The extra 1.2 litres is harmless to someone who drinks it and a steady loss to someone who does not. At a maximum of 300 mOsm/kg, 750 mOsm of solute needs 2.5 litres; at 100 mOsm/kg it needs 7.5 litres.',
        'Once the urine osmolality is fixed, the solute load sets the urine volume. Halving the solute halves the urine, which is why a low-salt, low-protein diet reduces the polyuria of diabetes insipidus. Volume depletion reduces it too: the filtration rate falls, the proximal tubule reabsorbs more, and less water reaches the collecting duct to be lost. The same logic explains why cortisol deficiency can hide diabetes insipidus until hydrocortisone is started.',
      ],
      chain: [
        'Solute to excrete: about 600–900 mOsm/day',
        'Divided by the highest urine osmolality the kidney can reach',
        'Gives the smallest urine volume that will carry it',
        'A lower ceiling or more solute means more obligatory urine',
      ],
      points: ['Urine volume ≈ solute excretion ÷ urine osmolality', 'Less solute (low-salt, low-protein diet) means less polyuria', 'Volume depletion limits the polyuria and can mask it'],
      cite: { rose: [24, 9], evidence: 'physiology' },
      route: '/water-disorders',
      equation: 'efwc',
    },
    {
      heading: 'Central and nephrogenic diabetes insipidus',
      body: [
        'Diabetes insipidus is either too little ADH (central) or a collecting duct that does not respond to it (nephrogenic). Both produce 3 to 20 litres a day of dilute urine. Most patients keep a near-normal sodium because they drink, so what they complain of is polyuria, nocturia and thirst, not hypernatraemia. Many with central diabetes insipidus prefer iced water, and they can often date the onset exactly.',
        'Central diabetes insipidus follows neurosurgery, head trauma, hypoxic brain injury, tumours and infiltrative disease, or appears without a cause. In adults, the acquired nephrogenic forms that are severe enough to cause polyuria come mainly from lithium, hypercalcaemia and the osmotic diuresis of uncontrolled diabetes. Lithium polyuria appears in about one patient in five, and a milder concentrating defect in another 30 per cent. The drug enters collecting-duct cells through the sodium channel and interferes with the ADH response there.',
        'Hypercalcaemia acts through the calcium-sensing receptor. In the thick ascending limb it reduces the NaCl transport that builds the medullary gradient; in the inner medullary collecting duct it blunts the ADH effect. Hypokalaemia impairs concentration once the potassium deficit reaches 300 to 400 mmol, a plasma potassium below about 3.0 mmol/L. Both defects usually reverse within weeks of correction.',
      ],
      points: [
        'Central: no ADH. Nephrogenic: no response to it',
        'Adult nephrogenic DI with real polyuria: lithium, hypercalcaemia, hyperglycaemia',
        'Pregnancy: placental vasopressinase destroys ADH; desmopressin resists it',
      ],
      cite: { rose: [24], evidence: 'clinical' },
      route: '/water-disorders',
    },
    {
      heading: 'The brain shrinks, then adapts, and that sets the rate of correction',
      body: [
        'A rising plasma osmolality pulls water out of brain cells. It is this shrinkage, not the sodium number itself, that causes the lethargy, irritability, twitching, seizures and coma of hypernatraemia. It can also tear bridging veins and cause intracerebral and subarachnoid haemorrhage. A clinically important shift seems to need a gradient of 30 to 35 mOsm/kg between plasma and brain. In children, seizures and permanent damage became likely once the sodium passed about 158 mmol/L.',
        'The brain defends itself in two stages. Within hours, fluid moves in from the cerebrospinal fluid and cells take up sodium, potassium and chloride. Over days, they accumulate organic osmolytes (inositol, glutamine and glutamate), which make up about a third of the new osmoles and do not disturb protein function the way a high cation concentration would. Brain volume returns towards normal, and a patient with chronic hypernatraemia can be surprisingly well at a sodium of 170 to 180.',
        'That adaptation is the danger in treatment. Lower the plasma osmolality quickly and water flows into brain cells that still hold their extra osmoles. The cations leave fast, but the osmolytes leave slowly, so the brain swells. The book\'s case: a young woman with a sodium of 183 was given large volumes of dextrose in water. The sodium fell to 154 in six hours, she became unresponsive with a raised cerebrospinal pressure, and recovered over the next day and a half.',
      ],
      chain: [
        'Plasma osmolality rises and water leaves brain cells',
        'Brain shrinks: symptoms, and vessels can tear',
        'Hours: electrolytes enter the cells. Days: osmolytes accumulate',
        'Brain volume is restored, and chronic hypernatraemia may be well tolerated',
        'Rapid correction drives water into cells still loaded with osmolytes: cerebral oedema',
      ],
      points: ['Symptoms track the rate of rise more than the level', 'Osmolytes: inositol, glutamine, glutamate, about 35% of the adaptation', 'Correct chronic hypernatraemia slowly'],
      cite: { rose: [24, 23], evidence: 'experimental' },
      route: '/water-disorders',
    },
    {
      heading: 'Reading the urine in a hypernatraemic patient',
      body: [
        'Once the sodium is above 150 mmol/L, the plasma osmolality is past 295 mOsm/kg, and at that level a normal subject has maximal ADH effect. The urine osmolality therefore reports on the kidney directly.',
        'A urine above 800 mOsm/kg means the kidney is working. The water was lost elsewhere (skin, lungs, gut), or not drunk (hypodipsia), or sodium was added. The urine sodium separates these: usually below 25 mmol/L after water loss, often above 100 mmol/L after sodium overload. A urine below 300 mOsm/kg, dilute despite a high plasma osmolality, means central or nephrogenic diabetes insipidus. Desmopressin then separates the two, raising the urine osmolality by at least 50 per cent in central diabetes insipidus and changing it little in nephrogenic.',
        'Between 300 and 800 lies an uninformative middle. It can mean partial central or partial nephrogenic diabetes insipidus, or an osmotic diuresis. It can also mean complete central diabetes insipidus with volume depletion, because when little water reaches the inner medulla, the small ADH-independent water permeability there concentrates it. Only the first and last respond to desmopressin.',
      ],
      points: ['Uosm > 800: kidney normal; look outside it', 'Uosm < 300 with Na⁺ > 150: diabetes insipidus', 'Desmopressin response: yes in central, no in nephrogenic'],
      cite: { rose: [24], evidence: 'reasoning' },
      route: '/water-disorders',
    },
    {
      heading: 'The water-restriction test',
      body: [
        'In a polyuric patient with a normal sodium, the question is whether the kidney can concentrate once ADH is maximally stimulated. Water is withheld; urine volume, urine osmolality and weight are measured hourly, and plasma osmolality every two hours. Restriction stops when the urine osmolality plateaus (a rise of less than 30 mOsm/kg in two consecutive hours), when the plasma osmolality reaches 295 to 300, or before 3 to 5 per cent of body weight has been lost. Then desmopressin is given and the measurements continue.',
        'The stopping rules are not a formality. In complete central diabetes insipidus the urine can run at 700 to 800 mL/h, and restriction carried past them causes severe volume depletion and circulatory collapse. A patient with primary polydipsia may need longer, because they start water-loaded.',
        'The patterns: a normal subject concentrates maximally and desmopressin adds nothing. In complete central diabetes insipidus the urine stays dilute, then rises 100 to 800 per cent with desmopressin; in partial central diabetes insipidus it rises 15 to 50 per cent from an already hypertonic urine. In nephrogenic diabetes insipidus it stays dilute, with a rise of at most about 45 per cent. In primary polydipsia it concentrates, though often not fully, because chronic water loading washes out the medullary gradient.',
        'The test\'s weak point is separating partial central diabetes insipidus from primary polydipsia. The book cites a study in which it gave the right answer in about 80 per cent of patients, and the distinction matters: desmopressin cures the polyuria of central diabetes insipidus, but in primary polydipsia it can cause dangerous hyponatraemia.',
      ],
      points: ['Stop at Posm 295–300, a plateau, or 3–5% weight loss', 'Desmopressin: +100–800% complete central, +15–50% partial central, ≤ 45% nephrogenic, none normal', 'Hardest call: partial central DI vs primary polydipsia'],
      cite: { rose: [24], evidence: 'clinical' },
      route: '/water-disorders',
    },
    {
      heading: 'Polyuria: water diuresis or solute diuresis',
      body: [
        'Polyuria means more than about 3 litres of urine a day, as opposed to frequency, where the volume is normal. Two questions sort it. Is it a water diuresis or a solute diuresis? And is it appropriate?',
        'A urine osmolality below 250 mOsm/kg means a water diuresis: diabetes insipidus, or excess water drunk or infused. Above 300 means a solute diuresis, because a kidney that can concentrate to 300 would pass only 2 to 3 litres of a normal solute load. Anything more needs extra solute. Measuring the urine sodium, glucose and urea identifies which solute. Sodium usually means an appropriate diuresis after saline loading or relief of obstruction, and the treatment is to stop replacing every millilitre.',
        'The book\'s case: a man comatose after a cardiac arrest passes 300 to 400 mL/h of urine at 130 mOsm/kg, a water diuresis. It responds to desmopressin, so central diabetes insipidus from hypoxic injury. Days later the polyuria returns at 500 mOsm/kg and no longer responds. The urine is now mostly urea from high-protein tube feeding, and the fix is less protein, not more desmopressin.',
      ],
      points: ['Polyuria: > 3 L/day', 'Uosm < 250: water diuresis. Uosm > 300: solute diuresis', 'Normal solute excretion 600–900 mOsm/day'],
      cite: { rose: [24], evidence: 'reasoning' },
      route: '/water-disorders',
    },
    {
      heading: 'Treatment: the deficit, the rate and the fluid',
      body: [
        'For water loss, the amount of positive water balance needed to bring the sodium back to 140 is estimated from total body water times (sodium ÷ 140 − 1). Body water is normally about 60 per cent of lean weight in men and 50 per cent in women, and it is reasonable to use about 10 per cent less in a water-depleted patient. The estimate covers pure water only; any accompanying isotonic loss has to be replaced separately.',
        'The rate is set by the brain\'s adaptation. Without trials, the book takes 0.5 mmol/L per hour, or 12 mmol/L per day, from observations in children as the safe maximum when there are no hypernatraemic symptoms. For the woman with a sodium of 183 and 50 kg of lean weight, that means about 6 litres of water over at least 86 hours, plus 30 to 50 mL/h of ongoing insensible losses: roughly 110 mL/h. The sodium has to be measured repeatedly, because the formula is only an estimate and overestimates body water in the cachectic elderly.',
        'Ongoing urinary losses count by their sodium-plus-potassium concentration, not their osmolality. Urea and ammonium do not change the plasma sodium, so a "concentrated" urine can still be removing free water. For the fluid, dextrose in water replaces pure water loss. Quarter-isotonic saline (750 mL of free water per litre) suits combined losses, and isotonic saline comes first in a hypotensive patient. Potassium added to a bag counts towards its tonicity.',
      ],
      points: ['Deficit ≈ TBW × (Na⁺/140 − 1)', 'Maximum 0.5 mmol/L/h, 12 mmol/L/day, in chronic hypernatraemia', 'Add insensible and urinary free-water losses', 'Measure the sodium, do not trust the formula'],
      cite: { refs: ['adrogue2000hyper'], rose: [24], evidence: 'clinical' },
      route: '/water-disorders',
      equation: 'waterdeficit',
    },
    {
      heading: 'Treating diabetes insipidus',
      body: [
        'Central diabetes insipidus is treated with desmopressin, which has more antidiuretic and no pressor activity and lasts long enough for once- or twice-daily dosing. The hazard is that the patient now has ADH activity that cannot be switched off, so drinking out of habit can cause hyponatraemia. The book advises the smallest effective dose, starting at bedtime to control nocturia, and letting some breakthrough urine confirm that water can still be excreted.',
        'Without ADH, the urine volume can still be lowered by reducing what reaches the collecting duct. A thiazide with a low-sodium diet induces mild volume depletion: the proximal tubule reabsorbs more, and less water is delivered to be lost. Losing as little as 1.0 to 1.5 kg can cut the urine output by more than half. A loop diuretic would make things worse, because it abolishes the medullary gradient. Restricting protein reduces the urea load. Amiloride adds natriuresis, and in lithium toxicity it also blocks the sodium channel through which lithium enters the cells. NSAIDs help some patients with nephrogenic diabetes insipidus by removing prostaglandin opposition to ADH.',
      ],
      points: ['Central: desmopressin, at the lowest dose that works', 'Nephrogenic: thiazide, low-solute diet, ± amiloride, ± NSAID', 'Never a loop diuretic: it dissipates the gradient'],
      cite: { rose: [24, 15], evidence: 'clinical' },
      route: '/water-disorders',
    },
  ],
  numbers: [
    { label: 'Plasma osmolality maintained', value: '280–290 mOsm/kg', note: 'within 1–2%' },
    { label: 'ADH threshold', value: '≈ 275–285 mOsm/kg', note: 'thirst a few mOsm/kg higher' },
    { label: 'Na⁺ in an alert adult with water available', value: 'rarely > 150 mmol/L' },
    { label: 'Insensible water loss', value: '800–1000 mL/day' },
    { label: 'Normal maximum urine osmolality', value: '800–1400 mOsm/kg' },
    { label: 'Daily solute excretion', value: '600–900 mOsm/day' },
    { label: 'Polyuria', value: '> 3 L/day' },
    { label: 'Urine output in diabetes insipidus', value: '3–20 L/day' },
    { label: 'Desmopressin response', value: '+100–800% complete, +15–50% partial central DI', note: 'little or none in nephrogenic DI' },
    { label: 'Maximum correction rate (chronic)', value: '0.5 mmol/L/h; 12 mmol/L/day' },
    { label: 'Brain osmolytes', value: '≈ 35% of the adaptive rise in osmoles' },
    { label: 'Water restriction stops at', value: 'Posm 295–300, a plateau, or 3–5% weight loss' },
  ],
  equations: ['waterdeficit', 'effosm', 'efwc'],
  clinical: [
    'An alert adult with a sodium above 150 and access to water has a thirst problem, usually a hypothalamic lesion. Look for it.',
    'Hospital hypernatraemia is usually made in hospital: an unconscious or intubated patient, insensible losses and hypotonic urine unreplaced, lactulose, an osmotic diuresis, or the glucose and water shift that follows insulin in hyperglycaemia.',
    'In a hypernatraemic patient the urine osmolality is the first test: above 800 means the kidney is working, below 300 means diabetes insipidus.',
    'Before starting desmopressin for polyuria, be sure it is not primary polydipsia. In a patient who keeps drinking, desmopressin causes hyponatraemia.',
    'Correct chronic hypernatraemia by about 12 mmol/L a day at most, and measure the sodium often. The formula is an estimate.',
    'Polyuria in hospital with a urine osmolality above 300 is a solute diuresis. Find the solute (sodium, glucose, urea) before reaching for desmopressin.',
  ],
  pathology: [
    { name: 'Complete central diabetes insipidus', broken: 'No ADH is secreted', consequence: 'Urine of 40–100 mOsm/kg at 10–20 L/day; sodium high-normal while thirst holds, rising fast when it does not', route: '/water-disorders' },
    { name: 'Lithium nephrogenic diabetes insipidus', broken: 'Lithium enters collecting-duct cells via ENaC and blunts the ADH response', consequence: 'High ADH, dilute urine, no response to desmopressin; amiloride blocks the entry', route: '/water-disorders' },
    { name: 'Hypercalcaemia', broken: 'Calcium-sensing receptor activation in the thick ascending limb and inner medullary collecting duct', consequence: 'A smaller medullary gradient and a weaker ADH effect; reversible', route: '/water-disorders' },
    { name: 'Hypokalaemia', broken: 'A K⁺ deficit of 300–400 mmol reduces collecting-duct ADH responsiveness', consequence: 'A reversible concentrating defect, and perhaps increased thirst', route: '/potassium' },
    { name: 'Osmotic diuresis', broken: 'Unreabsorbed glucose, urea or mannitol holds water in the lumen', consequence: 'Water lost in excess of Na⁺ + K⁺; sodium rises unless intake keeps up', route: '/glucose' },
    { name: 'Essential hypernatraemia', broken: 'Selective osmoreceptor damage; ADH is released by volume signals only', consequence: 'Hypodipsia, sodium drifting between 150 and 180, and a urine that dilutes with hypertonic saline', route: '/adh' },
    { name: 'Sodium overload', broken: 'Hypertonic sodium given or ingested', consequence: 'Volume-expanded hypernatraemia with a concentrated, sodium-rich urine', route: '/body-water' },
    { name: 'Primary hyperaldosteronism', broken: 'Mild chronic volume expansion shifts the ADH threshold up by 5–10 mOsm/kg', consequence: 'A true reset osmostat, with the sodium settling near 145', route: '/raas' },
  ],
  questions: [
    {
      q: 'A patient with complete central diabetes insipidus is alert, has a normal thirst mechanism and free access to water. Where is the plasma sodium most likely to be?',
      options: ['130–135 mmol/L', '140–145 mmol/L', '150–160 mmol/L', 'Above 160 mmol/L'],
      answer: 1,
      explanation: 'Thirst matches intake to the urine output, so the sodium sits in the high-normal range. Hypernatraemia needs impaired thirst or no access to water. Primary polydipsia, by contrast, sits low-normal.',
      route: '/water-disorders',
    },
    {
      q: 'After water restriction to a plasma osmolality of 300 mOsm/kg, the urine osmolality is 90 mOsm/kg. Two hours after desmopressin it is 95. What is the diagnosis?',
      options: ['Primary polydipsia', 'Partial central diabetes insipidus', 'Complete central diabetes insipidus', 'Nephrogenic diabetes insipidus'],
      answer: 3,
      explanation: 'The urine stays dilute despite a high plasma osmolality (so maximal endogenous ADH), and exogenous hormone adds nothing. The collecting duct cannot respond.',
      route: '/water-disorders',
    },
    {
      q: 'A patient with nephrogenic diabetes insipidus has a urine osmolality fixed at about 100 mOsm/kg and excretes 800 mOsm of solute a day. A low-salt, low-protein diet halves the solute. What happens to the urine volume?',
      options: ['Stays at about 8 L/day', 'Falls to about 4 L/day', 'Falls to about 2 L/day', 'Rises, because the diet is dilute'],
      answer: 1,
      explanation: 'With the urine osmolality fixed, volume = solute ÷ osmolality: 800 ÷ 100 = 8 L, and 400 ÷ 100 = 4 L.',
      route: '/water-disorders',
    },
    {
      q: 'A woman with 50 kg of lean weight has chronic hypernatraemia with a sodium of 170 mmol/L. Using 40% of lean weight as body water, what is her water deficit, and how long should correction to 140 take at most?',
      options: ['About 2 L over 12 h', 'About 4.3 L over at least 60 h', 'About 8 L over 24 h', 'About 4.3 L over 24 h'],
      answer: 1,
      explanation: '20 L × (170/140 − 1) ≈ 4.3 L. A fall of 30 mmol/L at no more than 0.5 mmol/L per hour takes at least 60 hours, and ongoing insensible losses have to be added on top.',
      route: '/water-disorders',
    },
    {
      q: 'A hypernatraemic infant has a urine osmolality of 900 mOsm/kg and a urine sodium of 160 mmol/L. What is the most likely cause?',
      options: ['Central diabetes insipidus', 'Unreplaced insensible losses', 'Sodium overload', 'Osmotic diarrhoea'],
      answer: 2,
      explanation: 'A concentrated urine means the kidney is working. After water loss the urine sodium is usually below 25 mmol/L, but after sodium overload the kidney excretes the excess and the urine sodium is high.',
      route: '/water-disorders',
    },
    {
      q: 'Why does a thiazide reduce the urine volume in nephrogenic diabetes insipidus?',
      options: [
        'It restores the collecting duct\'s response to ADH',
        'The mild volume depletion it causes increases proximal reabsorption, so less water reaches the collecting duct',
        'It stimulates ADH secretion',
        'It raises the medullary gradient',
      ],
      answer: 1,
      explanation: 'The effect depends on the sodium deficit, not on ADH. That is why it works in nephrogenic diabetes insipidus, and why it needs a low-sodium diet.',
      route: '/water-disorders',
    },
  ],
  updates: [
    {
      topic: 'Copeptin after hypertonic saline',
      text: 'The chapter calls the water-restriction test the definitive investigation, while noting its weak spot: separating partial central diabetes insipidus from primary polydipsia. A 2018 multicentre study tested that directly. In 141 patients with hypotonic polyuria given both tests, the indirect water-restriction test reached the correct diagnosis in 76.6 per cent. Plasma copeptin (a stable fragment of the vasopressin precursor), measured once hypertonic saline had raised the sodium to at least 150 mmol/L, was correct in 96.5 per cent at a cut-off of 4.9 pmol/L. For partial central diabetes insipidus versus primary polydipsia, the figures were 73.3 versus 95.2 per cent. One serious adverse event, desmopressin-induced hyponatraemia, occurred during water restriction. The physiology the test relies on is unchanged; copeptin measures the hormone instead of inferring it from the urine.',
      cite: { refs: ['fenske2018copeptin'], rose: [24], evidence: 'clinical', update: 'A direct measure of the hormone where the book had to infer it.' },
    },
    {
      topic: 'Renaming diabetes insipidus',
      text: 'In 2022 an international working group proposed replacing "central diabetes insipidus" and "nephrogenic diabetes insipidus" with arginine vasopressin deficiency (AVP-D) and arginine vasopressin resistance (AVP-R), because patients carrying the old name were coming to harm. The names now describe what the chapter always meant: too little hormone, or a kidney that does not answer it.',
      cite: { refs: ['arima2022rename'], rose: [24], evidence: 'guideline', update: 'New names for the same two mechanisms.' },
    },
    {
      topic: 'How fast to correct in adults',
      text: 'The chapter\'s limit of 0.5 mmol/L per hour comes, as it says, from observations in children, with no definitive trials. In a 2019 retrospective study of critically ill adults with a sodium above 155 mmol/L (122 at admission, 327 acquired in hospital), correction faster than 0.5 mmol/L per hour was not associated with higher 30-day mortality. Chart review found no case of cerebral oedema attributable to rapid correction. This is observational evidence in one population, not a trial, and it does not cover infants, in whom the cerebral oedema was described. It suggests the limit is a precaution rather than a threshold proven for adults.',
      cite: { refs: ['chauhan2019hypernat'], rose: [24], evidence: 'clinical', update: 'The evidence behind the rate limit in adults is weaker than the limit suggests.' },
    },
  ],
  modules: ['/water-disorders', '/adh', '/urine-osmolality', '/free-water', '/body-water', '/hyponatremia'],
};
