import type { ChapterContent } from './types';

export const chapter: ChapterContent = {
  n: 25,
  title: 'Hyperosmolal states — hyperglycaemia',
  thesis:
    'Uncontrolled diabetes is three disorders at once: a hyperosmolal state like hypernatraemia, a volume depletion driven by the glucose osmotic diuresis, and — when insulin is absent rather than merely short — a ketoacidosis. Each comes from the same lesion, too little insulin and too much glucagon, and the kidney sits in the middle of all three: it limits the glucose and the acid by excreting them, and it deepens the dehydration and the potassium deficit by doing so. Diabetic ketoacidosis and non-ketotic hyperglycaemia are two ends of one spectrum, and treatment has to anticipate what insulin will do to the potassium, the sodium and the brain as the glucose falls.',
  concepts: [
    {
      heading: 'Insulin and glucagon set the glucose; the liver is where they meet',
      body: [
        'The plasma glucose is the balance between production (diet, glycogen breakdown and hepatic gluconeogenesis from lactate, alanine and glycerol) and use by tissues. Insulin lowers it three ways: it suppresses hepatic glucose output, moves glucose transporters to the surface of muscle and fat cells, and, by blocking protein breakdown and lipolysis, cuts the supply of gluconeogenic substrate. Glucagon does the opposite in the liver, tipping the balance between glycolysis and gluconeogenesis through fructose 2,6-bisphosphate.',
        'Early insulin deficiency shows only after meals, because the liver, perfused by portal blood with a high insulin concentration and needing only half as much insulin as muscle, is still suppressed. As the deficiency deepens the liver escapes: fasting glucose rises from gluconeogenesis, fed partly by alanine from muscle, so fasting hyperglycaemia is also a catabolic state. Glucagon is essential to this. Block its release with somatostatin and fasting hyperglycaemia in an insulin-deficient subject is much smaller; give glucagon excess to someone who can still make insulin and the glucose barely moves.',
        'Stress hormones (adrenaline, cortisol, growth hormone) add to production and reduce uptake, which is why infection, volume depletion or surgery so often precipitate a crisis.',
      ],
      chain: [
        'Insulin deficiency with glucagon excess',
        'Hepatic gluconeogenesis and glycogenolysis rise; peripheral uptake falls',
        'Plasma glucose rises',
        'Filtered glucose exceeds the proximal transport maximum',
        'Glucosuria and an osmotic diuresis',
      ],
      points: ['Fasting glucose 3.3–5.6 mmol/L (60–100 mg/dL)', 'Hepatic effect of insulin needs half the dose of the peripheral one', 'Glucagon excess alone causes only mild hyperglycaemia'],
      cite: { rose: [25], evidence: 'physiology' },
      route: '/glucose',
    },
    {
      heading: 'Ketogenesis needs two changes, and glucagon supplies the second',
      body: [
        'When cells cannot use glucose, the liver makes ketones from fatty acids to supply other fuel and spare muscle protein. That needs more fatty acid delivered to the liver (lipolysis, released by insulin deficiency) and a liver prepared to oxidise it. The gate is carnitine palmitoyltransferase, which admits fatty acyl-CoA to the mitochondria and is held shut by malonyl-CoA. Glucagon lowers malonyl-CoA, the gate opens, and acetoacetate and β-hydroxybutyrate pour out. In the fed state the same fatty acids would simply be packed into triglyceride.',
        'Fasting ketosis is self-limiting, rarely beyond about 12 mmol/L, because ketones themselves release a little insulin. In an insulin-deficient diabetic that brake is missing, and ketoacidosis can become severe. Lipolysis is far more sensitive to insulin than glucose uptake is — suppressing it takes about a tenth of the insulin. That is one explanation for non-ketotic hyperglycaemia: enough insulin to stop the fatty acids, not enough to clear the glucose.',
      ],
      chain: ['Severe insulin deficiency → lipolysis → free fatty acids to the liver', 'Glucagon → low malonyl-CoA → CPT gate open', 'Acetoacetic and β-hydroxybutyric acid', 'HCO₃⁻ consumed; the anion gap rises'],
      points: ['Fasting ketoacidosis rarely exceeds 12 mmol/L', 'Lipolysis is suppressed by ~1/10 of the insulin that glucose uptake needs', 'Acetone is neutral; the other two are acids'],
      cite: { rose: [25, 19], evidence: 'physiology' },
      route: '/metabolic-acidosis',
    },
    {
      heading: 'The osmotic diuresis: volume and water lost together',
      body: [
        'Once the filtered glucose (GFR × plasma glucose) exceeds the proximal tubule\'s capacity, the unreabsorbed glucose holds water in the lumen, lowers the luminal sodium and so the sodium the proximal tubule can take back, and washes out the medullary gradient. Urine volume and sodium excretion both rise. In severe hyperglycaemia the losses reach 8 to 10 litres, a quarter of body water, enough to cause circulatory failure.',
        'The urine is not simply saline. Much of its osmolality is glucose, so its sodium-plus-potassium concentration is well below the plasma\'s — about 70 mmol for each litre lost. That is water lost in excess of sodium plus potassium, which pushes the plasma sodium and the effective osmolality up. It is the same arithmetic as in hypernatraemia (chapter 24), and it is why the sodium in these patients is usually higher than the glucose alone would predict.',
      ],
      chain: ['Filtered glucose > transport maximum', 'Unreabsorbed glucose holds water and sodium in the lumen', 'Medullary washout; urine only modestly hyperosmotic, mostly glucose', 'Urine Na⁺ + K⁺ ≈ 70 mmol/L, below plasma', 'Volume depletion plus a rising effective osmolality'],
      points: ['Fluid deficit 3–6 L in DKA, 8–10 L in non-ketotic hyperglycaemia', 'About 70 mmol of Na⁺ + K⁺ per litre of urine', 'Water lost in excess of solute raises the tonicity'],
      cite: { rose: [25, 24, 4], evidence: 'physiology' },
      route: '/hyperglycemia',
      equation: 'efwc',
    },
    {
      heading: 'The kidney helps and harms (Table 25-1)',
      body: [
        'Intact renal function limits the glucose and the acid. Excreting glucose caps how high the plasma level can climb, and excreting ketoacid anions with H⁺ (as the free acid) or with ammonium removes acid: in one study about 30 per cent of the ketoacid made was excreted, and another 15 to 25 per cent was neutralised by conversion to acetone.',
        'The same excretion does harm. It maximises the osmotic diuresis. It loses ketoacid anions as sodium and potassium salts, which deepens the volume and potassium deficits and throws away the anions that insulin would otherwise have turned back into bicarbonate. And the combination of high distal flow, non-reabsorbable anions and volume-driven aldosterone wastes potassium. That kaliuresis is what makes the potassium deficit so large, although it also protects against extreme hyperkalaemia at presentation.',
        'Take the kidney away and the picture changes. Diabetic patients on dialysis can reach glucose levels of 55 to 85 mmol/L (1000–1500 mg/dL) without volume depletion or marked hyperosmolality, because there is no osmotic diuresis; water moving out of cells even dilutes the sodium. But they are at risk of life-threatening hyperkalaemia (8–9 mmol/L), because the potassium leaving cells has nowhere to go, and the cell water shifted into an already expanded extracellular space can cause pulmonary oedema.',
      ],
      points: ['Beneficial: glucose and acid excreted', 'Harmful: osmotic diuresis, Na⁺/K⁺ salts of ketoacids lost, potential HCO₃⁻ lost', 'Dialysis patient: very high glucose, little hyperosmolality, dangerous hyperkalaemia'],
      cite: { rose: [25], evidence: 'clinical' },
      route: '/hyperglycemia',
    },
    {
      heading: 'The plasma sodium: dilution by cell water, concentration by the diuresis',
      body: [
        'Glucose enters most cells slowly without insulin, so a rise in plasma glucose is a rise in extracellular solute. Water leaves the cells until the osmolality is equal again, the extracellular fluid expands, and its sodium is diluted, while the total osmolality ends up higher than it was. This is translocational hyponatraemia, and it is the reverse of what the low sodium would usually mean.',
        'How large is the effect? Treating the body as an ideal osmometer (Katz) predicts a fall of about 1.6 mmol/L of sodium per 5.6 mmol/L (100 mg/dL) rise in glucose. When hyperglycaemia was actually induced in volunteers, the fall was steeper above about 22 mmol/L (400 mg/dL); overall about 2.4 per 5.6 mmol/L fitted better. A glucose of 55 mmol/L (1000 mg/dL) would take a sodium of 140 down to about 118, and the effective osmolality would then be only about 290 + 23: hyperglycaemia on its own is not enough for marked hyperosmolality.',
        'In practice the sodium is usually higher than predicted, because the osmotic diuresis has removed water in excess of sodium and potassium. Correcting the measured sodium for the glucose — adding back 1.6 to 2.4 mmol/L per 5.6 mmol/L of glucose above normal — estimates what the sodium will be once the glucose is gone, and a high corrected value warns that hypernatraemia will appear during treatment as glucose and water re-enter the cells. Severe lipaemia can lower the measured sodium spuriously; the measured osmolality then exceeds the calculated one.',
      ],
      chain: ['Glucose rises in the ECF', 'Water moves out of cells', 'ECF expands; Na⁺ diluted (translocation)', 'Osmotic diuresis then removes water in excess of Na⁺ + K⁺', 'Na⁺ drifts back up; the corrected Na⁺ is high'],
      points: ['Katz: −1.6 mmol/L Na⁺ per +5.6 mmol/L glucose', 'Hillier: about −2.4 overall, steeper above 22 mmol/L', 'Corrected Na⁺ predicts the sodium after the glucose falls'],
      cite: { refs: ['hillier1999'], rose: [25, 22], evidence: 'clinical' },
      route: '/hyperglycemia',
      equation: 'nacorr',
    },
    {
      heading: 'Ketoacidosis and non-ketotic hyperglycaemia are one spectrum',
      body: [
        'Diabetic ketoacidosis tends to occur in young patients with type 1 diabetes who have little or no insulin; non-ketotic hyperglycaemia in older patients, average age 60 to 65, whose insulin is reduced but not absent. Measured insulin levels do not always separate them, and ketoacidosis can occur in type 2 diabetes. They are better thought of as ends of one spectrum of insulin deficiency, both usually precipitated by stress rather than by omitted insulin.',
        'The glucose is usually much higher in the non-ketotic form, often above 55 mmol/L (1000 mg/dL), against usually below 44 mmol/L (800 mg/dL) in ketoacidosis. Two reasons: the older patient often has impaired renal function, while the young type 1 diabetic may have a GFR up to 50 per cent above normal and excretes glucose far better; and ketoacidosis brings the patient in early with breathlessness, whereas hyperosmolality creeps up until the patient is confused.',
        'Neurological symptoms track the effective osmolality (measured osmolality minus urea, since urea is an ineffective osmole). Coma is unusual below 320–330 mOsm/kg. In non-ketotic hyperglycaemia the effective osmolality may reach 380, and coma occurs in a quarter to a half. Brain cells defend their volume as in hypernatraemia, first with electrolytes and within hours with new organic osmolytes, which is what makes too-rapid correction dangerous.',
      ],
      points: ['DKA: glucose usually < 44 mmol/L; NKH: often > 55 mmol/L', 'Coma unusual below an effective osmolality of 320–330', 'Precipitants: infection, volume depletion, surgery, stress'],
      cite: { rose: [25, 24], evidence: 'clinical' },
      route: '/hyperglycemia',
    },
    {
      heading: 'Diagnosing ketoacidosis: the ketone test, the gap and its pitfalls',
      body: [
        'Nitroprusside tablets and sticks detect acetoacetate and acetone but not β-hydroxybutyrate, which outnumbers acetoacetate 3 to 1 in diabetic ketoacidosis and up to 8 to 1 in alcoholic ketoacidosis or with coexisting lactic acidosis, where the redox state favours the reduced form. The test can therefore underestimate the ketosis. Sulfhydryl drugs such as captopril give false positives.',
        'The anion gap does not rise one-for-one with the fall in bicarbonate. A patient with good renal function excretes ketoacid anions as sodium and potassium salts: this lowers the gap without changing the H⁺ retained, so a severe acidosis can come with only a modestly raised gap. After insulin, the ketoacid anions still in the body are metabolised and regenerate bicarbonate, but those lost in the urine are gone; a hyperchloraemic, normal-gap acidosis is common during recovery and resolves only as the kidney excretes the acid as ammonium. Vomiting or diuretics can add a metabolic alkalosis and even leave the patient alkalaemic; the raised gap and the glucose still give it away.',
        'Two cautions. Never give insulin on glucosuria or ketonuria alone: a diabetic in coma may be hypoglycaemic, and old glucose may still be in the bladder. When in doubt, give glucose after drawing blood. And in an alcoholic with a high-gap acidosis and a normal or low glucose, think of alcoholic ketoacidosis (treated with glucose, not insulin) and of methanol and ethylene glycol.',
      ],
      points: ['β-hydroxybutyrate : acetoacetate ≈ 3 : 1 in DKA', 'Ketonuria lowers the gap without lessening the acidosis', 'Recovery phase: normal-gap acidosis from lost potential bicarbonate'],
      cite: { rose: [25, 19], evidence: 'clinical' },
      route: '/metabolic-acidosis',
      equation: 'deltaratio',
    },
    {
      heading: 'Insulin and fluids',
      body: [
        'Insulin corrects the glucose chiefly by suppressing hepatic production, and the glucose usually falls at most 3.6 to 6.9 mmol/L per hour (65–125 mg/dL/h), reflecting considerable insulin resistance. Any dose that controls the glucose also stops lipolysis and ketogenesis, and the ketoacid anions are then metabolised back to bicarbonate over the first 5 to 10 hours. Acetone clears more slowly, over 36 hours or more, so persisting ketonuria is not a sign that insulin has failed. Low-dose regimens are as effective as high-dose ones.',
        'Fluid comes first in a markedly hypovolaemic patient. Insulin drives glucose, and with it water, into cells; given before volume is restored it can deepen the extracellular depletion. The average deficit is 3 to 6 litres in ketoacidosis and 8 to 10 in non-ketotic hyperglycaemia, with only about 70 mmol of sodium plus potassium lost per litre. Isotonic saline restores the extracellular volume fastest, still lowers the plasma osmolality because it is hypotonic to the patient, and itself lowers the glucose by 2 to 4 mmol/L per hour by dilution and by restoring renal excretion. Excessively fast infusion adds little and dilutes the bicarbonate.',
        'The creatinine can mislead: acetoacetate is read as creatinine by the colorimetric assay and can raise the reported value by up to about 180 µmol/L (2 mg/dL), falling quickly once insulin clears the ketones.',
      ],
      points: ['Glucose falls ≤ 3.6–6.9 mmol/L/h on insulin', 'Isotonic saline first; half-isotonic once perfusion is restored', 'Add dextrose once glucose falls below about 16.7 mmol/L (300 mg/dL)'],
      cite: { refs: ['umpierrez2024'], rose: [25], evidence: 'clinical' },
      route: '/hyperglycemia',
    },
    {
      heading: 'Cerebral oedema: why the osmolality must not fall too fast',
      body: [
        'Cerebral oedema is an uncommon complication within the first 24 hours of treatment, almost confined to patients under 20. In the series the book cites, herniation or death occurred in up to 3 per cent of children with ketoacidosis, particularly those given relatively dilute fluids. Subclinical brain swelling on imaging is far more common than symptoms.',
        'The mechanism is incompletely understood. Insulin plus fluids can lower the glucose by up to 11 mmol/L (200 mg/dL) per hour, an 11 mOsm/kg/h fall in osmolality if the sodium does not rise to compensate, and water then enters brain cells that have accumulated osmolytes, as in hypernatraemia. Animal work points to the fall in glucose rather than the ketoacidosis. The book\'s prudent regimen: isotonic saline until perfusion is adequate, dextrose-containing fluid once the glucose is below about 16.7 mmol/L, half-isotonic saline only after the rapid-repletion phase, and early mannitol for headache, incontinence or falling consciousness.',
      ],
      points: ['Mostly patients < 20 years', 'Glucose can fall 11 mmol/L/h — an 11 mOsm/kg/h fall in osmolality unless the sodium rises', 'The measured sodium should rise as the glucose falls'],
      cite: { refs: ['kuppermann2018'], rose: [25], evidence: 'clinical', update: 'A large randomised trial in children with DKA (PECARN FLUID) found that neither faster rehydration nor a lower sodium content (0.45% versus 0.9% saline) changed the rate of clinically apparent brain injury, which was about 1% overall. The trial does not support the idea that the rate or tonicity of fluid alone is the dominant cause, although rapid falls in osmolality remain undesirable.' },
      route: '/hyperglycemia',
    },
    {
      heading: 'Potassium: a deficit hidden behind a normal or high level',
      body: [
        'The average potassium deficit in ketoacidosis or non-ketotic hyperglycaemia is 3 to 5 mmol/kg and can exceed 10 mmol/kg. Vomiting, the osmotic diuresis, ketoacid anion excretion and potassium released from cells by glycogenolysis and protein breakdown all contribute. Yet the plasma potassium is usually normal and high in about a third.',
        'The shift out of cells comes from insulin deficiency and, more importantly, from hyperosmolality. Water leaving cells concentrates their potassium, favouring diffusion out through potassium channels, and drags potassium with it by solvent drag. Acidaemia itself contributes little here, because organic acids move potassium far less than mineral acids do; hyperkalaemia is as common in the non-ketotic form, where the pH is near normal.',
        'Insulin reverses the shift directly and by lowering the glucose, and the deficit is then unmasked. The book advises adding 20 to 40 mmol/L of KCl once the plasma potassium is below 4.5 mmol/L, and starting at once, before insulin, in a patient who is hypokalaemic at presentation, because insulin and fluid alone can then take the potassium to dangerous levels. Remember that potassium counts toward tonicity: 40 mmol of KCl in a litre of isotonic saline makes a solution with an effective osmolality near 400 mOsm/kg, so potassium is better given in half-isotonic saline once volume is restored.',
      ],
      chain: ['Insulin deficiency + hyperosmolality shift K⁺ out of cells', 'Plasma K⁺ normal or high despite a deficit of 3–5 mmol/kg', 'Insulin and falling glucose drive K⁺ back in', 'The deficit appears as hypokalaemia unless KCl is given'],
      points: ['Deficit 3–5 mmol/kg (can exceed 10)', 'Plasma K⁺ high in about a third at presentation', 'Add KCl once K⁺ < 4.5 (book); start before insulin if already low'],
      cite: { refs: ['umpierrez2024'], rose: [25, 12, 27], evidence: 'clinical', update: 'Current consensus (umpierrez2024) keeps the same logic with slightly different thresholds: potassium is added once the plasma level falls to about 5.0–5.2 mmol/L, and insulin is withheld until the potassium is at least 3.5 mmol/L.' },
      route: '/hypokalemia',
    },
    {
      heading: 'Bicarbonate and phosphate: usually not',
      body: [
        'Insulin partly corrects the acidosis on its own, by regenerating bicarbonate from the retained ketoacid anions, and small controlled trials found no benefit from sodium bicarbonate on outcome or on the rate at which bicarbonate rose; alkali may even increase hepatic ketone production. The book reserves cautious bicarbonate for severe acidaemia (pH ≤ 7.0–7.1), where depressed contractility and vasodilatation threaten perfusion, for the patient with a near-normal gap whose ketoacid anions have already been lost in the urine and cannot regenerate bicarbonate, and for life-threatening hyperkalaemia. The aim is a pH of 7.15–7.20, not normality.',
        'Phosphate is depleted too, with the plasma level initially high for the same reasons as the potassium. It falls rapidly on insulin — from a mean of 3.0 to 0.9 mmol/L (9.2 to 2.8 mg/dL) in 12 hours in one study — but routine replacement has not improved outcome and can cause hypocalcaemia. It is reserved for severe, symptomatic hypophosphataemia.',
      ],
      points: ['Bicarbonate only if pH ≤ 7.0–7.1, normal-gap recovery, or dangerous K⁺', 'Phosphate falls fast on insulin; replace only if severe'],
      cite: { refs: ['umpierrez2024'], rose: [25], evidence: 'clinical' },
      route: '/metabolic-acidosis',
    },
  ],
  numbers: [
    { label: 'Fasting plasma glucose', value: '3.3–5.6 mmol/L', note: '60–100 mg/dL' },
    { label: 'Fluid deficit', value: 'DKA 3–6 L; NKH 8–10 L' },
    { label: 'Na⁺ + K⁺ lost per litre of urine', value: '≈ 70 mmol' },
    { label: 'Fall in Na⁺ per 5.6 mmol/L rise in glucose', value: '1.6 (Katz) to 2.4 (Hillier)' },
    { label: 'Glucose in DKA', value: 'usually < 44 mmol/L (800 mg/dL)' },
    { label: 'Glucose in NKH', value: 'often > 55 mmol/L (1000 mg/dL)' },
    { label: 'Coma unusual below', value: 'effective osmolality 320–330 mOsm/kg' },
    { label: 'Ketone production in DKA', value: '≈ 51 mmol/h; ~30% excreted', note: '15–25% neutralised as acetone' },
    { label: 'β-hydroxybutyrate : acetoacetate', value: '3 : 1 (DKA); up to 8 : 1 (alcoholic, lactic)' },
    { label: 'K⁺ deficit', value: '3–5 mmol/kg; can exceed 10' },
    { label: 'Maximum glucose fall on insulin', value: '3.6–6.9 mmol/L/h', note: '65–125 mg/dL/h' },
    { label: 'Switch to dextrose-containing fluid', value: 'glucose < 16.7 mmol/L (300 mg/dL)' },
    { label: 'Bicarbonate considered', value: 'pH ≤ 7.0–7.1' },
  ],
  equations: ['nacorr', 'effosm', 'ag', 'deltaratio', 'efwc'],
  clinical: [
    'Polyuria, polydipsia and weight loss are the triad of the glucose osmotic diuresis; hyperventilation and the smell of acetone add ketoacidosis.',
    'Always check the glucose before giving insulin to a comatose diabetic: glucosuria or ketonuria can be hours old.',
    'Read the sodium against the glucose: a normal measured sodium with a glucose of 50 mmol/L means a corrected sodium in the 150s, and hypernatraemia will surface as the glucose falls.',
    'A normal or high potassium at presentation does not mean normal stores. Start KCl early; start it before insulin if the potassium is already low.',
    'Persisting ketonuria after the gap has closed is usually acetone, not treatment failure.',
    'A hyperchloraemic acidosis during recovery is expected when ketoacid anions were lost in the urine; it is not a new disorder.',
    'Patients on SGLT2 inhibitors can develop ketoacidosis with a near-normal glucose; measure ketones rather than relying on the glucose.',
  ],
  pathology: [
    { name: 'Diabetic ketoacidosis', broken: 'Absent insulin with glucagon excess: lipolysis plus an open CPT gate', consequence: 'High-gap metabolic acidosis, osmotic diuresis, K⁺ and phosphate deficits', route: '/hyperglycemia' },
    { name: 'Non-ketotic (hyperosmolar) hyperglycaemia', broken: 'Enough insulin to stop lipolysis, not enough to clear glucose; usually reduced GFR', consequence: 'Glucose often > 55 mmol/L, effective osmolality up to 380, coma in a quarter to a half', route: '/hyperglycemia' },
    { name: 'Hyperglycaemia on dialysis', broken: 'No glucose osmotic diuresis', consequence: 'Very high glucose with little hyperosmolality, dilutional hyponatraemia, dangerous hyperkalaemia, pulmonary oedema', route: '/hyperglycemia' },
    { name: 'Alcoholic ketoacidosis', broken: 'Starvation plus alcohol: low insulin, high glucagon, redox shift toward β-hydroxybutyrate', consequence: 'High-gap acidosis with glucose often normal; nitroprusside underestimates it; treat with glucose', route: '/metabolic-acidosis' },
    { name: 'Euglycaemic ketoacidosis on SGLT2 inhibitors', broken: 'Glucosuria keeps the glucose near normal while insulin is low and glucagon high', consequence: 'Ketoacidosis without the glucose alarm', route: '/glucose' },
    { name: 'Cerebral oedema during treatment', broken: 'Plasma osmolality falls faster than brain osmolytes can leave', consequence: 'Headache, falling consciousness, herniation, mainly in the young', route: '/hyperglycemia' },
  ],
  questions: [
    {
      q: 'A patient has a plasma glucose of 50 mmol/L (900 mg/dL) and a measured sodium of 138 mmol/L. What does this imply about water balance?',
      options: ['Water balance is normal', 'There has been water retention', 'There has been water loss in excess of Na⁺ + K⁺: the corrected sodium is about 150–160', 'Nothing: the sodium is normal'],
      answer: 2,
      explanation: 'Translocation alone would have lowered the sodium by roughly 13 to 20 mmol/L. A normal measured value means the osmotic diuresis has removed water in excess of sodium plus potassium, and hypernatraemia will appear as insulin lowers the glucose.',
      route: '/hyperglycemia',
    },
    {
      q: 'Why can a diabetic on haemodialysis reach a glucose of 70 mmol/L without being volume-depleted?',
      options: ['Insulin resistance', 'There is no glucose osmotic diuresis', 'Dialysis removes the glucose', 'Thirst is abolished'],
      answer: 1,
      explanation: 'Without filtration there is no glucosuria and no osmotic diuresis, so volume and water are not lost; cell water moves out and dilutes the sodium instead. The danger in that patient is hyperkalaemia, because shifted potassium cannot be excreted.',
      route: '/hyperglycemia',
    },
    {
      q: 'A woman with type 1 diabetes has not taken insulin for 36 hours while eating little. Her bicarbonate is 10 mmol/L, her anion gap only 15, and her urine is strongly positive for ketones. Why is the gap only slightly raised?',
      options: ['She has lactic acidosis instead', 'The ketoacid anions are being excreted in the urine as Na⁺ and K⁺ salts', 'Hypoalbuminaemia', 'Laboratory error'],
      answer: 1,
      explanation: 'With good renal function the ketoacid anions leave in the urine, lowering the gap without lessening the acidosis. Those anions cannot regenerate bicarbonate after insulin, so recovery will pass through a normal-gap phase (Rose problem 25-2).',
      route: '/metabolic-acidosis',
    },
    {
      q: 'A patient in DKA has a plasma K⁺ of 3.1 mmol/L at presentation. What comes first?',
      options: ['Insulin bolus', 'Potassium chloride, before insulin', 'Sodium bicarbonate', 'Half-isotonic saline without potassium'],
      answer: 1,
      explanation: 'Insulin and the fall in glucose will drive K⁺ into cells. Starting with a low K⁺ risks dangerous hypokalaemia and arrhythmia, so replacement starts first.',
      route: '/hyperglycemia',
    },
    {
      q: 'Twelve hours into treatment the anion gap has closed but the urine still tests positive for ketones by nitroprusside. What is the likeliest explanation?',
      options: ['Insulin has failed', 'Acetone is cleared slowly', 'A new ketoacidosis', 'Captopril interference'],
      answer: 1,
      explanation: 'Acetone, which nitroprusside detects, is cleared slowly, partly by the lungs, and can persist beyond 36 hours after the acidosis has resolved.',
    },
    {
      q: 'Which change most directly explains why potassium is high at presentation in non-ketotic hyperglycaemia, where the pH is near normal?',
      options: ['Acidaemia', 'Hyperosmolality pulling water and K⁺ out of cells, with insulin deficiency', 'Renal failure', 'Hypoaldosteronism'],
      answer: 1,
      explanation: 'Organic acidoses shift little potassium. Water leaving cells raises cell K⁺ and carries it out by solvent drag, and the absence of insulin removes the stimulus to uptake.',
      route: '/potassium',
    },
  ],
  updates: [
    {
      topic: 'Diagnostic criteria and ketone measurement',
      text: 'The 2024 international consensus defines DKA by three elements — diabetes or hyperglycaemia (glucose ≥ 11.1 mmol/L), ketosis (β-hydroxybutyrate ≥ 3.0 mmol/L), and acidosis (pH < 7.3 and/or bicarbonate < 18 mmol/L) — and recommends measuring β-hydroxybutyrate directly rather than relying on nitroprusside, which misses it. The hyperosmolar hyperglycaemic state is defined by glucose ≥ 33.3 mmol/L with raised effective osmolality and without significant ketoacidosis.',
      cite: { refs: ['umpierrez2024'], evidence: 'guideline' },
    },
    {
      topic: 'Euglycaemic ketoacidosis with SGLT2 inhibitors',
      text: 'The book predates SGLT2 inhibitors. By increasing glucosuria they can hold the glucose near normal while insulin falls and glucagon rises, so ketoacidosis can develop with a glucose below 14 mmol/L. The mechanism fits the chapter\'s physiology exactly — the glucose is being excreted, the ketogenesis is not — and the practical lesson is to measure ketones in an unwell patient on these drugs.',
      cite: { refs: ['peters2015', 'umpierrez2024'], evidence: 'clinical' },
    },
    {
      topic: 'Fluids and cerebral oedema in children',
      text: 'The PECARN FLUID trial randomised 1389 episodes of paediatric DKA to faster or slower rehydration with 0.9% or 0.45% saline and found no difference in clinically apparent brain injury. Rose\'s concern about dilute fluids came from retrospective series; the trial suggests other factors (cerebral hypoperfusion and the illness itself) matter at least as much.',
      cite: { refs: ['kuppermann2018'], evidence: 'clinical' },
    },
  ],
  modules: ['/glucose', '/metabolic-acidosis', '/potassium', '/water-disorders'],
};
