// Hormones acting on the kidney: where, how and to what effect (Rose ch. 6 organisation).

import type { Citation } from './sources';
import type { StructureId } from '../ui/NephronDiagram';

export interface HormoneInfo {
  id: string;
  name: string;
  source: string;
  messenger: string;
  stimuli: string[];
  inhibitors: string[];
  sites: StructureId[];
  actions: string[];
  excess: string;
  deficiency: string;
  drugs: string[];
  route?: string;
  cite: Citation;
}

export const HORMONES: HormoneInfo[] = [
  {
    id: 'adh',
    name: 'ADH (arginine vasopressin)',
    source: 'Supraoptic and paraventricular nuclei → posterior pituitary; half-life 15–20 min',
    messenger: 'V2: Gs → adenylyl cyclase → cAMP. V1: phospholipase C (vasoconstriction, prostaglandins). V1b/V3: ACTH release',
    stimuli: ['↑ Effective osmolality (threshold ~280–290 mOsm/kg; 1% sensitivity)', 'Hypotension / effective volume depletion (large, steep response)', 'Nausea (up to 500×), pain, surgery', 'Hypoglycaemia, nicotine, morphine, many drugs', 'Cortisol deficiency', 'Pregnancy lowers the threshold'],
    inhibitors: ['↓ Osmolality', 'Volume expansion', 'Ethanol', 'Phenytoin', 'Drinking (oropharyngeal reflex, transient)'],
    sites: ['CCD', 'OMCD', 'IMCD', 'TAL'],
    actions: ['Inserts aquaporin-2 in principal cells → water reabsorption', 'Raises inner medullary urea permeability ~4× (UT-A1)', 'May stimulate TAL NKCC2 (species-dependent)', 'Stimulates CCD K⁺ secretion, offsetting reduced flow', 'Releases factor VIII and von Willebrand factor (V2)'],
    excess: 'SIADH: water retention, hyponatraemia, inappropriately concentrated urine, no oedema (volume escape).',
    deficiency: 'Central DI: polyuria of dilute urine (up to 10–20 L/day), thirst keeps Na⁺ near normal.',
    drugs: ['Desmopressin (V2 agonist)', 'Tolvaptan/conivaptan (V2 antagonists)', 'Lithium (blocks AQP2 response)', 'NSAIDs (enhance ADH effect)'],
    route: '/adh',
    cite: { rose: [6, 9], evidence: 'physiology', refs: ['robertson1976', 'knepper2015'] },
  },
  {
    id: 'aldosterone',
    name: 'Aldosterone',
    source: 'Adrenal zona glomerulosa (aldosterone synthase)',
    messenger: 'Cytosolic mineralocorticoid receptor → gene transcription (~90-min lag)',
    stimuli: ['Angiotensin II', '↑ Plasma K⁺ (0.1–0.2 mmol/L suffices)', 'ACTH (transient)', 'Hyponatraemia (minor)'],
    inhibitors: ['ANP', 'Volume expansion (via ↓ renin)', 'Hypokalaemia', 'Heparin, ACE inhibitors/ARBs'],
    sites: ['CNT', 'CCD', 'OMCD', 'IMCD'],
    actions: ['↑ Open ENaC in principal cells (<100 → ~3000 per cell)', 'Later ↑ Na⁺-K⁺-ATPase and apical K⁺ channels', '↑ K⁺ secretion', '↑ H⁺ secretion (intercalated and outer medullary cells)', 'Na⁺ reabsorption only (no K⁺ secretion) in inner medulla'],
    excess: 'Primary aldosteronism: hypertension, hypokalaemia, metabolic alkalosis; no oedema because of escape.',
    deficiency: 'Hypoaldosteronism: hyperkalaemia, mild metabolic acidosis (type 4 RTA), modest salt wasting.',
    drugs: ['Spironolactone, eplerenone, finerenone (MR antagonists)', 'Amiloride, triamterene, trimethoprim (ENaC blockers)', 'Fludrocortisone (agonist)', 'Liquorice (lets cortisol act)'],
    route: '/raas',
    cite: { rose: [6], evidence: 'physiology', refs: ['pearce2015'] },
  },
  {
    id: 'angII',
    name: 'Angiotensin II',
    source: 'Renin (JG cells) → angiotensin I → ACE → angiotensin II; also local tissue systems',
    messenger: 'AT1 receptor → phospholipase C (vascular); Gi ↓ cAMP (proximal tubule)',
    stimuli: ['↓ Afferent arteriolar stretch', 'β₁ sympathetic stimulation', '↓ NaCl uptake at the macula densa'],
    inhibitors: ['Volume expansion', 'ANP', 'ACE inhibitors, ARBs, aliskiren, β-blockers, NSAIDs (↓ renin)'],
    sites: ['efferent', 'afferent', 'PT', 'mesangium'],
    actions: ['Efferent > afferent constriction: ↓ RBF, Pgc and GFR preserved', 'Stimulates NHE3 (up to 40–50% of S1 reabsorption)', 'Releases aldosterone', 'Mesangial contraction (↓ Kf) at high levels', 'Sensitises TGF', 'Systemic vasoconstriction; stimulates thirst and ADH'],
    excess: 'Renovascular hypertension, secondary aldosteronism.',
    deficiency: 'With blockade: fall in GFR where perfusion is angiotensin-dependent; hyperkalaemia.',
    drugs: ['ACE inhibitors', 'ARBs', 'Aliskiren'],
    route: '/raas',
    cite: { rose: [2, 6], evidence: 'physiology' },
  },
  {
    id: 'anp',
    name: 'Natriuretic peptides (ANP, BNP, urodilatin)',
    source: 'Atrial (ANP) and ventricular (BNP) myocytes; urodilatin from the kidney',
    messenger: 'Particulate guanylyl cyclase → cGMP',
    stimuli: ['Atrial stretch (any hypervolaemic state, heart failure, renal failure, salt load)'],
    inhibitors: ['Volume depletion', 'Neutral endopeptidase (degrades ANP)'],
    sites: ['IMCD', 'afferent', 'efferent', 'jgCells'],
    actions: ['Closes inner medullary Na⁺ channels', '↑ GFR (afferent dilation + efferent constriction)', '↓ Renin and aldosterone', 'Blunts ADH effect', 'Vasodilation'],
    excess: 'Cerebral salt wasting has been attributed to BNP.',
    deficiency: 'Contributes little alone; pressure natriuresis compensates.',
    drugs: ['Sacubitril (neprilysin inhibitor)', 'Nesiritide'],
    route: '/sodium',
    cite: { rose: [6], evidence: 'physiology' },
  },
  {
    id: 'pg',
    name: 'Prostaglandins (PGE₂, prostacyclin)',
    source: 'Glomeruli, endothelium, collecting duct, medullary interstitial cells (COX-1, COX-2)',
    messenger: 'G-protein-coupled EP and IP receptors; Gi inhibits ADH’s cAMP',
    stimuli: ['Angiotensin II', 'Noradrenaline', 'Vasopressin (V1)', 'Endothelin', 'Volume depletion'],
    inhibitors: ['NSAIDs (COX-1/2)', 'COX-2 inhibitors'],
    sites: ['glomerulus', 'afferent', 'efferent', 'TAL', 'CCD', 'IMCD', 'jgCells'],
    actions: ['Renal vasodilation opposing vasoconstrictors', 'Mediate baroreceptor and macula densa renin release', 'Antagonise ADH', 'Natriuresis (TAL, CD)', 'Protect TAL from hypoxia'],
    excess: 'Bartter syndrome (high PGE₂ contributes).',
    deficiency: 'NSAID effects: AKI in low effective volume, hyperkalaemia, hyponatraemia with non-suppressible ADH, Na⁺ retention, BP rise.',
    drugs: ['NSAIDs', 'Misoprostol'],
    route: '/arterioles',
    cite: { rose: [6], evidence: 'clinical', refs: ['whelton1999'] },
  },
  {
    id: 'pth',
    name: 'Parathyroid hormone',
    source: 'Parathyroid glands, via the calcium-sensing receptor',
    messenger: 'PTH1R → adenylyl cyclase and phospholipase C',
    stimuli: ['↓ Ionised Ca²⁺', '↑ Phosphate', '↓ Calcitriol', 'Acidaemia'],
    inhibitors: ['↑ Ca²⁺', 'Calcitriol', 'Severe hypomagnesaemia', 'Calcimimetics'],
    sites: ['PT', 'TAL', 'DCT', 'CNT'],
    actions: ['↓ Proximal phosphate reabsorption (NaPi-IIa withdrawn)', '↑ Distal Ca²⁺ reabsorption (TRPV5)', '↑ 1α-hydroxylase → calcitriol', 'Bone resorption', '↓ Proximal NHE3'],
    excess: 'Primary hyperparathyroidism: hypercalcaemia, low/normal phosphate.',
    deficiency: 'Hypoparathyroidism: hypocalcaemia, hyperphosphataemia, calciuria limiting correction.',
    drugs: ['Cinacalcet (calcimimetic)', 'Teriparatide'],
    route: '/minerals',
    cite: { rose: [3, 6], evidence: 'physiology' },
  },
  {
    id: 'calcitriol',
    name: 'Calcitriol (1,25-dihydroxyvitamin D)',
    source: 'Kidney (1α-hydroxylase); macrophages in granulomatous disease',
    messenger: 'Vitamin D receptor → gene transcription',
    stimuli: ['PTH', 'Hypophosphataemia', 'Hypocalcaemia (permissive)'],
    inhibitors: ['Hypercalcaemia', 'Phosphate load', 'FGF23', 'Calcitriol itself (24-hydroxylase)'],
    sites: ['PT', 'DCT', 'CNT'],
    actions: ['↑ Gut Ca²⁺ and phosphate absorption', 'Bone resorption (with PTH)', '↑ Distal Ca²⁺ reabsorption (calbindin)', 'Suppresses PTH'],
    excess: 'Vitamin D intoxication, sarcoidosis: hypercalciuria, hypercalcaemia.',
    deficiency: 'Rickets/osteomalacia, hypocalcaemia; contributes to CKD hyperparathyroidism.',
    drugs: ['Calcitriol, alfacalcidol, paricalcitol'],
    route: '/minerals',
    cite: { rose: [6], evidence: 'physiology' },
  },
  {
    id: 'fgf23',
    name: 'FGF23 (not in the 2001 text)',
    source: 'Osteocytes; acts with the co-receptor Klotho',
    messenger: 'FGF receptor–Klotho complex',
    stimuli: ['Phosphate load', 'Calcitriol', 'CKD (rises early)'],
    inhibitors: ['Phosphate restriction'],
    sites: ['PT'],
    actions: ['Removes NaPi-IIa/IIc: phosphaturia', 'Suppresses 1α-hydroxylase: ↓ calcitriol'],
    excess: 'X-linked hypophosphataemia, tumour-induced osteomalacia; CKD.',
    deficiency: 'Tumoral calcinosis with hyperphosphataemia.',
    drugs: ['Burosumab (anti-FGF23)'],
    route: '/minerals',
    cite: { evidence: 'clinical', refs: ['shimada2004', 'isakova2011'] },
  },
  {
    id: 'catecholamines',
    name: 'Noradrenaline / sympathetic nerves',
    source: 'Renal sympathetic nerves, adrenal medulla',
    messenger: 'α₁: phospholipase C; β₁: cAMP (renin); α₂: Gi',
    stimuli: ['Arterial and cardiopulmonary baroreceptor unloading', 'Stress'],
    inhibitors: ['Volume expansion'],
    sites: ['afferent', 'efferent', 'PT', 'TAL', 'jgCells'],
    actions: ['Afferent (and efferent) constriction: ↓ RBF', 'α₁: ↑ proximal and loop Na⁺ transport', 'β₁: renin release', 'α₂: ↓ Na⁺ and ADH-stimulated water reabsorption'],
    excess: 'Contributes to Na⁺ retention in heart failure and cirrhosis.',
    deficiency: 'Autonomic failure: orthostatic hypotension, nocturnal natriuresis.',
    drugs: ['β-blockers (↓ renin)', 'Clonidine (α₂)'],
    route: '/sodium',
    cite: { rose: [6, 8], evidence: 'physiology' },
  },
  {
    id: 'dopamine',
    name: 'Dopamine',
    source: 'Proximal tubule, from filtered L-dopa (more with volume expansion)',
    messenger: 'D1-like receptors → cAMP',
    stimuli: ['Volume expansion, high salt intake'],
    inhibitors: [],
    sites: ['PT', 'afferent', 'efferent'],
    actions: ['Inhibits NHE3 and Na⁺-K⁺-ATPase: natriuresis', 'Dilates both arterioles: ↑ RBF, little ↑ GFR'],
    excess: '—',
    deficiency: 'Blocking dopamine blunts natriuresis of volume expansion (animals).',
    drugs: ['“Renal-dose” dopamine — ineffective for preventing AKI in trials', 'Fenoldopam'],
    route: '/aki',
    cite: { rose: [6], evidence: 'clinical', refs: ['bellomo2000'] },
  },
  {
    id: 'epo',
    name: 'Erythropoietin',
    source: 'Peritubular interstitial fibroblasts (deep cortex, outer medulla); <10% liver',
    messenger: 'Produced via hypoxia-inducible factor; acts on EPO receptor (JAK2)',
    stimuli: ['↓ Oxygen delivery (anaemia, hypoxaemia)'],
    inhibitors: ['Loss of renal mass', 'Inflammation'],
    sites: ['peritubular'],
    actions: ['Terminal differentiation of red cell progenitors'],
    excess: 'Secondary polycythaemia (renal tumours, post-transplant).',
    deficiency: 'Anaemia of CKD.',
    drugs: ['Epoetin, darbepoetin', 'HIF-prolyl hydroxylase inhibitors'],
    route: '/ckd',
    cite: { rose: [6], evidence: 'clinical', refs: ['babitt2012'] },
  },
  {
    id: 'endothelin',
    name: 'Endothelin and nitric oxide',
    source: 'Endothelium (vessels), collecting duct (endothelin); eNOS, nNOS (macula densa, IMCD), iNOS',
    messenger: 'ETA/ETB receptors; NO → soluble guanylyl cyclase → cGMP',
    stimuli: ['Endothelin: ischaemia, nephrotoxins, vasoconstrictors, cytokines', 'NO: shear stress, salt loading'],
    inhibitors: ['Endothelin: NO, vasodilators', 'NO: NOS inhibitors'],
    sites: ['afferent', 'efferent', 'CCD', 'IMCD', 'maculaDensa'],
    actions: ['ETA: most potent renal vasoconstrictor; ETB: vasodilation and natriuresis', 'NO: tonic vasodilation, natriuresis, blunts TGF'],
    excess: 'Endothelin: post-ischaemic and cyclosporine vasoconstriction, fibrosis. Excess iNOS: tissue injury.',
    deficiency: 'Low NO: hypertension, reduced Na⁺ excretion.',
    drugs: ['Endothelin receptor antagonists'],
    route: '/aki',
    cite: { rose: [6], evidence: 'experimental' },
  },
];
