// Clinical case templates. Vitals and ECG measurements are filled from the simulation so
// that the vignette always matches the tracing.

import type { Rng } from '../engine/random';
import { pick, range } from '../engine/random';
import type { PhysioPatch } from '../engine/params';

export interface CaseTemplate {
  dx: string;
  preset: string;
  level: 1 | 2 | 3;
  patch?: PhysioPatch;
  age: [number, number];
  sex?: 'M' | 'F';
  symptoms: string[];
  history: string[];
  meds: string[];
  bp: (rng: Rng) => string;
  spo2?: [number, number];
  temp?: [number, number];
  labs?: (rng: Rng) => string;
  pDesc: string;
  qrsDesc: string;
  stDesc: string;
  rhythmDesc: string;
  mgmtFocus: string;
  unstable?: boolean;
}

const bp = (s0: number, s1: number, d0: number, d1: number) => (r: Rng): string => `${Math.round(range(r, s0, s1))}/${Math.round(range(r, d0, d1))} mmHg`;

export const CASES: CaseTemplate[] = [
  { dx: 'avnrt', preset: 'avnrt', level: 1, age: [19, 45], sex: 'F', symptoms: ['sudden-onset regular palpitations while standing up', 'pounding in the neck, lightheadedness'], history: ['similar short episodes that stop abruptly', 'no known heart disease'], meds: ['none', 'oral contraceptive'], bp: bp(105, 125, 65, 80), pDesc: 'No distinct P before the QRS; retrograde P at the end of the QRS (pseudo-r′ in V1).', qrsDesc: 'Narrow, normal morphology.', stDesc: 'Rate-related minor ST depression may occur; no ischaemic pattern.', rhythmDesc: 'Regular narrow-complex tachycardia with abrupt onset after a PAC.', mgmtFocus: 'Stable → vagal manoeuvre, then adenosine 6 mg → 12 mg; long-term: slow-pathway ablation.' },
  { dx: 'orthoAvrt', preset: 'orthoAvrt', level: 2, age: [16, 35], symptoms: ['recurrent paroxysmal palpitations since adolescence'], history: ['a previous ECG was reported as "short PR"'], meds: ['none'], bp: bp(100, 120, 60, 78), pDesc: 'Pre-excited sinus beats at the start; during tachycardia a retrograde P′ sits in the ST segment (RP ≥ 70 ms).', qrsDesc: 'Sinus beats: short PR + delta wave; tachycardia: narrow QRS.', stDesc: 'Secondary ST–T changes in the pre-excited beats.', rhythmDesc: 'Regular narrow-complex tachycardia initiated by a PAC.', mgmtFocus: 'Vagal/adenosine terminate (AV node is a limb) — with a defibrillator available; ablation of the accessory pathway.' },
  { dx: 'af', preset: 'afRvr', level: 1, age: [60, 85], symptoms: ['palpitations and breathlessness for 2 days'], history: ['hypertension', 'type 2 diabetes'], meds: ['amlodipine', 'metformin'], bp: bp(115, 140, 70, 90), pDesc: 'No organised P waves; fibrillatory baseline (best in V1).', qrsDesc: 'Narrow.', stDesc: 'Rate-related ST depression possible.', rhythmDesc: 'Irregularly irregular narrow-complex tachycardia.', mgmtFocus: 'Stable: rate control (β-blocker or diltiazem), assess stroke risk (CHA₂DS₂-VASc) and anticoagulate; rhythm control decisions per duration/anticoagulation.' },
  { dx: 'flutter', preset: 'flutter21', level: 2, age: [55, 80], symptoms: ['fatigue and palpitations'], history: ['COPD', 'previous CABG'], meds: ['inhaled bronchodilators'], bp: bp(110, 135, 65, 85), pDesc: 'Negative sawtooth flutter waves in II, III, aVF (one hidden in each QRS/T).', qrsDesc: 'Narrow.', stDesc: 'Flutter waves distort the ST–T.', rhythmDesc: 'Regular narrow-complex tachycardia at ~150/min (2:1 flutter).', mgmtFocus: 'Rate control or cardioversion; anticoagulation as for AF; CTI ablation definitive.' },
  { dx: 'mat', preset: 'mat', level: 2, age: [65, 85], symptoms: ['worsening dyspnoea and cough'], history: ['severe COPD'], meds: ['salbutamol', 'theophylline'], bp: bp(120, 150, 70, 90), spo2: [84, 89], labs: (r) => `K⁺ ${range(r, 3.0, 3.4).toFixed(1)} mmol/L, Mg²⁺ ${range(r, 0.55, 0.68).toFixed(2)} mmol/L`, pDesc: 'At least three different P-wave morphologies with varying PR.', qrsDesc: 'Narrow.', stDesc: 'Nonspecific.', rhythmDesc: 'Irregular narrow-complex tachycardia with discrete P waves.', mgmtFocus: 'Treat the COPD exacerbation/hypoxia, replace K⁺/Mg²⁺; rate control with verapamil or cautious β-blocker; cardioversion ineffective.' },
  { dx: 'sinusTach', preset: 'sinusTach', level: 1, age: [25, 70], symptoms: ['fever and rigors'], history: ['urinary symptoms for 3 days'], meds: ['none'], bp: bp(92, 108, 55, 65), temp: [38.6, 39.6], pDesc: 'Sinus P waves (upright II, III, aVF) before each QRS.', qrsDesc: 'Narrow.', stDesc: 'Normal.', rhythmDesc: 'Regular sinus tachycardia.', mgmtFocus: 'Treat the cause (sepsis: fluids, antibiotics) — do not cardiovert or rate-control a compensatory tachycardia.' },
  { dx: 'sinusBrady', preset: 'sinusBrady', level: 1, age: [60, 80], symptoms: ['dizziness'], history: ['hypertension'], meds: ['metoprolol recently increased'], bp: bp(95, 115, 55, 70), pDesc: 'Sinus P waves.', qrsDesc: 'Narrow.', stDesc: 'Normal.', rhythmDesc: 'Regular sinus bradycardia.', mgmtFocus: 'Review β-blocker dose; if unstable: atropine 1 mg (max 3 mg), then pacing / chronotropic infusion.' },
  { dx: 'mobitz1', preset: 'mobitz1', level: 2, age: [55, 80], symptoms: ['incidental finding on telemetry at night'], history: ['inferior STEMI treated yesterday'], meds: ['aspirin', 'ticagrelor', 'atorvastatin'], bp: bp(110, 130, 65, 80), pDesc: 'Sinus P waves marching regularly.', qrsDesc: 'Narrow.', stDesc: 'Resolving inferior changes (not modelled).', rhythmDesc: 'Group beating with progressive PR prolongation and dropped beats.', mgmtFocus: 'Observation; nodal and usually transient after inferior MI; atropine if symptomatic.' },
  { dx: 'mobitz2', preset: 'mobitz2', level: 2, age: [70, 88], symptoms: ['two episodes of sudden syncope without prodrome'], history: ['known right bundle branch block'], meds: ['ramipril'], bp: bp(120, 150, 60, 80), pDesc: 'Sinus P waves, some without a QRS.', qrsDesc: 'Wide, RBBB morphology.', stDesc: 'Secondary ST–T changes of RBBB.', rhythmDesc: 'Second-degree AV block with constant PR (Mobitz II).', mgmtFocus: 'Admit to monitored bed, transcutaneous pacing pads; permanent pacemaker. Atropine unlikely to help.' },
  { dx: 'chb', preset: 'chbVentricular', level: 2, age: [70, 90], symptoms: ['near-syncope, fatigue, confusion'], history: ['degenerative conduction disease'], meds: ['none'], bp: bp(80, 95, 40, 55), pDesc: 'Regular sinus P waves unrelated to QRS complexes.', qrsDesc: 'Wide ventricular escape.', stDesc: 'Secondary to wide QRS.', rhythmDesc: 'Complete heart block with a slow ventricular escape.', mgmtFocus: 'Unstable bradycardia: atropine may fail (infranodal); transcutaneous pacing ± dopamine/epinephrine; transvenous then permanent pacing.', unstable: true },
  { dx: 'chb', preset: 'chbJunctional', level: 2, age: [50, 80], symptoms: ['fatigue'], history: ['recent tick bite and rash (endemic area)'], meds: ['none'], bp: bp(105, 125, 60, 75), pDesc: 'Sinus P waves dissociated from QRS.', qrsDesc: 'Narrow junctional escape.', stDesc: 'Normal.', rhythmDesc: 'Complete heart block with junctional escape.', mgmtFocus: 'Consider reversible causes (e.g. Lyme carditis — often nodal and reversible with antibiotics); temporary pacing if unstable.' },
  { dx: 'monoVT', preset: 'monoVT', level: 2, age: [60, 80], symptoms: ['palpitations and chest pressure'], history: ['anterior MI 5 years ago, LVEF 30%'], meds: ['bisoprolol', 'sacubitril/valsartan', 'spironolactone'], bp: bp(100, 115, 60, 75), pDesc: 'Dissociated sinus P waves visible in places.', qrsDesc: 'Wide (> 140 ms), atypical morphology, superior axis.', stDesc: 'Secondary.', rhythmDesc: 'Regular wide-complex tachycardia with AV dissociation.', mgmtFocus: 'Stable VT: expert consultation, procainamide or amiodarone; synchronised cardioversion if deteriorates; ICD/ablation later.' },
  { dx: 'torsades', preset: 'torsades', level: 3, age: [55, 80], sex: 'F', symptoms: ['recurrent brief syncope in hospital'], history: ['pneumonia on IV azithromycin', 'furosemide'], meds: ['azithromycin', 'furosemide', 'ondansetron'], bp: bp(90, 115, 50, 70), labs: (r) => `K⁺ ${range(r, 2.8, 3.2).toFixed(1)} mmol/L, Mg²⁺ ${range(r, 0.5, 0.65).toFixed(2)} mmol/L`, pDesc: 'Sinus P in the non-arrhythmic beats.', qrsDesc: 'Polymorphic, twisting around the baseline during the run.', stDesc: 'Long QT with abnormal T/U before the run.', rhythmDesc: 'Pause-dependent polymorphic VT (torsades) on a background of long QT.', mgmtFocus: 'IV magnesium, stop QT drugs, correct K⁺/Mg²⁺, increase rate (pacing/isoproterenol) if pause-dependent; defibrillate if sustained.' },
  { dx: 'preexAf', preset: 'preexAf', level: 3, age: [18, 35], symptoms: ['palpitations and presyncope'], history: ['told of an "abnormal ECG" in school'], meds: ['none'], bp: bp(90, 105, 55, 65), pDesc: 'No P waves.', qrsDesc: 'Wide, varying morphology.', stDesc: 'Secondary.', rhythmDesc: 'Irregularly irregular very rapid wide-complex tachycardia.', mgmtFocus: 'Cardioversion or procainamide/ibutilide; AVOID AV-nodal blockers and IV amiodarone; later AP ablation.' },
  { dx: 'wpw', preset: 'wpw', level: 1, age: [16, 30], symptoms: ['asymptomatic pre-participation screening'], history: ['competitive athlete'], meds: ['none'], bp: bp(110, 125, 65, 78), pDesc: 'Sinus P waves.', qrsDesc: 'Short PR, delta wave, wide QRS.', stDesc: 'Secondary ST–T changes.', rhythmDesc: 'Sinus rhythm with ventricular pre-excitation.', mgmtFocus: 'Risk stratification (exercise test/EP study); ablation reasonable, especially with high-risk features or occupation.' },
  { dx: 'stemi', preset: 'stemiAnterior', level: 1, age: [45, 75], sex: 'M', symptoms: ['crushing central chest pain for 40 min, diaphoresis'], history: ['smoker', 'hypercholesterolaemia'], meds: ['none'], bp: bp(120, 150, 75, 95), pDesc: 'Sinus P waves.', qrsDesc: 'Narrow; early loss of R in V1–V3.', stDesc: 'ST elevation V1–V4, I, aVL with reciprocal inferior ST depression.', rhythmDesc: 'Sinus rhythm.', mgmtFocus: 'Activate cath lab — primary PCI (FMC-to-device ≤ 90 min); aspirin, P2Y12 inhibitor, anticoagulation.' },
  { dx: 'stemi', preset: 'stemiInferior', level: 2, age: [45, 80], symptoms: ['epigastric pain, nausea, lightheadedness'], history: ['hypertension'], meds: ['lisinopril'], bp: bp(85, 100, 50, 65), pDesc: 'Sinus P waves.', qrsDesc: 'Narrow.', stDesc: 'ST elevation II, III, aVF (III > II), reciprocal STD in aVL; STE in V4R.', rhythmDesc: 'Sinus rhythm.', mgmtFocus: 'Primary PCI; RV involvement → avoid nitrates, give fluids cautiously for hypotension.' },
  { dx: 'stemiPosterior', preset: 'stemiPosterior', level: 3, age: [50, 75], symptoms: ['ongoing chest pain'], history: ['diabetes'], meds: ['metformin'], bp: bp(120, 140, 70, 85), pDesc: 'Sinus P waves.', qrsDesc: 'Narrow, prominent R in V1–V2.', stDesc: 'Horizontal ST depression V1–V3 with upright T waves.', rhythmDesc: 'Sinus rhythm.', mgmtFocus: 'Record V7–V9; treat as STEMI equivalent (emergency reperfusion).' },
  { dx: 'pericarditis', preset: 'pericarditis', level: 2, age: [20, 45], symptoms: ['sharp chest pain, worse lying flat, better leaning forward'], history: ['viral illness 2 weeks ago'], meds: ['none'], bp: bp(115, 130, 70, 80), temp: [37.6, 38.3], pDesc: 'Sinus P; PR depression in most leads, PR elevation in aVR.', qrsDesc: 'Normal.', stDesc: 'Diffuse concave ST elevation, ST depression in aVR only.', rhythmDesc: 'Sinus tachycardia.', mgmtFocus: 'NSAID/aspirin + colchicine, activity restriction; echo; troponin to assess myocardial involvement.' },
  { dx: 'pe', preset: 'pe', level: 3, age: [35, 75], symptoms: ['sudden dyspnoea and pleuritic chest pain'], history: ['long-haul flight', 'oestrogen therapy'], meds: ['oral contraceptive'], bp: bp(95, 115, 60, 75), spo2: [86, 92], pDesc: 'Sinus P waves.', qrsDesc: 'Incomplete RBBB, rightward axis shift.', stDesc: 'T inversion V1–V4 and III.', rhythmDesc: 'Sinus tachycardia.', mgmtFocus: 'ECG is not diagnostic: CT pulmonary angiography by clinical probability; anticoagulation; risk-stratify (RV strain).' },
  { dx: 'hyperK', preset: 'hyperK7', level: 2, age: [55, 85], symptoms: ['generalised weakness'], history: ['CKD stage 4', 'recent start of spironolactone'], meds: ['spironolactone', 'lisinopril', 'trimethoprim-sulfamethoxazole'], bp: bp(120, 150, 70, 90), labs: (r) => `K⁺ ${range(r, 7.0, 7.6).toFixed(1)} mmol/L, creatinine elevated`, pDesc: 'Low-amplitude, broad P waves.', qrsDesc: 'Widened.', stDesc: 'Tall, narrow, peaked T waves.', rhythmDesc: 'Sinus rhythm with conduction slowing.', mgmtFocus: 'IV calcium now; insulin + glucose, salbutamol; stop culprit drugs; K⁺ binder/dialysis; repeat ECG/K⁺.' },
  { dx: 'hypoK', preset: 'hypoK', level: 2, age: [30, 70], symptoms: ['muscle weakness, palpitations'], history: ['severe diarrhoea'], meds: ['hydrochlorothiazide'], bp: bp(100, 120, 60, 75), labs: (r) => `K⁺ ${range(r, 2.3, 2.7).toFixed(1)} mmol/L`, pDesc: 'Sinus P waves.', qrsDesc: 'Normal.', stDesc: 'ST depression, flat T waves, prominent U waves (long QU).', rhythmDesc: 'Sinus rhythm.', mgmtFocus: 'Replace K⁺ and Mg²⁺; avoid QT-prolonging drugs; monitor.' },
  { dx: 'tca', preset: 'tca', level: 3, age: [18, 50], symptoms: ['found drowsy after an intentional overdose'], history: ['depression'], meds: ['amitriptyline'], bp: bp(85, 100, 45, 60), pDesc: 'Sinus P waves.', qrsDesc: 'Wide QRS with a terminal R wave in aVR.', stDesc: 'Secondary.', rhythmDesc: 'Sinus tachycardia with intraventricular conduction delay.', mgmtFocus: 'Sodium bicarbonate for QRS widening/arrhythmias, airway, benzodiazepines for seizures, vasopressors; avoid class IA/IC drugs.' },
  { dx: 'digoxinEffect', preset: 'atWithBlock', level: 3, age: [70, 90], symptoms: ['nausea, yellow-tinged vision, confusion'], history: ['heart failure', 'recent worsening kidney function'], meds: ['digoxin', 'furosemide'], bp: bp(100, 120, 60, 75), labs: (r) => `digoxin level high, K⁺ ${range(r, 5.2, 5.8).toFixed(1)} mmol/L`, pDesc: 'Rapid regular atrial P′ waves, every second not conducted.', qrsDesc: 'Narrow.', stDesc: 'Sagging ST depression (digoxin effect).', rhythmDesc: 'Atrial tachycardia with 2:1 AV block.', mgmtFocus: 'Stop digoxin; digoxin-specific antibody fragments for toxicity; correct K⁺/Mg²⁺.' },
  { dx: 'lbbb', preset: 'lbbb', level: 2, age: [60, 85], symptoms: ['exertional dyspnoea'], history: ['hypertension', 'LVEF 30% on echo'], meds: ['furosemide'], bp: bp(120, 140, 70, 85), pDesc: 'Sinus P waves.', qrsDesc: 'Wide; broad notched R in I, aVL, V5–V6 without q; QS in V1.', stDesc: 'Appropriately discordant ST–T.', rhythmDesc: 'Sinus rhythm.', mgmtFocus: 'Echo/HF work-up; CRT candidacy per HF guidelines; Sgarbossa/Smith criteria if chest pain.' },
  { dx: 'rbbb', preset: 'rbbb', level: 1, age: [40, 80], symptoms: ['routine pre-operative ECG'], history: ['none'], meds: ['none'], bp: bp(115, 135, 70, 85), pDesc: 'Sinus P waves.', qrsDesc: 'rSR′ in V1, wide S in I and V6, QRS ≥ 120 ms.', stDesc: 'Secondary T inversion V1–V2.', rhythmDesc: 'Sinus rhythm.', mgmtFocus: 'Isolated asymptomatic RBBB: no specific treatment.' },
  { dx: 'lafb', preset: 'lafb', level: 2, age: [55, 80], symptoms: ['routine ECG'], history: ['hypertension'], meds: ['amlodipine'], bp: bp(125, 145, 75, 90), pDesc: 'Sinus P waves.', qrsDesc: 'Narrow; qR in aVL, rS in II/III/aVF.', stDesc: 'Normal.', rhythmDesc: 'Sinus rhythm.', mgmtFocus: 'No treatment; look for associated conduction disease.' },
  { dx: 'lvh', preset: 'lvh', level: 1, age: [60, 85], symptoms: ['exertional breathlessness'], history: ['long-standing hypertension'], meds: ['amlodipine', 'indapamide'], bp: bp(160, 190, 90, 105), pDesc: 'Broad notched P in II (LA abnormality).', qrsDesc: 'High voltage: tall R V5–V6, deep S V1–V2.', stDesc: 'Lateral downsloping ST depression/T inversion (strain).', rhythmDesc: 'Sinus rhythm.', mgmtFocus: 'Blood-pressure control; echo for LV mass/function; evaluate for aortic stenosis.' },
  { dx: 'brugada', preset: 'brugada1', level: 3, age: [25, 50], sex: 'M', symptoms: ['nocturnal agonal breathing witnessed by partner'], history: ['brother died suddenly in his sleep aged 38'], meds: ['none'], bp: bp(115, 130, 70, 80), temp: [38.0, 38.8], pDesc: 'Sinus P waves.', qrsDesc: 'Normal width; no wide S in I/V6.', stDesc: 'Coved ST elevation ≥ 2 mm in V1–V2 with negative T.', rhythmDesc: 'Sinus rhythm.', mgmtFocus: 'Treat fever; avoid Na⁺-channel blockers; EP referral; ICD for arrhythmic syncope/arrest.' },
  { dx: 'lqts', preset: 'lqts', level: 3, age: [12, 30], sex: 'F', symptoms: ['syncope when startled by an alarm clock'], history: ['cousin with "epilepsy" and sudden death'], meds: ['none'], bp: bp(105, 120, 60, 75), pDesc: 'Sinus P waves.', qrsDesc: 'Normal.', stDesc: 'Long QT with broad/notched T waves.', rhythmDesc: 'Sinus rhythm.', mgmtFocus: 'β-blocker (nadolol/propranolol), avoid QT drugs, genetic testing and family screening; ICD if arrest.' },
  { dx: 'vf', preset: 'vf', level: 1, age: [45, 80], symptoms: ['collapsed in the waiting room, unresponsive, no pulse'], history: ['unknown'], meds: ['unknown'], bp: () => 'no pulse', pDesc: 'None.', qrsDesc: 'No identifiable QRS.', stDesc: 'n/a', rhythmDesc: 'Ventricular fibrillation.', mgmtFocus: 'CPR, defibrillate immediately, epinephrine every 3–5 min, amiodarone/lidocaine if refractory, reversible causes.', unstable: true },
  { dx: 'paced', preset: 'vvi', level: 1, age: [70, 90], symptoms: ['routine follow-up'], history: ['pacemaker for complete heart block'], meds: ['none'], bp: bp(120, 140, 70, 80), pDesc: 'Sinus P waves dissociated from ventricular paced complexes.', qrsDesc: 'Pacing spike then wide LBBB-like QRS with superior axis.', stDesc: 'Secondary (discordant) ST–T.', rhythmDesc: 'Ventricular paced rhythm.', mgmtFocus: 'Normal VVI function: every spike captures, rate at lower rate limit.' },
];

export function caseVitals(t: CaseTemplate, rng: Rng, hr: number | null): string {
  const parts = [`HR ${hr ?? '—'}${hr ? '/min' : ''}`, `BP ${t.bp(rng)}`, `SpO₂ ${Math.round(range(rng, ...(t.spo2 ?? [95, 99])))}%`, `T ${range(rng, ...(t.temp ?? [36.4, 37.2])).toFixed(1)} °C`, `RR ${Math.round(range(rng, 14, t.unstable ? 26 : 20))}/min`];
  return parts.join(' · ');
}

export const pickCase = (rng: Rng, filter?: (c: CaseTemplate) => boolean): CaseTemplate => pick(rng, CASES.filter(filter ?? (() => true)));
