import type { Dx } from './types';

// AV block, bundle-branch/fascicular block, pacemaker ECGs.

const avbMgmt = {
  recognition: 'Relationship between P waves and QRS complexes: prolonged PR (1°), progressive PR then drop (Mobitz I), constant PR then sudden drop (Mobitz II), ≥ 2 consecutive dropped P (high-grade), no relationship (complete).',
  mechanism: 'Conduction failure in the AV node (usually benign, vagal/drug, often responds to atropine) or in the His–Purkinje system (disease; unpredictable, may progress to complete block with slow ventricular escape).',
  stability: 'Unstable = hypotension, altered mental status, shock, ischaemic chest discomfort, acute heart failure attributable to bradycardia.',
  immediate: ['Identify reversible causes: drugs (β-blockers, CCB, digoxin, antiarrhythmics), hyperkalaemia, inferior MI/ischaemia, Lyme carditis, hypothyroidism, hypothermia, increased vagal tone.', 'Symptomatic/unstable (2025 AHA): atropine 1 mg IV every 3–5 min (max 3 mg) — useful for nodal block, often ineffective for infranodal block.', 'Then transcutaneous pacing and/or dopamine (5–20 mcg/kg/min) or epinephrine (2–10 mcg/min) infusion; expert consultation; transvenous pacing.'],
  definitive: ['Permanent pacing is indicated for acquired Mobitz II, high-grade or third-degree AV block not due to a reversible or physiological cause, regardless of symptoms (2018 ACC/AHA/HRS, Class I).', 'Mobitz I / first-degree block: pacing only when symptoms clearly correlate or the block is infranodal.', 'Physiological pacing (His-bundle or left-bundle-area pacing, or CRT) is considered when high ventricular pacing burden is expected, particularly with reduced LVEF (2023 HRS/APHRS/LAHRS).'],
  cautions: ['Atropine can WORSEN infranodal (Mobitz II) block: faster sinus rate sends more impulses to the diseased His–Purkinje system, which blocks more of them.', 'Do not suppress a ventricular escape rhythm with antiarrhythmics.', 'Inferior MI AV block is usually nodal and transient; anterior MI AV block is infranodal and ominous.'],
  whyWorks: ['Atropine removes vagal slowing of the AV node → improves nodal conduction.', 'β-agonists enhance nodal conduction and escape-focus automaticity.', 'Pacing bypasses the diseased conduction system entirely.'],
  whyNot: ['Atropine cannot restore conduction through diseased His–Purkinje fibres (they have little vagal innervation).', 'Adenosine and AV-nodal blockers deepen block.'],
  refs: ['brady2018', 'acls2025', 'pacing2023'],
};

export const CONDUCTION_DX: Dx[] = [
  {
    id: 'avb1',
    name: 'First-degree AV block',
    aliases: ['long PR', 'prolonged PR', '1st degree heart block'],
    category: 'avblock',
    tier: 1,
    tags: ['long-pr', 'av-node', 'block', 'regular', 'narrow-qrs'],
    preset: 'avb1',
    definition: 'PR interval > 200 ms with every P conducted (really AV "delay", not block).',
    mechanism: 'Slowed conduction, most often within the AV node (vagal tone, drugs, ageing, inferior ischaemia); less often in the atria or His–Purkinje system (then often with BBB).',
    ecg: ['PR > 200 ms, constant', '1:1 AV conduction', 'Very long PR can place the P wave in the preceding T wave'],
    why: [
      { level: 'cell', text: 'AV-nodal cells depend on the slow L-type Ca²⁺ current; vagal tone, β-blockers, CCBs and digoxin slow it further.' },
      { level: 'conduction', text: 'Every impulse gets through, just later.' },
      { level: 'waveform', text: 'Longer isoelectric PR segment; P and QRS unchanged.' },
      { level: 'clinical', text: 'Usually benign; very long PR (> 300 ms) can cause "pseudo-pacemaker syndrome" because atrial contraction occurs against closed AV valves.' },
    ],
    differential: [{ dx: 'mobitz1', how: 'PR not constant; dropped beats.' }, { dx: 'accelJunctional', how: 'Isorhythmic AV dissociation (junctional rhythm at about the sinus rate): P waves drift relative to the QRS, mimicking a long or changing PR — check that the PR is truly constant.' }],
    acute: ['None; review AV-nodal drugs, electrolytes.'],
    refs: ['brady2018'],
  },
  {
    id: 'mobitz1',
    name: 'Second-degree AV block, Mobitz I (Wenckebach)',
    aliases: ['Wenckebach', 'Mobitz type 1', 'group beating', 'decremental conduction'],
    category: 'avblock',
    tier: 1,
    tags: ['block', 'av-node', 'irregular', 'regularly-irregular', 'long-pr', 'bradycardia', 'atropine'],
    preset: 'mobitz1',
    definition: 'Progressive PR prolongation before a single non-conducted P wave; the cycle then repeats.',
    epidemiology: 'Common during sleep and in athletes (high vagal tone), with AV-nodal drugs, inferior MI. Usually at the level of the AV node → generally benign.',
    mechanism: 'Decremental conduction: AV-nodal conduction time depends on how long the node has had to recover since its last conduction. Each successive P arrives earlier in the recovery curve (because the previous PR was longer) → longer delay → until the node is still refractory → block. The pause resets recovery and the cycle restarts.',
    ecg: ['Progressive PR lengthening, then a P without QRS', 'The PR after the dropped beat is the shortest', 'Increments usually DECREASE → R–R intervals shorten before the pause (classic)', 'Pause < 2 × P–P', 'Group beating (regularly irregular)', 'Usually narrow QRS'],
    why: [
      { level: 'cell', text: 'AV-nodal cells recover excitability slowly (time-dependent recovery of L-type Ca²⁺ channels).' },
      { level: 'conduction', text: 'Impulse 1 arrives after a long rest → conducts quickly (short PR).' },
      { level: 'conduction', text: 'Impulse 2 arrives sooner after the node’s last conduction (the RP shortened by the previous PR) → partially recovered → slower conduction → longer PR.' },
      { level: 'conduction', text: 'Each beat is further up the steep part of the recovery curve until an impulse finds the node refractory → dropped QRS.' },
      { level: 'waveform', text: 'Progressive PR prolongation, then a P wave with no QRS; the pause lets the node fully recover → the cycle restarts with a short PR.' },
      { level: 'diagnosis', text: 'Progressive PR → drop → group beating: Mobitz I (nodal). Use the ladder diagram to watch recovery time shrink beat by beat.' },
      { level: 'treatment', text: 'Nodal and vagally sensitive → atropine improves conduction; usually observation.' },
    ],
    differential: [{ dx: 'mobitz2', how: 'Constant PR before and after the dropped beat; wide QRS common.' }, { dx: 'pacBlocked', how: 'A blocked PAC is PREMATURE (early P deforming the T); in Wenckebach the P waves march on time.' }, { dx: 'avb21', how: '2:1 block: every other P dropped — cannot see PR progression.' }],
    management: avbMgmt,
    refs: ['brady2018', 'acls2025'],
  },
  {
    id: 'mobitz2',
    name: 'Second-degree AV block, Mobitz II',
    aliases: ['Mobitz type 2', 'infranodal block', 'His-Purkinje block'],
    category: 'avblock',
    tier: 1,
    tags: ['block', 'his-purkinje', 'bradycardia', 'pacing', 'syncope', 'wide-qrs'],
    preset: 'mobitz2',
    definition: 'Intermittent non-conducted P waves with a CONSTANT PR interval in the conducted beats before and after the block.',
    epidemiology: 'Almost always infranodal (His bundle or bundle branches), frequently with bundle-branch block; degenerative conduction disease, anterior MI, post-TAVI, infiltrative disease.',
    mechanism: 'His–Purkinje tissue conducts in an all-or-none fashion (fast Na⁺-dependent, little decrement): either the impulse passes with normal timing or it fails completely. Diseased tissue fails intermittently without warning.',
    ecg: ['Constant PR (may be normal) in conducted beats', 'Sudden non-conducted P wave', 'P–P constant; pause = 2 × P–P', 'Often wide QRS (coexisting bundle-branch/fascicular block)'],
    why: [
      { level: 'cell', text: 'Purkinje cells use fast Na⁺ channels: conduction velocity is high and does not decrement — until the tissue fails entirely.' },
      { level: 'conduction', text: 'Therefore conduction time (PR) does not change beat to beat; one impulse simply fails.' },
      { level: 'waveform', text: 'Constant PR, then an unexpected P without QRS.' },
      { level: 'clinical', text: 'Unpredictable: can progress abruptly to complete heart block with a slow unreliable ventricular escape → syncope/sudden death.' },
      { level: 'treatment', text: 'Pacing (temporary → permanent). Atropine is ineffective/harmful: it speeds the sinus node and the AV node, sending MORE impulses to the diseased His–Purkinje system.' },
    ],
    differential: [{ dx: 'mobitz1', how: 'PR progressively lengthens before the drop.' }, { dx: 'pacBlocked', how: 'The blocked P is premature.' }, { dx: 'avb21', how: '2:1: cannot classify from a single strip.' }],
    management: avbMgmt,
    refs: ['brady2018', 'acls2025'],
  },
  {
    id: 'avb21',
    name: '2:1 AV block',
    aliases: ['2 to 1 AV block', 'fixed ratio block'],
    category: 'avblock',
    tier: 2,
    tags: ['block', 'bradycardia', 'regular'],
    preset: 'avb21',
    definition: 'Every second P wave is not conducted. It cannot be classified as Mobitz I or II from the ratio alone.',
    mechanism: 'Could be nodal (Wenckebach with 2:1) or infranodal. Clues: narrow QRS and PR prolongation favour nodal; wide QRS with normal PR favours infranodal; improvement with atropine/exercise → nodal; worsening → infranodal.',
    ecg: ['Two P waves per QRS; the non-conducted P is often in or near the T wave', 'Constant PR in the conducted beats'],
    why: [
      { level: 'conduction', text: 'With only one conducted beat between drops, there is no opportunity to observe PR progression.' },
      { level: 'diagnosis', text: 'Level of block inferred from QRS width, PR, response to vagal/atropine manoeuvres, and longer recordings showing 3:2 cycles.' },
    ],
    differential: [{ dx: 'sinusBrady', how: 'Look for the hidden P in the T wave.' }, { dx: 'pacBlocked', how: 'Blocked atrial bigeminy: premature P′ with different morphology.' }],
    management: avbMgmt,
    refs: ['brady2018'],
  },
  {
    id: 'highGrade',
    name: 'High-grade (advanced) AV block',
    aliases: ['advanced AV block', '3:1 block'],
    category: 'avblock',
    tier: 1,
    tags: ['block', 'bradycardia', 'pacing', 'syncope'],
    preset: 'highGrade',
    definition: 'Two or more consecutive non-conducted P waves with some P waves still conducting (e.g. 3:1, 4:1).',
    mechanism: 'Severe conduction disease, often infranodal (but nodal in, e.g., inferior MI or AV-nodal drug excess); can progress to complete heart block.',
    ecg: ['≥ 2 consecutive blocked P waves', 'Conducted beats have a fixed PR (distinguishes from complete block)', 'Escape beats may appear during long pauses'],
    why: [
      { level: 'conduction', text: 'The conduction system is failing for most impulses but still conducts some — so P and QRS are still related (fixed PR for conducted beats).' },
      { level: 'clinical', text: 'Very slow ventricular rates, high risk of asystole — a pacing indication.' },
    ],
    differential: [{ dx: 'chb', how: 'In complete block the PR varies randomly — no P conducts.' }],
    management: avbMgmt,
    refs: ['brady2018', 'acls2025'],
  },
  {
    id: 'chb',
    name: 'Third-degree (complete) AV block',
    aliases: ['complete heart block', 'CHB', 'third degree heart block', 'AV dissociation', 'junctional escape', 'ventricular escape'],
    category: 'avblock',
    tier: 1,
    tags: ['block', 'bradycardia', 'av-dissociation', 'pacing', 'syncope', 'escape'],
    preset: 'chbJunctional',
    altPresets: ['chbVentricular'],
    definition: 'No atrial impulses reach the ventricles; atria and ventricles are driven by independent pacemakers.',
    epidemiology: 'Degenerative conduction disease (Lenègre/Lev), ischaemia, drugs, hyperkalaemia, infiltrative disease (sarcoid, amyloid), Lyme carditis, congenital, post-cardiac surgery/TAVI.',
    mechanism: 'Complete conduction failure. The level of block decides which pacemaker can escape: block in the AV node leaves the junction below it (narrow QRS, 40–60/min); block in the His–Purkinje system leaves only a ventricular pacemaker (wide QRS, 20–40/min).',
    ecg: ['P waves regular at their own (usually faster) rate', 'QRS complexes regular at a slower escape rate', 'No consistent PR — P waves "march through" the QRS complexes (AV dissociation with atrial rate > ventricular rate)', 'Narrow escape (junctional) or wide escape (ventricular)'],
    why: [
      { level: 'conduction', text: 'The atria follow the sinus node; nothing crosses the block.' },
      { level: 'conduction', text: 'Below the block, the fastest remaining pacemaker escapes (pacemaker hierarchy).' },
      { level: 'waveform', text: 'Junctional escape travels down the intact His–Purkinje system → NARROW QRS, 40–60/min.' },
      { level: 'waveform', text: 'Ventricular escape spreads cell-to-cell → WIDE QRS, 20–40/min, less reliable.' },
      { level: 'diagnosis', text: 'Regular P–P + regular R–R + no relationship → complete heart block. (Try the escape selector: block in the AV node vs below the His bundle.)' },
      { level: 'treatment', text: 'Adenosine or AV-nodal drugs cannot help: there is no conduction to improve and the ventricles are already dissociated from the atria. Pacing replaces the escape pacemaker.' },
    ],
    differential: [{ dx: 'highGrade', how: 'Some P waves conduct with a fixed PR.' }, { dx: 'accelJunctional', how: 'Isorhythmic AV dissociation: ventricular rate ≥ atrial rate — dissociation from a faster junction, not block.' }, { dx: 'monoVT', how: 'VT also shows AV dissociation, but with ventricular rate > atrial rate.' }],
    management: avbMgmt,
    refs: ['brady2018', 'acls2025', 'pacing2023'],
  },
  // ======================================================================= IVCD
  {
    id: 'rbbb',
    name: 'Right bundle branch block',
    aliases: ['RBBB', 'rSR prime', 'M-shaped V1', 'incomplete RBBB'],
    category: 'ivcd',
    tier: 1,
    tags: ['wide-qrs', 'his-purkinje', 'block', 'regular'],
    preset: 'rbbb',
    altPresets: ['incompleteRbbb'],
    definition: 'QRS ≥ 120 ms (adults) with rsr′/rsR′/rSR′ in V1–V2 (the R′/r′ usually wider than the initial r), and an S wave in I and V6 longer than the R or > 40 ms; R-peak time normal in V5–V6 but > 50 ms in V1 (this criterion must be met when V1 shows a broad, often notched, pure R). Incomplete RBBB: same morphology with QRS 110–119 ms.',
    epidemiology: 'Common, often benign in isolation (prevalence increases with age); also with RV pressure/volume load, congenital heart disease (ASD), PE, ischaemia, degenerative disease.',
    mechanism: 'The right bundle does not conduct, so the RV is activated late, spreading cell-to-cell from the LV across the septum.',
    ecg: ['QRS ≥ 120 ms', 'V1–V2: rSR′ ("M" pattern)', 'I, aVL, V5–V6: wide slurred S wave', 'Secondary ST depression/T inversion in V1–V3', 'Axis usually normal (left axis → + LAFB; right axis → + LPFB)'],
    normal: 'Normally the RV and LV are activated simultaneously via both bundles in ~80–100 ms; the thick LV dominates, so RV forces are largely cancelled.',
    why: [
      { level: 'conduction', text: 'Blocked pathway: right bundle. The septum is still activated normally from the LEFT (left→right) → initial small r in V1 and small q in I/V6 are preserved.' },
      { level: 'conduction', text: 'The LV is activated normally → the middle of the QRS looks normal (S in V1, R in V6).' },
      { level: 'conduction', text: 'Rerouting: the RV free wall is reached only when the wavefront crosses the septum muscle-to-muscle — late and slow.' },
      { level: 'vector', text: 'Late, unopposed RV activation → a terminal vector pointing rightward and anterior.' },
      { level: 'lead', text: 'V1 (anterior-right) sees it coming toward it → tall terminal R′. I and V6 (leftward) see it going away → broad terminal S.' },
      { level: 'waveform', text: 'Slow muscle-to-muscle conduction adds ~40+ ms → QRS ≥ 120 ms. Repolarisation follows the delayed RV → T inverted in V1–V3 (secondary).' },
      { level: 'clinical', text: 'Isolated RBBB: little prognostic impact in asymptomatic people; new RBBB with chest pain/dyspnoea → consider PE or ischaemia. RBBB does not hide STEMI (initial forces preserved).' },
    ],
    differential: [{ dx: 'brugada1', how: 'Brugada: coved STE in V1–V2 WITHOUT the wide S in I/V6.' }, { dx: 'wpw', how: 'Short PR and delta wave.' }, { dx: 'rvh', how: 'Dominant R in V1 without QRS widening, right axis, RV strain.' }, { dx: 'stemiPosterior', how: 'Tall R in V1 with horizontal STD, narrow QRS.' }],
    refs: ['ecgStd3', 'durrer1970'],
  },
  {
    id: 'lbbb',
    name: 'Left bundle branch block',
    aliases: ['LBBB', 'Sgarbossa', 'broad notched R'],
    category: 'ivcd',
    tier: 1,
    tags: ['wide-qrs', 'his-purkinje', 'block', 'regular', 'st-elevation', 'discordance'],
    preset: 'lbbb',
    definition: 'QRS ≥ 120 ms, broad notched or slurred R in I, aVL, V5–V6, absent q waves in I, V5–V6, R-peak time > 60 ms in V5–V6, rS or QS in V1 (often V1–V3); ST–T usually opposite to the QRS (appropriate discordance).',
    epidemiology: 'Usually indicates underlying heart disease (hypertension, cardiomyopathy, coronary disease, aortic stenosis, degenerative); associated with LV dyssynchrony and worse outcomes in heart failure; a key indication for cardiac resynchronisation therapy (CRT) when LVEF is reduced.',
    mechanism: 'The left bundle does not conduct: the septum is activated from the RIGHT side, and the entire LV is activated slowly through working myocardium from the septum toward the lateral wall.',
    ecg: ['QRS ≥ 120 ms (often 140–160)', 'Broad, notched ("M") R in I, aVL, V5–V6 with no septal q', 'Deep QS or rS in V1–V3', 'Discordant ST–T: STE in V1–V3, STD/TWI in I, aVL, V5–V6', 'Prolonged R-wave peak time > 60 ms in V5–V6', 'Poor R-wave progression; left axis possible'],
    normal: 'Normally the left bundle activates the septum first from left to right → small septal q in I/V6 and small r in V1.',
    why: [
      { level: 'conduction', text: 'Blocked pathway: left bundle. The septum is now activated right→left (from the right bundle).' },
      { level: 'lead', text: 'Initial septal vector now points LEFTWARD → no septal q in I/V6; V1 loses its initial r (QS) or keeps a tiny r from RV activation.' },
      { level: 'conduction', text: 'Rerouting: the LV is activated cell-to-cell from the septum toward the lateral wall — slowly.' },
      { level: 'vector', text: 'A large, slowly progressing vector points leftward and posterior for the entire QRS.' },
      { level: 'waveform', text: 'I, aVL, V5–V6: broad positive R, notched as activation sweeps the anterior then lateral walls; V1–V3: deep broad S/QS.' },
      { level: 'waveform', text: 'Repolarisation follows the abnormal activation sequence → ST–T opposite the QRS ("appropriate discordance").' },
      { level: 'clinical', text: 'Abnormal repolarisation makes ischaemia diagnosis difficult: concordant ST elevation, concordant STD in V1–V3, or excessively discordant STE (Smith-modified Sgarbossa: ST/S ratio ≤ −0.25) suggest acute coronary occlusion.' },
    ],
    differential: [{ dx: 'lvh', how: 'LVH with strain: QRS < 120 ms, septal q may persist.' }, { dx: 'vvi', how: 'RV pacing: pacing spike, similar morphology.' }, { dx: 'wpw', how: 'Short PR and delta wave.' }, { dx: 'ivcd', how: 'Nonspecific IVCD: QRS > 110 ms without typical LBBB/RBBB pattern.' }],
    acute: ['New LBBB is no longer automatically considered a STEMI equivalent; use clinical assessment and Sgarbossa/Smith-modified criteria.'],
    longTerm: ['Echocardiography for structural disease; CRT when LVEF ≤ 35% with LBBB QRS ≥ 150 ms and symptomatic HF on guideline-directed therapy (per HF/pacing guidelines).'],
    refs: ['ecgStd3', 'sgarbossa1996', 'smith2012', 'acs2025', 'pacing2023'],
  },
  {
    id: 'lafb',
    name: 'Left anterior fascicular block',
    aliases: ['LAFB', 'left anterior hemiblock', 'LAHB', 'left axis deviation'],
    category: 'ivcd',
    tier: 1,
    tags: ['lad', 'his-purkinje', 'block', 'narrow-qrs'],
    preset: 'lafb',
    definition: 'Frontal axis −45° to −90°, qR in aVL (R-peak time ≥ 45 ms), rS in II, III, aVF, QRS < 120 ms.',
    epidemiology: 'The most common fascicular block (the anterior fascicle is long, thin, single blood supply from LAD septal perforators).',
    mechanism: 'The anterior fascicle does not conduct, so the LV is activated first through the posterior fascicle (inferior/posterior wall) and then, late, the anterosuperior wall.',
    ecg: ['Left axis deviation −45° to −90°', 'qR in I and aVL; rS in II, III, aVF', 'Prolonged R-wave peak time in aVL (≥ 45 ms)', 'QRS normal or slightly prolonged (< 120 ms)', 'May reduce R-wave amplitude in inferior leads (pseudo-inferior MI) or increase aVL voltage (confounds LVH criteria)'],
    why: [
      { level: 'conduction', text: 'Blocked pathway: left anterior fascicle. Activation starts via the posterior fascicle.' },
      { level: 'vector', text: 'Initial forces point inferiorly/rightward (small r in II/III/aVF, small q in I/aVL).' },
      { level: 'conduction', text: 'The anterosuperior LV is then activated late through myocardium.' },
      { level: 'vector', text: 'Late, dominant forces point superiorly and leftward → the mean axis swings to −45° or beyond.' },
      { level: 'lead', text: 'aVL (−30°) and I face the late superior vector → tall R; II, III, aVF (inferior) see it going away → deep S.' },
      { level: 'waveform', text: 'Only a small part of the conduction system is bypassed → QRS barely widens.' },
    ],
    differential: [{ dx: 'oldInferior', how: 'Inferior MI gives Q waves (qR/QS) rather than an initial r in inferior leads.' }, { dx: 'lvh', how: 'LVH can shift axis leftward but rarely beyond −30°.' }, { dx: 'wpw', how: 'Posteroseptal pathways give negative inferior delta waves.' }],
    refs: ['ecgStd3'],
  },
  {
    id: 'lpfb',
    name: 'Left posterior fascicular block',
    aliases: ['LPFB', 'left posterior hemiblock', 'right axis deviation'],
    category: 'ivcd',
    tier: 2,
    tags: ['rad', 'his-purkinje', 'block', 'narrow-qrs'],
    preset: 'lpfb',
    definition: 'Frontal axis +90° to +180°, rS in I and aVL, qR in III and aVF, QRS < 120 ms — after excluding other causes of right axis deviation (RVH, lateral MI, vertical heart, PE, lead reversal).',
    mechanism: 'The broad, dual-supplied posterior fascicle rarely blocks alone. With it blocked, the LV is activated first via the anterior fascicle (superior) and then, late, the inferoposterior wall.',
    ecg: ['Right axis deviation (≥ +90°, typically ~ +120°)', 'rS in I, aVL; qR in II, III, aVF', 'QRS < 120 ms', 'A diagnosis of exclusion: first exclude other causes of right axis deviation (RVH, lateral MI, acute PE, a vertical heart in slim young adults)'],
    why: [
      { level: 'conduction', text: 'Blocked pathway: left posterior fascicle. Activation starts via the anterior fascicle.' },
      { level: 'vector', text: 'Initial forces superior-leftward (small r in I, q in III), then late dominant inferior-rightward forces.' },
      { level: 'lead', text: 'III and aVF face the late forces → tall R; I sees them going away → S.' },
      { level: 'diagnosis', text: 'Diagnosis of exclusion because RVH, PE, COPD and lateral MI produce the same axis shift.' },
    ],
    differential: [{ dx: 'rvh', how: 'Dominant R in V1, RA enlargement, RV strain.' }, { dx: 'pe', how: 'Acute context, tachycardia, RV strain.' }, { dx: 'copd', how: 'Low voltage, vertical heart.' }],
    refs: ['ecgStd3'],
  },
  {
    id: 'bifascicular',
    name: 'Bifascicular block (RBBB + LAFB / LPFB)',
    aliases: ['bifascicular', 'trifascicular block'],
    category: 'ivcd',
    tier: 2,
    tags: ['wide-qrs', 'his-purkinje', 'block', 'lad', 'rad', 'syncope'],
    preset: 'bifascicular',
    altPresets: ['rbbbLpfb'],
    definition: 'RBBB plus block of one left fascicle: RBBB + LAFB (common; left axis deviation) or RBBB + LPFB (rarer; right axis deviation). ESC definitions also count complete LBBB as bifascicular; the AHA/ACCF/HRS 2009 ECG statement discourages the terms "bifascicular" and "trifascicular". "Trifascicular block" is an imprecise term usually meaning bifascicular block + prolonged PR.',
    mechanism: 'Only one fascicle remains to carry every impulse; if it fails intermittently → Mobitz II/complete heart block.',
    ecg: ['RBBB morphology (rSR′ V1, wide S in I/V6), QRS ≥ 120 ms', 'Plus left axis −45° to −90° (with LAFB) or right axis (with LPFB)'],
    why: [
      { level: 'conduction', text: 'Right bundle and one left fascicle are blocked; the ventricles depend on the remaining fascicle.' },
      { level: 'vector', text: 'The initial/mid-QRS vector reflects the fascicular block (axis shift) and the terminal vector reflects RBBB (late rightward/anterior).' },
      { level: 'clinical', text: 'Syncope with bifascicular block raises concern for intermittent complete heart block — evaluation (monitoring, EP study) and pacing if infranodal block is shown.' },
    ],
    differential: [{ dx: 'rbbb', how: 'Normal axis.' }, { dx: 'lbbb', how: 'Different morphology in V1 (QS/rS).' }],
    longTerm: ['Asymptomatic bifascicular block: no pacing. Syncope: investigate; pacing if HV prolongation/infranodal block demonstrated. Alternating bundle-branch block: pacing (Class I).'],
    refs: ['brady2018', 'ecgStd3'],
  },
  {
    id: 'ivcd',
    name: 'Nonspecific intraventricular conduction delay',
    aliases: ['IVCD', 'NSIVCD', 'wide QRS'],
    category: 'ivcd',
    tier: 2,
    tags: ['wide-qrs', 'block'],
    preset: 'ivcd',
    definition: 'QRS > 110 ms in adults without criteria for RBBB or LBBB.',
    mechanism: 'Diffuse slowing of myocardial or distal Purkinje conduction (cardiomyopathy, infarction scar, hypertrophy) or systemic factors (hyperkalaemia, Na⁺-channel-blocking drugs, hypothermia).',
    ecg: ['QRS > 110 ms', 'Morphology not typical of RBBB/LBBB'],
    why: [
      { level: 'cell', text: 'Slower phase-0 upstroke (fewer available Na⁺ channels) or longer paths through diseased myocardium.' },
      { level: 'waveform', text: 'All components of the QRS are stretched in time rather than a single late component being added.' },
      { level: 'clinical', text: 'Always consider hyperkalaemia and sodium-channel-blocker toxicity when a QRS widens acutely.' },
    ],
    differential: [{ dx: 'hyperK', how: 'Peaked T, small P, rapid change.' }, { dx: 'tca', how: 'Terminal R in aVR, sinus tachycardia, anticholinergic toxidrome.' }],
    refs: ['ecgStd3'],
  },
  // ======================================================================= PACING
  {
    id: 'paced',
    name: 'Paced rhythms (atrial, ventricular, AV sequential)',
    aliases: ['pacemaker', 'paced rhythm', 'pacing spike', 'AAI', 'VVI', 'DDD', 'AV sequential pacing'],
    category: 'pacing',
    tier: 1,
    tags: ['pacing-spikes', 'wide-qrs', 'pacing', 'regular'],
    preset: 'vvi',
    altPresets: ['aai', 'dddTracking', 'dddSequential'],
    definition: 'Rhythms in which an implanted (or temporary) device stimulates the atrium and/or ventricle. Mode codes (NBG): 1st letter = chamber paced (O/A/V/D), 2nd = chamber sensed (O/A/V/D), 3rd = response to sensing (O = none, I = inhibit, T = trigger, D = both), 4th R = rate modulation (e.g. VVIR, DDDR).',
    mechanism: 'A brief stimulus depolarises tissue at the lead tip; activation then spreads from that point. Atrial pacing produces a P wave that conducts normally (narrow QRS if AV conduction is intact). Conventional RV apical/septal pacing activates the ventricles cell-to-cell from the right → wide QRS resembling LBBB (usually with a superior axis for apical pacing). Biventricular or conduction-system (His/left-bundle-area) pacing narrows the QRS.',
    ecg: ['Pacing spike (small with bipolar leads, large with unipolar)', 'Atrial pacing: spike → P wave → native PR → narrow QRS', 'Ventricular pacing: spike → wide QRS (LBBB-like), discordant ST–T', 'DDD: atrial sensing with ventricular pacing (P then V-spike after programmed AV delay) or AV-sequential spikes', 'Fusion/pseudofusion beats when intrinsic and paced activation coincide'],
    why: [
      { level: 'conduction', text: 'Atrial pacing starts atrial activation at the lead tip; everything downstream uses the native system.' },
      { level: 'conduction', text: 'RV pacing starts ventricular activation at the RV apex/septum and bypasses the His–Purkinje network.' },
      { level: 'vector', text: 'Activation proceeds from right to left and from apex to base → leftward, superior vector.' },
      { level: 'waveform', text: 'Wide QRS with LBBB-like morphology (negative V1, positive I/aVL), superior axis with apical pacing; repolarisation discordant (secondary).' },
      { level: 'clinical', text: 'Chronic high RV-pacing burden can cause dyssynchrony and pacing-induced cardiomyopathy — the rationale for physiological pacing strategies.' },
    ],
    differential: [{ dx: 'lbbb', how: 'No pacing spikes.' }, { dx: 'monoVT', how: 'Rapid paced rhythms (tracking atrial tachyarrhythmias, pacemaker-mediated tachycardia) have spikes before each QRS.' }],
    refs: ['brady2018', 'pacing2023'],
  },
  {
    id: 'pacerMalfunction',
    name: 'Pacemaker malfunction: failure to capture, sense or pace',
    aliases: ['failure to capture', 'undersensing', 'oversensing', 'failure to pace', 'loss of capture'],
    category: 'pacing',
    tier: 2,
    tags: ['pacing-spikes', 'pacing', 'bradycardia', 'syncope'],
    preset: 'failCapture',
    altPresets: ['failSense', 'oversense'],
    definition: 'FAILURE TO CAPTURE: spike without subsequent depolarisation. FAILURE TO SENSE (undersensing): device ignores intrinsic beats and paces inappropriately. FAILURE TO PACE (no output): pauses without spikes — most often OVERSENSING (device detects non-cardiac or inappropriate signals and withholds output); less often battery depletion, lead fracture or a loose lead–header connection.',
    mechanism: 'Capture requires the stimulus to exceed the myocardial threshold while tissue is excitable (threshold rises with lead dislodgement/fibrosis, hyperkalaemia, antiarrhythmics, ischaemia). Sensing requires an intracardiac signal above the programmed sensitivity (low-amplitude signals → undersensing; myopotentials, T waves, lead fracture noise, electromagnetic interference → oversensing).',
    ecg: ['Failure to capture: spike NOT followed by P or QRS (when tissue should be excitable)', 'Undersensing: spikes at inappropriate times — e.g. shortly after native QRS, sometimes falling on the T wave', 'Oversensing: pauses longer than the programmed lower-rate interval with no spike'],
    why: [
      { level: 'cell', text: 'Tissue fires only if the delivered current exceeds threshold and the cells are not refractory.' },
      { level: 'waveform', text: 'A spike falling inside the native refractory period (e.g. just after an intrinsic QRS) cannot capture — that is functional non-capture, a clue to undersensing, not a capture problem.' },
      { level: 'clinical', text: 'Pacemaker-dependent patients may develop profound bradycardia/asystole → transcutaneous pacing, device interrogation, magnet (asynchronous pacing) for oversensing.' },
    ],
    differential: [{ dx: 'paced', how: 'Normal function: every spike captures, spikes suppressed by intrinsic beats.' }],
    acute: ['Unstable: transcutaneous pacing / chronotropic support; urgent device interrogation.', 'Oversensing with pauses: a magnet over most pacemakers produces asynchronous pacing (device-specific).', 'Check K⁺, drugs, chest X-ray for lead position.'],
    refs: ['brady2018'],
  },
];
