import type { Dx } from './types';

// Cardiomyopathies, athlete's heart, occlusion-MI look-alikes, and recording pitfalls
// (heart position, cable reversal, artefact).

export const EXTRA_DX: Dx[] = [
  // ======================================================================= CARDIOMYOPATHY
  {
    id: 'hcm',
    name: 'Hypertrophic cardiomyopathy',
    aliases: ['HCM', 'HOCM', 'asymmetric septal hypertrophy', 'dagger Q waves'],
    category: 'cardiomyopathy',
    tier: 2,
    tags: ['high-voltage', 'q-waves', 't-inversion', 'syncope'],
    preset: 'hcm',
    definition: 'Genetic cardiomyopathy with unexplained LV hypertrophy (commonly asymmetric septal). Typical ECG: LVH voltage with repolarisation abnormality, deep narrow ("dagger") Q waves in the lateral and/or inferior leads, left atrial abnormality. Apical HCM gives giant negative T waves in the mid-lateral precordial leads.',
    epidemiology: 'One of the commonest inherited heart diseases and an important cause of sudden cardiac death in the young. A normal ECG is unusual in established HCM, so an abnormal ECG often prompts the echo that makes the diagnosis.',
    mechanism: 'Sarcomere gene variants → myocyte hypertrophy and disarray with fibrosis. The hypertrophied basal septum produces a much larger initial left→right (rightward, anterior) activation force; the thick LV adds leftward/posterior voltage and delays repolarisation.',
    ecg: ['Deep (often > 3 mm) but NARROW (< 40 ms) Q waves in I, aVL, V5–V6 and/or II, III, aVF', 'Tall R waves in V1–V2 (the same septal force seen from the front)', 'LVH voltage with ST depression / T inversion', 'Left atrial abnormality', 'Apical variant: giant negative T waves in V3–V6'],
    why: [
      { level: 'cell', text: 'Hypertrophied, disarrayed myocytes — especially in the basal septum.' },
      { level: 'conduction', text: 'Septal activation is normally the FIRST event of the QRS (left→right). A thick septum makes that first event big.' },
      { level: 'vector', text: 'The initial vector grows and points rightward, superiorly and anteriorly — away from the lateral and inferior walls.' },
      { level: 'lead', text: 'Leads facing the lateral/inferior walls see it moving away → deep Q waves; V1–V2 see it approaching → tall R.' },
      { level: 'waveform', text: 'The Q is NARROW because septal activation is still fast (normal conduction) — unlike infarct Q waves, which reflect a missing region and are broader.' },
      { level: 'clinical', text: 'Deep narrow Q waves + LVH in a young person (or athlete) → echocardiography/CMR.' },
    ],
    differential: [
      { dx: 'oldMI', how: 'Infarct Q waves are usually broader (UDMI: ≥ 30 ms in most leads, ≥ 20 ms in V2–V3), follow a coronary territory and come with regional wall-motion loss.' },
      { dx: 'lvh', how: 'Hypertensive/valvular LVH rarely produces deep septal Q waves.' },
      { dx: 'athlete', how: 'Athletes may have isolated voltage criteria but not pathological Q waves, ST depression or T inversion beyond the recognised normal variants (juvenile pattern, black-athlete repolarisation variant).' },
      { dx: 'wpw', how: 'Negative delta waves mimic Q waves; look for short PR and slurred upstroke.' },
    ],
    presentation: 'Often asymptomatic; exertional dyspnoea, chest pain, syncope (particularly exertional), palpitations; a systolic murmur that increases with Valsalva in obstructive HCM.',
    complications: ['Sudden cardiac death (VT/VF)', 'Atrial fibrillation (stroke risk)', 'Heart failure', 'LV outflow tract obstruction'],
    acute: ['Obstructive HCM with hypotension: avoid vasodilators and inotropes, give volume, use β-blockers/phenylephrine per specialist advice', 'AF: rhythm/rate control; anticoagulation is recommended in HCM with AF regardless of the CHA₂DS₂-VASc score (2024 AHA/ACC HCM guideline)'],
    longTerm: ['Sudden-death risk stratification and ICD when indicated', 'Symptomatic obstruction: β-blocker or non-dihydropyridine CCB, then cardiac myosin inhibitor, or septal reduction therapy in experienced centres', 'Genetic counselling and family screening (ECG + imaging)'],
    pearls: ['A young patient with "infarct" Q waves and huge voltages: think HCM.', 'The 12-lead ECG is part of the initial evaluation and of family screening in HCM.'],
    refs: ['hcm2024', 'ecgStd5'],
  },
  {
    id: 'arvc',
    name: 'Arrhythmogenic right ventricular cardiomyopathy',
    aliases: ['ARVC', 'ARVD', 'arrhythmogenic cardiomyopathy', 'epsilon wave', 'ACM'],
    category: 'cardiomyopathy',
    tier: 3,
    tags: ['t-inversion', 'wide-qrs', 'syncope', 'palpitations'],
    preset: 'arvc',
    altPresets: ['arvcVT'],
    definition: 'Inherited (usually desmosomal) cardiomyopathy with fibrofatty replacement of RV myocardium. ECG Task Force criteria include T-wave inversion in V1–V3 or beyond (age > 14, no complete RBBB), epsilon waves in V1–V3, prolonged terminal activation duration (≥ 55 ms), and VT/PVCs of LBBB morphology.',
    epidemiology: 'Presents typically in adolescence to middle age with palpitations, syncope or sudden death, often exercise-related. Endurance exercise accelerates the phenotype.',
    mechanism: 'Loss of desmosomal adhesion → myocyte death → fibrofatty replacement. Surviving myocardial strands conduct slowly and circuitously (late activation = epsilon wave, terminal delay) and form scar-related re-entrant circuits in the RV.',
    ecg: ['T-wave inversion V1–V3 (± V4–V6)', 'Epsilon wave: small low-amplitude deflection(s) after the QRS in V1–V3', 'Terminal activation duration ≥ 55 ms in V1–V3 (nadir of S to end of QRS)', 'PVCs / VT with LBBB morphology — superior axis (RV body/inferior wall) is a major criterion', 'Low voltage in advanced disease'],
    why: [
      { level: 'cell', text: 'Desmosome failure → myocyte detachment and death → fibro-fatty tissue.' },
      { level: 'conduction', text: 'Islands of surviving RV muscle are activated late, after the rest of the ventricles.' },
      { level: 'lead', text: 'Those late, tiny potentials arise just under V1–V3 → only the right precordial electrodes record them.' },
      { level: 'waveform', text: 'Epsilon waves and a prolonged terminal S upstroke in V1–V3; abnormal RV repolarisation inverts T in V1–V3.' },
      { level: 'conduction', text: 'Scar channels allow RV re-entry → VT that activates the RV first → LBBB-like morphology.' },
      { level: 'clinical', text: 'LBBB-morphology VT with right precordial TWI in a young person → CMR, Task Force criteria, family screening.' },
    ],
    differential: [
      { dx: 'rvotVT', how: 'Idiopathic RVOT VT: normal resting ECG (no TWI/epsilon), LBBB with INFERIOR axis, normal CMR.' },
      { dx: 'brugada', how: 'Coved STE in V1–V2 rather than epsilon/TWI; typically no structural disease.' },
      { dx: 'athlete', how: 'TWI V1–V4 can be normal in black athletes (preceded by J-point elevation and convex ST elevation) and V1–V3 in athletes < 16 y (juvenile pattern).' },
      { dx: 'pe', how: 'Acute RV strain: TWI V1–V4 with tachycardia and a clinical context.' },
    ],
    acute: ['VT: standard wide-complex tachycardia algorithm; synchronised cardioversion if unstable'],
    longTerm: ['ICD for secondary prevention or high-risk primary prevention', 'Restriction of competitive/high-intensity endurance exercise', 'β-blockers; antiarrhythmics or catheter ablation (often endo-epicardial) for recurrent VT', 'Genetic testing and cascade family screening'],
    refs: ['arvcTfc2010', 'acm2019', 'escVa2022'],
  },
  {
    id: 'athlete',
    name: "Athlete's heart (training-related ECG findings)",
    aliases: ['athlete ECG', 'athletic heart', 'Seattle criteria', 'international criteria', 'normal variant'],
    category: 'cardiomyopathy',
    tier: 2,
    tags: ['bradycardia', 'high-voltage', 'long-pr'],
    preset: 'athlete',
    definition: 'ECG changes that are normal physiological adaptations to regular intense training: sinus bradycardia/arrhythmia, first-degree AV block, Mobitz I, junctional or ectopic atrial rhythm, isolated QRS voltage criteria for LVH/RVH, incomplete RBBB, early repolarisation, the black-athlete repolarisation variant and the juvenile T-wave pattern (< 16 y).',
    epidemiology: 'Common in endurance and mixed-sport athletes. International recommendations separate NORMAL training-related findings from BORDERLINE findings (isolated ones need no work-up; two or more do) and ABNORMAL findings that always need evaluation.',
    mechanism: 'High resting vagal tone slows the sinus node and the AV node; training enlarges the chambers (more voltage, mild RV conduction delay); the early-repolarisation pattern reflects a prominent epicardial Ito current.',
    ecg: ['Sinus bradycardia (≥ 30/min) and sinus arrhythmia', 'First-degree AV block (PR < 400 ms), Mobitz I', 'Isolated LVH/RVH voltage criteria', 'Incomplete RBBB', 'Early repolarisation (J-point elevation, ST elevation)'],
    why: [
      { level: 'cell', text: 'Acetylcholine (vagal tone) opens IK,ACh and reduces If in sinus-node cells → slower phase 4.' },
      { level: 'conduction', text: 'The same vagal tone slows AV-nodal conduction → long PR, occasionally Wenckebach at rest or during sleep; exercise abolishes it.' },
      { level: 'vector', text: 'Larger chambers generate bigger vectors → higher voltages without pathological Q waves or ST depression.' },
      { level: 'clinical', text: 'Findings that are NOT training-related (T inversion beyond the allowed variants, ST depression, pathological Q, LBBB, QRS ≥ 140 ms, epsilon wave, pre-excitation, long QT, Brugada type 1, Mobitz II/complete block, profound bradycardia < 30/min) need evaluation for HCM, ARVC, channelopathies or conduction disease.' },
    ],
    differential: [
      { dx: 'hcm', how: 'Pathological Q waves, lateral T inversion or ST depression are NOT training-related.' },
      { dx: 'arvc', how: 'TWI beyond V1 (beyond V3 in athletes < 16 y; beyond V4 in the black-athlete variant with preceding J-point/convex ST elevation) or epsilon waves need work-up.' },
      { dx: 'mobitz2', how: 'Mobitz II or complete block is never a normal athletic adaptation.' },
      { dx: 'lqts', how: 'QTc ≥ 470 ms (men) / ≥ 480 ms (women) is abnormal in athletes.' },
    ],
    pearls: ['Exercise normalises vagally mediated first-degree block, Wenckebach and junctional rhythm — a useful bedside test of mechanism.'],
    refs: ['athlete2017'],
  },
  {
    id: 'takotsubo',
    name: 'Takotsubo syndrome',
    aliases: ['stress cardiomyopathy', 'broken heart syndrome', 'apical ballooning', 'TTS'],
    category: 'cardiomyopathy',
    tier: 3,
    tags: ['st-elevation', 't-inversion', 'long-qt', 'chest-pain'],
    preset: 'takotsubo',
    definition: 'Acute, usually reversible LV dysfunction (typically apical/mid-ventricular ballooning) often triggered by emotional or physical stress, predominantly in post-menopausal women. ECG: ST elevation in the acute phase, then deep, widespread T inversion with QT prolongation over days.',
    epidemiology: 'A few per cent of patients presenting with suspected ACS; about 90% are women (mostly post-menopausal). Complications include cardiogenic shock, LV outflow tract obstruction, arrhythmias and torsades during the long-QT phase.',
    mechanism: 'Catecholamine surge → myocardial stunning (microvascular dysfunction, direct catecholamine toxicity) in a distribution that crosses coronary territories. Stunned apical myocardium repolarises late and abnormally.',
    ecg: ['Acute: ST elevation (often precordial, may extend beyond a single coronary territory); reciprocal ST depression is less common than in anterior STEMI', 'Days 1–3: deep, symmetric, widespread T inversion (I, aVL, II, V2–V6) with upright T in aVR', 'Marked QT prolongation', 'Transient Q waves / low voltage possible'],
    why: [
      { level: 'cell', text: 'Catecholamine excess → stunned (not dead) myocytes, most at the apex.' },
      { level: 'vector', text: 'Delayed apical repolarisation turns the T vector away from the apex.' },
      { level: 'lead', text: 'Leads facing the apex/anterior wall (and inferior leads) record deep negative T; aVR, looking from the opposite side, records an upright T.' },
      { level: 'waveform', text: 'Repolarisation is prolonged → long QT, which carries torsades risk.' },
      { level: 'clinical', text: 'The ECG cannot distinguish Takotsubo from anterior ACS — coronary angiography (and ventriculography/imaging) is required.' },
    ],
    differential: [
      { dx: 'stemi', how: 'Anterior STEMI more often shows reciprocal inferior STD and a single-territory pattern; angiography decides.' },
      { dx: 'wellens', how: 'Wellens T inversion is concentrated in V2–V3 after resolved pain, with a critical LAD lesion.' },
      { dx: 'myocarditis', how: 'Viral prodrome, troponin; CMR shows oedema/late enhancement.' },
      { dx: 'lqts', how: 'Congenital: long QT without acute wall-motion abnormality.' },
    ],
    acute: ['Manage as ACS until coronary anatomy is known', 'Monitor for arrhythmia; avoid QT-prolonging drugs and correct K⁺/Mg²⁺ during the long-QT phase', 'LV outflow obstruction: avoid inotropes and vasodilators'],
    refs: ['takotsubo2018', 'acs2025'],
  },
  // ======================================================================= ISCHAEMIA (additional)
  {
    id: 'deWinter',
    name: 'de Winter pattern',
    aliases: ['de Winter T waves', 'STEMI equivalent', 'occlusion MI without ST elevation'],
    category: 'ischemia',
    tier: 2,
    tags: ['st-depression', 'chest-pain', 'peaked-t'],
    preset: 'deWinter',
    definition: 'Acute proximal LAD occlusion presenting with 1–3 mm UPSLOPING ST depression at the J point in V1–V6 that continues into tall, positive, symmetric T waves, usually with 1–2 mm ST elevation in aVR — instead of precordial ST elevation.',
    epidemiology: 'Described in about 2% of anterior MIs in the original series (de Winter et al., NEJM 2008).',
    mechanism: 'Occlusion of the proximal LAD without the typical transmural ST vector (proposed explanations include anatomical variants of the Purkinje fibres and absent activation of sarcolemmal KATP channels). The hyperacute T waves reflect the ischaemic anterior wall; the J-point depression reflects a subendocardial-predominant injury vector.',
    ecg: ['Upsloping J-point depression 1–3 mm in V1–V6', 'Tall, broad, symmetric (hyperacute) T waves in the precordial leads', 'Slight ST elevation (1–2 mm) in aVR', 'QRS usually normal or slightly widened'],
    why: [
      { level: 'cell', text: 'Acute anterior ischaemia → abnormal repolarisation of the anterior wall (tall hyperacute T).' },
      { level: 'vector', text: 'Instead of pointing toward the anterior epicardium, the early ST vector points slightly away from it (toward the cavity).' },
      { level: 'lead', text: 'Precordial leads: J point depressed; aVR (looking into the cavity): small ST elevation.' },
      { level: 'waveform', text: 'The depressed ST slopes up into a giant T wave — the pattern persists until reperfusion.' },
      { level: 'clinical', text: 'Recognised as a pattern of acute LAD occlusion: discuss immediately for emergent angiography/reperfusion rather than waiting for ST elevation.' },
    ],
    differential: [
      { dx: 'hyperK', how: 'Peaked T waves are narrow-based with a normal or short QT, no J-point depression, and diffuse (not precordial-only).' },
      { dx: 'nste', how: 'NSTE-ACS ST depression is usually horizontal/downsloping with flat or inverted T waves.' },
      { dx: 'earlyRepol', how: 'J-point ELEVATION with concave STE, not depression.' },
      { dx: 'stemi', how: 'Hyperacute T waves may precede classic STE; serial ECGs every few minutes help.' },
    ],
    refs: ['dewinter2008', 'acs2025'],
  },
  {
    id: 'lvAneurysm',
    name: 'Left ventricular aneurysm (persistent ST elevation)',
    aliases: ['LV aneurysm morphology', 'persistent STE after MI', 'ventricular aneurysm'],
    category: 'ischemia',
    tier: 3,
    tags: ['st-elevation', 'q-waves'],
    preset: 'lvAneurysm',
    definition: 'ST elevation that persists weeks after a (usually anterior) transmural MI, together with Q/QS waves, over a dyskinetic segment of scar.',
    mechanism: 'Thin dyskinetic scar with a border zone of abnormal myocardium creates a persistent injury-like current (and possibly mechanical stretch effects) directed toward the aneurysm; scar removes depolarising forces (QS waves).',
    ecg: ['QS or deep Q waves in the infarct territory (e.g. V1–V4)', 'Persistent, often concave or straight ST elevation', 'Relatively small T waves compared with the QRS (unlike the large T of acute STEMI)', 'No evolution over serial ECGs'],
    why: [
      { level: 'cell', text: 'Necrotic myocardium replaced by thin fibrous scar that bulges outward in systole.' },
      { level: 'vector', text: 'No depolarising forces from the scar → initial vector points away → QS waves; a persistent ST vector points toward the aneurysm.' },
      { level: 'waveform', text: 'ST elevation without the evolving T-wave changes of acute injury; the ECG looks the same day after day.' },
      { level: 'clinical', text: 'Compare with an old ECG: identical STE argues against new occlusion. LV thrombus, heart failure and VT are complications.' },
    ],
    differential: [
      { dx: 'stemi', how: 'Acute STEMI: large T waves relative to QRS, dynamic changes, symptoms and rising troponin.' },
      { dx: 'oldMI', how: 'Old MI usually has Q waves with an isoelectric ST segment.' },
      { dx: 'pericarditis', how: 'Diffuse STE with PR depression and no Q waves.' },
    ],
    pearls: ['A lower T-wave amplitude relative to the QRS favours aneurysm over acute anterior STEMI — a heuristic, not a guideline criterion; old ECGs and clinical context decide.'],
    refs: ['udmi2018', 'ecgStd6'],
  },
  // ======================================================================= INHERITED (additional)
  {
    id: 'cpvt',
    name: 'Catecholaminergic polymorphic VT (CPVT)',
    aliases: ['CPVT', 'RyR2', 'exercise-induced bidirectional VT'],
    category: 'inherited',
    tier: 3,
    tags: ['wide-qrs', 'tachycardia', 'syncope', 'triggered'],
    preset: 'cpvt',
    definition: 'Inherited calcium-handling disorder (most often RYR2, also CASQ2) with a normal resting ECG and adrenergically triggered ventricular arrhythmias: PVCs, bidirectional VT and polymorphic VT during exercise or emotion.',
    epidemiology: 'Presents in childhood/adolescence with exertional or emotional syncope or cardiac arrest; the exercise test is the key diagnostic test because the resting ECG is normal.',
    mechanism: 'Leaky ryanodine receptors (or abnormal calsequestrin) release Ca²⁺ from the sarcoplasmic reticulum during diastole when β-adrenergic stimulation loads the cell with Ca²⁺. The Na⁺/Ca²⁺ exchanger extrudes it and generates an inward current → delayed afterdepolarisations → triggered beats, typically from alternating Purkinje sites (bidirectional VT).',
    ecg: ['Normal resting ECG (sinus bradycardia possible)', 'With exercise: PVCs increasing with heart rate → couplets → bidirectional VT (beat-to-beat alternating axis) → polymorphic VT/VF'],
    why: [
      { level: 'cell', text: 'Adrenergic stimulation → Ca²⁺ overload of the sarcoplasmic reticulum → spontaneous diastolic Ca²⁺ release through leaky RyR2.' },
      { level: 'cell', text: 'Na⁺/Ca²⁺ exchange (3 Na⁺ in per Ca²⁺ out) creates an inward current → delayed afterdepolarisation → triggered action potential.' },
      { level: 'conduction', text: 'Triggered beats arise alternately from two His–Purkinje sites (e.g. right- and left-ventricular Purkinje networks).' },
      { level: 'waveform', text: 'Alternating origin → alternating frontal axis beat to beat: bidirectional VT.' },
      { level: 'treatment', text: 'β-blockade removes the trigger; flecainide additionally blocks RyR2 release/Na⁺ current; left cardiac sympathetic denervation removes sympathetic input.' },
    ],
    differential: [
      { dx: 'bidirectionalVT', how: 'Digoxin toxicity causes the same DAD mechanism — check drug history/levels.' },
      { dx: 'lqts', how: 'LQT1 also causes exercise-triggered events, but the QT is long and the arrhythmia is torsades.' },
      { dx: 'polyVT', how: 'Ischaemic polymorphic VT in older patients with coronary disease.' },
    ],
    longTerm: ['β-blocker (non-selective, e.g. nadolol, commonly preferred) for all affected patients', 'Add flecainide if arrhythmias persist on β-blockade', 'Left cardiac sympathetic denervation in selected patients; ICD for survivors of arrest or breakthrough events (programmed to avoid shock storms)', 'Avoid strenuous exercise/competitive sport per specialist advice; family screening'],
    refs: ['escVa2022', 'va2017'],
  },
  // ======================================================================= TECHNICAL
  {
    id: 'dextrocardia',
    name: 'Dextrocardia',
    aliases: ['mirror-image dextrocardia', 'situs inversus', 'right-sided heart'],
    category: 'technical',
    tier: 3,
    tags: ['rad'],
    preset: 'dextrocardia',
    definition: 'The heart lies in the right hemithorax with its apex pointing right (mirror-image dextrocardia, usually with situs inversus). ECG: inverted P, QRS and T in lead I; aVR and aVL swapped; reversed R-wave progression (R waves shrink from V1 to V6).',
    mechanism: 'Every activation and repolarisation vector is reflected across the midline (x → −x). Limb leads that look leftward now look at the back of the vectors; the left-sided chest electrodes are placed ever farther from the heart.',
    ecg: ['Negative P, QRS and T in lead I (a "globally negative" lead I)', 'aVR positive, aVL looks like a normal aVR', 'Right axis deviation', 'Dominant QRS in V1–V2 with progressively DECREASING R amplitude to V6', 'Right-sided chest leads (V1R–V6R) restore normal-looking progression'],
    why: [
      { level: 'vector', text: 'The heart vector is mirrored: its leftward component becomes rightward.' },
      { level: 'lead', text: 'Lead I (left arm +) sees all waves moving away → everything inverted; II and III swap roles.' },
      { level: 'lead', text: 'Chest leads V3–V6 now lie over the empty left chest → low voltage, "reverse" progression.' },
      { level: 'diagnosis', text: 'Distinguish from right/left arm cable reversal: reversal leaves the CHEST leads normal.' },
    ],
    differential: [
      { dx: 'leadReversal', how: 'RA/LA reversal also inverts lead I, but chest-lead R progression is normal.' },
      { dx: 'rvh', how: 'Right axis with tall R in V1, but the P wave in lead I is upright (the atria are not mirrored).' },
      { dx: 'lpfb', how: 'Right axis without P-wave inversion in I.' },
    ],
    refs: ['leadReversal2007', 'ecgStd1'],
  },
  {
    id: 'leadReversal',
    name: 'Limb-lead (cable) reversal',
    aliases: ['lead reversal', 'arm lead reversal', 'misplaced electrodes', 'RA/LA reversal', 'limb lead swap'],
    category: 'technical',
    tier: 2,
    tags: ['rad'],
    preset: 'raLaReversal',
    altPresets: ['laLlReversal', 'raLlReversal'],
    definition: 'Interchange of limb-electrode cables. RA/LA reversal: inverted P-QRS-T in lead I, II ↔ III and aVR ↔ aVL swapped, aVF and chest leads unchanged. LA/LL reversal: I ↔ II, aVL ↔ aVF swapped, III inverted — often subtle. Reversal involving the right-leg (neutral) cable produces a near-flat lead.',
    epidemiology: 'A common and important recording error: it can simulate ectopic atrial rhythm, dextrocardia, axis deviation, or infarction.',
    mechanism: 'Limb leads are fixed combinations of three electrode potentials. Swapping two cables simply relabels those potentials, so every limb lead becomes another lead, or its inverse. Wilson’s central terminal is the average of all three, so the chest leads are unchanged.',
    ecg: ['RA/LA: P, QRS, T all negative in I; positive P in aVR; normal chest leads', 'LA/LL: P wave in I larger than in II, negative P in III (may be the only clue)', 'RA/LL: II inverted; I and III become inverted copies of III and I', 'Neutral (RL) cable involved: almost flat line in I, II or III'],
    why: [
      { level: 'lead', text: 'Lead I = LA − RA. Swap RA and LA and lead I = RA − LA = −(true lead I): every wave in I flips.' },
      { level: 'lead', text: 'II = LL − RA becomes LL − LA = true III (and vice versa); aVR and aVL exchange their electrodes.' },
      { level: 'vector', text: 'Nothing about the heart changed; only the labels. The chest leads, referenced to the unchanged central terminal, look normal.' },
      { level: 'diagnosis', text: 'Globally negative lead I + normal R-wave progression = RA/LA reversal until proven otherwise; repeat the ECG.' },
    ],
    differential: [
      { dx: 'dextrocardia', how: 'Lead I inverted too, but chest R waves DECREASE from V1 to V6.' },
      { dx: 'focalAT', how: 'Low atrial rhythm gives negative P in II/III/aVF, not a negative P in I with a positive P in aVR.' },
      { dx: 'oldMI', how: 'Q waves that appear only after cable swap disappear on a correctly recorded ECG.' },
    ],
    pearls: ['Try it: open the preset in the simulator and compare lead I, aVR and V1–V6 with the true ECG (set lead reversal to "none").'],
    refs: ['leadReversal2007', 'ecgStd1'],
  },
  {
    id: 'artifact',
    name: 'Artefact mimicking arrhythmia',
    aliases: ['pseudo-VT', 'motion artifact', 'tremor artifact', 'artifact', 'pseudotachycardia'],
    category: 'technical',
    tier: 2,
    tags: ['wide-qrs', 'tachycardia'],
    preset: 'artifactMotion',
    altPresets: ['artifactTremor'],
    definition: 'Non-cardiac electrical signals (limb movement, tremor, shivering, loose electrodes) that simulate VT, VF, flutter or AF on monitors and ECGs.',
    epidemiology: 'Misinterpreted artefact has led to unnecessary drugs, device implantation and invasive procedures (Knight et al., NEJM 1999).',
    mechanism: 'Movement or muscle activity changes the potential at ONE electrode (or its skin contact). That potential enters every lead that uses that electrode, in proportion to its weight — and is absent from the lead that does not.',
    ecg: ['Native QRS complexes (often visible as sharp "notches") continue at the underlying rate through the "tachycardia"', 'A lead that does not use the moving electrode is clean (RA artefact spares lead III; LA spares II; LL spares I)', 'No haemodynamic change during the "arrhythmia"', 'Abrupt onset/offset tied to movement; baseline wander'],
    why: [
      { level: 'lead', text: 'I = LA − RA, II = LL − RA, III = LL − LA. A signal on RA appears in I and II (and aVR, aVL, aVF, and at one-third size in V1–V6) but cancels out of III.' },
      { level: 'waveform', text: 'The heart is still in sinus rhythm: sharp QRS complexes march through at the sinus interval.' },
      { level: 'diagnosis', text: 'Look for the clean lead and for the marching native QRS before calling VT.' },
      { level: 'clinical', text: 'Assess the patient: a conscious, well-perfused patient during "VT/VF" suggests artefact — but never delay treatment of a pulseless patient.' },
    ],
    differential: [
      { dx: 'monoVT', how: 'Real VT: no native sinus QRS marching through, often AV dissociation, a pulse (or pulse-oximeter) rate that matches the tachycardia, present in all leads.' },
      { dx: 'vf', how: 'Real VF: the patient is pulseless and unresponsive.' },
      { dx: 'af', how: 'Tremor mimics f waves, but RR intervals remain regular in sinus rhythm.' },
      { dx: 'flutter', how: 'Tremor at ~300/min can mimic flutter; flutter waves appear in all the inferior leads (II, III, aVF) rather than being absent from one.' },
    ],
    refs: ['artifact1999', 'leadReversal2007'],
  },
];
