import type { Dx } from './types';

// Hypertrophy/enlargement, ischaemia/infarction, pericardial disease, pulmonary/right heart.

export const MORPH_DX: Dx[] = [
  // ======================================================================= STRUCTURAL
  {
    id: 'lvh',
    name: 'Left ventricular hypertrophy',
    aliases: ['LVH', 'Sokolow-Lyon', 'Cornell', 'strain pattern', 'high voltage'],
    category: 'structural',
    tier: 1,
    tags: ['high-voltage', 'st-depression', 't-inversion', 'lad'],
    preset: 'lvh',
    altPresets: ['lvhVoltage'],
    definition: 'ECG evidence of increased LV mass: increased QRS voltage (e.g. Sokolow–Lyon SV1 + RV5/V6 > 3.5 mV; Cornell RaVL + SV3 > 2.8 mV men / > 2.0 mV women) often with left atrial abnormality, slight QRS widening, left axis shift and secondary ST–T ("strain") changes.',
    epidemiology: 'Hypertension, aortic stenosis, hypertrophic cardiomyopathy, athletes (physiological). ECG criteria are specific but insensitive (Sokolow–Lyon sensitivity ~22% vs autopsy in Casale et al.).',
    mechanism: 'More myocardium depolarising in the LV free wall generates a larger leftward/posterior dipole; the thicker wall takes longer to activate (QRS slightly longer, delayed intrinsicoid deflection) and repolarisation becomes abnormal (subendocardial supply–demand mismatch, altered transmural gradients).',
    ecg: ['Tall R in V5–V6/I/aVL and deep S in V1–V3', 'QRS modestly prolonged; delayed R-peak time in V5–V6', 'Left axis shift (usually not beyond −30° unless LAFB)', 'Strain: downsloping ST depression with asymmetric T inversion in I, aVL, V5–V6 (discordant to the tall R)', 'Left atrial enlargement often coexists'],
    why: [
      { level: 'cell', text: 'Each myocyte is larger; there is more tissue depolarising simultaneously in the LV free wall.' },
      { level: 'vector', text: 'The main (LV free-wall) vector grows in magnitude and points leftward and posterior.' },
      { level: 'lead', text: 'Left-sided leads (I, aVL, V5–V6) lie along it → taller R. Right precordial leads (V1–V2) lie opposite → deeper S.' },
      { level: 'waveform', text: 'Voltage criteria are sums of these projections — they depend on distance to the chest wall too, which is why obesity, emphysema and effusion hide LVH and thin young people "have" it.' },
      { level: 'cell', text: 'Thick walls repolarise abnormally (prolonged subendocardial activation, relative subendocardial ischaemia).' },
      { level: 'waveform', text: 'The repolarisation vector swings away from the LV → ST depression/T inversion in the leads with the tallest R (strain).' },
      { level: 'clinical', text: 'LVH with strain is associated with higher cardiovascular risk; echo/MRI measure mass directly.' },
    ],
    differential: [{ dx: 'lbbb', how: 'QRS ≥ 120 ms, absent septal q.' }, { dx: 'subendo', how: 'Ischaemic STD is often horizontal and dynamic with symptoms.' }, { dx: 'digoxinEffect', how: 'Scooped ST in many leads, short QT.' }, { dx: 'wpw', how: 'Pre-excitation spuriously increases voltage.' }],
    refs: ['ecgStd5', 'sokolow1949', 'casale1987'],
  },
  {
    id: 'rvh',
    name: 'Right ventricular hypertrophy',
    aliases: ['RVH', 'dominant R V1', 'right ventricular strain'],
    category: 'structural',
    tier: 2,
    tags: ['rad', 'dominant-r-v1', 't-inversion'],
    preset: 'rvh',
    altPresets: ['pulmHtn'],
    definition: 'ECG evidence of increased RV mass: right axis deviation, dominant R in V1 (R/S > 1), deep S in V5–V6, RA enlargement, RV strain (ST–T changes V1–V3).',
    epidemiology: 'Pulmonary hypertension (all causes), pulmonary stenosis, congenital heart disease, mitral stenosis, chronic lung disease.',
    mechanism: 'Normally the LV outweighs the RV and RV forces are cancelled. When the RV thickens enough to rival the LV, the net forces swing rightward and anteriorly.',
    ecg: ['Right axis deviation (> +90°)', 'R ≥ S in V1 (qR or tall R), deep S in V5–V6', 'P pulmonale (RA enlargement)', 'ST depression/T inversion V1–V3 (RV strain)', 'Clockwise rotation may coexist'],
    why: [
      { level: 'vector', text: 'Extra RV mass adds a large rightward/anterior force that now dominates the LV force.' },
      { level: 'lead', text: 'V1 (anterior-right) sees the dominant force coming toward it → tall R; I and V6 see it moving away → S waves.' },
      { level: 'waveform', text: 'Right axis deviation and dominant R in V1.' },
      { level: 'clinical', text: 'The ECG is insensitive for mild RVH (the LV still dominates) — echo is the test.' },
    ],
    differential: [{ dx: 'stemiPosterior', how: 'Tall R V1 with horizontal STD V1–V3, normal axis.' }, { dx: 'rbbb', how: 'QRS ≥ 120 ms with rSR′.' }, { dx: 'wpw', how: 'Left-sided pathway: short PR, delta wave.' }, { dx: 'lpfb', how: 'Right axis without dominant R in V1.' }],
    refs: ['ecgStd5'],
  },
  {
    id: 'atrialEnlargement',
    name: 'Atrial enlargement / abnormality (P pulmonale, P mitrale)',
    aliases: ['RAE', 'LAE', 'P pulmonale', 'P mitrale', 'left atrial abnormality', 'right atrial abnormality', 'Morris index', 'P terminal force'],
    category: 'structural',
    tier: 2,
    tags: ['p-wave'],
    preset: 'lae',
    altPresets: ['rae'],
    definition: 'RIGHT atrial abnormality: tall peaked P ≥ 2.5 mm in II, III, aVF (or > 1.5 mm initial P in V1). LEFT atrial abnormality: P duration ≥ 120 ms, notched P in II (> 40 ms between peaks), and/or deep, broad terminal negative P in V1 (≥ 1 mm × 40 ms).',
    mechanism: 'The P wave is the sum of RA activation (early, anterior-inferior) and LA activation (later, leftward-posterior). Enlarging one chamber increases its contribution; delayed interatrial (Bachmann bundle) conduction separates them further.',
    ecg: ['RAE: taller early component → peaked P in inferior leads, prominent initial positive P in V1', 'LAE: prolonged, notched ("M") P in II; large terminal negative deflection in V1'],
    why: [
      { level: 'conduction', text: 'Sinus impulse → RA first (anterior/inferior vector) → LA later via Bachmann bundle (leftward/posterior vector).' },
      { level: 'vector', text: 'RA enlargement increases the early vector → taller P in II/aVF (pointing inferiorly) and a bigger initial positive P in V1 (anterior).' },
      { level: 'vector', text: 'LA enlargement increases and delays the late posterior vector → V1 (anterior) sees a deep late negative wave; II shows two humps (RA then LA).' },
      { level: 'clinical', text: 'LA abnormality reflects raised LA pressure/volume (mitral disease, LVH, diastolic dysfunction) and predicts AF; P pulmonale suggests pulmonary hypertension/lung disease.' },
    ],
    differential: [{ dx: 'nsr', how: 'Normal P ≤ 120 ms, ≤ 2.5 mm.' }, { dx: 'Intra-atrial block', how: 'Interatrial conduction delay (Bayés syndrome) prolongs P without enlargement.' }],
    refs: ['ecgStd5'],
  },
  {
    id: 'poorR',
    name: 'Poor R-wave progression',
    aliases: ['PRWP', 'delayed transition', 'clockwise rotation'],
    category: 'structural',
    tier: 2,
    tags: ['q-waves'],
    preset: 'poorR',
    definition: 'Failure of the R wave to grow normally across V1–V4 (e.g. R ≤ 3 mm in V3), with the transition zone shifted to V5–V6.',
    mechanism: 'Loss or reduction of anterior forces: prior anterior MI, LVH or LBBB, clockwise rotation (e.g. COPD), lead misplacement (electrodes too high), dextrocardia, cardiomyopathy.',
    ecg: ['Small r in V1–V4, transition at V5 or later'],
    why: [
      { level: 'vector', text: 'The anterior component of ventricular activation (toward V2–V4) is smaller or rotated away.' },
      { level: 'lead', text: 'Anterior leads therefore record small R and relatively deep S until far lateral.' },
      { level: 'diagnosis', text: 'Nonspecific: always check lead placement and look for Q waves, LVH, LBBB before calling an old anterior MI.' },
    ],
    differential: [{ dx: 'evolvingMI', how: 'Q waves/QS in V1–V3 with T inversion.' }, { dx: 'lbbb', how: 'QRS ≥ 120.' }, { dx: 'copd', how: 'Low voltage, right axis.' }],
    refs: ['ecgStd6'],
  },
  {
    id: 'lowVoltage',
    name: 'Low QRS voltage & electrical alternans',
    aliases: ['low voltage', 'pericardial effusion', 'tamponade', 'electrical alternans', 'amyloid'],
    category: 'pericardial',
    tier: 2,
    tags: ['low-voltage', 'tachycardia'],
    preset: 'lowVolt',
    definition: 'Low voltage: QRS amplitude < 5 mm in all limb leads (± < 10 mm in all precordial leads). Electrical alternans: beat-to-beat alternation of QRS amplitude/axis.',
    mechanism: 'Voltage recorded at the skin falls when tissue between heart and electrodes attenuates the signal (effusion, obesity, emphysema, anasarca) or when fewer viable myocytes generate current (infiltration such as amyloidosis, extensive infarction, myxoedema). In large effusions the heart swings to and fro within the pericardial sac → its distance/orientation to the electrodes alternates → alternans.',
    ecg: ['Small QRS complexes in all leads', 'Sinus tachycardia and alternans suggest tamponade'],
    why: [
      { level: 'lead', text: 'Surface voltage ∝ source strength and inversely to distance/insulation: fluid or air "short-circuits" or insulates the signal.' },
      { level: 'vector', text: 'Swinging heart → alternating vector projection each beat → alternating QRS size.' },
      { level: 'clinical', text: 'Low voltage + tachycardia + alternans + hypotension → consider tamponade (a clinical/echo diagnosis).' },
    ],
    differential: [{ dx: 'copd', how: 'Hyperinflation: low voltage with right axis, P pulmonale.' }, { dx: 'lvh', how: 'Infiltrative "hypertrophy" (amyloid) paradoxically shows LOW voltage with thick walls on echo.' }],
    refs: ['escPeri2015', 'escMyoPeri2025'],
  },
  // ======================================================================= ISCHAEMIA
  {
    id: 'stemi',
    name: 'ST-elevation myocardial infarction (STEMI) / acute coronary occlusion',
    aliases: ['STEMI', 'acute MI', 'anterior MI', 'inferior MI', 'lateral MI', 'reciprocal changes', 'injury current', 'OMI'],
    category: 'ischemia',
    tier: 1,
    tags: ['st-elevation', 'st-depression', 'chest-pain', 'q-waves', 'ischemia', 'lad', 'rca', 'lcx', 'reperfusion'],
    preset: 'stemiAnterior',
    altPresets: ['stemiInferior', 'stemiLateral', 'hyperacute', 'evolvingMI'],
    definition: 'Acute myocardial infarction with new ST elevation at the J point in ≥ 2 contiguous leads: ≥ 1 mm in all leads other than V2–V3; in V2–V3 ≥ 2 mm in men ≥ 40 y, ≥ 2.5 mm in men < 40 y, ≥ 1.5 mm in women (Fourth Universal Definition of MI), in the absence of LVH or LBBB.',
    epidemiology: 'Usually thrombotic occlusion of an epicardial coronary artery. Some occlusions do not meet STE criteria (posterior MI, some LCx occlusions, de Winter pattern, hyperacute T waves) — "STEMI equivalents".',
    mechanism: 'Transmural ischaemia depolarises the resting membrane and shortens/depresses the action potential plateau of injured cells. The voltage difference between injured and healthy myocardium creates an "injury current". With transmural injury the net ST vector points TOWARD the injured epicardial surface.',
    ecg: ['Hyperacute T waves (broad, tall, symmetric) — earliest', 'ST elevation in leads facing the injured territory (convex/straight)', 'Reciprocal ST depression in leads facing the opposite wall (supports true STEMI)', 'Later: Q waves, T inversion; persistent STE weeks later suggests aneurysm', 'Territories: V1–V4 anterior (LAD); I, aVL, V5–V6 lateral (LCx/diagonal); II, III, aVF inferior (RCA or LCx); V1, V4R right ventricle (proximal RCA); V1–V3 ST depression with tall R = posterior (confirm with V7–V9)'],
    normal: 'In healthy myocardium all cells sit at the same plateau voltage during the ST segment → no current flows → isoelectric ST.',
    why: [
      { level: 'cell', text: 'Ischaemic cells lose ATP → K⁺ leaks out (IK,ATP opens) → less negative resting potential, shorter and lower plateau.' },
      { level: 'vector', text: 'During the ST segment healthy cells are at plateau while injured cells are at a lower potential → a systolic injury current; with transmural injury the ST vector points toward the injured epicardium.' },
      { level: 'lead', text: 'Leads whose positive pole faces the injured wall record ST elevation; leads on the opposite side record the same vector as ST depression (reciprocal).' },
      { level: 'waveform', text: 'E.g. LAD occlusion → ST vector anterior → STE V1–V4; RCA occlusion → inferior (and rightward) ST vector → STE II/III/aVF with III > II and reciprocal STD in aVL.' },
      { level: 'cell', text: 'Necrotic myocardium no longer depolarises → the initial QRS vector points away from it → Q waves.' },
      { level: 'clinical', text: 'Time is myocardium: the ECG’s job is to identify occlusion needing emergency reperfusion.' },
      { level: 'treatment', text: 'Reperfusion (primary PCI or fibrinolysis) restores oxygen → injury current resolves (rapid STE resolution is a marker of reperfusion).' },
    ],
    differential: [{ dx: 'pericarditis', how: 'Diffuse STE, PR depression, no reciprocal STD except aVR/V1, no Q waves.' }, { dx: 'earlyRepol', how: 'J notch/slur, concave STE, stable over time, young patient.' }, { dx: 'lbbb', how: 'Discordant STE is expected — use Sgarbossa/Smith criteria.' }, { dx: 'lvh', how: 'Discordant STE in V1–V3 with deep S waves.' }, { dx: 'brugada1', how: 'Coved STE limited to V1–V2 with negative T.' }, { dx: 'hyperK', how: 'Peaked T and pseudo-STE (Brugada phenocopy) in hyperkalaemia.' }, { dx: 'Ventricular aneurysm', how: 'Persistent STE with deep Q waves weeks after MI.' }, { dx: 'takotsubo', how: 'Takotsubo can mimic anterior STEMI — requires angiography.' }],
    management: {
      recognition: 'New STE meeting UDMI thresholds in contiguous leads with reciprocal changes; or STEMI equivalents (posterior MI, hyperacute T, de Winter, Sgarbossa-positive LBBB/paced rhythm).',
      mechanism: 'Transmural ischaemic injury current from coronary occlusion.',
      stability: 'Cardiogenic shock, electrical instability (VT/VF, high-grade AV block) and acute HF mark highest risk.',
      immediate: ['Activate the reperfusion system; primary PCI preferred when timely (first-medical-contact-to-device ≤ 90 min, ≤ 120 min if transfer).', 'Fibrinolysis (within 12 h of symptoms, no contraindications) when timely PCI is not available.', 'Aspirin, P2Y12 inhibitor, parenteral anticoagulation per 2025 ACC/AHA/ACEP/NAEMSP/SCAI ACS guideline; treat pain, hypoxaemia (if SpO₂ low), arrhythmias.', 'Right-sided leads (V4R) in inferior STEMI; avoid nitrates/volume depletion if RV infarction.'],
      definitive: ['Revascularisation, secondary prevention (high-intensity statin, antiplatelet therapy, β-blocker where indicated, ACE-I/ARB/ARNI and MRA for reduced EF, cardiac rehabilitation).', 'ICD evaluation for persistent LVEF ≤ 35% after the appropriate waiting period.'],
      cautions: ['Absence of STE does not exclude occlusion (LCx territory, posterior MI).', 'Mimics (pericarditis, early repolarisation, LVH, LBBB, Brugada, hyperkalaemia, takotsubo) cause false activations — but when uncertain, serial ECGs, echo and expert review help.'],
      whyWorks: ['Reopening the artery restores oxygen supply → injured cells repolarise normally → ST resolves; salvage is time-dependent.'],
      whyNot: ['Antiarrhythmic prophylaxis (e.g. lidocaine) does not improve outcomes.', 'Fibrinolysis does not help NSTE-ACS.'],
      refs: ['acs2025', 'udmi2018', 'ecgStd6'],
    },
    refs: ['acs2025', 'udmi2018', 'ecgStd6'],
  },
  {
    id: 'stemiPosterior',
    name: 'Posterior MI',
    aliases: ['posterior STEMI', 'posterior infarction', 'V7-V9', 'mirror image'],
    category: 'ischemia',
    tier: 2,
    tags: ['st-depression', 'dominant-r-v1', 'chest-pain', 'ischemia', 'lcx', 'rca'],
    preset: 'stemiPosterior',
    definition: 'Infarction of the inferobasal (formerly "posterior") LV wall, usually LCx or RCA, often with inferior or lateral MI.',
    mechanism: 'The injury vector points posteriorly — away from V1–V3 — so the standard 12-lead shows it as a mirror image.',
    ecg: ['Horizontal ST depression in V1–V3 (maximal V2–V3) with upright T waves', 'Tall broad R in V1–V2 (R/S > 1) — the mirror of posterior Q waves (develops later)', 'ST elevation ≥ 0.5 mm in posterior leads V7–V9 confirms'],
    why: [
      { level: 'vector', text: 'Posterior injury current → ST vector points backward.' },
      { level: 'lead', text: 'V1–V3 look from the front → they see it moving away → ST depression. V7–V9 on the back see ST elevation.' },
      { level: 'waveform', text: 'Loss of posterior forces → net forces anterior → tall R in V1–V2 (posterior Q in the mirror).' },
      { level: 'clinical', text: 'A STEMI equivalent that is often missed — flip the ECG and look at the back.' },
    ],
    differential: [{ dx: 'subendo', how: 'Diffuse STD with STE in aVR.' }, { dx: 'rvh', how: 'Right axis, RV strain T inversion.' }, { dx: 'rbbb', how: 'Wide QRS, rSR′.' }],
    refs: ['udmi2018', 'ecgStd6', 'acs2025'],
  },
  {
    id: 'nste',
    name: 'Subendocardial ischaemia / NSTE-ACS (ST depression, STE in aVR)',
    aliases: ['NSTEMI', 'unstable angina', 'ST depression', 'aVR elevation', 'left main', 'demand ischaemia'],
    category: 'ischemia',
    tier: 1,
    tags: ['st-depression', 'st-elevation', 'chest-pain', 'ischemia'],
    preset: 'subendo',
    definition: 'Ischaemia confined to the subendocardium: horizontal or downsloping ST depression ≥ 0.5 mm in ≥ 2 contiguous leads and/or T-wave inversion. Widespread STD with STE in aVR (± V1) suggests left-main/multivessel or severe supply–demand ischaemia.',
    mechanism: 'The subendocardium is most vulnerable (highest wall stress, last perfused). Its injury current points toward the ventricular cavity — i.e. away from most surface leads and toward aVR.',
    ecg: ['ST depression (horizontal/downsloping) in multiple leads, maximal V4–V6, I, II', 'STE in aVR (and V1)', 'Dynamic changes with pain', 'ST depression does NOT localise the culprit artery'],
    why: [
      { level: 'cell', text: 'Subendocardial cells are injured (lower plateau); epicardium is healthy.' },
      { level: 'vector', text: 'The ST vector points from healthy epicardium toward injured endocardium/cavity → superior-rightward (toward aVR).' },
      { level: 'lead', text: 'Most leads face the epicardium → ST depression; aVR (looking into the cavity) → ST elevation.' },
      { level: 'clinical', text: 'Troponin distinguishes NSTEMI from unstable angina; high-risk features warrant early invasive strategy.' },
    ],
    differential: [{ dx: 'lvh', how: 'Strain pattern in leads with tall R.' }, { dx: 'digoxinEffect', how: 'Scooped ST, short QT.' }, { dx: 'hypoK', how: 'U waves, flat T.' }, { dx: 'stemiPosterior', how: 'STD maximal V1–V3 = posterior STEMI until proven otherwise.' }, { dx: 'af', how: 'Rate-related STD during tachyarrhythmias is common and may resolve.' }],
    acute: ['Antiplatelet and anticoagulant therapy, anti-ischaemic therapy, risk stratification with high-sensitivity troponin; invasive strategy timing by risk (immediate for refractory angina, haemodynamic or electrical instability) per 2025 ACS guideline.'],
    refs: ['acs2025', 'udmi2018', 'ecgStd6'],
  },
  {
    id: 'wellens',
    name: 'Wellens pattern',
    aliases: ['Wellens syndrome', 'LAD T waves', 'biphasic T V2'],
    category: 'ischemia',
    tier: 2,
    tags: ['t-inversion', 'chest-pain', 'ischemia', 'lad'],
    preset: 'wellens',
    definition: 'Deep symmetric (type B) or biphasic (type A) T waves in V2–V3 in a patient with recent chest pain who is now pain-free, with minimal ST elevation and preserved R waves — indicating a reperfused but critically stenosed proximal LAD.',
    mechanism: 'Transient LAD occlusion followed by spontaneous reperfusion leaves reperfused myocardium with prolonged, altered repolarisation (T inversion) without necrosis.',
    ecg: ['Deep symmetric T inversion or biphasic T in V2–V3 (± V1–V6)', 'Little or no ST elevation, no Q waves, preserved R progression', 'Recorded when pain-free'],
    why: [
      { level: 'cell', text: 'Reperfused ("stunned") myocardium repolarises late → the local repolarisation vector reverses.' },
      { level: 'waveform', text: 'Anterior leads show inverted T waves while depolarisation (R waves) is preserved — no infarct.' },
      { level: 'clinical', text: 'High risk of re-occlusion (anterior MI) — urgent angiography; stress testing is dangerous.' },
    ],
    differential: [{ dx: 'lvh', how: 'Strain in lateral leads with high voltage.' }, { dx: 'pe', how: 'RV strain TWI V1–V4 with tachycardia, hypoxia.' }, { dx: 'Takotsubo / CNS event', how: 'Giant T inversion with long QT.' }],
    refs: ['acs2025', 'ecgStd6'],
  },
  {
    id: 'oldMI',
    name: 'Old (prior) myocardial infarction — pathological Q waves',
    aliases: ['Q waves', 'old MI', 'prior infarct', 'pathological Q'],
    category: 'ischemia',
    tier: 1,
    tags: ['q-waves', 'ischemia'],
    preset: 'oldInferior',
    definition: 'Pathological Q waves (e.g. any Q ≥ 20 ms in V2–V3 or QS; Q ≥ 30 ms and ≥ 1 mm deep in ≥ 2 contiguous leads of a territory — UDMI) indicating prior transmural infarction.',
    mechanism: 'Scar does not depolarise. Normally forces from that wall cancel forces from the opposite wall; without them, the initial QRS vector points AWAY from the infarct.',
    ecg: ['Q waves in the leads facing the scar', 'Loss of R-wave amplitude', 'T inversion may persist or normalise', 'Posterior scar → tall R in V1–V2 (mirror)'],
    why: [
      { level: 'cell', text: 'Necrosis → fibrous scar with no action potential.' },
      { level: 'vector', text: 'The lead overlying the scar looks through an "electrical window" into the cavity and sees the opposite wall moving away.' },
      { level: 'waveform', text: 'Initial negative deflection = Q wave.' },
    ],
    differential: [{ dx: 'lafb', how: 'Initial small r in inferior leads (rS), not Q.' }, { dx: 'wpw', how: 'Negative delta waves mimic Q.' }, { dx: 'Hypertrophic cardiomyopathy', how: 'Narrow deep septal Q waves in lateral/inferior leads.' }, { dx: 'poorR', how: 'Lead position, COPD.' }],
    refs: ['udmi2018', 'ecgStd6'],
  },
  // ======================================================================= PERICARDIAL
  {
    id: 'pericarditis',
    name: 'Acute pericarditis',
    aliases: ['pericarditis', 'PR depression', 'diffuse ST elevation', 'Spodick sign'],
    category: 'pericardial',
    tier: 1,
    tags: ['st-elevation', 'pr-depression', 'chest-pain', 'tachycardia', 'colchicine'],
    preset: 'pericarditis',
    altPresets: ['pericarditis3'],
    definition: 'Inflammation of the pericardium; diagnosis requires ≥ 2 of: pericarditic chest pain (sharp, pleuritic, better sitting forward), pericardial rub, new widespread ST elevation or PR depression, new or worsening pericardial effusion.',
    epidemiology: 'Commonly idiopathic/viral in high-income countries; also post-cardiac injury, autoimmune, uraemic, neoplastic, tuberculous. ECG changes are present in a majority but not all.',
    mechanism: 'The ECG changes come from inflammation of the SUPERFICIAL (epicardial) myocardium beneath the inflamed pericardium — diffuse, not confined to one coronary territory. Atrial epicardial injury produces PR-segment deviation.',
    ecg: ['Stage 1: diffuse concave ST elevation (I, II, aVL, aVF, V2–V6) with PR depression; ST depression and PR elevation in aVR (± V1)', 'No reciprocal ST depression other than aVR/V1; no Q waves', 'Stage 2: ST normalises, T flattens; Stage 3: diffuse T inversion; Stage 4: normalisation', 'Sinus tachycardia common; low voltage/alternans if large effusion'],
    why: [
      { level: 'cell', text: 'Epicardial myocytes around the whole heart are injured by adjacent inflammation.' },
      { level: 'vector', text: 'Diffuse epicardial injury → ST vector points toward the apex/epicardium in general (roughly along the mean QRS axis).' },
      { level: 'lead', text: 'Almost every lead faces some epicardium → ST elevation in most leads; only aVR (looking into the cavity from the right shoulder) and often V1 face away → ST depression.' },
      { level: 'cell', text: 'Atrial epicardial injury current flows during the PR segment → PR depression (and PR elevation in aVR).' },
      { level: 'diagnosis', text: 'Diffuse STE crossing coronary territories + PR depression + no reciprocal changes → pericarditis rather than STEMI.' },
      { level: 'treatment', text: 'Anti-inflammatory therapy targets the cause of the injury current.' },
    ],
    differential: [{ dx: 'stemi', how: 'Territorial STE, reciprocal STD, convex ST, Q waves, regional wall-motion abnormality.' }, { dx: 'earlyRepol', how: 'J-point notch, STE/T ratio lower, stable, no PR depression, asymptomatic.' }, { dx: 'myocarditis', how: 'Troponin rise, LV dysfunction, arrhythmias.' }],
    acute: ['First-line (2025 ESC myocarditis & pericarditis guideline): NSAID or high-dose aspirin plus colchicine; restriction of strenuous exercise; evaluate for myocardial involvement (troponin), effusion (echo) and high-risk features (fever > 38 °C, large effusion/tamponade, lack of response, immunosuppression).', 'Corticosteroids are second-line (associated with recurrence); anti-IL-1 agents for recurrent, colchicine-resistant, corticosteroid-dependent cases.'],
    cautions: ['Do not give fibrinolysis for misread pericarditis — haemopericardium risk.'],
    refs: ['escMyoPeri2025', 'escPeri2015'],
  },
  {
    id: 'myocarditis',
    name: 'Myocarditis / myopericarditis',
    aliases: ['myocarditis', 'myopericarditis', 'perimyocarditis'],
    category: 'pericardial',
    tier: 2,
    tags: ['st-elevation', 't-inversion', 'tachycardia', 'chest-pain', 'arrhythmia'],
    preset: 'myocarditis',
    definition: 'Inflammatory disease of the myocardium (viral, immune-mediated, toxic — including immune-checkpoint-inhibitor and vaccine-associated forms); myopericarditis when pericarditis predominates with myocardial involvement (troponin rise).',
    mechanism: 'Myocyte inflammation and necrosis cause heterogeneous depolarisation/repolarisation abnormalities, conduction disease and triggered/re-entrant arrhythmias.',
    ecg: ['Sinus tachycardia', 'ST elevation (diffuse or regional — can mimic STEMI), T inversion', 'PVCs, AF, VT; AV block or BBB (e.g. giant-cell myocarditis, sarcoidosis, Lyme)', 'Low voltage, QRS widening in severe disease', 'The ECG can be normal'],
    why: [
      { level: 'cell', text: 'Patchy myocyte injury depolarises cells and slows conduction unevenly.' },
      { level: 'vector', text: 'Injury currents and altered repolarisation vectors depend on WHERE the inflammation is — so patterns vary.' },
      { level: 'clinical', text: 'Conduction block or ventricular arrhythmias suggest more severe forms; cardiac MRI and troponin are key.' },
    ],
    differential: [{ dx: 'stemi', how: 'Coronary angiography may be needed to exclude occlusion.' }, { dx: 'pericarditis', how: 'Pericarditis without myocardial involvement: normal troponin/LV function.' }],
    acute: ['Hospital monitoring when high-risk; HF therapy; arrhythmia management; exercise restriction; specific therapy for specific aetiologies (per 2025 ESC guideline).'],
    refs: ['escMyoPeri2025'],
  },
  // ======================================================================= PULMONARY / RIGHT HEART
  {
    id: 'pe',
    name: 'Acute pulmonary embolism / acute RV strain',
    aliases: ['PE', 'pulmonary embolism', 'S1Q3T3', 'RV strain', 'acute cor pulmonale'],
    category: 'pulmonary',
    tier: 1,
    tags: ['tachycardia', 't-inversion', 'rad', 'dyspnea', 'chest-pain', 'syncope'],
    preset: 'pe',
    definition: 'ECG changes reflecting acute RV pressure overload and sympathetic activation in PE.',
    epidemiology: 'The ECG is neither sensitive nor specific for PE: it is often normal or shows only sinus tachycardia. In an ED cohort (Richman et al. 2004), "classic" findings (S1Q3T3, RBBB, right axis) were rare and did not distinguish PE from controls. RV-strain findings are more useful for PROGNOSIS than diagnosis.',
    mechanism: 'Sudden rise in pulmonary vascular resistance dilates and strains the RV: delayed RV conduction, rightward rotation of forces, RV subendocardial ischaemia; catecholamines and hypoxia cause tachycardia and atrial arrhythmias.',
    ecg: ['Sinus tachycardia (most common abnormality)', 'T-wave inversion V1–V4 and III (RV strain) — associated with RV dysfunction/worse prognosis', 'New RBBB (complete or incomplete), right axis shift', 'S1Q3T3 (S in I, Q and T inversion in III) — uncommon, nonspecific', 'P pulmonale, AF/flutter, low voltage', 'ST elevation in V1/aVR in massive PE'],
    why: [
      { level: 'conduction', text: 'RV dilatation stretches the right bundle → delayed RV activation → incomplete/complete RBBB and a late rightward vector (S in I).' },
      { level: 'vector', text: 'Rightward/clockwise rotation of the heart shifts the axis rightward and alters initial forces (Q in III).' },
      { level: 'cell', text: 'RV wall stress with reduced coronary perfusion → RV subendocardial ischaemia → T inversion in leads over the RV (V1–V4, III).' },
      { level: 'clinical', text: 'Diagnosis requires imaging (CT pulmonary angiography / V/Q) guided by clinical probability and D-dimer — never the ECG alone.' },
    ],
    differential: [{ dx: 'wellens', how: 'Anterior TWI from LAD disease — clinical context, echo, troponin.' }, { dx: 'rbbb', how: 'Chronic RBBB without RV strain.' }, { dx: 'sinusTach', how: 'Most common PE ECG finding — non-specific.' }],
    acute: ['Risk stratify and treat per the 2026 AHA/ACC/ACCP/ACEP/CHEST/SCAI/SHM/SIR/SVM/SVN PE guideline (anticoagulation; advanced therapies for higher-risk categories).', 'Cardiac arrest from PE: CPR; thrombolysis considered (2025 AHA special circumstances).'],
    refs: ['pe2026', 'escPe2019', 'richman2004', 'special2025'],
  },
  {
    id: 'copd',
    name: 'COPD / emphysema and chronic pulmonary hypertension patterns',
    aliases: ['COPD', 'emphysema', 'pulmonary hypertension', 'cor pulmonale', 'P pulmonale'],
    category: 'pulmonary',
    tier: 2,
    tags: ['low-voltage', 'rad', 'p-wave'],
    preset: 'copd',
    altPresets: ['pulmHtn'],
    definition: 'ECG changes associated with hyperinflated lungs and/or chronic RV pressure overload.',
    mechanism: 'Hyperinflation increases the distance/insulation between heart and electrodes and pulls the heart into a vertical, clockwise-rotated position. Chronic pulmonary hypertension produces RVH and RA enlargement.',
    ecg: ['Low QRS voltage (especially limb leads)', 'Right axis deviation; vertical heart', 'Poor R-wave progression / late transition (clockwise rotation)', 'P pulmonale (tall P in II, III, aVF); rightward P axis', 'MAT and AF are common; RVH pattern in advanced pulmonary hypertension'],
    why: [
      { level: 'lead', text: 'Air is a poor conductor → lower surface voltages.' },
      { level: 'vector', text: 'A low diaphragm makes the heart vertical → QRS and P axes swing rightward/inferior.' },
      { level: 'waveform', text: 'Clockwise rotation shifts the precordial transition toward V5–V6.' },
    ],
    differential: [{ dx: 'lowVoltage', how: 'Effusion/infiltration.' }, { dx: 'lpfb', how: 'Isolated right axis without lung disease.' }],
    refs: ['ecgStd5'],
  },
];
