import type { Dx } from './types';

// Electrolytes, drugs/toxicology, inherited/primary electrical syndromes.

export const METABOLIC_DX: Dx[] = [
  // ======================================================================= ELECTROLYTES
  {
    id: 'hyperK',
    name: 'Hyperkalaemia',
    aliases: ['high potassium', 'peaked T waves', 'sine wave', 'hyperkalemia'],
    category: 'electrolyte',
    tier: 1,
    tags: ['peaked-t', 'wide-qrs', 'p-absent', 'bradycardia', 'calcium', 'insulin', 'block', 'cardiac-arrest'],
    preset: 'hyperK6',
    altPresets: ['hyperK7', 'hyperK8', 'hyperK9'],
    definition: 'Serum K⁺ above the reference range (commonly > 5.0–5.5 mmol/L); ECG changes signal cardiac membrane toxicity.',
    epidemiology: 'Kidney disease, RAAS inhibitors, K⁺-sparing diuretics, NSAIDs, trimethoprim, digoxin toxicity, tissue breakdown, acidosis, adrenal insufficiency. The ECG correlates poorly with the exact level: some patients with severe hyperkalaemia have near-normal ECGs, and peaked T waves are an unreliable marker of life-threatening severity.',
    mechanism: 'Raising extracellular K⁺ (1) increases IKr/IK1 conductance → faster phase-3 repolarisation; (2) depolarises the resting membrane (smaller K⁺ gradient) → inactivates fast Na⁺ channels → slower phase-0 upstroke and conduction. Atrial myocytes are especially sensitive; the sinus node and internodal tracts are more resistant (sinoventricular rhythm).',
    ecg: ['Tall, narrow-based, peaked ("tented") T waves', 'Shortened QT (early)', 'P-wave flattening → loss of P waves; PR prolongation', 'QRS widening (bizarre IVCD), axis shifts, Brugada-like pattern, pseudo-STEMI', 'AV block, bradycardia, junctional/idioventricular rhythms', 'Sine-wave pattern (QRS merges with T) → VF/asystole/PEA'],
    why: [
      { level: 'cell', text: 'Higher [K⁺]ₒ increases K⁺-channel conductance (IKr) → phase 3 is faster and more synchronous.' },
      { level: 'waveform', text: 'Faster, more uniform repolarisation → narrow, tall, symmetric T waves and a short QT.' },
      { level: 'cell', text: 'Smaller K⁺ gradient → resting potential rises from ~−90 toward −75 mV (Nernst).' },
      { level: 'cell', text: 'At less negative potentials many fast Na⁺ channels stay inactivated → fewer available → slower, smaller phase-0 upstroke.' },
      { level: 'conduction', text: 'Slower conduction in atria (most sensitive) → P flattens and disappears; in ventricles → QRS widens; in the AV node/His–Purkinje → block.' },
      { level: 'waveform', text: 'Eventually depolarisation and repolarisation merge → sine wave → VF or asystole.' },
      { level: 'treatment', text: 'IV calcium raises the threshold potential, restoring the gap between resting and threshold potential → stabilises excitability within minutes WITHOUT lowering K⁺. Insulin–glucose and β₂-agonists shift K⁺ into cells (Na⁺/K⁺-ATPase); binders, diuretics and dialysis remove it.' },
    ],
    differential: [{ dx: 'stemi', how: 'Hyperacute T waves are broader-based with STE in a territory; hyperkalaemic T waves are narrow and diffuse.' }, { dx: 'earlyRepol', how: 'Benign tall T waves in young people — normal QRS/P.' }, { dx: 'tca', how: 'Na⁺-channel blocker toxicity: wide QRS + terminal R in aVR, tachycardia.' }, { dx: 'monoVT', how: 'Hyperkalaemic wide-complex rhythm is usually slower; check K⁺ first.' }],
    management: {
      recognition: 'Peaked T → loss of P, PR/QRS prolongation → sine wave in a patient with risk factors.',
      mechanism: 'Membrane depolarisation and Na⁺-channel inactivation with accelerated repolarisation.',
      stability: 'Any ECG change, arrhythmia or K⁺ ≥ ~6.5 mmol/L warrants emergency treatment and monitoring.',
      immediate: ['IV calcium (gluconate or chloride) for ECG changes — repeat if changes persist (KDIGO conference summary).', 'Shift K⁺ into cells: IV insulin with glucose (monitor for hypoglycaemia); nebulised/inhaled β₂-agonist (salbutamol/albuterol); sodium bicarbonate mainly when metabolic acidosis coexists.', 'Remove K⁺: loop diuretics (if kidneys respond), K⁺ binders (patiromer, sodium zirconium cyclosilicate), haemodialysis for severe/refractory cases or kidney failure.', 'Stop contributing drugs; recheck K⁺ frequently.', 'Cardiac arrest: standard CPR/ACLS; IV calcium, sodium bicarbonate and insulin–glucose may be considered (2025 AHA: Class 2b, effectiveness not well established); inhaled β₂-agonists are not recommended during arrest.'],
      definitive: ['Address the cause (kidney function, drug review, dietary K⁺); monitor during RAAS-inhibitor therapy.'],
      cautions: ['Calcium does not lower K⁺ — effect lasts ~30–60 min; shifting agents buy time; only removal is definitive.', 'Digoxin toxicity with hyperkalaemia: prioritise digoxin-specific antibody fragments.', 'Pacing may fail to capture in severe hyperkalaemia (high threshold).'],
      whyWorks: ['Calcium raises the threshold potential → restores the resting-to-threshold difference → normalises excitability.', 'Insulin/β₂-agonists activate Na⁺/K⁺-ATPase → K⁺ enters cells → larger K⁺ gradient restored.'],
      whyNot: ['Antiarrhythmics (e.g. amiodarone, lidocaine) do not correct the membrane problem and can worsen conduction.'],
      refs: ['kdigoK2020', 'littmann2018', 'special2025'],
    },
    refs: ['kdigoK2020', 'littmann2018', 'special2025', 'ecgStd4'],
  },
  {
    id: 'hypoK',
    name: 'Hypokalaemia',
    aliases: ['low potassium', 'U waves', 'hypokalemia'],
    category: 'electrolyte',
    tier: 1,
    tags: ['u-wave', 'st-depression', 'long-qt', 'torsades-risk'],
    preset: 'hypoK',
    definition: 'Serum K⁺ below the reference range (commonly < 3.5 mmol/L).',
    epidemiology: 'Diuretics, vomiting/diarrhoea, hyperaldosteronism, insulin/β-agonist therapy, hypomagnesaemia (which impairs renal K⁺ conservation).',
    mechanism: 'Low [K⁺]ₒ paradoxically REDUCES the conductance of IK1 and IKr → slower late repolarisation (longer APD, particularly in Purkinje/M-cells), increased automaticity and EAD/DAD propensity.',
    ecg: ['T-wave flattening or inversion', 'Prominent U waves (> 1 mm, often larger than T in V2–V3)', 'ST depression', 'Apparent QT prolongation (really Q–U / T–U fusion)', 'PACs, PVCs, AF; torsades de pointes (especially with QT drugs), digoxin toxicity potentiated'],
    why: [
      { level: 'cell', text: 'K⁺ channels (IK1, IKr) conduct less when extracellular K⁺ is low → phase 3 slows.' },
      { level: 'waveform', text: 'Repolarisation is spread out → low, flat T; late repolarising regions produce a prominent U wave; T and U merge → long "QU".' },
      { level: 'cell', text: 'Reduced repolarisation reserve + increased automaticity → ectopy and torsades.' },
      { level: 'treatment', text: 'Replace K⁺ (and Mg²⁺ — K⁺ repletion fails if Mg²⁺ is low).' },
    ],
    differential: [{ dx: 'lqts', how: 'Congenital long QT with normal K⁺.' }, { dx: 'digoxinEffect', how: 'Scooped ST with SHORT QT.' }, { dx: 'nste', how: 'Ischaemic STD without U waves, symptomatic.' }],
    acute: ['Replace K⁺ (IV if severe, arrhythmias, or ECG changes; oral otherwise); replace Mg²⁺; review diuretics.'],
    refs: ['ecgStd4', 'tdp2010'],
  },
  {
    id: 'hyperCa',
    name: 'Hypercalcaemia',
    aliases: ['high calcium', 'short QT', 'short ST'],
    category: 'electrolyte',
    tier: 2,
    tags: ['short-qt'],
    preset: 'hyperCa',
    definition: 'Raised serum calcium (commonly total > 2.6 mmol/L / > 10.5 mg/dL).',
    mechanism: 'High extracellular Ca²⁺ accelerates Ca²⁺-dependent inactivation of L-type Ca²⁺ channels and shortens the plateau (phase 2).',
    ecg: ['Short ST segment → short QT (T wave begins almost at the J point)', 'Severe: J (Osborn-like) waves, bradycardia, AV block'],
    why: [
      { level: 'cell', text: 'Phase 2 shortens (plateau ends earlier).' },
      { level: 'waveform', text: 'The ST segment (≈ phase 2) shortens while T-wave shape (phase 3) is little changed → QT shortens mainly by losing ST.' },
    ],
    differential: [{ dx: 'sqts', how: 'Congenital short QT with normal calcium; very tall T waves.' }, { dx: 'digoxinEffect', how: 'Digoxin also shortens QT but with scooped ST depression.' }],
    acute: ['Treat the cause; IV fluids, bisphosphonates/calcitonin per endocrine guidance.'],
    refs: ['ecgStd4'],
  },
  {
    id: 'hypoCa',
    name: 'Hypocalcaemia',
    aliases: ['low calcium', 'long ST', 'long QT'],
    category: 'electrolyte',
    tier: 2,
    tags: ['long-qt'],
    preset: 'hypoCa',
    definition: 'Low serum calcium (commonly total < 2.1 mmol/L / < 8.5 mg/dL; interpret with albumin or ionised Ca²⁺).',
    mechanism: 'Low extracellular Ca²⁺ slows Ca²⁺-dependent inactivation of L-type channels → prolonged plateau (phase 2).',
    ecg: ['Long, flat (straight) ST segment', 'QT prolongation with a normal-looking T wave'],
    why: [
      { level: 'cell', text: 'Phase 2 (plateau) is prolonged.' },
      { level: 'waveform', text: 'The ST segment lengthens; the T wave itself (phase 3) keeps its usual width → long QT due to a long ST. (Contrast hypokalaemia/IKr block, where the T wave itself widens.)' },
    ],
    differential: [{ dx: 'hypoK', how: 'Flat T and U waves rather than a long ST.' }, { dx: 'qtDrug', how: 'Broad/notched T waves.' }],
    acute: ['Symptomatic or severe: IV calcium; correct Mg²⁺.'],
    refs: ['ecgStd4'],
  },
  {
    id: 'magnesium',
    name: 'Magnesium disorders',
    aliases: ['hypomagnesaemia', 'hypermagnesaemia', 'magnesium'],
    category: 'electrolyte',
    tier: 2,
    tags: ['long-qt', 'torsades-risk', 'magnesium'],
    preset: 'hypoMg',
    altPresets: ['hyperMg'],
    definition: 'Low Mg²⁺ (often with low K⁺ and Ca²⁺) or high Mg²⁺ (usually iatrogenic or with kidney failure).',
    mechanism: 'Mg²⁺ is a cofactor for Na⁺/K⁺-ATPase and blocks L-type Ca²⁺ and some K⁺ channels. Low Mg²⁺ → renal K⁺ wasting, prolonged repolarisation, EADs/torsades, enhanced digoxin toxicity. High Mg²⁺ depresses SA/AV-nodal and intraventricular conduction.',
    ecg: ['Hypomagnesaemia: nonspecific — features of accompanying hypokalaemia (flat T, U waves), QT prolongation, torsades, atrial and ventricular ectopy', 'Hypermagnesaemia (marked): bradycardia, PR and QRS prolongation, AV block; cardiac arrest at very high levels'],
    why: [
      { level: 'cell', text: 'Mg²⁺ stabilises repolarisation (Na⁺/K⁺-ATPase, Ca²⁺-channel block).' },
      { level: 'waveform', text: 'Deficiency looks like hypokalaemia on the ECG because the mechanism overlaps; the ECG cannot distinguish them.' },
      { level: 'treatment', text: 'Magnesium therapy suppresses EAD-driven torsades even when serum Mg²⁺ is normal.' },
    ],
    differential: [{ dx: 'hypoK', how: 'Often coexists — measure both.' }],
    acute: ['Hypomagnesaemia: IV/oral magnesium, replace K⁺. Hypermagnesaemia: stop Mg²⁺, IV calcium for toxicity, dialysis if kidney failure.'],
    refs: ['tdp2010', 'ecgStd4'],
  },
  {
    id: 'hypothermia',
    name: 'Hypothermia (Osborn / J waves)',
    aliases: ['Osborn wave', 'J wave', 'hypothermia'],
    category: 'electrolyte',
    tier: 2,
    tags: ['bradycardia', 'j-wave', 'long-qt'],
    preset: 'hypothermia',
    definition: 'Core temperature < 35 °C; ECG changes become prominent below ~32 °C.',
    mechanism: 'Cold enhances the transient outward current (Ito) notch in epicardium more than endocardium → transmural voltage gradient at the J point (Osborn wave); it slows all ion-channel kinetics (bradycardia, prolonged PR/QRS/QT) and predisposes to AF and VF.',
    ecg: ['J (Osborn) waves: positive hump at the J point, most visible in inferior/lateral leads, larger with colder temperature', 'Sinus bradycardia, prolonged PR, QRS, QT', 'Shivering artefact', 'AF (often slow), VF at very low temperatures'],
    why: [
      { level: 'cell', text: 'Epicardial phase-1 notch deepens relative to endocardium.' },
      { level: 'vector', text: 'Transmural gradient at the end of depolarisation → a J-point vector.' },
      { level: 'waveform', text: 'Osborn wave (a "hump" at the J point).' },
    ],
    differential: [{ dx: 'earlyRepol', how: 'Small J notch, normal temperature.' }, { dx: 'hyperCa', how: 'Severe hypercalcaemia can produce J waves.' }],
    acute: ['Rewarming; gentle handling; hypothermic cardiac arrest management per 2025 AHA special circumstances.'],
    refs: ['special2025', 'jwave2016'],
  },
  // ======================================================================= DRUGS
  {
    id: 'digoxinEffect',
    name: 'Digoxin effect and toxicity',
    aliases: ['digitalis', 'scooped ST', 'reverse tick', 'Salvador Dali', 'digoxin toxicity'],
    category: 'drug',
    tier: 1,
    tags: ['st-depression', 'short-qt', 'digoxin', 'bradycardia', 'block', 'bidirectional', 'triggered'],
    preset: 'digoxinEffect',
    altPresets: ['atWithBlock', 'bidirectionalVT', 'accelJunctional'],
    definition: 'EFFECT: expected ECG changes at therapeutic levels. TOXICITY: arrhythmias caused by enhanced automaticity/triggered activity combined with AV-nodal depression.',
    mechanism: 'Na⁺/K⁺-ATPase inhibition → ↑intracellular Na⁺ → ↑intracellular Ca²⁺ (via Na⁺/Ca²⁺ exchange) → inotropy but also Ca²⁺ overload (DADs); shortened ventricular action potential; vagotonic effect on SA and AV nodes.',
    ecg: ['Effect: "scooped" / sagging ST depression (reverse tick), flattened T, short QT, PR mildly prolonged', 'Toxicity: frequent PVCs/bigeminy, atrial tachycardia with block, accelerated junctional rhythm, bidirectional VT, any AV block, regularised slow AF (AF with complete heart block + junctional escape)'],
    why: [
      { level: 'cell', text: 'Shorter ventricular APD → shorter QT; altered repolarisation gradients → sagging ST.' },
      { level: 'cell', text: 'Ca²⁺ overload → spontaneous SR Ca²⁺ release → DADs → triggered beats (atrial, junctional, ventricular).' },
      { level: 'conduction', text: 'Vagotonic effect slows the AV node → block.' },
      { level: 'diagnosis', text: 'Hallmark of toxicity: increased automaticity PLUS impaired conduction (e.g. AT with block).' },
    ],
    differential: [{ dx: 'nste', how: 'Ischaemic STD is horizontal/downsloping without QT shortening.' }, { dx: 'lvh', how: 'Strain limited to leads with tall R.' }],
    acute: ['Toxicity: stop digoxin; correct K⁺ (both hyper- and hypokalaemia matter) and Mg²⁺; digoxin-specific antibody fragments for life-threatening arrhythmias, severe hyperkalaemia or end-organ toxicity (2023 AHA poisoning update).', 'Bradyarrhythmias: atropine; pacing if needed.'],
    refs: ['tox2023', 'special2025'],
  },
  {
    id: 'avnBlockers',
    name: 'β-blocker and calcium-channel-blocker effects / toxicity',
    aliases: ['beta blocker', 'calcium channel blocker', 'verapamil', 'diltiazem', 'metoprolol', 'overdose'],
    category: 'drug',
    tier: 1,
    tags: ['bradycardia', 'long-pr', 'block', 'beta-blocker', 'ccb', 'av-node'],
    preset: 'betaBlocker',
    altPresets: ['ccbTox'],
    definition: 'Expected slowing of sinus and AV-nodal conduction at therapeutic doses; in overdose, profound bradycardia, AV block, hypotension and shock.',
    mechanism: 'Sinus- and AV-nodal cells depend on L-type Ca²⁺ current (phase 0) and sympathetic modulation of If/ICa,L. β-blockade removes catecholamine enhancement; non-dihydropyridine CCBs block ICa,L directly.',
    ecg: ['Sinus bradycardia', 'PR prolongation → higher-degree AV block, junctional escape', 'QRS normal unless membrane-stabilising β-blockers (propranolol) in overdose widen it'],
    why: [
      { level: 'cell', text: 'Nodal action potentials are Ca²⁺-dependent: less ICa,L → slower phase 4 and slower upstroke.' },
      { level: 'conduction', text: 'Slower nodal conduction and longer nodal refractoriness → PR prolongation and block.' },
      { level: 'clinical', text: 'Therapeutically, this is exactly how they control AF rate and terminate AVNRT.' },
    ],
    differential: [{ dx: 'sinusBrady', how: 'Other causes.' }, { dx: 'hyperK', how: 'Bradycardia with peaked T/wide QRS.' }, { dx: 'digoxinEffect', how: 'Scooped ST.' }],
    acute: ['Toxicity (2023 AHA focused update): IV calcium, high-dose insulin (with glucose), vasopressors; glucagon for β-blocker poisoning; atropine and pacing for bradycardia; VA-ECMO for refractory shock.'],
    refs: ['tox2023', 'brady2018'],
  },
  {
    id: 'tca',
    name: 'Sodium-channel-blocker toxicity (tricyclic antidepressants and others)',
    aliases: ['TCA overdose', 'tricyclic', 'sodium channel blockade', 'terminal R aVR', 'amitriptyline'],
    category: 'drug',
    tier: 1,
    tags: ['wide-qrs', 'tachycardia', 'tca', 'bicarbonate', 'regular-wide-tachycardia'],
    preset: 'tca',
    altPresets: ['flecainide'],
    definition: 'ECG toxicity from fast Na⁺-channel blockade: TCAs, class IA/IC antiarrhythmics, cocaine, diphenhydramine, carbamazepine and others.',
    mechanism: 'Blocking fast Na⁺ channels reduces the phase-0 upstroke slope → slower conduction through His–Purkinje and ventricular myocardium. Block is use-dependent (worse at fast rates). TCAs add anticholinergic sinus tachycardia and α-blockade (hypotension).',
    ecg: ['QRS widening (maximal limb-lead QRS ≥ 100 ms predicted seizures; ventricular arrhythmias occurred only at ≥ 160 ms in Boehnert & Lovejoy 1985)', 'Terminal R in aVR ≥ 3 mm and R/S in aVR ≥ 0.7 (Liebelt 1995)', 'Rightward terminal 40-ms axis', 'Sinus tachycardia (TCAs)', 'QT prolongation, Brugada-type pattern', 'Wide-complex tachycardia that can mimic VT'],
    why: [
      { level: 'cell', text: '↓ fast Na⁺ current → slower phase-0 depolarisation.' },
      { level: 'conduction', text: 'Slower conduction velocity through the His–Purkinje system and myocardium.' },
      { level: 'waveform', text: 'Ventricular activation takes longer → wider QRS.' },
      { level: 'vector', text: 'The last-activated regions (RV outflow / basal septum, rightward-superior) are delayed disproportionately → terminal rightward vector → R wave in aVR, S in I.' },
      { level: 'treatment', text: 'Sodium bicarbonate: the Na⁺ load increases the driving force through unblocked channels and alkalosis reduces drug binding → QRS narrows.' },
    ],
    differential: [{ dx: 'hyperK', how: 'Peaked T, small P waves, K⁺ level.' }, { dx: 'monoVT', how: 'Context: overdose, sinus P waves may be visible, bicarbonate response.' }, { dx: 'brugada1', how: 'Drug-induced Brugada pattern.' }],
    acute: ['Sodium bicarbonate for QRS widening / ventricular arrhythmias from sodium-channel blockers (2023 AHA poisoning update); airway, seizure control (benzodiazepines), vasopressors; lidocaine may be considered for refractory arrhythmias.', 'Avoid class IA/IC antiarrhythmics.'],
    refs: ['tox2023', 'boehnert1985', 'liebelt1995'],
  },
  {
    id: 'qtDrug',
    name: 'Drug-induced QT prolongation',
    aliases: ['long QT drug', 'hERG', 'IKr block', 'QT prolonging medication'],
    category: 'drug',
    tier: 1,
    tags: ['long-qt', 'torsades-risk', 'qt-drug'],
    preset: 'qtDrug',
    definition: 'QTc prolongation from drugs that block the rapid delayed-rectifier K⁺ current (IKr, hERG channel).',
    epidemiology: 'Class IA/III antiarrhythmics (sotalol, dofetilide, quinidine), some antipsychotics, methadone, macrolides, fluoroquinolones, ondansetron, and many others (updated lists: crediblemeds.org). Risk multiplies with hypokalaemia, hypomagnesaemia, bradycardia, female sex, heart failure, multiple QT drugs, and genetic variants.',
    mechanism: 'IKr block slows phase-3 repolarisation → longer action potential → longer QT; heterogeneous prolongation → dispersion of repolarisation; EADs → torsades de pointes.',
    ecg: ['Long QTc; broad, low or notched T waves; prominent U waves', 'Risk rises steeply above QTc ~500 ms or with an increase > 60 ms from baseline', 'Pause-dependent T-wave changes and PVCs herald torsades'],
    why: [
      { level: 'cell', text: 'Less IKr → phase 3 slower → action potential prolonged (most in M-cells, least in epicardium).' },
      { level: 'waveform', text: 'Longer, broader T wave → long QT.' },
      { level: 'clinical', text: 'Prolonged, dispersed repolarisation creates EADs and the substrate for torsades.' },
    ],
    differential: [{ dx: 'lqts', how: 'Congenital; family history, persistent without drug.' }, { dx: 'hypoCa', how: 'Long ST, normal T.' }, { dx: 'hypoK', how: 'U waves, low K⁺.' }],
    acute: ['Stop offending drug if QTc > 500 ms or ΔQTc > 60 ms; correct K⁺/Mg²⁺; monitor (AHA/ACCF 2010 statement).', 'Torsades: magnesium, pacing/isoproterenol for pause-dependence, defibrillation if sustained.'],
    refs: ['tdp2010', 'escVa2022'],
  },
  {
    id: 'antiarrhythmics',
    name: 'Antiarrhythmic drug ECG effects (amiodarone, flecainide, sotalol)',
    aliases: ['amiodarone', 'flecainide', 'propafenone', 'sotalol', 'dofetilide', 'Vaughan Williams'],
    category: 'drug',
    tier: 2,
    tags: ['long-qt', 'wide-qrs', 'long-pr', 'bradycardia', 'amiodarone', 'flecainide'],
    preset: 'amiodarone',
    altPresets: ['flecainide'],
    definition: 'Expected and toxic ECG changes produced by antiarrhythmic drugs according to their dominant channel effects.',
    mechanism: 'Class I (Na⁺ block): IA slows conduction and prolongs repolarisation; IC strongly slows conduction (use-dependent). Class II (β-block): nodal slowing. Class III (K⁺ block): prolongs repolarisation. Class IV (Ca²⁺ block): nodal slowing. Amiodarone has all four effects.',
    ecg: ['Class IC (flecainide/propafenone): PR and QRS prolongation, more at faster rates; can organise AF into slow flutter with 1:1 conduction; Brugada unmasking', 'Class III (sotalol/dofetilide): QT prolongation, torsades risk', 'Amiodarone: sinus bradycardia, PR and QT prolongation (torsades uncommon), AV block'],
    why: [
      { level: 'cell', text: 'Na⁺ block → slow phase 0 → wider QRS; K⁺ block → slow phase 3 → longer QT; Ca²⁺/β block → nodal slowing.' },
      { level: 'clinical', text: 'The same effect that suppresses re-entry (slower conduction, longer refractoriness) can create new arrhythmias (proarrhythmia).' },
    ],
    differential: [{ dx: 'tca', how: 'Toxidrome context.' }, { dx: 'qtDrug', how: 'Non-cardiac QT drugs.' }],
    acute: ['QRS widening > 25% from baseline with IC drugs or QTc > 500 ms with class III drugs usually prompts dose review.'],
    refs: ['escVa2022', 'af2023', 'tdp2010'],
  },
  // ======================================================================= INHERITED / PRIMARY ELECTRICAL
  {
    id: 'lqts',
    name: 'Congenital long QT syndrome',
    aliases: ['LQTS', 'LQT1', 'LQT2', 'LQT3', 'Schwartz score'],
    category: 'inherited',
    tier: 2,
    tags: ['long-qt', 'torsades-risk', 'syncope', 'cardiac-arrest', 'beta-blocker'],
    preset: 'lqts',
    definition: 'Inherited channelopathy with prolonged ventricular repolarisation and risk of torsades/sudden death. ESC 2022: diagnosed with QTc ≥ 480 ms on repeated ECGs, or LQTS diagnostic score > 3 (borderline QTc, syncope and family history add points); also with a pathogenic variant irrespective of QTc.',
    epidemiology: 'Approximately 1 in 2000. LQT1 (KCNQ1, IKs; triggers: exercise/swimming), LQT2 (KCNH2, IKr; triggers: auditory stimuli, postpartum), LQT3 (SCN5A gain-of-function late INa; events at rest/sleep).',
    mechanism: 'Loss of repolarising K⁺ current (LQT1/2) or persistent inward Na⁺ current (LQT3) prolongs the action potential → EADs + transmural dispersion → torsades.',
    ecg: ['Long QTc (measure in II/V5, tangent method; exclude U waves)', 'Genotype-typical T waves: broad-based (LQT1), low-amplitude notched/bifid (LQT2), long isoelectric ST with late T (LQT3)', 'T-wave alternans; failure of QT to shorten with exercise', 'Sinus bradycardia/pauses in some'],
    why: [
      { level: 'cell', text: 'Repolarising current too small (or depolarising current too large) → phase 2/3 prolonged.' },
      { level: 'waveform', text: 'The T wave shifts later and changes shape according to which current is affected.' },
      { level: 'clinical', text: 'Adrenergic surges (LQT1/2) or bradycardia (LQT3) trigger EADs → torsades → syncope or sudden death.' },
      { level: 'treatment', text: 'β-blockers blunt adrenergic triggers (most effective in LQT1); mexiletine reduces late INa in LQT3.' },
    ],
    differential: [{ dx: 'qtDrug', how: 'Acquired, drug-related.' }, { dx: 'hypoK', how: 'Electrolyte-related.' }, { dx: 'hypoCa', how: 'Long ST, normal T.' }],
    longTerm: ['β-blockers (nadolol/propranolol preferred) for all with the diagnosis (ESC 2022).', 'Avoid QT-prolonging drugs; correct electrolytes; genetic testing and family screening.', 'ICD for survivors of cardiac arrest; left cardiac sympathetic denervation for breakthrough events.'],
    refs: ['escVa2022', 'va2017', 'schwartz1993', 'ipa2013'],
  },
  {
    id: 'sqts',
    name: 'Short QT syndrome',
    aliases: ['SQTS', 'short QT'],
    category: 'inherited',
    tier: 3,
    tags: ['short-qt', 'syncope', 'cardiac-arrest'],
    preset: 'sqts',
    definition: 'Inherited channelopathy with a very short QT and risk of AF and VF. The 2022 ESC guideline combines QTc thresholds in the ~320–360 ms range with a pathogenic variant, family history, or survived VT/VF in a structurally normal heart (see the guideline for exact criteria).',
    mechanism: 'Gain-of-function in repolarising K⁺ channels (KCNH2, KCNQ1, KCNJ2) shortens atrial and ventricular refractoriness → substrate for re-entry.',
    ecg: ['QTc ≤ 320–360 ms', 'Short or absent ST segment; tall, peaked, symmetric T waves', 'Poor QT rate adaptation; AF in young patients'],
    why: [
      { level: 'cell', text: 'More outward K⁺ current → faster, earlier repolarisation.' },
      { level: 'waveform', text: 'T wave begins right after the QRS and peaks early → short QT.' },
      { level: 'clinical', text: 'Short refractory periods allow re-entrant wavelets → AF and VF.' },
    ],
    differential: [{ dx: 'hyperCa', how: 'Short ST due to high Ca²⁺.' }, { dx: 'digoxinEffect', how: 'Scooped ST.' }, { dx: 'hyperK', how: 'Peaked T with high K⁺.' }],
    longTerm: ['ICD for survivors of cardiac arrest/sustained VT; quinidine may be considered (ESC 2022).'],
    refs: ['escVa2022', 'gollob2011'],
  },
  {
    id: 'brugada',
    name: 'Brugada pattern / syndrome',
    aliases: ['Brugada', 'coved ST', 'saddleback', 'type 1 Brugada', 'SCN5A', 'J-wave syndrome'],
    category: 'inherited',
    tier: 2,
    tags: ['st-elevation', 'syncope', 'cardiac-arrest', 'vf', 'rvot'],
    preset: 'brugada1',
    altPresets: ['brugada2'],
    definition: 'Type 1 (diagnostic) pattern: coved ST elevation ≥ 2 mm in ≥ 1 right precordial lead (V1–V2, including high intercostal positions) followed by a negative T wave. Type 2 (saddleback) is suggestive only. Syndrome = pattern plus arrhythmic events/risk features. ESC 2022: spontaneous type 1 is diagnostic; drug-induced type 1 requires additional criteria.',
    epidemiology: 'More common in men and in Southeast Asia; events often at rest/sleep, with fever. SCN5A loss-of-function variants in a minority.',
    mechanism: 'Reduced Na⁺ current and/or accentuated Ito in RV outflow tract (RVOT) epicardium causes loss of the action-potential dome in epicardium but not endocardium → transmural voltage gradient → coved ST elevation; heterogeneous loss of the dome → phase-2 re-entry → polymorphic VT/VF. Depolarisation (conduction-delay) mechanisms in the RVOT also contribute.',
    ecg: ['Type 1: coved STE ≥ 2 mm, descending into inverted T in V1–V2', 'Type 2: saddleback STE with positive/biphasic T', 'Recording V1–V2 in the 2nd–3rd intercostal spaces increases sensitivity', 'Pattern fluctuates; unmasked by fever and Na⁺-channel blockers (ajmaline, flecainide, procainamide)'],
    why: [
      { level: 'cell', text: 'In RVOT epicardium a strong Ito and weak INa end phase 1 so low that the plateau (dome) is lost; endocardium keeps its dome.' },
      { level: 'vector', text: 'During the ST segment, endocardium is at plateau voltage but RVOT epicardium has already repolarised → a transmural voltage gradient whose ST vector points from endocardium toward the RVOT epicardium, i.e. toward V1–V2.' },
      { level: 'lead', text: 'Only electrodes directly over the RVOT (V1–V2) sense this local gradient — it is a proximity effect, not a whole-heart vector (the simulator models it as a local term for exactly this reason).' },
      { level: 'waveform', text: 'Coved ST elevation with a negative T wave.' },
      { level: 'clinical', text: 'Where the dome is lost in some sites but not others, the dome can propagate into repolarised tissue (phase-2 re-entry) → VF, typically at rest/fever.' },
      { level: 'treatment', text: 'Avoid Na⁺-channel blockers and fever; quinidine (Ito block) restores the dome; ICD for high risk; RVOT epicardial ablation in selected patients.' },
    ],
    differential: [{ dx: 'rbbb', how: 'RBBB has R′ plus a wide S in I/V6.' }, { dx: 'stemi', how: 'Territorial STE, reciprocal changes, ischaemic symptoms.' }, { dx: 'hyperK', how: 'Brugada phenocopy that resolves with K⁺ correction.' }, { dx: 'tca', how: 'Drug-induced Brugada pattern.' }, { dx: 'arvc', how: 'Epsilon waves, T inversion V1–V3, RV structural abnormalities on imaging.' }],
    longTerm: ['All: avoid drugs that may induce ST elevation (list at brugadadrugs.org), treat fever promptly, avoid excessive alcohol and large meals (ESC 2022).', 'ICD for survivors of cardiac arrest or documented sustained VA; consider with arrhythmic syncope.', 'Quinidine or catheter ablation for recurrent events/electrical storm.'],
    refs: ['escVa2022', 'jwave2016', 'brugadaCellular1999', 'brugadaCrit2002'],
  },
  {
    id: 'earlyRepol',
    name: 'Early repolarisation pattern / syndrome',
    aliases: ['early repolarization', 'benign early repolarization', 'J point elevation', 'ERP', 'J-wave syndrome'],
    category: 'inherited',
    tier: 1,
    tags: ['st-elevation', 'j-wave'],
    preset: 'earlyRepol',
    definition: 'Pattern (consensus definition): J-point elevation ≥ 1 mm with a notch or slur on the terminal QRS downstroke in ≥ 2 contiguous inferior and/or lateral leads (with QRS < 120 ms). Early repolarisation SYNDROME: the pattern in a survivor of otherwise unexplained VF/polymorphic VT.',
    epidemiology: 'Common in young, athletic, male, Black individuals; the pattern alone is usually benign. Features associated with higher risk: J waves in inferior leads, high amplitude (≥ 2 mm), horizontal/descending ST after the J point.',
    mechanism: 'Prominent Ito-mediated notch in epicardial (not endocardial) action potentials creates a transmural voltage gradient at the end of the QRS (J wave), with early epicardial repolarisation elevating the ST.',
    ecg: ['J-point notch or slur at the end of the QRS in inferior/lateral leads', 'Concave upward ST elevation, usually with tall upright T waves', 'Stable over time, often decreases with tachycardia', 'No reciprocal ST depression (except aVR), no PR depression'],
    why: [
      { level: 'cell', text: 'Epicardial Ito notch deeper than endocardial → transmural current flow at the J point.' },
      { level: 'vector', text: 'J-point vector directed toward the epicardium of the inferolateral wall.' },
      { level: 'waveform', text: 'Notch/slur at the J point plus mild concave STE.' },
      { level: 'clinical', text: 'The pattern is common and benign in most; the syndrome is defined by arrhythmic events.' },
    ],
    differential: [{ dx: 'stemi', how: 'Convex/straight STE, reciprocal STD, Q waves, evolution over serial ECGs.' }, { dx: 'pericarditis', how: 'PR depression, diffuse STE, symptoms, higher ST/T ratio in V6.' }, { dx: 'hypothermia', how: 'Osborn waves with bradycardia and low temperature.' }],
    longTerm: ['Pattern alone: no treatment. Syndrome (survived VF): ICD; isoproterenol for electrical storm; quinidine (ESC 2022).'],
    refs: ['erp2015', 'jwave2016', 'escVa2022'],
  },
];
