import type { Dx } from './types';

// Sinus rhythms, premature beats, atrial tachyarrhythmias, junctional rhythms.

export const RHYTHM_DX: Dx[] = [
  // ======================================================================= SINUS
  {
    id: 'nsr',
    name: 'Normal sinus rhythm',
    category: 'sinus',
    tier: 1,
    tags: ['regular', 'narrow-qrs', 'sinus-node', 'normal'],
    preset: 'nsr',
    definition: 'Rhythm originating in the sinus node at 60–100/min (some references use 50–90/min), with a P wave before every QRS and a QRS after every P.',
    mechanism: 'Sinus-node cells have no stable resting potential: the funny current (If) and T-type Ca²⁺ current depolarise them spontaneously (phase 4) until L-type Ca²⁺ channels fire the upstroke. Being the fastest automatic tissue, the sinus node overdrive-suppresses every other pacemaker.',
    ecg: ['P upright in I, II, aVF; inverted in aVR (aVL and III variable)', 'P axis roughly 0° to +75°', 'Constant PR 120–200 ms', 'Rate 60–100/min, regular (small respiratory variation is normal)'],
    normal: 'The sinus node sits high in the right atrium, so atrial activation spreads downward and leftward toward the positive pole of lead II.',
    why: [
      { level: 'cell', text: 'Phase-4 depolarisation of sinus-node cells (If + ICa,T) reaches threshold ~60–100 times/min.' },
      { level: 'conduction', text: 'The impulse spreads from the high right atrium through both atria (Bachmann bundle to the left atrium) and reaches the AV node.' },
      { level: 'vector', text: 'Mean atrial activation vector points inferiorly and leftward (≈ +45° to +60°).' },
      { level: 'lead', text: 'Lead II is almost parallel to this vector (+60°), aVR almost opposite (−150°).' },
      { level: 'waveform', text: 'Upright P in II (and I, aVF), inverted P in aVR — the "sinus P" signature.' },
      { level: 'waveform', text: 'AV-nodal delay (~70–100 ms) produces the isoelectric PR segment; fast His–Purkinje conduction synchronises the ventricles → narrow QRS.' },
      { level: 'diagnosis', text: 'Sinus-shaped P before every QRS, constant PR, rate 60–100 → normal sinus rhythm.' },
    ],
    differential: [
      { dx: 'Ectopic atrial rhythm', how: 'Ectopic atrial rhythm has a P axis that is not sinus (e.g. inverted in II/III/aVF from a low atrial focus).' },
      { dx: 'accelJunctional', how: 'Junctional rhythm: retrograde P (inverted inferiorly) with short PR, or no visible P.' },
    ],
    refs: ['ecgStd1', 'ionChannels2009'],
  },
  {
    id: 'sinusBrady',
    name: 'Sinus bradycardia',
    category: 'sinus',
    tier: 1,
    tags: ['bradycardia', 'regular', 'narrow-qrs', 'sinus-node', 'atropine', 'pacing', 'beta-blocker'],
    preset: 'sinusBrady',
    definition: 'Sinus rhythm slower than 50–60/min.',
    epidemiology: 'Very common: athletes, sleep, older adults, β-blockers, non-dihydropyridine calcium-channel blockers, hypothyroidism, raised intracranial pressure, hypothermia, inferior MI.',
    mechanism: 'Slower phase-4 slope (↑vagal acetylcholine → IK,ACh opening and reduced If), a more negative maximum diastolic potential, or a higher threshold in sinus-node cells. Intrinsic sinus-node disease (fibrosis) produces the same ECG.',
    ecg: ['Normal sinus P waves and PR', 'Rate < 50–60/min', 'Junctional escape beats may appear if the rate falls below the junctional rate'],
    why: [
      { level: 'cell', text: 'Acetylcholine (vagus) hyperpolarises sinus cells and flattens phase 4; β-blockers remove sympathetic acceleration of If.' },
      { level: 'conduction', text: 'Every impulse still follows the normal path — only the timing between impulses changes.' },
      { level: 'waveform', text: 'P, PR, QRS morphology are normal; the P–P interval is long. QT lengthens at slower rates (rate-dependent repolarisation).' },
      { level: 'clinical', text: 'Only matters if it causes symptoms or hypoperfusion (chronotropic incompetence, syncope, hypotension).' },
      { level: 'treatment', text: 'Atropine blocks muscarinic receptors on sinus/AV-nodal cells, so it works when the mechanism is vagal — not in a denervated (transplanted) heart.' },
    ],
    differential: [
      { dx: 'saExitBlock', how: 'SA exit block: sudden pauses that are exact multiples of the P–P interval.' },
      { dx: 'avb21', how: 'Blocked P waves (hidden in T waves) can mimic sinus bradycardia — look for extra P waves.' },
      { dx: 'pacBlocked', how: 'Non-conducted atrial bigeminy produces a slow ventricular rate; the premature P waves deform the T waves.' },
    ],
    causes: ['Physiological (athletes, sleep)', 'Drugs: β-blockers, verapamil/diltiazem, digoxin, amiodarone, ivabradine, clonidine', 'Sinus-node dysfunction (sick sinus syndrome)', 'Hypothyroidism, hypothermia, hyperkalaemia', 'Raised intracranial pressure (Cushing reflex)', 'Inferior MI (vagal, RCA supplies the sinus node in ~60%)'],
    management: {
      recognition: 'Sinus P before each QRS, constant PR, rate < 50–60/min.',
      mechanism: 'Reduced sinus-node automaticity (vagal, drug, intrinsic disease).',
      stability: 'Assess perfusion: hypotension, altered mental status, shock, ischaemic chest discomfort or acute heart failure define an unstable bradycardia.',
      immediate: ['Asymptomatic: no treatment; review drugs and causes.', 'Symptomatic/unstable (2025 AHA bradycardia algorithm): atropine 1 mg IV, repeat every 3–5 min to a maximum of 3 mg.', 'If atropine ineffective: transcutaneous pacing and/or dopamine infusion 5–20 mcg/kg/min or epinephrine infusion 2–10 mcg/min; consider expert consultation and transvenous pacing.', 'Treat causes: stop offending drugs, correct hyperkalaemia, hypothermia, hypoxia.'],
      definitive: ['Permanent pacing for symptomatic sinus-node dysfunction not due to reversible causes (2018 ACC/AHA/HRS).', 'Avoid pacing asymptomatic sinus bradycardia.'],
      cautions: ['Do not treat a number: athletes may have resting rates in the 40s.', 'Avoid atropine after cardiac transplantation without evidence of reinnervation: it is ineffective (no vagal innervation) and may cause paradoxical sinus arrest or high-grade AV block (2018 ACC/AHA/HRS: Class III: Harm).'],
      whyWorks: ['Atropine removes vagal hyperpolarisation of sinus cells → steeper phase 4 → faster rate.', 'Catecholamine infusions increase If and ICa,L → faster automaticity.', 'Pacing bypasses the failing pacemaker entirely.'],
      whyNot: ['AV-nodal–directed drugs (adenosine, β-blockers) worsen it.', 'Atropine cannot fix structural sinus-node fibrosis for long; pacing does.'],
      refs: ['acls2025', 'brady2018'],
    },
    refs: ['brady2018', 'acls2025'],
  },
  {
    id: 'sinusTach',
    name: 'Sinus tachycardia',
    category: 'sinus',
    tier: 1,
    tags: ['tachycardia', 'regular', 'narrow-qrs', 'sinus-node', 'adenosine-no-effect', 'regular-narrow-tachycardia'],
    preset: 'sinusTach',
    definition: 'Sinus rhythm > 100/min.',
    epidemiology: 'The most common tachycardia; almost always secondary (fever, pain, hypovolaemia, anaemia, hypoxia, sepsis, PE, thyrotoxicosis, stimulants, withdrawal, heart failure).',
    mechanism: 'Sympathetic stimulation (↑cAMP → ↑If and ICa,L) and vagal withdrawal steepen phase-4 depolarisation of sinus-node cells.',
    ecg: ['Sinus P waves (upright II, III, aVF)', 'Rate usually 100–150/min in adults at rest (can exceed 180 with exercise)', 'Gradual onset and offset ("warm-up/cool-down")', 'P may merge with the preceding T wave at high rates'],
    why: [
      { level: 'cell', text: 'Catecholamines increase If and L-type Ca²⁺ current → faster phase 4 in sinus-node cells.' },
      { level: 'conduction', text: 'The same catecholamines speed AV-nodal conduction, so the PR stays normal or shortens.' },
      { level: 'waveform', text: 'Normal P axis, P–QRS 1:1; QT shortens with rate.' },
      { level: 'clinical', text: 'The rhythm is a response, not a disease: the cause (fever, bleeding, sepsis, hypoxia, PE…) is the target.' },
      { level: 'treatment', text: 'Adenosine transiently blocks the AV node but does not stop the sinus node: P waves continue (and may be unmasked) and the tachycardia resumes.' },
    ],
    differential: [
      { dx: 'flutter21', how: 'Flutter with 2:1 conduction sits at ~150/min with no rate variation; look for a second flutter wave hidden in the QRS/T, negative sawtooth in II, III, aVF.' },
      { dx: 'focalAT', how: 'Focal AT: abrupt onset, P axis often not sinus, may show warm-up but the rate is not matched to physiological demand.' },
      { dx: 'avnrt', how: 'AVNRT: abrupt onset/offset, P hidden in or just after the QRS (pseudo-r′ in V1).' },
      { dx: 'orthoAvrt', how: 'Orthodromic AVRT: retrograde P after the QRS (RP ≥ 70 ms), abrupt onset.' },
      { dx: 'ist', how: 'Inappropriate sinus tachycardia: same ECG, no secondary cause.' },
    ],
    acute: ['Identify and treat the cause (fluids, antipyretics, analgesia, oxygen, treat sepsis/PE/bleeding).', 'Do NOT cardiovert — it is not a re-entrant rhythm and it is compensatory.'],
    cautions: ['Rate-slowing drugs can be dangerous when tachycardia is compensating for low stroke volume (hypovolaemia, tamponade, sepsis).'],
    refs: ['svt2015', 'acls2025'],
  },
  {
    id: 'sinusArrhythmia',
    name: 'Sinus arrhythmia',
    category: 'sinus',
    tier: 2,
    tags: ['irregular', 'narrow-qrs', 'sinus-node', 'normal'],
    preset: 'sinusArrhythmia',
    definition: 'Sinus rhythm with phasic variation of the P–P interval (> 120 ms or > 10%), typically respiratory.',
    mechanism: 'Inspiration lowers vagal efferent activity (baroreflex/Bainbridge) → sinus speeds up; expiration restores vagal tone → slows. It reflects healthy autonomic modulation and is most prominent in the young.',
    ecg: ['Identical sinus P waves', 'Constant PR', 'Gradual cyclic shortening and lengthening of P–P'],
    why: [
      { level: 'cell', text: 'Breath-by-breath changes in acetylcholine release alter the phase-4 slope of sinus-node cells.' },
      { level: 'waveform', text: 'P morphology and PR stay constant because the origin and the conduction path do not change — only the timing does.' },
      { level: 'diagnosis', text: 'Irregular rhythm with identical sinus P waves → sinus arrhythmia (not AF, which has no P waves).' },
    ],
    differential: [
      { dx: 'af', how: 'AF has no discrete P waves and is irregularly irregular without a respiratory pattern.' },
      { dx: 'mat', how: 'MAT has ≥ 3 different P morphologies and varying PR.' },
      { dx: 'pac', how: 'PACs are premature P waves with a different morphology.' },
    ],
    refs: ['ecgStd1'],
  },
  {
    id: 'sinusPause',
    name: 'Sinus pause / sinus arrest',
    aliases: ['sinus arrest', 'sinus node dysfunction', 'sick sinus syndrome'],
    category: 'sinus',
    tier: 2,
    tags: ['bradycardia', 'pause', 'sinus-node', 'syncope', 'pacing'],
    preset: 'sinusPause',
    altPresets: ['sinusArrest'],
    definition: 'Failure of the sinus node to discharge, producing a pause that is NOT a multiple of the basic P–P interval. Prolonged failure = sinus arrest.',
    mechanism: 'Transient loss of sinus-node automaticity (intrinsic sinus-node disease, vagal surges, drugs, ischaemia, hyperkalaemia). If the pause exceeds the escape interval of a subsidiary pacemaker, a junctional (or ventricular) escape beat appears.',
    ecg: ['Sudden absence of P–QRS–T', 'Pause length unrelated to the P–P interval', 'Escape beats (junctional: narrow, no/retrograde P) if long enough'],
    why: [
      { level: 'cell', text: 'Sinus-node cells stop reaching threshold (e.g. fibrotic node, strong vagal discharge).' },
      { level: 'conduction', text: 'With no impulse, atria and ventricles stay electrically silent — a flat line.' },
      { level: 'conduction', text: 'The AV junction depolarises spontaneously (40–60/min): if nothing resets it within ~1.0–1.5 s it fires → escape beat.' },
      { level: 'diagnosis', text: 'A pause that is not a multiple of the P–P interval → sinus arrest (vs. SA exit block, where it is).' },
      { level: 'clinical', text: 'Pauses causing syncope/presyncope in sinus-node dysfunction are an indication for pacing when no reversible cause is found.' },
    ],
    differential: [
      { dx: 'saExitBlock', how: 'Pause = exact multiple of the P–P interval.' },
      { dx: 'pacBlocked', how: 'A non-conducted PAC hidden in the T wave causes a pause — look for a deformed T before the pause.' },
      { dx: 'mobitz2', how: 'In AV block a P wave is present in the pause; in sinus arrest there is none.' },
    ],
    acute: ['Symptomatic: treat as bradycardia (atropine, then pacing or chronotropic infusion) and correct reversible causes.'],
    longTerm: ['Permanent pacing for symptomatic sinus-node dysfunction (incl. tachy–brady syndrome) not due to reversible causes.'],
    refs: ['brady2018', 'acls2025'],
  },
  {
    id: 'saExitBlock',
    name: 'Sinoatrial exit block',
    category: 'sinus',
    tier: 3,
    tags: ['bradycardia', 'pause', 'sinus-node', 'block'],
    preset: 'saExitBlock',
    definition: 'The sinus node discharges normally but the impulse fails to exit into the atrium. In second-degree type II SA block the pause equals an exact multiple of the P–P interval.',
    mechanism: 'Conduction failure in the perinodal (sinoatrial junction) tissue. The pacemaker keeps time, so the next impulse arrives exactly on schedule. (Sinus-node discharge itself is invisible on the surface ECG — it is inferred from timing.)',
    ecg: ['Dropped P–QRS–T', 'Type II: pause = 2 × (or n ×) the P–P interval', 'Type I (Wenckebach): P–P shortens progressively, then a pause < 2 × P–P', 'Normal P morphology otherwise'],
    why: [
      { level: 'conduction', text: 'The clock (sinus node) keeps firing; the exit gate (perinodal tissue) intermittently fails.' },
      { level: 'waveform', text: 'Because the clock is intact, the next P arrives precisely when expected → pause is an exact multiple.' },
      { level: 'diagnosis', text: 'Exact-multiple pause distinguishes exit block from sinus arrest (clock stops) — a purely timing-based inference.' },
    ],
    differential: [{ dx: 'sinusPause', how: 'Pause not a multiple of P–P.' }, { dx: 'sinusArrhythmia', how: 'Gradual phasic change, no abrupt pause.' }],
    refs: ['brady2018'],
  },
  {
    id: 'ist',
    name: 'Inappropriate sinus tachycardia',
    category: 'sinus',
    tier: 3,
    tags: ['tachycardia', 'regular', 'narrow-qrs', 'sinus-node', 'palpitations'],
    preset: 'ist',
    definition: 'Sinus rate > 100/min at rest (mean > 90/min over 24 h) with exaggerated rate response, not explained by physiological demand or secondary causes.',
    mechanism: 'Enhanced intrinsic sinus-node automaticity and/or autonomic imbalance (increased sympathetic or decreased vagal tone).',
    ecg: ['Sinus P morphology identical to normal', 'Resting rate > 100/min', 'Gradual onset/offset'],
    why: [
      { level: 'cell', text: 'Sinus-node cells have an intrinsically steep phase-4 slope or excessive sympathetic drive.' },
      { level: 'waveform', text: 'P axis identical to the patient’s normal sinus P — this is what distinguishes it from a high right atrial focal AT (which has a slightly different P).' },
      { level: 'diagnosis', text: 'Diagnosis of exclusion: rule out anaemia, hyperthyroidism, infection, hypovolaemia, stimulants, POTS.' },
    ],
    differential: [{ dx: 'sinusTach', how: 'Secondary cause present.' }, { dx: 'focalAT', how: 'Focal AT near the crista terminalis: abrupt onset, P morphology subtly different.' }],
    longTerm: ['Ivabradine (If blocker) is reasonable for symptomatic IST (2015 ACC/AHA/HRS SVT guideline); β-blockers may be considered; treat reversible factors.'],
    refs: ['svt2015'],
  },
  // ======================================================================= PREMATURE BEATS
  {
    id: 'pac',
    name: 'Premature atrial complex (PAC)',
    aliases: ['atrial premature beat', 'APC', 'atrial ectopic', 'noncompensatory pause'],
    category: 'premature',
    tier: 1,
    tags: ['irregular', 'narrow-qrs', 'automaticity', 'triggered', 'palpitations'],
    preset: 'pac',
    altPresets: ['pacBlocked', 'pacAberrant'],
    definition: 'An atrial depolarisation arising earlier than the next expected sinus beat from a non-sinus atrial focus.',
    mechanism: 'Enhanced automaticity, triggered activity or micro-re-entry in atrial (often pulmonary-vein) myocardium. The premature wavefront also invades and RESETS the sinus node.',
    ecg: ['Early P wave (P′) with a morphology different from sinus', 'P′R may be normal, prolonged (partially recovered AV node), or the P′ may not conduct', 'Usually narrow QRS; may be aberrant (RBBB-like) if very early after a long cycle', 'Pause after the PAC is usually NON-compensatory (sinus node reset)'],
    why: [
      { level: 'cell', text: 'An atrial focus reaches threshold before the sinus node does.' },
      { level: 'vector', text: 'Atrial activation starts somewhere else, so the P-wave vector (and therefore its shape in each lead) differs from sinus.' },
      { level: 'conduction', text: 'The earlier the P′, the less recovered the AV node: decremental conduction lengthens the P′R; if the node is still refractory the P′ is blocked (no QRS).' },
      { level: 'conduction', text: 'If the right bundle (longer refractory period after a long preceding cycle) is still refractory, the QRS takes an RBBB shape (aberration; Ashman phenomenon).' },
      { level: 'conduction', text: 'The P′ wavefront enters the sinus node and resets its timing: the next sinus P comes one sinus cycle after the reset → the pause is less than compensatory.' },
      { level: 'diagnosis', text: 'Early, differently shaped P with non-compensatory pause → PAC.' },
    ],
    differential: [
      { dx: 'pvc', how: 'PVC: wide, bizarre QRS without a preceding premature P; usually fully compensatory pause.' },
      { dx: 'pacAberrant', how: 'An aberrantly conducted PAC looks wide — search the preceding T wave for the premature P′.' },
      { dx: 'sinusArrhythmia', how: 'Gradual change, identical P waves.' },
    ],
    acute: ['Usually no treatment. Reduce triggers (caffeine, alcohol, sleep deprivation, stimulants).'],
    longTerm: ['Frequent PACs are associated with incident AF; symptomatic patients may use β-blockers.'],
    refs: ['svt2015', 'escSvt2019', 'af2023'],
  },
  {
    id: 'pvc',
    name: 'Premature ventricular complex (PVC)',
    aliases: ['VPB', 'ventricular ectopic', 'ventricular extrasystole', 'bigeminy', 'trigeminy', 'interpolated PVC', 'compensatory pause'],
    category: 'premature',
    tier: 1,
    tags: ['wide-qrs', 'irregular', 'automaticity', 'triggered', 'reentry', 'palpitations'],
    preset: 'pvc',
    altPresets: ['pvcBigeminy', 'pvcInterpolated', 'pvcCouplet'],
    definition: 'Premature depolarisation originating in ventricular myocardium or Purkinje fibres, not conducted from the atria.',
    epidemiology: 'Found on Holter monitoring in most adults; frequency rises with age and structural heart disease.',
    mechanism: 'Enhanced automaticity, triggered activity (afterdepolarisations) or re-entry around scar. Common idiopathic sites: RV/LV outflow tracts, fascicles, papillary muscles.',
    ecg: ['Premature, wide (≥ 120 ms), bizarre QRS not preceded by a premature P', 'ST–T opposite in direction to the main QRS deflection (secondary repolarisation change)', 'Usually a FULLY compensatory pause (P–P around the PVC = 2 × sinus cycle)', 'Patterns: bigeminy, trigeminy, couplets; interpolated PVC (no pause) at slow sinus rates', 'Morphology points to origin: LBBB-like + inferior axis → outflow tract (usually RVOT); RBBB-like → LV origin'],
    why: [
      { level: 'cell', text: 'A ventricular focus reaches threshold before the next sinus impulse arrives.' },
      { level: 'conduction', text: 'Activation spreads cell-to-cell through working myocardium (~0.3–1 m/s) instead of the Purkinje network (~2–4 m/s).' },
      { level: 'vector', text: 'Slow, sequential activation from one point: the vector points away from the focus for a long time.' },
      { level: 'waveform', text: 'Wide QRS whose shape depends on where the focus is; repolarisation follows the abnormal sequence → discordant ST–T.' },
      { level: 'conduction', text: 'The sinus node is usually NOT reset (the PVC rarely conducts retrograde to the atria in time); the next sinus P arrives on schedule but finds the AV node/ventricles refractory → it is blocked; the following P conducts → fully compensatory pause.' },
      { level: 'diagnosis', text: 'Premature wide QRS, no preceding P, compensatory pause → PVC.' },
    ],
    differential: [
      { dx: 'pacAberrant', how: 'Aberrant PAC: premature P′ before the QRS, typical RBBB morphology (rSR′), usually non-compensatory pause.' },
      { dx: 'aivr', how: 'Idioventricular beats are not premature (late/escape timing).' },
      { dx: 'wpw', how: 'Intermittent pre-excitation: short PR and delta wave preceded by a normal sinus P.' },
    ],
    acute: ['Usually none; correct K⁺/Mg²⁺, ischaemia, stimulants.'],
    longTerm: ['Evaluate for structural heart disease (echo) when frequent or symptomatic.', 'Symptomatic or high-burden PVCs (burden-related cardiomyopathy): β-blockers/non-DHP CCB, antiarrhythmics, or catheter ablation (particularly outflow-tract PVCs).'],
    refs: ['va2017', 'escVa2022', 'durrer1970'],
  },
  // ======================================================================= ATRIAL
  {
    id: 'focalAT',
    name: 'Focal atrial tachycardia',
    aliases: ['ectopic atrial tachycardia', 'atrial tachycardia', 'long RP tachycardia'],
    category: 'atrial',
    tier: 1,
    tags: ['tachycardia', 'regular', 'narrow-qrs', 'automaticity', 'triggered', 'reentry', 'regular-narrow-tachycardia', 'long-rp', 'adenosine-unmasks'],
    preset: 'focalAT',
    altPresets: ['atWithBlock'],
    definition: 'Regular atrial rhythm at 100–250/min from a single atrial focus other than the sinus node, spreading centrifugally.',
    mechanism: 'Automaticity, triggered activity or micro-re-entry at typical sites (crista terminalis, tricuspid/mitral annuli, pulmonary veins, coronary-sinus ostium). Because the AV node is not part of the mechanism, AV block does NOT terminate it.',
    ecg: ['Distinct P′ waves with non-sinus morphology, usually long RP (P′ closer to the next QRS)', 'Isoelectric baseline between P′ waves (unlike flutter)', 'Warm-up at onset / cool-down at termination (automatic foci)', 'AV block may occur without stopping the tachycardia (e.g. 2:1 with digoxin toxicity)'],
    why: [
      { level: 'cell', text: 'One ectopic atrial site discharges faster than the sinus node and suppresses it.' },
      { level: 'vector', text: 'Atrial activation starts at the focus → the P-wave axis encodes the location (e.g. low RA focus → superiorly directed vector → inverted P in II, III, aVF; left-atrial focus → negative P in I/aVL, positive in V1).' },
      { level: 'conduction', text: 'Each P′ conducts through a normal AV node → narrow QRS; the PR depends on nodal recovery at that rate.' },
      { level: 'waveform', text: 'Because conduction to the ventricles is "normal", the P′ sits before the next QRS → long-RP tachycardia.' },
      { level: 'treatment', text: 'Adenosine produces AV block that unmasks the P′ waves; it also acts on the focus itself, terminating many focal ATs (especially triggered, cAMP-mediated foci) or transiently suppressing automatic ones, whereas macro-re-entrant AT and flutter continue.' },
    ],
    differential: [
      { dx: 'sinusTach', how: 'Sinus P axis, gradual physiological rate changes.' },
      { dx: 'flutter21', how: 'Flutter: continuous undulating baseline, atrial rate ~250–350/min.' },
      { dx: 'mat', how: 'MAT: ≥3 P morphologies, irregular.' },
      { dx: 'orthoAvrt', how: 'Orthodromic AVRT: short RP, retrograde P; AV block terminates it.' },
    ],
    management: {
      recognition: 'Regular narrow-complex tachycardia with non-sinus P′ waves, usually long RP; AV block does not stop it.',
      mechanism: 'Single atrial focus (automatic/triggered/micro-re-entry) independent of the AV node.',
      stability: 'Unstable → synchronised cardioversion (less effective for automatic foci, which may simply restart).',
      immediate: ['Stable: IV β-blocker or diltiazem/verapamil to slow the ventricular rate or terminate (2015 ACC/AHA/HRS: Class I).', 'Adenosine can be useful (2015 ACC/AHA/HRS: Class IIa): it terminates many focal ATs; otherwise the AV block is diagnostic.', 'IV amiodarone or ibutilide may be considered to restore sinus rhythm.', 'If digoxin toxicity is suspected (AT with block): stop digoxin, correct K⁺, consider digoxin-specific antibody fragments.'],
      definitive: ['Catheter ablation is recommended for symptomatic focal AT (Class I) — highly effective.', 'Oral β-blocker or non-DHP CCB; flecainide/propafenone if no structural or ischaemic heart disease.'],
      cautions: ['Incessant focal AT can cause tachycardia-induced cardiomyopathy.'],
      whyWorks: ['β-blockers/CCBs suppress catecholamine- and Ca²⁺-dependent automatic/triggered foci and slow AV conduction.', 'Ablation destroys the focus itself.'],
      whyNot: ['AV-nodal block by itself (e.g. vagal manoeuvres) does not terminate it: the AV node is a bystander — adenosine, β-blockers and CCBs stop it only by acting on the focus itself.', 'Cardioversion cannot prevent an automatic focus from immediately firing again.'],
      refs: ['svt2015', 'escSvt2019'],
    },
    refs: ['svt2015', 'escSvt2019'],
  },
  {
    id: 'mat',
    name: 'Multifocal atrial tachycardia',
    category: 'atrial',
    tier: 1,
    tags: ['tachycardia', 'irregular', 'narrow-qrs', 'automaticity', 'triggered', 'irregular-narrow-tachycardia', 'copd'],
    preset: 'mat',
    definition: 'Irregular atrial rhythm > 100/min with ≥ 3 distinct P-wave morphologies and variable P–P, PR and R–R intervals, with an isoelectric baseline.',
    epidemiology: 'Mostly in acutely ill older patients with pulmonary disease (COPD exacerbation), pulmonary hypertension, hypoxaemia, heart failure, hypomagnesaemia/hypokalaemia, theophylline.',
    mechanism: 'Multiple atrial sites with triggered activity or enhanced automaticity (catecholamines, hypoxia, atrial stretch, electrolyte depletion).',
    ecg: ['≥ 3 different P-wave morphologies', 'Variable PR intervals', 'Irregularly irregular R–R', 'Isoelectric baseline between P waves (unlike AF)', 'Rate > 100/min (100–150 typical)'],
    why: [
      { level: 'cell', text: 'Several atrial foci are simultaneously irritable (hypoxia, catecholamines, stretch, low Mg²⁺/K⁺).' },
      { level: 'vector', text: 'Each focus activates the atria in a different sequence → a different P axis → different P shape.' },
      { level: 'conduction', text: 'Foci fire at varying coupling intervals; the AV node recovers to different degrees → varying PR and irregular ventricular response.' },
      { level: 'diagnosis', text: 'Irregular rhythm WITH distinct P waves of ≥3 shapes → MAT (not AF).' },
      { level: 'treatment', text: 'Not re-entrant, so cardioversion does nothing; treating the underlying illness removes the trigger.' },
    ],
    differential: [
      { dx: 'af', how: 'AF: no discrete P waves.' },
      { dx: 'sinusArrhythmia', how: 'One P morphology.' },
      { dx: 'pac', how: 'Sinus rhythm with frequent multifocal PACs: a dominant sinus P morphology.' },
    ],
    management: {
      recognition: '≥ 3 P morphologies, irregular, rate > 100, isoelectric baseline.',
      mechanism: 'Multiple triggered/automatic atrial foci driven by the underlying illness.',
      stability: 'Rarely the primary cause of instability — the underlying illness usually is.',
      immediate: ['Treat the precipitant: bronchodilation and oxygenation in COPD, heart failure therapy, correct Mg²⁺ and K⁺, review theophylline/β-agonists.', 'IV metoprolol or verapamil can be useful for acute rate control (2015 ACC/AHA/HRS) — β-blockers with caution in bronchospasm.'],
      definitive: ['Oral verapamil/diltiazem or metoprolol for recurrent symptomatic MAT (2015 ACC/AHA/HRS).', 'No role for ablation of multiple foci in typical cases; AV-junction ablation + pacing is rarely considered.'],
      cautions: ['Cardioversion and antiarrhythmics aimed at re-entry are ineffective.', 'Avoid mislabelling as AF and starting anticoagulation on that basis.'],
      whyWorks: ['Correcting hypoxia/electrolytes removes the triggers; non-DHP CCBs and β-blockers suppress triggered/automatic foci and slow AV conduction.'],
      whyNot: ['DC cardioversion terminates re-entry, but MAT has no circuit to interrupt.'],
      refs: ['svt2015'],
    },
    refs: ['svt2015'],
  },
  {
    id: 'flutter',
    name: 'Atrial flutter',
    aliases: ['typical flutter', 'CTI-dependent flutter', '2:1 flutter', 'sawtooth'],
    category: 'atrial',
    tier: 1,
    tags: ['tachycardia', 'regular', 'narrow-qrs', 'reentry', 'sawtooth', 'regular-narrow-tachycardia', 'adenosine-unmasks', 'cardioversion', 'anticoagulation', 'ablation'],
    preset: 'flutter21',
    altPresets: ['flutter41', 'flutterVariable'],
    definition: 'Macro-re-entrant atrial tachycardia with an atrial rate typically 250–350/min. Typical flutter circulates around the tricuspid annulus using the cavotricuspid isthmus (CTI).',
    epidemiology: 'Often coexists with AF; associated with structural heart disease, lung disease, post-cardiac surgery, alcohol, older age.',
    mechanism: 'A single large re-entrant circuit in the right atrium: in counter-clockwise (typical) flutter the wavefront ascends the interatrial septum and descends the lateral RA wall, then passes through the slowly conducting CTI. The circuit is so large that there is always excitable tissue ahead of the wavefront, so the cycle length is stable (~200 ms).',
    ecg: ['Flutter (F) waves at ~300/min without an isoelectric baseline — "sawtooth"', 'Typical CCW: negative F waves in II, III, aVF, positive in V1', 'Ventricular rate = atrial rate ÷ conduction ratio: 2:1 → ~150/min (very common), 4:1 → ~75/min; variable block → irregular', 'Narrow QRS unless bundle-branch block or aberrancy'],
    why: [
      { level: 'conduction', text: 'One wavefront circulates the tricuspid annulus every ~200 ms → the atria are ALWAYS being activated somewhere → no flat baseline.' },
      { level: 'vector', text: 'In CCW flutter the septum is activated from bottom to top for most of the cycle → a superiorly directed vector.' },
      { level: 'lead', text: 'Inferior leads (II, III, aVF) point downward → they see the long superior-directed limb as a slow negative ramp followed by a sharp rise.' },
      { level: 'waveform', text: 'Negative sawtooth waves in II/III/aVF; V1 sees the anterior limb → positive F waves.' },
      { level: 'conduction', text: 'The AV node cannot conduct 300/min: its refractory period filters every 2nd (2:1), 3rd or 4th wave. Longer nodal refractoriness (drugs, vagal tone) → higher ratio → slower ventricular rate.' },
      { level: 'diagnosis', text: 'A regular ventricular rate "stuck" near 150/min should always prompt a search for 2:1 flutter.' },
      { level: 'treatment', text: 'Adenosine increases AV block and unmasks F waves — but does not stop the atrial circuit. Ablating the CTI (a critical isthmus of the circuit) cures typical flutter.' },
    ],
    differential: [
      { dx: 'sinusTach', how: 'Rate varies with physiology, discrete P waves with flat baseline.' },
      { dx: 'avnrt', how: 'AVNRT has no F waves; adenosine terminates it rather than unmasking flutter waves.' },
      { dx: 'focalAT', how: 'Isoelectric baseline between P′ waves; atrial rate usually < 250.' },
      { dx: 'af', how: 'Coarse AF can look flutter-like but f waves vary in shape and timing; R–R irregularly irregular.' },
    ],
    management: {
      recognition: 'Sawtooth F waves (~300/min), negative in inferior leads (typical), fixed or variable AV conduction.',
      mechanism: 'Macro-re-entry around the tricuspid annulus through the CTI; ventricular rate set by AV-nodal filtering.',
      stability: 'Unstable (hypotension, shock, ischaemia, acute HF) → synchronised cardioversion.',
      immediate: ['Synchronised cardioversion for unstable patients (flutter often converts with low energies; the 2025 AHA tachycardia algorithm lists 200 J as the initial biphasic energy for both AF and flutter).', 'Rate control: IV β-blocker or diltiazem/verapamil (avoid non-DHP CCB with reduced LVEF).', 'Rhythm control: cardioversion, rapid atrial pacing (with pacing wires), or ibutilide/dofetilide.', 'Anticoagulation follows the same risk-based rules as AF (2023 ACC/AHA/ACCP/HRS: Class I).'],
      definitive: ['CTI catheter ablation is recommended for symptomatic/recurrent typical flutter (Class I; high success).', 'Long-term anticoagulation per CHA₂DS₂-VASc as for AF.'],
      cautions: ['Class IC drugs (flecainide/propafenone) can slow the flutter cycle enough to allow 1:1 AV conduction with a very fast, wide-QRS rhythm — co-prescribe an AV-nodal blocker.', 'Do not electively cardiovert AF/flutter lasting ≥ 48 h (US; ESC 2024 uses > 24 h) or of unknown duration without ≥3 weeks of anticoagulation or TEE exclusion of thrombus, then ≥4 weeks after.'],
      whyWorks: ['Cardioversion depolarises all tissue in the circuit at once → no excitable gap → re-entry stops.', 'AV-nodal blockers lengthen nodal refractoriness → more flutter waves blocked → slower ventricular rate.', 'Ablation creates a line of block across the CTI → the circuit cannot close.'],
      whyNot: ['Adenosine/vagal manoeuvres block the AV node, which is outside the circuit — the flutter continues.'],
      refs: ['svt2015', 'af2023', 'acls2025'],
    },
    refs: ['svt2015', 'escSvt2019', 'af2023', 'acls2025'],
  },
  {
    id: 'af',
    name: 'Atrial fibrillation',
    aliases: ['AF', 'AFib', 'irregularly irregular', 'rapid ventricular response', 'RVR'],
    category: 'atrial',
    tier: 1,
    tags: ['irregular', 'narrow-qrs', 'tachycardia', 'p-absent', 'reentry', 'irregular-narrow-tachycardia', 'anticoagulation', 'cardioversion', 'ablation', 'beta-blocker', 'ccb', 'digoxin', 'adenosine-unmasks'],
    preset: 'af',
    altPresets: ['afRvr'],
    definition: 'Supraventricular tachyarrhythmia with uncoordinated atrial activation and consequently ineffective atrial contraction; ECG shows irregular R–R intervals, no distinct repeating P waves, and irregular atrial activity.',
    epidemiology: 'The most common sustained arrhythmia; prevalence rises steeply with age. Risk factors: hypertension, obesity, diabetes, sleep apnoea, alcohol, heart failure, valvular disease, genetics.',
    mechanism: 'Triggers (often pulmonary-vein ectopy) initiate AF; a substrate of atrial fibrosis, dilatation and shortened refractoriness sustains multiple wandering wavelets/rotors. "AF begets AF": electrical remodelling shortens atrial refractory periods further.',
    ecg: ['No organised P waves; fibrillatory (f) waves (fine or coarse), best seen in V1', 'Irregularly irregular R–R intervals', 'Ventricular rate depends on AV-nodal conduction (untreated often 110–160/min)', 'QRS narrow unless aberrancy, bundle-branch block or pre-excitation'],
    why: [
      { level: 'cell', text: 'Short, heterogeneous atrial refractory periods let many small wavefronts re-excite tissue as soon as it recovers.' },
      { level: 'conduction', text: 'No single wavefront activates the atria as a whole → no coherent atrial vector → no P wave, only small chaotic f waves.' },
      { level: 'conduction', text: 'The AV node is bombarded 350–600 times/min. Its refractory period blocks most impulses, and blocked impulses that partially penetrate (concealed conduction) reset its recovery unpredictably.' },
      { level: 'waveform', text: 'Result: irregularly irregular QRS timing with narrow complexes (normal His–Purkinje activation).' },
      { level: 'clinical', text: 'Loss of atrial contraction and stasis in the left atrial appendage → thromboembolism (stroke); fast/irregular rates → heart failure.' },
      { level: 'treatment', text: 'Rate control targets the AV node (the filter). Rhythm control targets the atria (the source). Anticoagulation targets the clot, not the rhythm.' },
    ],
    differential: [
      { dx: 'mat', how: 'Discrete P waves of ≥ 3 morphologies.' },
      { dx: 'flutterVariable', how: 'Flutter with variable block: organised identical F waves at a constant rate.' },
      { dx: 'sinusArrhythmia', how: 'Identical P waves before each QRS.' },
      { dx: 'preexAf', how: 'Wide, bizarre, varying QRS at very fast rates (> 200/min) → pre-excited AF.' },
    ],
    management: {
      recognition: 'Irregularly irregular narrow QRS without discrete P waves.',
      mechanism: 'Chaotic atrial re-entry filtered by the AV node.',
      stability: 'Unstable (hypotension, shock, ischaemia, acute HF attributable to the rate) → immediate synchronised cardioversion (2025 AHA ALS: initial 200 J biphasic).',
      immediate: ['Rate control: IV/oral β-blocker or non-dihydropyridine CCB (diltiazem, verapamil); avoid non-DHP CCB in LVEF < 40%; digoxin/amiodarone as adjuncts (e.g. in hypotension/HF).', 'Rhythm control (cardioversion, antiarrhythmics) based on symptoms, duration and anticoagulation status.', 'Before elective cardioversion of AF ≥ 48 h (US; ESC 2024 uses > 24 h) or of unknown duration: ≥ 3 weeks of therapeutic anticoagulation or TEE excluding thrombus; continue ≥ 4 weeks after.', 'Treat triggers: sepsis, thyrotoxicosis, alcohol, electrolytes, PE.'],
      definitive: ['Stroke prevention: oral anticoagulation when annual stroke risk ≥ 2% (e.g. CHA₂DS₂-VASc ≥ 2 in men or ≥ 3 in women) — Class I in the 2023 ACC/AHA/ACCP/HRS guideline; reasonable at 1–<2%. The 2024 ESC guideline uses the sex-neutral CHA₂DS₂-VA: OAC recommended at ≥ 2, should be considered at 1. DOACs preferred over warfarin except with mechanical valves or moderate–severe mitral stenosis.', 'Early rhythm control is reasonable; catheter ablation is first-line in selected symptomatic patients and recommended in suitable patients with HFrEF.', 'Risk-factor modification (weight loss, exercise, alcohol reduction, BP, sleep apnoea) is recommended.', 'Left atrial appendage occlusion is an option when long-term anticoagulation is contraindicated.'],
      cautions: ['If AF is pre-excited (wide, bizarre, very fast), AV-nodal blockers are potentially harmful — see pre-excited AF.', 'Digoxin alone controls the resting rate but performs poorly during exertion/sympathetic states.'],
      whyWorks: ['β-blockers and non-DHP CCBs lengthen AV-nodal refractoriness and slow conduction (Ca²⁺-dependent nodal tissue) → fewer f waves conducted.', 'Cardioversion simultaneously depolarises the atria, extinguishing all wavelets.', 'Ablation (pulmonary-vein isolation) electrically isolates pulmonary-vein triggers from the atria.', 'Anticoagulation prevents thrombus formation in the stagnant appendage — independent of rhythm.'],
      whyNot: ['Adenosine only transiently blocks the AV node — it unmasks f waves but does not treat AF (and may precipitate AF by shortening atrial refractoriness).', 'Rate or rhythm control does not remove the need for anticoagulation.'],
      refs: ['af2023', 'escAf2024', 'ccsAf2020', 'acls2025'],
    },
    refs: ['af2023', 'escAf2024', 'ccsAf2020', 'acls2025'],
  },
  // ======================================================================= JUNCTIONAL
  {
    id: 'junctionalEscape',
    name: 'Junctional escape rhythm',
    category: 'junctional',
    tier: 1,
    tags: ['bradycardia', 'regular', 'narrow-qrs', 'p-retrograde', 'p-absent', 'automaticity', 'escape'],
    preset: 'junctionalEscape',
    definition: 'A regular rhythm at 40–60/min originating in the AV junction, appearing when faster pacemakers fail or impulses are blocked.',
    mechanism: 'The AV junction (nodal–His region) has slower phase-4 automaticity than the sinus node. It is normally reset (overdrive-suppressed) by every conducted beat; when none arrives within its cycle, it fires — a protective escape mechanism.',
    ecg: ['Narrow QRS (unless pre-existing BBB)', 'Rate 40–60/min', 'P waves absent, or retrograde (inverted in II, III, aVF) just before (short PR < 120 ms), within, or after the QRS'],
    why: [
      { level: 'cell', text: 'Junctional pacemaker cells depolarise spontaneously but more slowly than the sinus node.' },
      { level: 'conduction', text: 'The junctional impulse travels DOWN the His bundle and both bundle branches — the normal ventricular pathway.' },
      { level: 'waveform', text: 'So the QRS is narrow and looks like the patient’s normal QRS.' },
      { level: 'conduction', text: 'It may also travel UP through the AV node into the atria from below → atrial activation from the septum upward.' },
      { level: 'vector', text: 'Upward (superior) atrial vector → inverted P waves in II, III, aVF; its timing (before/in/after QRS) depends on relative antegrade vs retrograde conduction times.' },
      { level: 'clinical', text: 'The escape is a symptom of a higher-level failure (sinus arrest, AV block) — look for the cause.' },
    ],
    differential: [
      { dx: 'ventEscape', how: 'Ventricular escape: wide QRS, rate 20–40/min.' },
      { dx: 'sinusBrady', how: 'Sinus P waves with normal PR.' },
      { dx: 'chbJunctional', how: 'In complete heart block with junctional escape, sinus P waves march through independently.' },
    ],
    acute: ['Treat as bradycardia if symptomatic; address the cause (sinus-node dysfunction, drugs, AV block).'],
    refs: ['brady2018'],
  },
  {
    id: 'accelJunctional',
    name: 'Accelerated junctional rhythm / junctional tachycardia',
    aliases: ['junctional tachycardia', 'JET', 'nonparoxysmal junctional tachycardia', 'isorhythmic dissociation'],
    category: 'junctional',
    tier: 2,
    tags: ['narrow-qrs', 'regular', 'automaticity', 'p-retrograde', 'av-dissociation', 'digoxin'],
    preset: 'accelJunctional',
    altPresets: ['junctionalTach'],
    definition: 'Junctional rhythm faster than the intrinsic escape rate: 60–100/min (accelerated) or > 100/min (junctional tachycardia).',
    epidemiology: 'Digoxin toxicity, post-cardiac surgery (especially in children), inferior MI/ischaemia, myocarditis, catecholamines, during slow-pathway ablation (a marker of effective heating).',
    mechanism: 'Enhanced automaticity (or triggered activity) of junctional cells that overtakes the sinus node. Often competes with sinus → isorhythmic AV dissociation.',
    ecg: ['Narrow QRS at 60–100 (or > 100)/min', 'Retrograde P waves or AV dissociation with sinus P waves drifting in and out of the QRS', 'Gradual onset (warm-up)'],
    why: [
      { level: 'cell', text: 'Junctional phase-4 slope becomes steeper than the sinus node’s.' },
      { level: 'conduction', text: 'Whichever pacemaker is faster captures the ventricles through the normal His–Purkinje system → narrow QRS either way.' },
      { level: 'waveform', text: 'When rates are similar, sinus P waves appear to "walk" into the QRS — isorhythmic dissociation.' },
    ],
    differential: [{ dx: 'avnrt', how: 'AVNRT: abrupt onset/termination, faster (usually 140–250), terminated by adenosine.' }, { dx: 'junctionalEscape', how: 'Escape rate 40–60.' }],
    acute: ['Treat the cause (check digoxin level, K⁺, ischaemia).', 'β-blockers are reasonable for symptomatic junctional tachycardia (2015 ACC/AHA/HRS).'],
    refs: ['svt2015'],
  },
];
