import type { Dx } from './types';

// AV-nodal re-entry, accessory-pathway re-entry, pre-excitation.

export const REENTRY_DX: Dx[] = [
  {
    id: 'avnrt',
    name: 'AV nodal re-entrant tachycardia (AVNRT)',
    aliases: ['AVNRT', 'SVT', 'PSVT', 'paroxysmal supraventricular tachycardia', 'dual AV nodal physiology', 'slow-fast', 'pseudo r prime'],
    category: 'reentrant',
    tier: 1,
    tags: ['tachycardia', 'regular', 'narrow-qrs', 'reentry', 'av-node', 'regular-narrow-tachycardia', 'short-rp', 'p-retrograde', 'adenosine', 'adenosine-terminates', 'vagal', 'ablation', 'palpitations'],
    preset: 'avnrt',
    definition: 'Re-entrant tachycardia whose circuit lies within the AV node and perinodal atrial tissue, using two functionally distinct pathways: a FAST pathway (fast conduction, long refractory period) and a SLOW pathway (slow conduction, short refractory period).',
    epidemiology: 'The most common regular paroxysmal SVT in adults, more frequent in women; often presents in young adults with abrupt-onset palpitations, neck pounding ("frog sign") and polyuria.',
    mechanism: 'In sinus rhythm impulses travel down the fast pathway. A premature atrial beat that arrives while the fast pathway is still refractory (its refractory period is LONGER) but the slow pathway has recovered is forced down the slow pathway. The slow conduction gives the fast pathway time to recover, so the impulse returns retrogradely up the fast pathway (an "echo") and can re-enter the slow pathway again — a sustained circuit (typical slow–fast AVNRT).',
    ecg: ['Regular narrow-complex tachycardia, typically 140–250/min, abrupt onset and termination', 'Initiating PAC with a sudden PR prolongation ("jump" to the slow pathway)', 'Retrograde P waves buried in the QRS or just after it (RP very short, < 70–90 ms)', 'Pseudo-r′ in V1 and pseudo-S waves in II, III, aVF (the retrograde P distorting the end of the QRS)', 'QRS narrow unless aberrancy/pre-existing BBB'],
    why: [
      { level: 'cell', text: 'The two nodal inputs have different ion-channel properties: the fast pathway recovers slowly (long ERP); the slow pathway conducts slowly but recovers quickly (short ERP).' },
      { level: 'conduction', text: 'A premature beat finds the fast pathway refractory → it travels down the slow pathway (long PR "jump").' },
      { level: 'conduction', text: 'By the time it reaches the bottom, the fast pathway has recovered → it returns up the fast pathway → re-enters the slow pathway → circuit (atrium → slow pathway → fast pathway → re-entry → rapid ventricular activation).' },
      { level: 'conduction', text: 'Each turn sends one impulse DOWN the His bundle (ventricles) and one UP into the atria almost simultaneously.' },
      { level: 'vector', text: 'Atria are activated retrogradely from the septum upward → superior atrial vector.' },
      { level: 'lead', text: 'Inferior leads see the atrial wave moving away (negative P); V1 sees it moving toward it (positive).' },
      { level: 'waveform', text: 'Because atria and ventricles are activated almost at the same time, the retrograde P hides in or just after the QRS: pseudo-S in II/III/aVF, pseudo-r′ in V1, very short RP.' },
      { level: 'diagnosis', text: 'Abrupt regular narrow tachycardia with no visible P or a short-RP retrograde P → AVNRT (vs AVRT, whose P is later because the impulse must travel through the ventricles and the pathway).' },
      { level: 'treatment', text: 'The AV node IS the circuit. Anything that transiently blocks the node (vagal manoeuvre, adenosine) breaks the loop.' },
    ],
    differential: [
      { dx: 'orthoAvrt', how: 'AVRT: retrograde P separated from the QRS (RP ≥ 70 ms) because the circuit includes ventricular myocardium and the pathway; may alternate QRS amplitude; pre-excitation in sinus rhythm if manifest.' },
      { dx: 'focalAT', how: 'Long RP; AV block during tachycardia does not stop it.' },
      { dx: 'flutter', how: '2:1 flutter at ~150: F waves unmasked by adenosine rather than termination.' },
      { dx: 'sinusTach', how: 'Gradual onset, sinus P waves before each QRS.' },
      { dx: 'accelJunctional', how: 'Junctional tachycardia can look identical but is automatic (not terminated reliably by adenosine) and may show AV dissociation.' },
    ],
    management: {
      recognition: 'Abrupt regular narrow-complex tachycardia, no visible P or short-RP retrograde P (pseudo-r′ V1, pseudo-S inferior).',
      mechanism: 'Re-entry within the AV node using fast and slow pathways.',
      stability: 'Most patients are stable. Hypotension, altered mental status, ischaemic chest pain or acute HF → synchronised cardioversion (adenosine may be tried first if immediately available and the rhythm is regular narrow).',
      immediate: ['Vagal manoeuvres (e.g. modified Valsalva with supine leg raise) — Class I.', 'Adenosine 6 mg rapid IV push with saline flush, then 12 mg if needed (2025 AHA algorithm) — Class I.', 'If ineffective: IV diltiazem or verapamil (stable, no HFrEF) or IV β-blocker.', 'Synchronised cardioversion if unstable or drugs fail.'],
      definitive: ['Catheter ablation of the slow pathway — Class I; high success, low risk of AV block.', 'Oral β-blocker, diltiazem or verapamil if ablation not desired; flecainide/propafenone if no structural/ischaemic heart disease; "pill-in-the-pocket" for infrequent episodes.'],
      cautions: ['Warn patients about transient chest discomfort/flushing/sense of doom with adenosine; record a rhythm strip during administration (the response is diagnostic).', 'Adenosine is less effective with methylxanthines (theophylline, caffeine) and more potent with dipyridamole or in transplanted hearts (use reduced dose).'],
      whyWorks: ['Adenosine (A1 receptors → IK,Ado) hyperpolarises AV-nodal cells and blocks conduction for seconds — long enough to extinguish the circuit, which cannot survive a single blocked limb.', 'Vagal tone does the same via acetylcholine (same potassium channel).', 'Slow-pathway ablation removes one limb of the circuit permanently.'],
      whyNot: ['Antiarrhythmics aimed at atrial or ventricular myocardium are unnecessary — the circuit is nodal.', 'Rate-control thinking is wrong here: the goal is termination, not slowing.'],
      refs: ['svt2015', 'escSvt2019', 'acls2025'],
    },
    refs: ['svt2015', 'escSvt2019', 'acls2025'],
  },
  {
    id: 'orthoAvrt',
    name: 'Atrioventricular re-entrant tachycardia (AVRT)',
    aliases: ['AVRT', 'orthodromic AVRT', 'antidromic AVRT', 'concealed accessory pathway', 'reciprocating tachycardia', 'SVT'],
    category: 'reentrant',
    tier: 1,
    tags: ['tachycardia', 'regular', 'narrow-qrs', 'reentry', 'accessory-pathway', 'regular-narrow-tachycardia', 'p-retrograde', 'adenosine', 'adenosine-terminates', 'ablation', 'palpitations'],
    preset: 'orthoAvrt',
    altPresets: ['concealedAvrt', 'antiAvrt'],
    definition: 'Macro-re-entrant tachycardia using the AV node–His–Purkinje system as one limb and an accessory pathway (AP) as the other. ORTHODROMIC (~90–95%): down the AV node, up the AP → narrow QRS. ANTIDROMIC: down the AP, up the AV node → fully pre-excited wide QRS.',
    epidemiology: 'Second most common regular paroxysmal SVT; more often in younger patients. The AP may be MANIFEST (conducts antegrade → pre-excitation/WPW pattern in sinus rhythm) or CONCEALED (retrograde-only → normal ECG in sinus rhythm).',
    mechanism: 'Accessory pathways are strands of working myocardium bridging the AV groove. They conduct fast and non-decrementally but usually have a longer refractory period than the AV node at physiological rates. A premature beat blocked in the AP but conducted through the AV node reaches the ventricles, then finds the recovered AP and returns to the atria → circuit: atrium → AV node → His–Purkinje → ventricle → accessory pathway → atrium.',
    ecg: ['Orthodromic: regular narrow-complex tachycardia 150–250/min', 'Retrograde P′ after the QRS in the ST segment, RP typically ≥ 70 ms (RP < PR)', 'P′ axis depends on AP location (e.g. left lateral AP → negative P′ in I/aVL)', 'QRS alternans and rate-related BBB are common; BBB ipsilateral to the AP slows the tachycardia', 'Antidromic: regular WIDE-complex tachycardia (maximally pre-excited) — indistinguishable from VT on morphology alone', 'Sinus rhythm: pre-excitation if the AP is manifest; normal if concealed'],
    why: [
      { level: 'conduction', text: 'Orthodromic: the impulse reaches the ventricles through the normal AV node and His–Purkinje system.' },
      { level: 'waveform', text: '→ normal, synchronised ventricular activation → NARROW QRS (unless aberrancy).' },
      { level: 'conduction', text: 'The atria can only be re-activated after the impulse has crossed the ventricle to the AP and back up — a longer journey than in AVNRT.' },
      { level: 'waveform', text: '→ the retrograde P′ is clearly separated from the QRS (RP ≥ ~70 ms), usually in the ST segment.' },
      { level: 'vector', text: 'Atrial activation starts at the AP’s atrial insertion: a left lateral AP activates the LA first → atrial vector points rightward → negative P′ in lead I.' },
      { level: 'conduction', text: 'Antidromic: the ventricles are activated entirely through the AP, cell-to-cell from the AV groove → maximal pre-excitation → WIDE QRS.' },
      { level: 'treatment', text: 'Both forms need the AV node as one limb → transient AV-nodal block (vagal, adenosine) can terminate the circuit; ablation of the AP cures it.' },
    ],
    differential: [
      { dx: 'avnrt', how: 'AVNRT: P′ hidden in or immediately after QRS (RP < 70 ms), pseudo-r′ V1.' },
      { dx: 'focalAT', how: 'Long RP, AV block does not terminate the tachycardia.' },
      { dx: 'monoVT', how: 'Antidromic AVRT vs VT: history of pre-excitation, young patient; in doubt, treat as VT.' },
    ],
    management: {
      recognition: 'Regular narrow (orthodromic) or wide (antidromic) tachycardia; retrograde P′ with RP ≥ 70 ms; pre-excitation in sinus rhythm if the AP is manifest.',
      mechanism: 'Macro-re-entry through AV node and accessory pathway.',
      stability: 'Unstable → synchronised cardioversion.',
      immediate: ['Orthodromic AVRT: vagal manoeuvres and adenosine are recommended (Class I).', 'Stable, refractory: IV diltiazem, verapamil or β-blockers are reasonable for orthodromic AVRT WITHOUT pre-excitation on the resting ECG.', 'If pre-excitation is present or suspected: be prepared — adenosine may precipitate AF, which can conduct rapidly over the pathway (have a defibrillator available).', 'Antidromic AVRT / uncertain wide-complex tachycardia: procainamide or ibutilide, or synchronised cardioversion; treat as VT if in doubt.'],
      definitive: ['Catheter ablation of the accessory pathway is recommended for symptomatic AVRT (Class I).', 'Alternatives: β-blockers/non-DHP CCB for orthodromic AVRT without pre-excitation; flecainide/propafenone if no structural heart disease.'],
      cautions: ['Never use AV-nodal blockers for pre-excited AF (see pre-excited AF).', 'Wide-complex regular tachycardia in a patient with WPW could be antidromic AVRT, VT, or SVT with aberrancy — cardioversion is always a safe choice.'],
      whyWorks: ['Adenosine blocks the AV-nodal limb → circuit broken (the AP itself is usually adenosine-insensitive, which is why the node is the target).', 'Ablation removes the other limb permanently.'],
      whyNot: ['Drugs that act only on the atria do not address the circuit.', 'Adenosine does not stop antidromic AVRT if a second AP forms the retrograde limb (AP–AP tachycardia).'],
      refs: ['svt2015', 'escSvt2019', 'acls2025'],
    },
    refs: ['svt2015', 'escSvt2019'],
  },
  {
    id: 'wpw',
    name: 'Ventricular pre-excitation (WPW pattern / syndrome)',
    aliases: ['WPW', 'Wolff-Parkinson-White', 'delta wave', 'short PR', 'pre-excitation', 'accessory pathway'],
    category: 'reentrant',
    tier: 1,
    tags: ['short-pr', 'delta-wave', 'wide-qrs', 'accessory-pathway', 'ablation', 'syncope', 'palpitations'],
    preset: 'wpw',
    definition: 'Pre-excitation: part of the ventricle is activated early through an accessory pathway that bypasses the AV node. WPW PATTERN = the ECG finding; WPW SYNDROME = pre-excitation plus symptomatic tachyarrhythmia.',
    epidemiology: 'Pre-excitation is found in roughly 1–3 per 1000 ECGs; the risk of sudden death (from pre-excited AF degenerating to VF) is low but real — highest with short pathway refractory periods and multiple pathways.',
    mechanism: 'The AP conducts without the AV node’s built-in delay, so ventricular myocardium near its insertion is activated early and slowly (muscle-to-muscle). The rest is activated normally once the impulse arrives through the His–Purkinje system → a FUSION complex.',
    ecg: ['Short PR (< 120 ms)', 'Delta wave: slurred initial QRS upstroke', 'Wide QRS (> 110–120 ms) with normal PJ interval (QRS begins early, ends on time)', 'Secondary ST–T changes opposite to the delta wave', 'Delta-wave polarity localises the pathway (e.g. positive in V1 → left-sided AP; negative in II/III/aVF → posteroseptal)', 'Degree of pre-excitation varies with AV-nodal conduction speed and pathway location (left lateral APs, far from the sinus node, often show subtle pre-excitation)'],
    why: [
      { level: 'conduction', text: 'Normal: AV node delays the impulse (~70–100 ms) → PR 120–200 ms.' },
      { level: 'conduction', text: 'Pre-excitation: the AP conducts with almost no delay → ventricular activation starts earlier → short PR.' },
      { level: 'cell', text: 'The pre-excited region is activated cell-to-cell through working myocardium (slow) rather than the Purkinje network.' },
      { level: 'waveform', text: 'Slow initial activation → slurred, low-slope start of the QRS = delta wave.' },
      { level: 'vector', text: 'The delta-wave vector points away from the AP insertion (e.g. left lateral AP → rightward/anterior delta → negative in I/aVL, positive in V1).' },
      { level: 'waveform', text: 'The rest of the ventricle is activated normally via His–Purkinje → the complex is a fusion of both; it widens at the start, not the end.' },
      { level: 'waveform', text: 'Repolarisation follows the altered activation → secondary ST–T changes.' },
      { level: 'clinical', text: 'Danger: in AF the AP (no decremental filter) can conduct very fast → VF.' },
    ],
    differential: [
      { dx: 'lbbb', how: 'Normal PR; widening affects the whole QRS; no delta wave.' },
      { dx: 'stemiPosterior', how: 'Tall R in V1 from a left-sided AP can mimic posterior MI (look for short PR and delta wave).' },
      { dx: 'oldInferior', how: 'Negative delta waves in inferior leads (posteroseptal AP) mimic inferior Q waves.' },
      { dx: 'lvh', how: 'Pre-excitation increases QRS voltage — voltage criteria for LVH are not valid.' },
    ],
    management: {
      recognition: 'Short PR, delta wave, wide QRS with secondary ST–T changes.',
      mechanism: 'Antegrade conduction over an accessory pathway producing ventricular fusion.',
      stability: 'In sinus rhythm the pattern itself is harmless; danger arises with AF (pre-excited AF) or AVRT.',
      immediate: ['No acute therapy for the pattern alone.', 'Tachycardia: see AVRT and pre-excited AF.'],
      definitive: ['Symptomatic WPW syndrome: catheter ablation of the AP is recommended (Class I).', 'Asymptomatic pre-excitation: risk stratification (exercise test for abrupt loss of pre-excitation, EP study) is reasonable; ablation reasonable if high-risk properties (e.g. short pathway refractory period, SPERRI ≤ 250 ms) or in certain occupations.'],
      cautions: ['Avoid AV-nodal blockers in pre-excited AF.', 'Intermittent pre-excitation (beat-to-beat) suggests a pathway with a long refractory period (lower risk).'],
      whyWorks: ['Ablation eliminates the pathway → no bypass → normal PR, no delta wave, no substrate for AVRT or pre-excited AF.'],
      whyNot: ['AV-nodal drugs do not affect the AP and may increase conduction over it during AF.'],
      refs: ['svt2015', 'wpw2012', 'escSvt2019'],
    },
    refs: ['svt2015', 'wpw2012', 'arruda1998', 'escSvt2019'],
  },
  {
    id: 'preexAf',
    name: 'Pre-excited atrial fibrillation',
    aliases: ['AF with WPW', 'pre-excited AF', 'FBI tachycardia'],
    category: 'reentrant',
    tier: 2,
    tags: ['tachycardia', 'irregular', 'wide-qrs', 'accessory-pathway', 'irregular-wide-tachycardia', 'adenosine-harm', 'procainamide', 'cardioversion', 'syncope'],
    preset: 'preexAf',
    definition: 'Atrial fibrillation in a patient with an antegradely conducting accessory pathway, so that fibrillatory impulses reach the ventricles over the pathway as well as (or instead of) the AV node.',
    epidemiology: 'Uncommon but potentially lethal: very rapid ventricular rates can degenerate into VF; the most common mechanism of sudden death in WPW.',
    mechanism: 'The AV node protects the ventricles in ordinary AF through decremental conduction and a relatively long refractory period. An AP conducts non-decrementally; its refractory period — sometimes < 250 ms — becomes the only limit on the ventricular rate. The QRS varies because each beat is a different fusion between AP and AV-nodal activation.',
    ecg: ['Irregularly irregular (AF) and very fast (often > 200/min; shortest R–R may be < 250 ms)', 'Wide QRS complexes of VARYING width and morphology (different degrees of fusion)', 'Occasional narrow beats (conducted via the AV node)', 'No P waves'],
    why: [
      { level: 'conduction', text: 'Ordinary AF: 400–600 impulses/min reach the AV node; decremental conduction and concealed conduction filter them.' },
      { level: 'conduction', text: 'Pre-excited AF: the same impulses also reach the AP, which conducts in an all-or-none, non-decremental way — only its refractory period limits how often it fires.' },
      { level: 'waveform', text: 'Ventricles activated mostly via the AP → wide, bizarre QRS (maximal pre-excitation); the degree of fusion with AV-nodal beats changes beat to beat → varying QRS width.' },
      { level: 'clinical', text: 'Short R–R intervals can land on the vulnerable period → VF.' },
      { level: 'treatment', text: 'Blocking the AV node removes the competing (protective) route and its retrograde concealed invasion of the AP → MORE impulses may conduct over the pathway, faster and wider. Vasodilating/negative inotropic blockers can also drop blood pressure and raise sympathetic tone.' },
    ],
    differential: [
      { dx: 'af', how: 'AF with bundle-branch block/aberrancy: QRS morphology constant (typical RBBB/LBBB), rates usually < 200/min.' },
      { dx: 'polyVT', how: 'Polymorphic VT: usually faster, with continuously changing axis; clinical context (ischaemia, long QT).' },
      { dx: 'monoVT', how: 'VT is regular (or nearly) with identical complexes.' },
    ],
    management: {
      recognition: 'Irregularly irregular, very fast (> 200/min), wide QRS with beat-to-beat varying morphology.',
      mechanism: 'AF conducting through a non-decremental accessory pathway.',
      stability: 'Unstable → immediate synchronised cardioversion (Class I).',
      immediate: ['Unstable: synchronised cardioversion.', 'Stable: IV procainamide or ibutilide to slow pathway conduction/restore sinus rhythm (Class I, 2015 SVT and 2023 AF guidelines); cardioversion is also appropriate.', 'Avoid AV-nodal–blocking agents: IV adenosine, digoxin, β-blockers, diltiazem, verapamil — and IV amiodarone — are listed as potentially harmful (Class III: Harm).'],
      definitive: ['Catheter ablation of the accessory pathway (Class I) — the pathway is by definition high-risk.'],
      cautions: ['This is one of the few settings where "AF → give diltiazem/β-blocker" is wrong and dangerous.', 'Irregular wide-complex tachycardia in a young patient: think pre-excited AF.'],
      whyWorks: ['Procainamide and ibutilide prolong refractoriness of the accessory pathway (and atrial tissue) → fewer impulses conducted, possible conversion.', 'Cardioversion terminates AF itself.'],
      whyNot: ['AV-nodal blockers act on the node, not the pathway; by removing the node’s competition they can accelerate pathway conduction and precipitate VF.'],
      refs: ['svt2015', 'af2023', 'acls2025'],
    },
    refs: ['svt2015', 'af2023', 'escAf2024', 'wpw2012'],
  },
];
