import type { Dx } from './types';

// Ventricular rhythms and cardiac-arrest rhythms.

export const VENTRICULAR_DX: Dx[] = [
  {
    id: 'ventEscape',
    name: 'Ventricular escape (idioventricular) rhythm',
    aliases: ['idioventricular rhythm', 'ventricular escape'],
    category: 'ventricular',
    tier: 1,
    tags: ['bradycardia', 'wide-qrs', 'regular', 'automaticity', 'escape', 'pacing'],
    preset: 'ventEscape',
    definition: 'A regular wide-complex rhythm at 20–40/min from a ventricular (Purkinje/myocardial) pacemaker, appearing when all higher pacemakers fail or cannot reach the ventricles.',
    mechanism: 'Purkinje fibres have the slowest intrinsic automaticity in the pacemaker hierarchy (SA 60–100 > junction 40–60 > ventricle 20–40). They are normally reset by every conducted beat; they "escape" only when nothing arrives.',
    ecg: ['Wide QRS (≥ 120 ms), bizarre, with discordant ST–T', 'Rate 20–40/min', 'P waves absent or dissociated (e.g. complete heart block)'],
    why: [
      { level: 'cell', text: 'Ventricular pacemaker cells depolarise very slowly during phase 4 → low rate.' },
      { level: 'conduction', text: 'The impulse starts in the ventricle and spreads cell-to-cell, not via the rapid His–Purkinje network.' },
      { level: 'waveform', text: 'Slow sequential activation → wide QRS; morphology depends on the focus location.' },
      { level: 'clinical', text: 'Unreliable and slow: often haemodynamically inadequate and can stop — prepare for pacing.' },
    ],
    differential: [{ dx: 'junctionalEscape', how: 'Narrow QRS, rate 40–60.' }, { dx: 'aivr', how: 'Rate 50–110 (accelerated).' }, { dx: 'hyperK9', how: 'Severe hyperkalaemia gives a slow, very wide rhythm — always check K⁺.' }],
    acute: ['Treat as unstable bradycardia: transcutaneous pacing is often needed (atropine is usually ineffective for infranodal escape); dopamine/epinephrine infusion; transvenous pacing.', 'Never suppress an escape rhythm with antiarrhythmics (e.g. lidocaine) — it may be the only rhythm keeping the patient alive.'],
    refs: ['brady2018', 'acls2025'],
  },
  {
    id: 'aivr',
    name: 'Accelerated idioventricular rhythm (AIVR)',
    aliases: ['AIVR', 'reperfusion arrhythmia', 'slow VT'],
    category: 'ventricular',
    tier: 2,
    tags: ['wide-qrs', 'regular', 'automaticity', 'fusion'],
    preset: 'aivr',
    definition: 'Ventricular rhythm at 50–110/min (faster than escape, slower than VT).',
    epidemiology: 'Classic after reperfusion of an occluded coronary artery; also digoxin toxicity, cardiomyopathy, cocaine.',
    mechanism: 'Enhanced automaticity of Purkinje/ventricular cells that competes with the sinus node; it takes over when sinus slows and yields when sinus speeds up.',
    ecg: ['Wide QRS at 50–110/min', 'Gradual onset, often starting with a fusion beat', 'AV dissociation or competition with sinus rhythm (capture and fusion beats)'],
    why: [
      { level: 'cell', text: 'Ischaemia/reperfusion increases ventricular phase-4 automaticity.' },
      { level: 'conduction', text: 'When the sinus rate dips below the ventricular focus rate the focus captures the ventricles; when they are similar, both activate part of the ventricle → fusion beats.' },
      { level: 'clinical', text: 'Usually benign and self-limited; it is a marker (e.g. of reperfusion), not a target.' },
    ],
    differential: [{ dx: 'monoVT', how: 'Rate > 100–120/min, abrupt onset.' }, { dx: 'ventEscape', how: 'Rate 20–40.' }],
    acute: ['Usually no treatment. If haemodynamically important (loss of AV synchrony), atropine can speed the sinus node to overdrive it.'],
    cautions: ['Suppressing it with antiarrhythmics can leave the patient without an adequate rhythm.'],
    refs: ['va2017'],
  },
  {
    id: 'monoVT',
    name: 'Monomorphic ventricular tachycardia',
    aliases: ['VT', 'ventricular tachycardia', 'scar VT', 'wide complex tachycardia', 'AV dissociation', 'capture beat', 'fusion beat'],
    category: 'ventricular',
    tier: 1,
    tags: ['tachycardia', 'regular', 'wide-qrs', 'reentry', 'av-dissociation', 'regular-wide-tachycardia', 'scar', 'cardioversion', 'procainamide', 'amiodarone', 'adenosine-no-effect', 'syncope'],
    preset: 'monoVT',
    altPresets: ['nsvt', 'rvotVT', 'fascicularVT'],
    definition: '≥ 3 consecutive ventricular beats > 100/min with a single stable QRS morphology. Sustained VT lasts > 30 s or needs termination because of haemodynamic compromise.',
    epidemiology: 'Most sustained monomorphic VT in adults occurs with structural heart disease — especially healed myocardial infarction scar and cardiomyopathy. Idiopathic VT (outflow tract, fascicular) occurs in structurally normal hearts.',
    mechanism: 'Scar-related re-entry: surviving myocardial bundles within scar conduct slowly and form protected isthmuses; the wavefront exits the scar at the same site every cycle → identical QRS. Idiopathic outflow-tract VT is triggered activity (cAMP-mediated DADs, adenosine-sensitive); fascicular VT is re-entry involving the Purkinje system (verapamil-sensitive).',
    ecg: ['Regular wide QRS (usually ≥ 140 ms), rate typically 120–250/min', 'AV dissociation (P waves marching independently) — highly specific when seen', 'Capture beats (narrow, normally conducted) and fusion beats', 'Concordance (all precordial QRS positive or all negative)', 'Extreme ("northwest") axis', 'Initial R or wide initial r/q in aVR, slurred initial QRS (slow initial activation)', 'Morphology points to exit site: LBBB-like = RV/septal exit; RBBB-like = LV exit; superior axis = inferior-wall exit'],
    why: [
      { level: 'cell', text: 'Scar interleaves surviving myocytes with fibrosis → slow, zig-zag conduction → a protected channel that allows re-entry.' },
      { level: 'conduction', text: 'Each cycle exits the scar at the same point and spreads cell-to-cell across the ventricles.' },
      { level: 'vector', text: 'Activation starts at the exit site and moves away from it slowly: the vector points AWAY from the exit throughout much of the QRS.' },
      { level: 'waveform', text: 'Wide QRS; slurred start (no Purkinje engagement); concordance and extreme axis when activation starts at the apex or base.' },
      { level: 'conduction', text: 'The atria continue at the sinus rate; the AV node is usually refractory from retrograde concealment → AV dissociation.' },
      { level: 'waveform', text: 'Occasionally a sinus impulse arrives when the ventricle is excitable → capture (narrow) or fusion (intermediate) beat — proof of VT.' },
      { level: 'clinical', text: 'Haemodynamics depend on rate, LV function and loss of AV synchrony; VT can degenerate to VF.' },
      { level: 'treatment', text: 'The AV node is not part of the circuit → adenosine/AV-nodal blockers do not terminate scar VT (and CCBs may cause collapse). Cardioversion extinguishes the circuit; procainamide/amiodarone slow conduction and prolong refractoriness within it.' },
    ],
    differential: [
      { dx: 'orthoAvrt', how: 'SVT with aberrancy: typical RBBB/LBBB morphology, QRS often < 140 ms, 1:1 P–QRS, response to vagal/adenosine. Prior MI makes VT far more likely.' },
      { dx: 'antiAvrt', how: 'Antidromic AVRT: pre-excitation on baseline ECG; young patient.' },
      { dx: 'hyperK8', how: 'Hyperkalaemia and Na⁺-channel-blocker toxicity: very wide QRS, sine-wave morphology, rates often slower; check K⁺, drug history.' },
      { dx: 'vvi', how: 'Paced rhythm: pacing spikes before each QRS.' },
    ],
    management: {
      recognition: 'Regular wide-complex tachycardia; AV dissociation, capture/fusion beats, concordance, northwest axis, prior MI → VT. Default: treat any wide-complex tachycardia as VT unless proven otherwise.',
      mechanism: 'Re-entry around/through scar (or triggered activity in idiopathic forms).',
      stability: 'Pulseless → cardiac-arrest algorithm (defibrillation). With pulse but unstable (hypotension, altered mental status, shock, ischaemic chest pain, acute HF) → synchronised cardioversion.',
      immediate: ['Unstable with pulse: synchronised cardioversion (sedate if possible) — Class I.', 'Stable: expert consultation; IV procainamide is reasonable (avoid in severe HF/long QT); amiodarone may be considered; sotalol is an option (avoid if QT prolonged). 2025 AHA algorithm: procainamide 20–50 mg/min until arrhythmia suppressed, hypotension, QRS widens > 50% or 17 mg/kg; amiodarone 150 mg over 10 min (repeat as needed).', 'Adenosine may be considered for diagnosis/treatment ONLY if the rhythm is regular and monomorphic (2025 AHA).', 'Correct K⁺/Mg²⁺, treat ischaemia.'],
      definitive: ['ICD for secondary prevention after sustained VT/VF not due to a completely reversible cause (with reasonable expected survival).', 'Catheter ablation for recurrent scar VT (reduces ICD shocks); antiarrhythmics (amiodarone, sotalol) as adjuncts.', 'Idiopathic VT: β-blockers/non-DHP CCB (RVOT), verapamil (fascicular), catheter ablation.'],
      cautions: ['IV verapamil/diltiazem in a wide-complex tachycardia that is actually VT can cause haemodynamic collapse.', 'Irregular or polymorphic wide-complex tachycardia: do NOT give adenosine.'],
      whyWorks: ['Cardioversion depolarises the whole circuit → no excitable gap → termination.', 'Procainamide (Na⁺ block) slows conduction in the circuit and prolongs refractoriness → the wavefront meets refractory tissue and stops.', 'Ablation severs the critical isthmus of the circuit.'],
      whyNot: ['AV-nodal blockers act on a structure outside the circuit.', 'Lidocaine is relatively ineffective for scar-related monomorphic VT (more effective in ischaemic tissue).'],
      refs: ['va2017', 'escVa2022', 'acls2025'],
    },
    refs: ['va2017', 'escVa2022', 'acls2025', 'brugadaWct1991', 'vereckei2008', 'wellens1978'],
  },
  {
    id: 'polyVT',
    name: 'Polymorphic ventricular tachycardia (normal QT)',
    aliases: ['polymorphic VT', 'ischaemic VT'],
    category: 'ventricular',
    tier: 1,
    tags: ['tachycardia', 'irregular', 'wide-qrs', 'reentry', 'irregular-wide-tachycardia', 'ischemia', 'defibrillation', 'syncope', 'cardiac-arrest'],
    preset: 'polyVT',
    definition: 'VT with continuously changing QRS morphology, without QT prolongation in the preceding sinus rhythm.',
    epidemiology: 'Most often acute myocardial ischaemia; also cardiomyopathies, CPVT, Brugada syndrome, short QT.',
    mechanism: 'Functional re-entry (wandering rotors/spiral waves) in electrically heterogeneous ischaemic myocardium — the path changes every beat.',
    ecg: ['Irregular wide QRS with beat-to-beat changing axis and amplitude', 'Rate usually 150–300/min', 'QT normal in sinus beats (distinguishes from torsades)'],
    why: [
      { level: 'cell', text: 'Acute ischaemia depolarises cells, slows conduction and shortens/heterogenises refractoriness.' },
      { level: 'conduction', text: 'Re-entrant wavefronts meander rather than following a fixed scar channel.' },
      { level: 'waveform', text: 'Each beat exits from a different place → the QRS vector changes continuously → polymorphic complexes.' },
      { level: 'treatment', text: 'No stable circuit to "synchronise" to → unsynchronised defibrillation; treat ischaemia (revascularisation, β-blockade).' },
    ],
    differential: [{ dx: 'torsades', how: 'Long QT / pause-dependent onset, "twisting" axis.' }, { dx: 'preexAf', how: 'Pre-excited AF: slower, irregular with some narrow beats.' }, { dx: 'vf', how: 'VF: no discernible QRS complexes.' }],
    acute: ['Pulseless/unstable: defibrillation (unsynchronised) — sensing cannot synchronise to varying complexes.', 'Recurrent ischaemic polymorphic VT: urgent coronary angiography/revascularisation, IV β-blocker, amiodarone; correct electrolytes.'],
    longTerm: ['Revascularisation; ICD per secondary-prevention criteria when not reversible.'],
    refs: ['va2017', 'escVa2022', 'acls2025'],
  },
  {
    id: 'torsades',
    name: 'Torsades de pointes',
    aliases: ['TdP', 'torsade', 'long QT arrhythmia', 'short-long-short'],
    category: 'ventricular',
    tier: 1,
    tags: ['tachycardia', 'irregular', 'wide-qrs', 'triggered', 'long-qt', 'irregular-wide-tachycardia', 'magnesium', 'defibrillation', 'syncope', 'qt-drug'],
    preset: 'torsades',
    definition: 'Polymorphic VT occurring in the setting of QT prolongation, with QRS complexes that appear to twist around the isoelectric baseline.',
    epidemiology: 'Drug-induced (IKr blockers: class IA/III antiarrhythmics, some macrolides/fluoroquinolones, antipsychotics, methadone, ondansetron…) and congenital LQTS. Risk factors: female sex, hypokalaemia, hypomagnesaemia, bradycardia/pauses, heart failure, multiple QT drugs, genetic susceptibility.',
    mechanism: 'Reduced repolarisation reserve prolongs phase 2–3 of the action potential → L-type Ca²⁺ channels reactivate → early afterdepolarisations (EADs) → triggered beats. Transmural dispersion of repolarisation (M-cells prolong most) provides the substrate for re-entry. Onset is characteristically PAUSE-dependent ("short–long–short").',
    ecg: ['Long QTc (often > 500 ms) and abnormal T/U waves in the preceding beats', 'Initiation: premature beat → pause → sinus beat with an even longer QT → R-on-T PVC', 'Polymorphic VT 160–250/min with sinusoidal waxing/waning amplitude "twisting" around the baseline', 'Often self-terminating; can degenerate to VF'],
    why: [
      { level: 'cell', text: 'Less outward K⁺ current (IKr block, LQT1/2) or more inward late Na⁺ current (LQT3) → longer action potential.' },
      { level: 'cell', text: 'During the prolonged plateau, L-type Ca²⁺ channels recover and reopen → an early afterdepolarisation; if it reaches threshold → triggered beat.' },
      { level: 'conduction', text: 'Pauses lengthen the next action potential further (the longer the preceding cycle, the longer the AP) → EADs most likely after a pause.' },
      { level: 'vector', text: 'Re-entry through regions with very different refractoriness gives a slowly rotating activation pattern.' },
      { level: 'waveform', text: 'The QRS axis rotates progressively → complexes appear to twist around the baseline.' },
      { level: 'treatment', text: 'Magnesium suppresses EADs (Ca²⁺ current) without shortening QT; increasing the heart rate (pacing/isoproterenol) shortens APD and removes pauses; K⁺ repletion increases IKr.' },
    ],
    differential: [{ dx: 'polyVT', how: 'Normal QT; ischaemic context.' }, { dx: 'vf', how: 'No organised complexes.' }, { dx: 'preexAf', how: 'Irregular wide complexes with varying fusion, pre-excitation history.' }],
    management: {
      recognition: 'Polymorphic VT with twisting axis in a patient with long QT (look at sinus beats before/after).',
      mechanism: 'EAD-triggered activity on a substrate of prolonged, heterogeneous repolarisation.',
      stability: 'Sustained/pulseless → defibrillation (unsynchronised).',
      immediate: ['Defibrillation for sustained/pulseless TdP.', 'IV magnesium sulfate (commonly 2 g IV) — supported by AHA/ACC/HRS 2017 and ESC 2022 guidance, even when serum Mg²⁺ is normal.', 'Stop all QT-prolonging drugs; correct K⁺ (target high-normal) and Mg²⁺.', 'Pause-dependent recurrent TdP: increase heart rate — temporary transvenous pacing or isoproterenol (avoid isoproterenol in congenital LQT1/2 adrenergic-dependent forms).'],
      definitive: ['Drug-induced: avoid QT-prolonging drugs in future (list at crediblemeds.org).', 'Congenital LQTS: β-blockers, avoid QT drugs, ICD in arrest survivors, left cardiac sympathetic denervation in selected patients.'],
      cautions: ['Class IA/III antiarrhythmics (procainamide, amiodarone, sotalol) prolong QT further — avoid in TdP.', 'Hospital QT monitoring and risk-factor management prevent TdP (AHA/ACCF 2010 statement).'],
      whyWorks: ['Mg²⁺ blocks the L-type Ca²⁺ current underlying EADs.', 'Faster heart rates shorten action-potential duration (rate adaptation) → fewer EADs.', 'K⁺ increases IKr conductance → shorter QT.'],
      whyNot: ['Procainamide/amiodarone prolong repolarisation — worsening the substrate.', 'Synchronised cardioversion cannot reliably sense polymorphic complexes.'],
      refs: ['va2017', 'escVa2022', 'tdp2010', 'acls2025'],
    },
    refs: ['tdp2010', 'va2017', 'escVa2022', 'acls2025'],
  },
  {
    id: 'bidirectionalVT',
    name: 'Bidirectional VT',
    aliases: ['digoxin toxicity VT', 'CPVT'],
    category: 'ventricular',
    tier: 3,
    tags: ['tachycardia', 'wide-qrs', 'triggered', 'digoxin', 'regular-wide-tachycardia'],
    preset: 'bidirectionalVT',
    definition: 'VT with a beat-to-beat alternating QRS axis (often RBBB morphology with alternating left/right axis).',
    epidemiology: 'Classic in digoxin toxicity and catecholaminergic polymorphic VT (CPVT); rarely aconitine poisoning, Andersen–Tawil syndrome.',
    mechanism: 'Delayed afterdepolarisations from intracellular Ca²⁺ overload (digoxin inhibits Na⁺/K⁺-ATPase; CPVT has leaky RyR2 channels), with triggered foci alternating between two sites (e.g. the two fascicles).',
    ecg: ['Regular rhythm with alternating QRS axis every other beat', 'Relatively narrow for VT (fascicular origin)'],
    why: [
      { level: 'cell', text: 'Ca²⁺ overload → spontaneous sarcoplasmic reticulum Ca²⁺ release after repolarisation → Na⁺/Ca²⁺ exchanger inward current → DAD → triggered beat.' },
      { level: 'vector', text: 'Beats alternate between two exit sites (left anterior vs posterior fascicle) → the frontal axis flips each beat.' },
    ],
    differential: [{ dx: 'torsades', how: 'Gradual twisting rather than strict alternation.' }, { dx: 'pvc', how: 'Bigeminy with alternating sinus and PVC morphologies.' }],
    acute: ['Digoxin toxicity: digoxin-specific antibody fragments (Fab), correct K⁺/Mg²⁺.', 'CPVT: β-blockers, flecainide; avoid catecholamines.'],
    refs: ['tox2023', 'escVa2022'],
  },
  {
    id: 'vflutter',
    name: 'Ventricular flutter',
    category: 'arrest',
    tier: 3,
    tags: ['tachycardia', 'wide-qrs', 'reentry', 'defibrillation', 'cardiac-arrest'],
    preset: 'vflutter',
    definition: 'Very rapid (≈ 250–350/min) regular ventricular re-entry producing a sine-wave pattern without distinguishable QRS complexes and T waves.',
    mechanism: 'A single rapid re-entrant circuit — intermediate between rapid VT and VF.',
    ecg: ['Continuous sine-wave oscillation', 'No identifiable QRS/ST/T'],
    why: [
      { level: 'conduction', text: 'Circuit so fast that depolarisation of one cycle merges into repolarisation of the last.' },
      { level: 'waveform', text: 'No isoelectric intervals → sinusoidal pattern.' },
      { level: 'clinical', text: 'No effective output — treat as VF.' },
    ],
    differential: [{ dx: 'vf', how: 'VF is irregular and chaotic.' }, { dx: 'hyperK9', how: 'Hyperkalaemic sine wave is SLOWER (and the patient may still have a pulse).' }],
    acute: ['Defibrillation and CPR per cardiac-arrest algorithm.'],
    refs: ['acls2025'],
  },
  {
    id: 'vf',
    name: 'Ventricular fibrillation',
    aliases: ['VF', 'cardiac arrest', 'shockable rhythm'],
    category: 'arrest',
    tier: 1,
    tags: ['cardiac-arrest', 'irregular', 'defibrillation', 'amiodarone', 'lidocaine', 'epinephrine'],
    preset: 'vf',
    definition: 'Chaotic, disorganised ventricular electrical activity without effective contraction or cardiac output.',
    mechanism: 'Multiple wandering wavelets / rotors in heterogeneous myocardium (ischaemia, scar, electrolyte disturbance, channelopathy). Coarse VF becomes fine over minutes as myocardial energy stores fall.',
    ecg: ['Irregular undulations of varying amplitude and frequency', 'No identifiable P, QRS or T', 'Coarse → fine with time'],
    why: [
      { level: 'conduction', text: 'Many independent re-entrant wavelets activate small regions at random.' },
      { level: 'vector', text: 'No coordinated dipole → the summed vector swings randomly.' },
      { level: 'waveform', text: 'Chaotic baseline; amplitude falls as ischaemia progresses.' },
      { level: 'treatment', text: 'Defibrillation depolarises a critical mass of myocardium simultaneously, extinguishing all wavelets so the sinus node (or any organised rhythm) can take over. High-quality CPR maintains coronary perfusion that makes defibrillation more likely to succeed.' },
    ],
    differential: [{ dx: 'asystole', how: 'Check gain/leads — fine VF can look like asystole.' }, { dx: 'polyVT', how: 'Discernible (if varying) QRS complexes.' }, { dx: 'Artefact', how: 'Movement/electrode artefact: check the patient (pulse, consciousness) — regular QRS complexes may be visible "through" the artefact.' }],
    management: {
      recognition: 'Chaotic irregular waveform, no QRS, pulseless unresponsive patient.',
      mechanism: 'Multiple-wavelet ventricular re-entry.',
      stability: 'Always cardiac arrest.',
      immediate: ['High-quality CPR; defibrillate as soon as possible (biphasic energy per manufacturer, often 120–200 J; if unknown use maximum).', 'Resume CPR immediately for 2 min after each shock; minimise pauses.', 'Epinephrine 1 mg IV/IO every 3–5 min (after initial shocks per algorithm).', 'Shock-refractory VF/pVT: amiodarone 300 mg IV/IO, then 150 mg; or lidocaine 1–1.5 mg/kg, then 0.5–0.75 mg/kg.', 'Refractory VF: vector change or double sequential external defibrillation may be considered (2025 AHA: Class 2b).', 'Search for reversible causes (Hs and Ts): hypoxia, hypovolaemia, H⁺, hypo/hyperkalaemia, hypothermia, tension pneumothorax, tamponade, toxins, thrombosis (coronary/pulmonary).'],
      definitive: ['Post-cardiac-arrest care (2025 AHA Part 11); emergency coronary angiography when a coronary cause is likely; ICD for secondary prevention when the cause is not reversible.'],
      cautions: ['Do not delay defibrillation for airway or drugs.', 'Synchronised mode will not fire in VF — use unsynchronised defibrillation.'],
      whyWorks: ['Simultaneous depolarisation → all tissue refractory → wavelets cannot re-enter → an organised pacemaker can resume.', 'Epinephrine’s α-effect raises aortic diastolic (coronary perfusion) pressure during CPR.', 'Amiodarone/lidocaine raise the fibrillation threshold and suppress recurrent VF.'],
      whyNot: ['Atropine, adenosine and pacing have no role in VF.'],
      refs: ['acls2025', 'aclsExec2025', 'postArrest2025'],
    },
    refs: ['acls2025', 'aclsExec2025', 'postArrest2025'],
  },
  {
    id: 'pulselessVT',
    name: 'Pulseless ventricular tachycardia',
    aliases: ['pVT', 'shockable rhythm'],
    category: 'arrest',
    tier: 1,
    tags: ['cardiac-arrest', 'wide-qrs', 'regular', 'defibrillation'],
    preset: 'pulselessVT',
    definition: 'VT without a palpable pulse — managed identically to VF.',
    mechanism: 'Ventricular rate too fast (or ventricle too damaged) for effective filling and ejection.',
    ecg: ['Regular wide-complex tachycardia (monomorphic or polymorphic)', 'Diagnosis requires the clinical finding of no pulse'],
    why: [
      { level: 'clinical', text: 'The ECG shows organised VT; the patient has no output.' },
      { level: 'treatment', text: 'Unsynchronised defibrillation (as VF) — no time to synchronise and no pulse to protect.' },
    ],
    differential: [{ dx: 'monoVT', how: 'VT with a pulse is treated by the tachycardia algorithm.' }],
    acute: ['Cardiac-arrest algorithm: CPR, defibrillation, epinephrine, amiodarone/lidocaine.'],
    refs: ['acls2025'],
  },
  {
    id: 'pea',
    name: 'Pulseless electrical activity (PEA)',
    aliases: ['PEA', 'electromechanical dissociation', 'non-shockable rhythm', 'Hs and Ts'],
    category: 'arrest',
    tier: 1,
    tags: ['cardiac-arrest', 'epinephrine'],
    preset: 'pea',
    definition: 'Organised electrical activity on the monitor without a palpable pulse. PEA is a clinical diagnosis — any non-VF/VT rhythm can be PEA.',
    mechanism: 'Electrical activation occurs but mechanical output fails: no preload (hypovolaemia, tension pneumothorax, tamponade, massive PE), no contractility (profound acidosis, hyperkalaemia, toxins, massive MI), or pseudo-PEA (weak contraction without palpable pulse).',
    ecg: ['Any organised rhythm (sinus, junctional, idioventricular) in a pulseless patient', 'Narrow-complex PEA suggests mechanical/obstructive causes (tamponade, tension pneumothorax, PE, hypovolaemia); wide/slow PEA suggests metabolic/myocardial causes (hyperkalaemia, acidosis, toxins, massive MI)'],
    why: [
      { level: 'clinical', text: 'Electricity without output: the conduction system works; the pump or its filling does not.' },
      { level: 'treatment', text: 'Shocks do nothing (there is no chaotic rhythm to reset). Treatment = CPR + epinephrine + fixing the specific cause.' },
    ],
    differential: [{ dx: 'vf', how: 'Shockable.' }, { dx: 'asystole', how: 'No electrical activity.' }],
    acute: ['CPR; epinephrine 1 mg IV/IO as soon as feasible and every 3–5 min.', 'Actively search for and treat reversible causes (Hs and Ts; point-of-care ultrasound may help).', 'Hyperkalaemia-associated arrest: IV calcium, bicarbonate/insulin–glucose per AHA special-circumstances guidance.'],
    refs: ['acls2025', 'special2025'],
  },
  {
    id: 'asystole',
    name: 'Asystole',
    aliases: ['flatline', 'P-wave asystole', 'ventricular standstill', 'non-shockable'],
    category: 'arrest',
    tier: 1,
    tags: ['cardiac-arrest', 'epinephrine'],
    preset: 'asystole',
    definition: 'Absence of ventricular electrical activity.',
    mechanism: 'Failure of all pacemakers or complete AV block without escape (P waves may persist: "P-wave asystole" / ventricular standstill), usually the end-stage of prolonged arrest.',
    ecg: ['Flat line (confirm in ≥ 2 leads, check gain and connections)', 'P waves without QRS in ventricular standstill'],
    why: [
      { level: 'conduction', text: 'No ventricular depolarisation → no QRS.' },
      { level: 'treatment', text: 'Nothing to defibrillate; CPR and epinephrine; pacing is not recommended in asystolic cardiac arrest (ineffective), though P-wave asystole from complete AV block in a patient who still has some circulation is a different situation.' },
    ],
    differential: [{ dx: 'vf', how: 'Fine VF — increase gain, check another lead.' }],
    acute: ['CPR, epinephrine 1 mg every 3–5 min, reversible causes.'],
    refs: ['acls2025'],
  },
];
