// Named ECG signs, criteria, phenomena and patterns (an "eponym" index in the spirit of the
// LITFL ECG library). Each entry is short, states the ECG criteria precisely, says why it matters,
// and links to the diagnosis page, a simulator preset and/or an interactive tool where the
// feature can be generated and explored.

export type EponymKind = 'sign' | 'criteria' | 'pattern' | 'phenomenon' | 'wave' | 'law';

export interface Eponym {
  id: string;
  name: string;
  aka?: string[];
  kind: EponymKind;
  /** One-sentence definition. */
  def: string;
  /** ECG criteria / how to recognise it. */
  ecg: string[];
  /** Why it matters / mechanism in one or two sentences. */
  significance: string;
  dx?: string; // diagnosis id
  preset?: string; // simulator preset that shows it
  tool?: string; // hash route of an interactive tool/lab
  refs: string[];
}

export const KIND_LABEL: Record<EponymKind, string> = {
  sign: 'Sign',
  criteria: 'Criteria / algorithm',
  pattern: 'Pattern',
  phenomenon: 'Phenomenon',
  wave: 'Wave',
  law: 'Law / lead system',
};

export const EPONYMS: Eponym[] = [
  {
    id: 'ashman',
    name: 'Ashman phenomenon',
    kind: 'phenomenon',
    def: 'Aberrant (usually RBBB-pattern) conduction of a supraventricular beat that ends a short R–R cycle preceded by a long one.',
    ecg: ['A long R–R interval followed by a short one ("long–short" sequence)', 'The beat ending the short cycle is wide, usually with RBBB morphology', 'Commonly seen in atrial fibrillation; the next beats return to normal width'],
    significance: 'Refractoriness of the His–Purkinje system (especially the right bundle) lengthens after a long cycle, so an early impulse finds that bundle still refractory. It is a benign mimic of ventricular ectopy.',
    dx: 'pac',
    preset: 'pacAberrant',
    refs: ['ecgStd3'],
  },
  {
    id: 'aslanger',
    name: 'Aslanger pattern',
    kind: 'pattern',
    def: 'A pattern of acute inferior infarction with concomitant critical disease elsewhere, in which ST elevation is confined to lead III.',
    ecg: ['ST elevation in lead III but not in the other inferior leads', 'ST depression in V4–V6 (with a positive or terminally positive T wave) but not in V2', 'ST segment in V1 higher than in V2'],
    significance: 'An occlusion-MI pattern that does not meet conventional STEMI criteria. It is a recognised "STEMI equivalent" in the occlusion-MI literature; it is not part of the guideline STEMI definition.',
    dx: 'stemi',
    refs: ['acs2025'],
  },
  {
    id: 'avr-ste',
    name: 'ST elevation in aVR with widespread ST depression',
    aka: ['aVR sign', 'subendocardial ischaemia pattern'],
    kind: 'pattern',
    def: 'ST elevation in aVR (often also V1) with ST depression in many other leads.',
    ecg: ['STE in aVR ≥ 1 mm', 'ST depression ≥ 1 mm in ≥ 6–8 leads, usually maximal in V4–V6 and I/II', 'No reciprocal pattern of a single territory'],
    significance: 'Indicates diffuse subendocardial ischaemia: severe left-main or multivessel disease, or supply–demand mismatch (tachyarrhythmia, anaemia, hypotension). The ST vector points toward the cavity — i.e. toward aVR.',
    dx: 'nste',
    preset: 'subendo',
    tool: '#/ischemia',
    refs: ['acs2025', 'ecgStd6'],
  },
  {
    id: 'bazett',
    name: 'Bazett formula',
    kind: 'criteria',
    def: 'QTc = QT / √RR (RR in seconds).',
    ecg: ['The most widely used heart-rate correction of the QT interval', 'Over-corrects (QTc too long) at fast heart rates and under-corrects at slow rates', 'Fridericia (QT / ∛RR) or Framingham (QT + 154 × (1 − RR)) behave better outside 60–90/min'],
    significance: 'QT shortens as heart rate rises; comparing QT values needs a correction. The choice of formula changes whether a borderline QT is called prolonged.',
    tool: '#/tools/qtc',
    refs: ['ecgStd4', 'tdp2010'],
  },
  {
    id: 'bix',
    name: 'Bix rule',
    kind: 'sign',
    def: 'In a narrow-complex tachycardia, if a P wave sits exactly halfway between two QRS complexes, suspect a second P wave hidden in the QRS.',
    ecg: ['Regular narrow-complex tachycardia, often ~150/min', 'Visible P (or flutter wave) midway between QRS complexes', 'A second atrial deflection buried in the QRS → 2:1 conduction (atrial flutter or atrial tachycardia)'],
    significance: 'Prevents 2:1 flutter or atrial tachycardia being mistaken for sinus tachycardia; vagal manoeuvres or adenosine can unmask the hidden waves.',
    dx: 'flutter',
    preset: 'flutter21',
    tool: '#/sandbox/adenosine',
    refs: ['svt2015'],
  },
  {
    id: 'brugada-algorithm',
    name: 'Brugada algorithm (wide-complex tachycardia)',
    kind: 'criteria',
    def: 'Four sequential questions that distinguish VT from SVT with aberrancy (Brugada P, et al., 1991).',
    ecg: ['1. Absence of an RS complex in all precordial leads → VT', '2. R-to-S interval > 100 ms in any precordial lead → VT', '3. AV dissociation → VT', '4. Morphology criteria for VT in both V1–V2 and V6 → VT; otherwise SVT with aberrancy'],
    significance: 'High reported accuracy in the original series, lower in later validation; when in doubt, treat a wide-complex tachycardia as VT.',
    dx: 'monoVT',
    tool: '#/tools/wct',
    refs: ['brugadaWct1991'],
  },
  {
    id: 'brugada-sign',
    name: 'Brugada sign',
    kind: 'sign',
    def: 'In a wide-complex tachycardia, an interval from QRS onset to the nadir of the S wave > 100 ms in any precordial lead.',
    ecg: ['Measure from the start of the QRS to the deepest point of the S wave', '> 100 ms in any precordial lead favours VT (step 2 of the Brugada algorithm)'],
    significance: 'Slow initial activation means the impulse is spreading through myocardium rather than the Purkinje system. Not to be confused with the Brugada syndrome ECG pattern.',
    dx: 'monoVT',
    tool: '#/tools/wct',
    refs: ['brugadaWct1991'],
  },
  {
    id: 'brugada-pattern',
    name: 'Brugada pattern (type 1 and type 2)',
    kind: 'pattern',
    def: 'Right-precordial ST elevation characteristic of Brugada syndrome.',
    ecg: ['Type 1 ("coved"): J-point/ST elevation ≥ 2 mm with a coved ST segment descending into a negative T wave, in ≥ 1 lead of V1–V2 (standard or 2nd–3rd intercostal space positions)', 'Type 2 ("saddleback"): ST elevation ≥ 0.5 mm (usually ≥ 2 mm in V2) with a saddleback shape and upright or biphasic T', 'Only type 1 (spontaneous or drug-induced) is diagnostic'],
    significance: 'Reflects loss of the epicardial action-potential dome in the RV outflow tract (Ito-dominated) creating a transmural voltage gradient; risk of polymorphic VT/VF, especially with fever, sodium-channel blockers or at night.',
    dx: 'brugada',
    preset: 'brugada1',
    refs: ['jwave2016', 'ipa2013', 'escVa2022'],
  },
  {
    id: 'cabrera',
    name: 'Cabrera sign',
    kind: 'sign',
    def: 'Notching of ≥ 40 ms on the ascending limb of the S wave in V3–V4 in LBBB, suggesting old anterior infarction.',
    ecg: ['LBBB', 'Notch ≥ 40 ms on the upstroke of the S wave in V3 and/or V4'],
    significance: 'Highly specific but insensitive marker of prior myocardial infarction in LBBB; a related finding is Chapman sign (notching of the R upstroke in I, aVL or V6).',
    dx: 'lbbb',
    refs: ['ecgStd3'],
  },
  {
    id: 'capture-fusion',
    name: 'Capture and fusion (Dressler) beats',
    kind: 'sign',
    def: 'During a wide-complex tachycardia, a sinus impulse occasionally reaches the ventricles: completely (capture beat, narrow) or partly (fusion or Dressler beat, intermediate shape).',
    ecg: ['Capture beat: an early narrow QRS during wide-complex tachycardia', 'Fusion (Dressler) beat: QRS with morphology intermediate between sinus and the tachycardia', 'Usually accompanied by visible AV dissociation'],
    significance: 'Proves that the atria and ventricles are dissociated and that the ventricles are being driven independently — very strong evidence of VT (rare exceptions exist).',
    dx: 'monoVT',
    preset: 'monoVT',
    refs: ['brugadaWct1991', 'va2017'],
  },
  {
    id: 'chatterjee',
    name: 'Chatterjee phenomenon (cardiac memory)',
    kind: 'phenomenon',
    def: 'T-wave inversion that persists in conducted beats after a period of abnormal ventricular activation (ventricular pacing, intermittent LBBB, pre-excitation or VT).',
    ecg: ['T waves invert in leads where the abnormal QRS was negative', 'Persists for hours to weeks after normal conduction resumes'],
    significance: 'Repolarisation "remembers" the altered activation sequence (electrical remodelling). It can mimic ischaemic T-wave inversion.',
    dx: 'paced',
    preset: 'vvi',
    refs: ['ecgStd5'],
  },
  {
    id: 'coumel',
    name: 'Coumel law (Coumel sign)',
    kind: 'law',
    def: 'In orthodromic AVRT, the development of bundle-branch block on the same side as the accessory pathway lengthens the tachycardia cycle.',
    ecg: ['Orthodromic AVRT that switches from narrow to bundle-branch-block morphology', 'Cycle length increases (typically by ≥ 35 ms, through a longer VA interval) when the block is ipsilateral to the pathway'],
    significance: 'The circuit must now travel through the other bundle and across the septum to reach the pathway; this proves the pathway participates in the tachycardia and localises it.',
    dx: 'orthoAvrt',
    tool: '#/rhythms/avrt-lab',
    refs: ['wpw2012', 'svt2015'],
  },
  {
    id: 'cornell',
    name: 'Cornell voltage criteria (LVH)',
    kind: 'criteria',
    def: 'R in aVL + S in V3 > 28 mm in men or > 20 mm in women.',
    ecg: ['Add the R-wave amplitude in aVL to the S-wave depth in V3', 'Men > 28 mm (2.8 mV); women > 20 mm (2.0 mV)'],
    significance: 'More sensitive than Sokolow–Lyon in many populations, but all voltage criteria are insensitive; voltage depends on body habitus, age and sex.',
    dx: 'lvh',
    preset: 'lvh',
    refs: ['casale1987', 'ecgStd5'],
  },
  {
    id: 'de-winter',
    name: 'de Winter T waves',
    kind: 'pattern',
    def: 'An anterior STEMI-equivalent of proximal LAD occlusion without precordial ST elevation.',
    ecg: ['1–3 mm upsloping ST depression at the J point in V1–V6', 'Tall, prominent, symmetrical T waves in the precordial leads', 'Often slight ST elevation in aVR'],
    significance: 'Seen in ~2% of acute LAD occlusions; usually persists until reperfusion. It warrants emergency reperfusion despite not meeting STEMI criteria.',
    dx: 'deWinter',
    preset: 'deWinter',
    refs: ['dewinter2008', 'acs2025'],
  },
  {
    id: 'delta',
    name: 'Delta wave',
    kind: 'wave',
    def: 'Slurred initial upstroke of the QRS caused by ventricular pre-excitation through an accessory pathway.',
    ecg: ['Short PR (< 120 ms)', 'Slurred, slow initial QRS (delta wave)', 'Wide QRS (> 110–120 ms) with secondary ST–T changes'],
    significance: 'The pathway bypasses AV-nodal delay and activates myocardium slowly, cell to cell, before the His–Purkinje impulse arrives (a fusion complex). The delta-wave polarity localises the pathway.',
    dx: 'wpw',
    preset: 'wpw',
    tool: '#/rhythms/avrt-lab',
    refs: ['wpw2012'],
  },
  {
    id: 'einthoven',
    name: 'Einthoven triangle and law',
    kind: 'law',
    def: 'The three bipolar limb leads form a closed loop: lead I + lead III = lead II at every instant.',
    ecg: ['I = LA − RA; II = LL − RA; III = LL − LA', 'Therefore I + III = II', 'A tracing that violates this indicates a recording or labelling error'],
    significance: 'Underlies the hexaxial reference system and axis calculation; Goldberger augmented leads and the Wilson central terminal are derived from the same three electrodes.',
    tool: '#/fundamentals/leads',
    refs: ['ecgStd1'],
  },
  {
    id: 'epsilon',
    name: 'Epsilon wave',
    kind: 'wave',
    def: 'A small low-amplitude deflection (positive notch or wiggle) between the end of the QRS and the onset of the T wave in the right precordial leads.',
    ecg: ['Reproducible low-amplitude signal after the QRS in V1–V3', 'Often with terminal activation delay (S-wave upstroke ≥ 55 ms in V1–V3) and T inversion in V1–V3'],
    significance: 'Late activation of fibro-fatty RV myocardium in arrhythmogenic right ventricular cardiomyopathy. It is a major criterion in the 2010 Task Force criteria; later proposals (the 2020 Padua criteria) downgrade it to a minor criterion because it is often over-read.',
    dx: 'arvc',
    preset: 'arvc',
    refs: ['arvcTfc2010'],
  },
  {
    id: 'fridericia',
    name: 'Fridericia formula',
    kind: 'criteria',
    def: 'QTc = QT / ∛RR (RR in seconds).',
    ecg: ['Less rate-dependent bias than Bazett at fast and slow heart rates', 'Commonly used in drug-safety studies'],
    significance: 'Gives a more reliable corrected QT in tachycardia and bradycardia.',
    tool: '#/tools/qtc',
    refs: ['ecgStd4'],
  },
  {
    id: 'hyperacute-t',
    name: 'Hyperacute T waves',
    kind: 'sign',
    def: 'Broad-based, tall, symmetrical T waves that are disproportionately large relative to the QRS in a coronary territory.',
    ecg: ['T-wave area large relative to the preceding QRS', 'Broad base, often with a straightened ST segment', 'Confined to a territory, often with reciprocal changes'],
    significance: 'The earliest ECG sign of coronary occlusion, preceding ST elevation; compare with old tracings and repeat the ECG.',
    dx: 'stemi',
    preset: 'hyperacute',
    tool: '#/ischemia',
    refs: ['udmi2018', 'acs2025'],
  },
  {
    id: 'josephson',
    name: 'Josephson sign',
    kind: 'sign',
    def: 'Notching near the nadir of the S wave in a wide-complex tachycardia.',
    ecg: ['Wide-complex tachycardia', 'Notch close to the bottom of the S wave (usually assessed in the right precordial leads)'],
    significance: 'Favours VT over SVT with aberrancy (activation spreading through myocardium rather than the bundle branches).',
    dx: 'monoVT',
    tool: '#/tools/wct',
    refs: ['va2017'],
  },
  {
    id: 'lewis-lead',
    name: 'Lewis lead',
    kind: 'law',
    def: 'A modified bipolar chest lead used to enlarge atrial activity: the right-arm electrode on the manubrium and the left-arm electrode on the 5th right intercostal space beside the sternum, recorded as lead I.',
    ecg: ['Makes P waves or flutter waves easier to see', 'Helps to detect AV dissociation in wide-complex tachycardia'],
    significance: 'Moving electrodes changes what a "lead" sees: each lead is just a voltage difference along a chosen line.',
    refs: ['ecgStd1'],
  },
  {
    id: 'mobitz',
    name: 'Mobitz type II',
    kind: 'phenomenon',
    def: 'Second-degree AV block in which conducted beats have a constant PR interval and a P wave suddenly fails to conduct.',
    ecg: ['Constant PR (normal or long) before and after the dropped beat', 'The P–P interval stays constant', 'The R–R interval containing the dropped P equals two P–P intervals', 'Often a wide QRS (block below the His bundle)'],
    significance: 'Usually infranodal disease with a high risk of progression to complete heart block; permanent pacing is generally indicated.',
    dx: 'mobitz2',
    preset: 'mobitz2',
    tool: '#/conduction/av',
    refs: ['brady2018'],
  },
  {
    id: 'osborn',
    name: 'Osborn wave (J wave)',
    kind: 'wave',
    def: 'A positive, dome- or hump-shaped deflection at the J point.',
    ecg: ['Best seen in the inferior and lateral precordial leads', 'Amplitude increases as body temperature falls', 'Accompanied by bradycardia, long intervals and shivering artefact'],
    significance: 'A transmural voltage gradient during phase 1 (prominent epicardial Ito notch). Classic in hypothermia; also seen with hypercalcaemia, brain injury and in the J-wave syndromes.',
    dx: 'hypothermia',
    preset: 'hypothermia',
    refs: ['jwave2016'],
  },
  {
    id: 'r-on-t',
    name: 'R-on-T phenomenon',
    kind: 'phenomenon',
    def: 'A premature ventricular complex that falls on the T wave of the preceding beat.',
    ecg: ['Very short coupling interval: the PVC begins on the upslope or peak of the T wave'],
    significance: 'The T wave is the vulnerable period, when some cells have recovered and others are still refractory; a stimulus then can initiate re-entry (polymorphic VT or VF), especially with ischaemia or a long QT. Use the 3-D heart’s refractoriness view to see it.',
    dx: 'pvc',
    tool: '#/heart3d',
    refs: ['va2017'],
  },
  {
    id: 'sgarbossa',
    name: 'Sgarbossa and Smith-modified Sgarbossa criteria',
    kind: 'criteria',
    def: 'Criteria for acute MI (occlusion) in the presence of LBBB or ventricular pacing.',
    ecg: ['Concordant ST elevation ≥ 1 mm in any lead (5 points)', 'Concordant ST depression ≥ 1 mm in V1–V3 (3 points)', 'Excessively discordant ST elevation ≥ 5 mm (2 points); score ≥ 3 is specific for MI', 'Smith modification: replaces the third criterion with discordant ST elevation whose ratio to the preceding S-wave depth is ≤ −0.25 — more sensitive'],
    significance: 'LBBB and paced rhythms normally produce discordant ST–T changes; concordance or disproportionate discordance points to superimposed injury.',
    dx: 'lbbb',
    tool: '#/tools/sgarbossa',
    refs: ['sgarbossa1996', 'smith2012'],
  },
  {
    id: 'sokolow-lyon',
    name: 'Sokolow–Lyon criteria (LVH)',
    kind: 'criteria',
    def: 'S in V1 + R in V5 or V6 (whichever is larger) ≥ 35 mm, or R in aVL ≥ 11 mm.',
    ecg: ['SV1 + RV5/RV6 ≥ 35 mm (3.5 mV)', 'or R aVL ≥ 11 mm (1.1 mV)'],
    significance: 'Specific but insensitive; young, thin adults and athletes often exceed it without LVH. Repolarisation abnormality ("strain") and left atrial abnormality add weight.',
    dx: 'lvh',
    preset: 'lvh',
    refs: ['sokolow1949', 'ecgStd5'],
  },
  {
    id: 'south-african-flag',
    name: 'South African flag sign',
    kind: 'pattern',
    def: 'The distribution of ST changes in high lateral infarction, which on a standard 3 × 4 layout resembles the South African flag.',
    ecg: ['ST elevation in I, aVL and V2', 'ST depression in III (and often aVF)', 'Lateral precordial leads V5–V6 may be unremarkable'],
    significance: 'Usually first diagonal (or obtuse marginal) occlusion; easily missed because the elevation in aVL and I is small.',
    dx: 'stemi',
    preset: 'stemiLateral',
    refs: ['acs2025'],
  },
  {
    id: 'spodick',
    name: 'Spodick sign',
    kind: 'sign',
    def: 'A downward-sloping TP segment in acute pericarditis.',
    ecg: ['Best seen in lead II and the lateral precordial leads', 'Accompanies diffuse concave ST elevation and PR depression'],
    significance: 'Reflects atrial and ventricular injury currents of epicardial inflammation; helps distinguish pericarditis from STEMI.',
    dx: 'pericarditis',
    preset: 'pericarditis',
    refs: ['escPeri2015'],
  },
  {
    id: 'torsades',
    name: 'Torsades de pointes',
    kind: 'pattern',
    def: 'Polymorphic VT in the setting of a prolonged QT, with QRS axis and amplitude that twist around the baseline.',
    ecg: ['Long QT (often with a long–short initiating sequence)', 'Rate ~200–250/min; QRS amplitude waxes and wanes, the axis rotating ("twisting of the points")', 'Often self-terminating; may degenerate to VF'],
    significance: 'Triggered by early afterdepolarisations when repolarisation is prolonged (drugs blocking IKr, hypokalaemia, hypomagnesaemia, congenital LQTS). Treatment targets the mechanism: IV magnesium, correcting K⁺, removing drugs, increasing the heart rate.',
    dx: 'torsades',
    preset: 'torsades',
    refs: ['tdp2010', 'acls2025'],
  },
  {
    id: 'vereckei',
    name: 'Vereckei aVR algorithm',
    kind: 'criteria',
    def: 'A four-step algorithm using only lead aVR to distinguish VT from SVT in wide-complex tachycardia.',
    ecg: ['1. Initial R wave in aVR → VT', '2. Initial r or q wave > 40 ms → VT', '3. Notch on the descending limb of a negative-onset, predominantly negative QRS → VT', '4. Vi/Vt ≤ 1 (voltage change in the initial 40 ms ≤ that in the terminal 40 ms) → VT; otherwise SVT'],
    significance: 'In SVT with aberrancy, the initial septal activation is fast and moves away from aVR; in VT, initial activation is slow and often directed toward aVR.',
    dx: 'monoVT',
    tool: '#/tools/wct',
    refs: ['vereckei2008'],
  },
  {
    id: 'wellens',
    name: 'Wellens syndrome',
    kind: 'pattern',
    def: 'Characteristic precordial T-wave changes in a pain-free patient after an episode of angina, indicating critical proximal LAD stenosis.',
    ecg: ['Type A: biphasic T waves in V2–V3 (initially positive, terminally negative)', 'Type B: deep, symmetrical T-wave inversion in V2–V3 (may extend to V1–V6)', 'Isoelectric or minimally elevated ST (< 1 mm), no precordial Q waves, preserved R-wave progression', 'Recent chest pain, now resolved; normal or slightly raised troponin'],
    significance: 'A reperfusion pattern: the artery has reopened but is critically narrowed, with a high risk of extensive anterior infarction. Avoid stress testing; arrange angiography.',
    dx: 'wellens',
    preset: 'wellens',
    refs: ['wellens1982'],
  },
  {
    id: 'wenckebach',
    name: 'Wenckebach phenomenon (Mobitz type I)',
    kind: 'phenomenon',
    def: 'Progressive prolongation of conduction time until one impulse fails to conduct, after which the cycle repeats.',
    ecg: ['PR lengthens beat by beat; the largest PR increment is between the first and second beats after the pause', 'R–R intervals shorten progressively before the dropped beat', 'The pause containing the dropped P is shorter than two P–P intervals', '"Group beating"'],
    significance: 'Usually decremental conduction within the AV node (vagal tone, inferior MI, AV-nodal drugs, athletes) and usually benign; the same behaviour occurs at the SA junction and in re-entry circuits.',
    dx: 'mobitz1',
    preset: 'mobitz1',
    tool: '#/conduction/av',
    refs: ['brady2018'],
  },
  {
    id: 'wilson',
    name: 'Wilson central terminal and Goldberger augmented leads',
    kind: 'law',
    def: 'The reference electrode for the unipolar leads: the average of the right-arm, left-arm and left-leg potentials (Wilson); Goldberger’s augmented leads (aVR, aVL, aVF) compare one limb with the average of the other two, enlarging the signal by 50%.',
    ecg: ['Precordial leads V1–V6 are measured against the Wilson central terminal', 'aVR + aVL + aVF = 0 at every instant'],
    significance: 'Explains why aVR looks like an inverted lateral lead and why limb-electrode reversals change the augmented leads in predictable ways.',
    tool: '#/fundamentals/leads',
    refs: ['ecgStd1'],
  },
];

export const eponymById = (id: string): Eponym | undefined => EPONYMS.find((e) => e.id === id);
export const eponymsForDx = (dxId: string): Eponym[] => EPONYMS.filter((e) => e.dx === dxId);
