// Glossary of electrophysiology and ECG terms. Each definition is short and mechanistic;
// `see` points to the page or diagnosis where the concept is explored interactively.

export interface Term {
  id: string;
  term: string;
  aka?: string[];
  def: string;
  see?: string; // hash route
}

export const GLOSSARY: Term[] = [
  { id: 'aberrancy', term: 'Aberrant conduction (aberrancy)', aka: ['aberration', 'Ashman phenomenon'], def: 'A supraventricular impulse conducted with a bundle-branch-block pattern because one bundle is still refractory (rate-related) or diseased. Ashman phenomenon: a short cycle after a long one finds the right bundle refractory (refractoriness lengthens after long cycles).', see: '#/dx/pac' },
  { id: 'action-potential', term: 'Action potential', def: 'The transient change in membrane voltage of a cardiac cell: phase 0 upstroke (Na⁺ or, in nodal cells, Ca²⁺), phase 1 early repolarisation (Ito), phase 2 plateau (Ca²⁺ in, K⁺ out), phase 3 repolarisation (IKr, IKs), phase 4 resting/diastolic potential.', see: '#/fundamentals/ap' },
  { id: 'afterdepolarisation', term: 'Afterdepolarisation', aka: ['EAD', 'DAD', 'triggered activity'], def: 'Oscillation of membrane voltage that can trigger a new action potential. Early (EAD): during phase 2–3 when repolarisation is prolonged (long QT → torsades). Delayed (DAD): after repolarisation, from diastolic Ca²⁺ release (digoxin toxicity, CPVT).', see: '#/dx/torsades' },
  { id: 'automaticity', term: 'Automaticity', def: 'Spontaneous phase-4 depolarisation leading to an action potential. Normal in the sinus node, AV junction and Purkinje fibres (the pacemaker hierarchy); abnormal or enhanced automaticity causes AIVR, focal atrial and junctional tachycardias.', see: '#/sandbox/hierarchy' },
  { id: 'av-dissociation', term: 'AV dissociation', def: 'Atria and ventricles beat independently. Occurs when a lower pacemaker is faster than the sinus (VT, accelerated junctional) or when conduction fails (complete block). Not synonymous with complete heart block.', see: '#/dx/chb' },
  { id: 'axis', term: 'Electrical axis', aka: ['QRS axis', 'mean QRS vector'], def: 'The direction of the mean QRS vector in the frontal plane, normally −30° to +90°. It reflects the sequence and mass of ventricular activation.', see: '#/sandbox/axis' },
  { id: 'capture', term: 'Capture', def: 'Depolarisation of myocardium by a pacing stimulus. Electrical capture = spike followed by a paced complex; mechanical capture = a palpable pulse.', see: '#/dx/pacerMalfunction' },
  { id: 'concealed-conduction', term: 'Concealed conduction', def: 'An impulse that penetrates a structure (usually the AV node) without traversing it. It is invisible on the ECG but leaves the tissue refractory and so influences the next impulse — e.g. irregular ventricular response in AF.', see: '#/rhythms/flutter-lab' },
  { id: 'decremental', term: 'Decremental conduction', def: 'Conduction that slows as impulses arrive earlier (faster rates). Typical of the AV node (Ca²⁺-dependent recovery); absent in most accessory pathways — which is why pathways are dangerous in AF.', see: '#/dx/mobitz1' },
  { id: 'delta-wave', term: 'Delta wave', def: 'Slurred initial QRS upstroke produced by ventricular myocardium pre-excited through an accessory pathway before the His–Purkinje impulse arrives (fusion).', see: '#/dx/wpw' },
  { id: 'discordance', term: 'Appropriate discordance', def: 'In secondary repolarisation abnormalities (BBB, paced, ventricular beats), the ST segment and T wave point opposite to the main QRS deflection. Concordance breaks this rule and suggests ischaemia (Sgarbossa).', see: '#/tools/sgarbossa' },
  { id: 'dipole', term: 'Dipole / heart vector', def: 'The summed electrical activity of the heart at an instant behaves like a single dipole with a size and direction. Each lead records the projection of this vector onto its axis.', see: '#/fundamentals/leads' },
  { id: 'epsilon', term: 'Epsilon wave', def: 'Small, low-amplitude deflection(s) between the end of the QRS and the T wave in V1–V3, from late-activated RV myocardium in ARVC.', see: '#/dx/arvc' },
  { id: 'erp', term: 'Effective refractory period (ERP)', aka: ['refractory period', 'refractoriness'], def: 'The interval after activation during which a new stimulus cannot propagate. Differences in refractoriness between pathways set up unidirectional block — the prerequisite for re-entry.', see: '#/rhythms/avnrt-lab' },
  { id: 'escape', term: 'Escape beat / rhythm', def: 'A beat from a subsidiary pacemaker that fires because the dominant one failed or was blocked. Junctional escape 40–60/min (narrow), ventricular 20–40/min (wide).', see: '#/sandbox/hierarchy' },
  { id: 'fusion', term: 'Fusion beat', def: 'A complex produced by two wavefronts activating the ventricles together (sinus + ventricular focus, sinus + pacing, AV node + accessory pathway). Its shape is intermediate. Fusion beats in a wide-complex tachycardia support VT.', see: '#/dx/monoVT' },
  { id: 'hexaxial', term: 'Hexaxial reference system', def: 'The six frontal-plane limb-lead axes spaced 30° apart: I 0°, II +60°, III +120°, aVF +90°, aVL −30°, aVR −150°.', see: '#/fundamentals/leads' },
  { id: 'injury-current', term: 'Injury current', def: 'Current flowing between injured (partially depolarised, shortened action potential) and healthy myocardium. On the ECG it shifts the ST segment toward the injured region: transmural → ST elevation facing it; subendocardial → ST depression.', see: '#/ischemia' },
  { id: 'intrinsicoid', term: 'R-wave peak time (intrinsicoid deflection)', def: 'Time from QRS onset to the peak of R in a lead facing a ventricle. Prolonged when that ventricle is activated late or is thick (LVH, LBBB in V5–V6; RVH, RBBB in V1).' },
  { id: 'j-point', term: 'J point', def: 'The junction between the end of the QRS and the start of the ST segment; the reference point for measuring ST deviation.' },
  { id: 'ladder', term: 'Ladder diagram', def: 'A schematic of impulse timing through atrium, AV node and ventricle used to reason about conduction, block and re-entry. Every strip in this app can show one.', see: '#/simulator' },
  { id: 'overdrive', term: 'Overdrive suppression', def: 'A pacemaker driven faster than its intrinsic rate is suppressed (Na⁺/K⁺-pump hyperpolarisation) and takes time to recover — the reason escape rhythms start after a pause.', see: '#/sandbox/hierarchy' },
  { id: 'pre-excitation', term: 'Pre-excitation', def: 'Activation of part of the ventricles earlier than via the normal AV node–His route, through an accessory pathway: short PR, delta wave, wide QRS.', see: '#/rhythms/avrt-lab' },
  { id: 'primary-secondary', term: 'Primary vs secondary ST–T change', def: 'Secondary changes result from an abnormal activation sequence (BBB, pacing, pre-excitation, LVH) and are discordant to the QRS. Primary changes arise from altered repolarisation itself (ischaemia, drugs, electrolytes) and are independent of the QRS.' },
  { id: 'qtc', term: 'QTc (corrected QT)', def: 'QT adjusted to a heart rate of 60/min because repolarisation shortens at faster rates. Bazett (QT/√RR) over-corrects at high rates; Fridericia (QT/∛RR), Framingham and Hodges are alternatives.', see: '#/tools/qtc' },
  { id: 'reciprocal', term: 'Reciprocal change', def: 'ST depression in leads facing away from an injured territory — the same injury vector seen from behind. It supports acute occlusion rather than pericarditis or early repolarisation.', see: '#/ischemia' },
  { id: 'reentry', term: 'Re-entry', aka: ['reentry', 'circus movement'], def: 'An impulse circulates around a circuit and re-excites tissue it has already activated. Requires two pathways, unidirectional block and slow enough conduction for the tissue ahead to recover (wavelength < path length).', see: '#/rhythms/avnrt-lab' },
  { id: 'rp', term: 'RP interval (short / long RP)', def: 'Time from the QRS to the next P wave in a tachycardia. Short RP (P just after QRS): typical AVNRT (very short), orthodromic AVRT. Long RP: atrial tachycardia, atypical AVNRT, PJRT.', see: '#/ddx' },
  { id: 'transition', term: 'Transition zone', def: 'The precordial lead where R and S are equal (normally V3–V4). Earlier or later transition reflects rotation, hypertrophy, infarction or lead position.', see: '#/dx/poorR' },
  { id: 'unidirectional-block', term: 'Unidirectional block', def: 'Block in one direction with conduction in the other, usually because one pathway is still refractory when a premature impulse arrives — the trigger event of re-entry.', see: '#/rhythms/avnrt-lab' },
  { id: 'vector-loop', term: 'Vector loop (VCG)', def: 'The path traced by the tip of the heart vector through a beat. Each lead’s waveform is the projection of this loop onto the lead axis.', see: '#/physiology/activation' },
  { id: 'wct', term: 'Wide-complex tachycardia (WCT)', def: 'Tachycardia > 100/min with QRS ≥ 120 ms: VT (most common, especially with structural heart disease), SVT with aberrancy, pre-excited tachycardia, paced or drug/electrolyte-widened rhythms. Treat as VT when uncertain.', see: '#/tools/wct' },
  { id: 'wct-central', term: 'Wilson central terminal', def: 'The average of the right-arm, left-arm and left-leg potentials; the reference ("negative pole") of the unipolar chest leads. Swapping limb cables does not change it — so chest leads are unaffected by limb-lead reversal.', see: '#/tools/leads' },
];
