import { h, p } from '../ui/dom';
import { header, loopBanner, presetPhysio } from '../ui/common';
import { EcgPanel } from '../ui/panel';
import { ALL_DX } from '../content/index';

export function renderHome(root: HTMLElement): () => void {
  root.append(
    header('Physiology-first ECG education', 'Don’t memorise the ECG — predict it', 'Every tracing in this app is generated by a conduction simulator: pacemaker cells, AV-nodal refractoriness, fast and slow pathways, accessory pathways, bundle branches, ventricular mass, ions, drugs and injury currents. Change the physiology and the ECG changes — then explain why.'),
    loopBanner(),
  );
  const panel = new EcgPanel({ heart: true, duration: 8000, layout: 'strips', leads: ['II', 'V1'], showLadder: true, showLabels: true });
  root.append(h('section', { class: 'card' }, h('h2', null, 'Live example: a PAC initiates AV nodal re-entry'), p('A premature atrial beat finds the **fast pathway** still refractory, travels down the **slow pathway** (long PR "jump"), and returns up the recovered fast pathway — a circuit is born. Press **Play** (choose a slow speed, or step ±1 ms) and watch the ladder diagram and the heart.'), panel.el));
  panel.show(presetPhysio('avnrt'));

  const tiles: [string, string, string, string][] = [
    ['A', 'ECG Fundamentals', '#/fundamentals', 'Membrane and action potentials, vectors, the 12 leads, a rotatable activation vector, systematic interpretation.'],
    ['B', 'ECG Physiology', '#/physiology', 'Why each wave exists; activation sequence beat-by-beat; "WHY?" chains for every major finding.'],
    ['3D', '3-D heart & slow-motion ECG', '#/heart3d', 'Rotate the heart, slow time to 0.01×, and watch the wavefront, conduction system and heart vector write each part of the ECG.'],
    ['C', 'ECG Simulator', '#/simulator', 'Every physiological variable on sliders, live 12-lead, ladder diagram and conduction animation.'],
    ['D', 'Rhythm Library', '#/rhythms', 'Sinus, ectopic, atrial, junctional, AVNRT, AVRT, WPW, ventricular and arrest rhythms — each with mechanism, ECG and management.'],
    ['E', 'Conduction Disorders', '#/conduction', 'AV block with selectable level and escape; bundle-branch and fascicular block step-through; pacemakers.'],
    ['F', 'Structural / Physiological', '#/structural', 'LVH, RVH, atrial enlargement, poor R progression, pericarditis, effusion, PE and pulmonary patterns.'],
    ['G', 'Ischaemia & Infarction', '#/ischemia', 'Pick an artery/territory and stage; watch injury currents create ST elevation and reciprocal depression.'],
    ['H', 'Electrolytes & Toxicology', '#/electrolytes', 'Slide K⁺, Ca²⁺, Mg²⁺ continuously; digoxin, β-blockers, CCBs, sodium-channel blockers, QT drugs.'],
    ['I', 'Inherited / Electrical', '#/inherited', 'Long and short QT, Brugada, early repolarisation, and the cellular basis of each.'],
    ['J', 'Arrhythmia Management', '#/management', 'Recognition → mechanism → stable/unstable → immediate/definitive therapy → why it works (and why others don’t).'],
    ['K', 'ACLS ECG Reference', '#/acls', '2025 AHA algorithms: arrest, tachycardia with a pulse, bradycardia with a pulse.'],
    ['L', 'ECG Cases', '#/cases', 'Randomised clinical cases with a stepwise interpretation and full explanation.'],
    ['M', 'ECG Challenge Mode', '#/challenge', 'Five levels: recognition → interpretation → mechanism → electrophysiology → management.'],
    ['N', 'Physiology Sandbox', '#/sandbox', 'Change-one-variable, build-your-own-arrhythmia, adenosine demonstrator, comparisons, axis/P/QRS/ST labs.'],
  ];
  root.append(
    h('h2', null, 'Explore'),
    h('div', { class: 'grid' }, ...tiles.map(([l, t, href, d]) => h('a', { class: 'tile', href }, h('span', { class: 'pill core' }, l), h('h3', null, t), h('p', null, d)))),
    h('section', { class: 'card' }, h('h2', null, 'How the model works'), p('1. **Rhythm engine** — an event-driven graph of excitable elements (sinus node, atria, AV-nodal fast/slow pathways, His bundle, bundle branches, accessory pathway, ventricles, escape foci, pacemaker). Each has a conduction time and refractory period; blocked impulses can conceal; opposite wavefronts collide. Re-entry, Wenckebach, AV dissociation, fusion and adenosine responses emerge rather than being drawn.'), p('2. **Waveform engine** — each activation or repolarisation is a set of dipole components (direction, strength, timing) based on the normal activation sequence (Durrer 1970) and its modification by conduction abnormalities, mass, ions, drugs and injury. Each lead records the projection of the summed heart vector on its axis.'), p(`3. **Content database** — ${ALL_DX.length} diagnosis records with definition, mechanism, ECG findings, WHY-chains, differential, management and verified references (ACC/AHA/HRS, ESC, AHA 2025 ACLS, CCS).`)),
  );
  return () => panel.destroy();
}
