// Named physiological states. A preset never contains a waveform — only the physiology
// (rates, refractory periods, pathways, masses, ions, drugs, injury) from which the
// simulator generates the ECG. Changing any value in the simulator shows why the ECG changes.

import type { PhysioPatch } from './params';

export interface Preset {
  label: string;
  patch: PhysioPatch;
  duration?: number;
  /** Physiology summary shown next to the ECG. */
  physiology: string;
}

const flutterNode = { avnERP: 250, avnDecrement: 60 };
const wenck = { sinusArrhythmia: 0, avnERP: 530, avnDecrement: 300, avnTau: 250, junctionalRate: 36 };
const avnrt = { dualPathway: true, triggerPAC: { at: 1500, coupling: 300, site: 'leftAtrial' as const } };

export const PRESETS: Record<string, Preset> = {
  // ------------------------------------------------------------------ Sinus
  nsr: { label: 'Normal sinus rhythm', patch: {}, physiology: 'Sinus node 72/min; normal AV nodal delay; normal His–Purkinje activation.' },
  sinusBrady: { label: 'Sinus bradycardia', patch: { rhythm: { sinusRate: 46, junctionalRate: 38 } }, physiology: 'Slower phase-4 depolarisation of sinus-node cells (e.g. vagal tone, β-blockade, athletic heart).' },
  sinusTach: { label: 'Sinus tachycardia', patch: { autonomic: 0.35, rhythm: { sinusRate: 92 } }, physiology: 'Sympathetic tone steepens sinus-node phase-4 slope; AV node speeds up too, so PR stays normal or shortens.' },
  sinusArrhythmia: { label: 'Sinus arrhythmia', patch: { age: 22, rhythm: { sinusRate: 64, sinusArrhythmia: 0.2 } }, physiology: 'Respiratory variation in vagal tone modulates the sinus rate (faster on inspiration).' },
  sinusPause: { label: 'Sinus pause', patch: { rhythm: { sinusRate: 70, sinusPause: { at: 3500, duration: 2300 }, junctionalRate: 38 } }, physiology: 'Transient failure of sinus-node discharge; the pause is NOT a multiple of the P–P interval.' },
  sinusArrest: { label: 'Sinus arrest with junctional escape', patch: { rhythm: { sinusRate: 66, sinusPause: { at: 2500, duration: 20000 }, junctionalRate: 44 } }, physiology: 'Sinus node stops discharging; the next pacemaker in the hierarchy (AV junction) escapes at its intrinsic rate.' },
  saExitBlock: { label: 'Sinoatrial exit block (2:1 intermittent)', patch: { rhythm: { sinusRate: 75, saExitBlockEvery: 4, junctionalRate: 38 } }, physiology: 'The sinus node fires on time but an impulse fails to exit into the atria → the pause equals exactly two P–P intervals.' },
  ist: { label: 'Inappropriate sinus tachycardia (resting)', patch: { autonomic: 0.25, rhythm: { sinusRate: 105 } }, physiology: 'Sinus-origin P waves (upright II, III, aVF) at rest >100/min without a secondary cause.' },
  // ------------------------------------------------------------------ Premature beats
  pac: { label: 'Premature atrial complex (PAC)', patch: { rhythm: { pac: { pattern: 'single', coupling: 540, site: 'leftAtrial', every: 5 } } }, physiology: 'An ectopic atrial focus fires early, resets the sinus node → non-compensatory pause.' },
  pacBlocked: { label: 'Non-conducted (blocked) PAC', patch: { rhythm: { pac: { pattern: 'single', coupling: 330, site: 'lowRA', every: 4 } } }, physiology: 'The PAC arrives while the AV node is still refractory: a P wave (often hidden in the T) with no QRS.' },
  pacAberrant: { label: 'PAC with aberrant conduction', patch: { rhythm: { pac: { pattern: 'trigeminy', coupling: 390, site: 'leftAtrial' } } }, physiology: 'Early PAC reaches the right bundle while it is still refractory (long–short cycle) → functional RBBB morphology.' },
  pvc: { label: 'Premature ventricular complex (PVC)', patch: { rhythm: { pvc: { pattern: 'single', coupling: 440, site: 'rvot', retrograde: false, multifocal: false } } }, physiology: 'Ventricular focus fires early; activation spreads cell-to-cell → wide QRS; sinus node not reset → fully compensatory pause.' },
  pvcBigeminy: { label: 'Ventricular bigeminy', patch: { rhythm: { pvc: { pattern: 'bigeminy', coupling: 450, site: 'lvLateral', retrograde: false, multifocal: false } } }, physiology: 'Every sinus beat followed by a PVC at a fixed coupling interval (fixed coupling suggests re-entry or triggered activity).' },
  pvcInterpolated: { label: 'Interpolated PVC', patch: { rhythm: { sinusRate: 50, pvc: { pattern: 'single', coupling: 460, site: 'rvot', retrograde: false, multifocal: false } } }, physiology: 'With slow sinus rates the next sinus impulse arrives after the conduction system has recovered: no pause at all.' },
  pvcCouplet: { label: 'PVC couplets (multifocal)', patch: { rhythm: { pvc: { pattern: 'couplet', coupling: 420, site: 'rvApex', retrograde: false, multifocal: true } } }, physiology: 'Two consecutive ventricular ectopic beats from different foci (different morphologies).' },
  // ------------------------------------------------------------------ Atrial
  focalAT: { label: 'Focal atrial tachycardia', patch: { rhythm: { atrialMechanism: 'focalAT', focalATRate: 165, focalATSite: 'lowRA' } }, physiology: 'A single ectopic atrial focus (automatic, triggered or micro-re-entrant) drives the atria; P morphology depends on the focus (inverted inferior P waves from a low right atrial focus).' },
  atWithBlock: { label: 'Atrial tachycardia with 2:1 block', patch: { drugs: { digoxin: 1.2 }, rhythm: { atrialMechanism: 'focalAT', focalATRate: 180, focalATSite: 'highRA', avnERP: 330 } }, physiology: 'Rapid focal AT + slowed AV-nodal conduction (classically digoxin toxicity: enhanced atrial automaticity + vagotonic AV-nodal effect).' },
  mat: { label: 'Multifocal atrial tachycardia', patch: { rhythm: { atrialMechanism: 'mat', matRate: 118 } }, physiology: '≥3 atrial foci fire irregularly: ≥3 P-wave morphologies, variable PP/PR/RR intervals (often with severe lung disease).' },
  flutter21: { label: 'Atrial flutter with 2:1 conduction', patch: { rhythm: { atrialMechanism: 'flutter', flutterCL: 200, ...flutterNode } }, physiology: 'Macro-re-entry around the tricuspid annulus at ~300/min; the AV node conducts every second flutter wave → ventricular rate ~150.' },
  flutter41: { label: 'Atrial flutter with 4:1 conduction', patch: { rhythm: { atrialMechanism: 'flutter', flutterCL: 200, avnERP: 640, avnDecrement: 40, concealed: false } }, physiology: 'Longer AV-nodal refractoriness (e.g. AV-nodal blocker) lets only every fourth flutter wave through → ~75/min, sawtooth waves clearly visible.' },
  flutterVariable: { label: 'Atrial flutter with variable block', patch: { rhythm: { atrialMechanism: 'flutter', flutterCL: 205, avnERP: 330, avnDecrement: 260, avnTau: 90 } }, physiology: 'AV-nodal refractoriness close to multiples of the flutter cycle + concealed conduction → alternating 2:1, 3:1, 4:1.' },
  af: { label: 'Atrial fibrillation (controlled)', patch: { drugs: { betaBlocker: 0.6 }, rhythm: { atrialMechanism: 'fibrillation', afCoarse: 0.45 } }, physiology: 'Multiple wandering wavelets bombard the AV node at 350–600/min; refractoriness and concealed conduction filter them → irregularly irregular ventricular response.' },
  afRvr: { label: 'Atrial fibrillation with rapid ventricular response', patch: { autonomic: 0.3, rhythm: { atrialMechanism: 'fibrillation', afCoarse: 0.5 } }, physiology: 'Same atrial chaos; with high sympathetic tone the AV node recovers quickly and conducts more impulses.' },
  // ------------------------------------------------------------------ Junctional
  junctionalEscape: { label: 'Junctional escape rhythm', patch: { rhythm: { sinusRate: 34, junctionalRate: 46 } }, physiology: 'The sinus rate falls below the intrinsic junctional rate (40–60/min) → the junction escapes: narrow QRS, retrograde or absent P.' },
  accelJunctional: { label: 'Accelerated junctional rhythm', patch: { rhythm: { sinusRate: 66, junctionalRate: 85, junctionalAccelerated: true } }, physiology: 'Enhanced junctional automaticity (60–100/min; e.g. digoxin, post-cardiac surgery, ischaemia) overtakes the sinus node.' },
  junctionalTach: { label: 'Junctional tachycardia', patch: { rhythm: { sinusRate: 70, junctionalRate: 135, junctionalAccelerated: true } }, physiology: 'Automatic focus in the AV junction >100/min, often with AV (VA) dissociation or retrograde P waves.' },
  // ------------------------------------------------------------------ Re-entrant SVT
  avnrt: { label: 'AV nodal re-entrant tachycardia (typical slow–fast)', patch: { rhythm: avnrt }, physiology: 'Dual AV-nodal pathways. A PAC blocks in the fast pathway (long refractory period), conducts down the slow pathway, then returns up the recovered fast pathway → re-entry.' },
  orthoAvrt: { label: 'Orthodromic AVRT (manifest WPW)', patch: { rhythm: { ap: { present: true, location: 'leftLateral' }, triggerPAC: { at: 1500, coupling: 330, site: 'leftAtrial' } } }, physiology: 'Down the AV node, up the accessory pathway: narrow QRS (normal His–Purkinje activation) with retrograde P after the QRS (RP > 70 ms).' },
  concealedAvrt: { label: 'Orthodromic AVRT (concealed pathway)', patch: { rhythm: { ap: { present: true, location: 'leftLateral', antegrade: false }, triggerPAC: { at: 1500, coupling: 300, site: 'leftAtrial' } } }, physiology: 'A pathway that conducts only retrogradely: normal ECG in sinus rhythm but supports orthodromic AVRT.' },
  antiAvrt: { label: 'Antidromic AVRT', patch: { rhythm: { ap: { present: true, location: 'leftLateral', erp: 180 }, avnERP: 340, triggerPAC: { at: 1500, coupling: 360, site: 'leftAtrial' } } }, physiology: 'Down the accessory pathway, up the AV node: fully pre-excited, wide QRS that can mimic VT.' },
  wpw: { label: 'WPW pattern (sinus rhythm with pre-excitation)', patch: { rhythm: { ap: { present: true, location: 'rightFreeWall' } } }, physiology: 'Sinus impulses reach the ventricles early via a non-decremental accessory pathway: short PR, delta wave, wide QRS (fusion).' },
  preexAf: { label: 'Pre-excited atrial fibrillation', patch: { rhythm: { atrialMechanism: 'fibrillation', ap: { present: true, location: 'leftLateral', erp: 210 } } }, physiology: 'AF wavefronts bypass the filtering AV node through a short-refractory accessory pathway → very fast, irregular, wide and varying QRS complexes.' },
  // ------------------------------------------------------------------ AV block
  avb1: { label: 'First-degree AV block', patch: { rhythm: { avnAHmin: 230 } }, physiology: 'Every P conducts, but slowly: prolonged AV-nodal (usually) or His–Purkinje conduction → PR > 200 ms.' },
  mobitz1: { label: 'Second-degree AV block, Mobitz I (Wenckebach)', patch: { rhythm: wenck }, physiology: 'Decremental AV-nodal conduction: each impulse arrives earlier in the node’s recovery → progressively longer PR until one P fails.' },
  mobitz2: { label: 'Second-degree AV block, Mobitz II', patch: { bundle: 'rbbb', rhythm: { infranodal: 'mobitz2', infranodalRatio: 4 } }, physiology: 'All-or-none failure in diseased His–Purkinje tissue: constant PR, then a sudden non-conducted P (usually with bundle-branch disease).' },
  avb21: { label: '2:1 AV block', patch: { rhythm: { highGrade: 2, sinusRate: 84 } }, physiology: 'Every second P fails. From one strip you cannot tell Mobitz I from II — look for QRS width, response to atropine/exercise, or longer strips.' },
  highGrade: { label: 'High-grade AV block (3:1)', patch: { bundle: 'lafb', rhythm: { highGrade: 3, sinusRate: 90 } }, physiology: 'Two or more consecutive P waves fail to conduct while some still conduct (so not complete block).' },
  chbJunctional: { label: 'Complete heart block — junctional escape', patch: { rhythm: { nodalBlock: 'complete', sinusRate: 82, junctionalRate: 46 } }, physiology: 'Block within the AV node: the junction below the block escapes at 40–60/min with a NARROW QRS (uses the His–Purkinje system).' },
  chbVentricular: { label: 'Complete heart block — ventricular escape', patch: { rhythm: { infranodal: 'complete', sinusRate: 82, ventEscapeRate: 32, ventEscapeSite: 'lvInferobasal' } }, physiology: 'Block below the His bundle: only a ventricular focus can escape — slow (20–40/min) and WIDE (cell-to-cell activation).' },
  // ------------------------------------------------------------------ Intraventricular conduction
  rbbb: { label: 'Right bundle branch block', patch: { bundle: 'rbbb' }, physiology: 'Right bundle blocked: the RV is activated late, cell-to-cell from the LV → late unopposed rightward/anterior forces (rSR′ in V1, wide S in I/V6).' },
  incompleteRbbb: { label: 'Incomplete RBBB', patch: { bundle: 'incompleteRbbb' }, physiology: 'Mild RV conduction delay: rSr′ in V1 with QRS 110–119 ms.' },
  lbbb: { label: 'Left bundle branch block', patch: { bundle: 'lbbb' }, physiology: 'Left bundle blocked: septum activated right→left, LV activated slowly through myocardium → broad notched R in I/aVL/V5–V6, QS/rS in V1, discordant ST–T.' },
  lafb: { label: 'Left anterior fascicular block', patch: { bundle: 'lafb' }, physiology: 'Anterior fascicle blocked: LV activated via the posterior fascicle first (inferior), then superiorly → left axis deviation (−45° to −90°), qR in aVL, rS in II/III/aVF.' },
  lpfb: { label: 'Left posterior fascicular block', patch: { bundle: 'lpfb' }, physiology: 'Posterior fascicle blocked: initial superior activation then inferior-rightward forces → right axis deviation, rS in I, qR in III (diagnosis of exclusion).' },
  bifascicular: { label: 'Bifascicular block (RBBB + LAFB)', patch: { bundle: 'rbbb+lafb' }, physiology: 'Only the left posterior fascicle conducts: RBBB pattern + left axis deviation.' },
  rbbbLpfb: { label: 'Bifascicular block (RBBB + LPFB)', patch: { bundle: 'rbbb+lpfb' }, physiology: 'Only the left anterior fascicle conducts: RBBB pattern + right axis deviation.' },
  ivcd: { label: 'Nonspecific intraventricular conduction delay', patch: { bundle: 'ivcd', lvMass: 1.2 }, physiology: 'Diffusely slowed myocardial conduction (cardiomyopathy, drugs, hyperkalaemia) without a typical bundle-branch pattern.' },
  // ------------------------------------------------------------------ Ventricular
  ventEscape: { label: 'Ventricular escape rhythm', patch: { rhythm: { sinusEnabled: false, junctionalEnabled: false, ventEscapeRate: 34, ventEscapeSite: 'lvApex' } }, physiology: 'No supraventricular or junctional pacemaker: a ventricular focus escapes at 20–40/min.' },
  aivr: { label: 'Accelerated idioventricular rhythm', patch: { rhythm: { sinusRate: 70, ventMechanism: 'aivr', vtRate: 82, vtSite: 'lvApex' } }, physiology: 'Enhanced ventricular automaticity (50–110/min), classically after reperfusion; competes with sinus → fusion beats.' },
  monoVT: { label: 'Monomorphic VT (scar re-entry)', patch: { lvMass: 1.1, ischemia: { territory: 'inferior', stage: 'old', extent: 0.6 }, rhythm: { ventMechanism: 'monoVT', vtRate: 175, vtSite: 'lvInferobasal' } }, physiology: 'Re-entry around/through myocardial scar: each beat follows the same path → identical wide complexes; atria continue independently (AV dissociation).' },
  rvotVT: { label: 'Idiopathic RVOT VT', patch: { age: 32, rhythm: { ventMechanism: 'monoVT', vtRate: 190, vtSite: 'rvot', vtAdenosineSensitive: true } }, physiology: 'cAMP-mediated triggered activity from the RV outflow tract: LBBB-like morphology with an inferior axis; often adenosine-sensitive.' },
  fascicularVT: { label: 'Idiopathic fascicular VT', patch: { age: 28, rhythm: { ventMechanism: 'monoVT', vtRate: 170, vtSite: 'fascicularPosterior' } }, physiology: 'Re-entry involving the left posterior fascicle (verapamil-sensitive): RBBB-like, left superior axis, relatively narrow QRS.' },
  nsvt: { label: 'Non-sustained VT', patch: { rhythm: { ventMechanism: 'monoVT', vtRate: 180, vtSite: 'lvLateral', vtStart: 3500, vtDuration: 1800 } }, physiology: '≥3 consecutive ventricular beats >100/min lasting <30 s.' },
  polyVT: { label: 'Polymorphic VT (normal QT, ischaemic)', patch: { ischemia: { territory: 'anterior', stage: 'stemi', extent: 0.6 }, rhythm: { ventMechanism: 'polyVT', vtRate: 230, vtStart: 2500 } }, physiology: 'Continuously changing activation sequence (functional re-entry), typically acute ischaemia with a normal QT.' },
  torsades: { label: 'Torsades de pointes', patch: { qtcBase: 540, K: 3.1, drugs: { qtDrug: 0.6 }, rhythm: { sinusRate: 55, ventMechanism: 'torsades', vtRate: 240, vtStart: 3500, vtDuration: 5000 } }, physiology: 'Prolonged, heterogeneous repolarisation → early afterdepolarisations (triggered activity) → polymorphic VT whose axis twists around the baseline.' },
  bidirectionalVT: { label: 'Bidirectional VT', patch: { drugs: { digoxin: 1.3 }, rhythm: { ventMechanism: 'bidirectional', vtRate: 150 } }, physiology: 'Alternating origin from two fascicular sites (delayed afterdepolarisations: digoxin toxicity, CPVT) → beat-to-beat axis alternation.' },
  vflutter: { label: 'Ventricular flutter', patch: { rhythm: { ventMechanism: 'vflutter' } }, physiology: 'Single very rapid re-entrant circuit (~250–300/min): sine-wave pattern without distinguishable QRS/T.' },
  vf: { label: 'Ventricular fibrillation', patch: { rhythm: { ventMechanism: 'vf' } }, physiology: 'Multiple chaotic wavelets: no organised ventricular activation, no cardiac output.' },
  asystole: { label: 'Asystole (with P waves: "P-wave asystole")', patch: { rhythm: { ventMechanism: 'asystole', sinusRate: 55 } }, physiology: 'No ventricular electrical activity; atrial activity may persist when the problem is complete AV block without escape.' },
  pea: { label: 'PEA (organised rhythm, no pulse)', patch: { lowVoltage: 0.3, rhythm: { sinusRate: 118 } }, physiology: 'Electrical activity present but no palpable pulse — the ECG alone cannot diagnose PEA; think hypovolaemia, hypoxia, tamponade, tension pneumothorax, PE, H+, K+, toxins.' },
  pulselessVT: { label: 'Pulseless VT', patch: { rhythm: { ventMechanism: 'monoVT', vtRate: 210, vtSite: 'lvApex' } }, physiology: 'Rapid VT without effective output — treated as VF (defibrillation).' },
  // ------------------------------------------------------------------ Pacing
  aai: { label: 'Atrial pacing (AAI)', patch: { rhythm: { sinusRate: 45, pacer: { mode: 'AAI', lowerRate: 70 } } }, physiology: 'Atrial stimulus → atrial capture (paced P) → conduction through the native AV node and His–Purkinje system (narrow QRS).' },
  vvi: { label: 'Ventricular pacing (VVI)', patch: { rhythm: { nodalBlock: 'complete', junctionalEnabled: false, pacer: { mode: 'VVI', lowerRate: 60 } } }, physiology: 'RV-apical stimulus activates the ventricles cell-to-cell from the apex → wide, LBBB-like QRS with superior axis; atria dissociated.' },
  dddTracking: { label: 'Dual-chamber pacing: atrial sensing, ventricular pacing', patch: { rhythm: { sinusRate: 78, nodalBlock: 'complete', junctionalEnabled: false, pacer: { mode: 'DDD', lowerRate: 60, avDelay: 150 } } }, physiology: 'Sinus P waves are sensed and the ventricle is paced after the programmed AV delay (restores AV synchrony in heart block).' },
  dddSequential: { label: 'AV sequential pacing (DDD)', patch: { rhythm: { sinusRate: 42, nodalBlock: 'complete', junctionalEnabled: false, pacer: { mode: 'DDD', lowerRate: 70, avDelay: 170 } } }, physiology: 'Both chambers paced: atrial spike → P, AV delay, ventricular spike → wide QRS.' },
  failCapture: { label: 'Pacemaker failure to capture', patch: { rhythm: { nodalBlock: 'complete', junctionalEnabled: false, ventEscapeRate: 28, pacer: { mode: 'VVI', lowerRate: 60, fault: 'failCapture' } } }, physiology: 'Stimuli delivered but no depolarisation follows (lead dislodgement, high threshold, hyperkalaemia, drugs).' },
  failSense: { label: 'Pacemaker failure to sense (undersensing)', patch: { rhythm: { sinusRate: 78, pacer: { mode: 'VVI', lowerRate: 60, fault: 'failSense' } } }, physiology: 'Device ignores intrinsic beats and paces anyway: spikes at fixed intervals regardless of native QRS (risk of R-on-T).' },
  oversense: { label: 'Pacemaker oversensing (failure to pace)', patch: { rhythm: { nodalBlock: 'complete', junctionalEnabled: false, ventEscapeRate: 30, pacer: { mode: 'VVI', lowerRate: 60, fault: 'oversense' } } }, physiology: 'Device misinterprets noise (myopotentials, T waves, lead fracture) as beats and withholds output → pauses without spikes.' },
  // ------------------------------------------------------------------ Structural
  lvh: { label: 'Left ventricular hypertrophy with strain', patch: { age: 64, lvMass: 1.95, laSize: 1.5, interatrialDelay: 20 }, physiology: 'Thicker LV wall → more myocardium depolarising leftward/posteriorly (tall R in V5–V6, deep S in V1–V2) and slower transmural repolarisation (secondary ST depression/T inversion laterally).' },
  lvhVoltage: { label: 'LVH by voltage (no repolarisation change)', patch: { age: 40, lvMass: 1.45 }, physiology: 'Increased LV mass without strain; voltage criteria are specific but insensitive.' },
  rvh: { label: 'Right ventricular hypertrophy', patch: { rvMass: 3.1, raSize: 1.7, anatomicalAxis: 15 }, physiology: 'RV mass rivals the LV: net forces swing rightward and anterior → right axis deviation, dominant R in V1, RV strain T inversion V1–V3.' },
  rae: { label: 'Right atrial enlargement (P pulmonale)', patch: { raSize: 2.1 }, physiology: 'Larger RA → bigger early (RA) component of the P wave → tall, peaked P (>2.5 mm) in II, III, aVF.' },
  lae: { label: 'Left atrial enlargement (P mitrale)', patch: { laSize: 2, interatrialDelay: 45 }, physiology: 'Larger, later-activated LA → broad (≥120 ms), notched P in II and deep terminal negative P in V1 (LA lies posteriorly).' },
  poorR: { label: 'Poor R-wave progression', patch: { horizontalRotation: -28 }, physiology: 'Clockwise rotation / lead placement / prior anterior infarct → small R waves persisting to V3–V4.' },
  lowVolt: { label: 'Low voltage + electrical alternans (large effusion)', patch: { lowVoltage: 0.72, alternans: 0.8, rhythm: { sinusRate: 112 } }, physiology: 'Fluid between heart and electrodes attenuates voltage; the heart swinging within a large effusion alternates its position beat-to-beat.' },
  // ------------------------------------------------------------------ Ischaemia
  stemiAnterior: { label: 'Anterior STEMI (proximal LAD)', patch: { age: 58, autonomic: 0.2, ischemia: { territory: 'proxLAD', stage: 'stemi', extent: 0.9 } }, physiology: 'Transmural injury of the anterior wall → injury current toward V1–V4, I, aVL; reciprocal ST depression inferiorly.' },
  stemiInferior: { label: 'Inferior STEMI (RCA) with RV involvement', patch: { age: 63, ischemia: { territory: 'proxRCA', stage: 'stemi', extent: 0.9 } }, physiology: 'Injury vector points inferiorly and rightward: STE II, III, aVF (III > II), reciprocal STD I/aVL, STE V1/V4R when the RV is involved.' },
  stemiLateral: { label: 'High lateral STEMI', patch: { ischemia: { territory: 'highLateral', stage: 'stemi', extent: 0.9 } }, physiology: 'Injury vector superior-leftward: STE I, aVL, reciprocal STD III/aVF.' },
  stemiPosterior: { label: 'Posterior STEMI', patch: { ischemia: { territory: 'posterior', stage: 'stemi', extent: 1 } }, physiology: 'Injury vector points posteriorly, AWAY from V1–V3: horizontal ST depression and tall R waves in V1–V3 (the "mirror image").' },
  hyperacute: { label: 'Hyperacute T waves (early LAD occlusion)', patch: { ischemia: { territory: 'anterior', stage: 'hyperacute', extent: 0.9 } }, physiology: 'Earliest phase: broad, tall, symmetric T waves before obvious ST elevation.' },
  evolvingMI: { label: 'Evolving anterior MI (Q waves, T inversion)', patch: { ischemia: { territory: 'anterior', stage: 'evolving', extent: 0.9 } }, physiology: 'Hours later: loss of viable myocardium (Q waves), residual STE, T inversion.' },
  oldInferior: { label: 'Old inferior MI', patch: { ischemia: { territory: 'inferior', stage: 'old', extent: 0.9 } }, physiology: 'Scar no longer generates forces → initial vector points away from the inferior wall → pathological Q in II, III, aVF.' },
  wellens: { label: 'Wellens pattern (reperfused critical LAD)', patch: { ischemia: { territory: 'anterior', stage: 'wellens', extent: 1 } }, physiology: 'Deep symmetric (or biphasic) T inversion in V2–V3 in a pain-free patient after chest pain — critical proximal LAD stenosis.' },
  subendo: { label: 'Diffuse subendocardial ischaemia (STE aVR)', patch: { autonomic: 0.3, ischemia: { territory: 'diffuseSubendo', stage: 'subendocardial', extent: 1 } }, physiology: 'Circumferential subendocardial injury → ST vector toward the cavity: ST elevation in aVR (± V1), diffuse ST depression.' },
  // ------------------------------------------------------------------ Inflammatory / pulmonary
  pericarditis: { label: 'Acute pericarditis (stage 1)', patch: { age: 29, pericarditis: 1, rhythm: { sinusRate: 98 } }, physiology: 'Diffuse epicardial inflammation: ST elevation in most leads (concave), PR depression; reciprocal only in aVR (± V1).' },
  pericarditis3: { label: 'Pericarditis stage 3 (T inversion)', patch: { pericarditis: 3 }, physiology: 'After ST normalises, diffuse T-wave inversion develops.' },
  myocarditis: { label: 'Myocarditis', patch: { age: 25, myocarditis: 0.7, rhythm: { sinusRate: 112, pvc: { pattern: 'random', coupling: 420, site: 'lvLateral', retrograde: false, multifocal: false } } }, physiology: 'Myocyte inflammation/necrosis: sinus tachycardia, nonspecific ST–T changes, ectopy, conduction disease; can mimic STEMI.' },
  pe: { label: 'Acute pulmonary embolism with RV strain', patch: { age: 55, rvStrain: 0.85, bundle: 'incompleteRbbb', raSize: 1.3, rhythm: { sinusRate: 118 } }, physiology: 'Acute RV pressure load: sinus tachycardia, RV conduction delay, right-ward axis, T inversion V1–V4 and III. Most PE ECGs are nonspecific.' },
  pulmHtn: { label: 'Chronic pulmonary hypertension', patch: { rvMass: 2.7, raSize: 1.9, anatomicalAxis: 20 }, physiology: 'Chronic RV pressure overload → RVH pattern with RA enlargement.' },
  copd: { label: 'COPD / emphysema pattern', patch: { age: 72, habitus: 0.62, raSize: 1.7, anatomicalAxis: 25, horizontalRotation: -20, rhythm: { sinusRate: 96 } }, physiology: 'Hyperinflated lungs insulate the heart (low voltage), the heart is vertical and rotated clockwise (right axis, poor R progression), RA enlargement.' },
  // ------------------------------------------------------------------ Electrolytes
  hyperK6: { label: 'Hyperkalaemia (K⁺ ≈ 6.3)', patch: { K: 6.3 }, physiology: 'Faster phase-3 repolarisation (↑IKr conductance) → tall, narrow, peaked T waves.' },
  hyperK7: { label: 'Hyperkalaemia (K⁺ ≈ 7.3)', patch: { K: 7.3 }, physiology: 'Depolarised resting potential inactivates Na⁺ channels → P flattening, PR and QRS prolongation.' },
  hyperK8: { label: 'Hyperkalaemia (K⁺ ≈ 8.3)', patch: { K: 8.3, rhythm: { sinusRate: 64 } }, physiology: 'Severe conduction slowing: absent P waves, very wide QRS merging with T.' },
  hyperK9: { label: 'Hyperkalaemia — sine-wave pattern (K⁺ ≈ 9.2)', patch: { K: 9.2, rhythm: { sinusEnabled: false, junctionalRate: 55 } }, physiology: 'QRS and T fuse into a sine wave; peri-arrest.' },
  hypoK: { label: 'Hypokalaemia (K⁺ ≈ 2.5)', patch: { K: 2.5 }, physiology: 'Reduced IK1/IKr → slower late repolarisation: T flattening, ST depression, prominent U waves, long QU.' },
  hyperCa: { label: 'Hypercalcaemia', patch: { Ca: 3.4 }, physiology: 'Faster plateau (phase 2) → short ST segment and short QT.' },
  hypoCa: { label: 'Hypocalcaemia', patch: { Ca: 1.7 }, physiology: 'Longer plateau (phase 2) → long ST segment, QT prolongation with a normal T wave.' },
  hypoMg: { label: 'Hypomagnesaemia (with hypokalaemia)', patch: { Mg: 0.45, K: 3.2 }, physiology: 'Low Mg²⁺ promotes renal K⁺ loss and prolongs repolarisation; risk of torsades.' },
  hyperMg: { label: 'Marked hypermagnesaemia', patch: { Mg: 3.2, rhythm: { sinusRate: 56 } }, physiology: 'High Mg²⁺ depresses AV-nodal and intraventricular conduction (PR and QRS prolongation) and sinus rate.' },
  // ------------------------------------------------------------------ Drugs
  digoxinEffect: { label: 'Digoxin effect', patch: { drugs: { digoxin: 0.9 }, rhythm: { sinusRate: 62 } }, physiology: 'Shortened ventricular APD + Na⁺/K⁺-ATPase inhibition → "scooped" (sagging) ST depression, short QT; vagotonic AV-nodal slowing.' },
  betaBlocker: { label: 'β-blocker effect / toxicity', patch: { drugs: { betaBlocker: 1 }, rhythm: { sinusRate: 70 } }, physiology: 'Reduced sympathetic If/ICa,L effect: sinus slowing and AV-nodal delay (PR ↑); toxicity → high-grade AV block.' },
  ccbTox: { label: 'Calcium-channel-blocker toxicity', patch: { drugs: { ccb: 1 }, rhythm: { sinusRate: 58, avnERP: 420, avnDecrement: 260, avnTau: 200 } }, physiology: 'L-type Ca²⁺ current drives sinus and AV-nodal cells: blockade → bradycardia and AV block (nodal tissue is Ca²⁺-dependent).' },
  tca: { label: 'Tricyclic antidepressant toxicity', patch: { drugs: { naBlocker: 0.95 }, rhythm: { sinusRate: 124 } }, physiology: 'Fast Na⁺-channel blockade → slower phase 0 → wide QRS with a terminal R in aVR; anticholinergic sinus tachycardia.' },
  flecainide: { label: 'Class IC (flecainide) effect', patch: { drugs: { naBlocker: 0.32 } }, physiology: 'Use-dependent Na⁺-channel block: PR and QRS prolongation, more at faster rates.' },
  qtDrug: { label: 'Drug-induced QT prolongation', patch: { drugs: { qtDrug: 1 }, rhythm: { sinusRate: 60 } }, physiology: 'IKr (hERG) blockade lengthens phase 3 → long QT, broad/notched T; susceptibility to torsades.' },
  amiodarone: { label: 'Amiodarone effect', patch: { drugs: { amiodarone: 1 }, rhythm: { sinusRate: 70 } }, physiology: 'Multichannel block: sinus slowing, PR and QT prolongation (torsades less common than with pure IKr blockers).' },
  // ------------------------------------------------------------------ Inherited / repolarisation
  lqts: { label: 'Long QT syndrome', patch: { age: 19, sex: 'F', qtcBase: 520 }, physiology: 'Genetic loss of repolarising K⁺ current (LQT1/2) or gain of late Na⁺ current (LQT3) → long QT, abnormal T waves.' },
  sqts: { label: 'Short QT syndrome', patch: { age: 24, qtcBase: 305 }, physiology: 'Gain-of-function in repolarising K⁺ channels → very short QT, tall peaked T, short/absent ST.' },
  earlyRepol: { label: 'Early repolarisation pattern', patch: { age: 23, earlyRepol: 1, rhythm: { sinusRate: 56 } }, physiology: 'Prominent epicardial Ito notch → J-point elevation with notch/slur, concave STE in inferolateral leads; usually benign.' },
  brugada1: { label: 'Brugada type 1 pattern', patch: { age: 38, brugada: 1 }, physiology: 'Loss of the RVOT epicardial action-potential dome creates a transmural gradient → coved STE ≥2 mm with negative T in V1–V2.' },
  brugada2: { label: 'Brugada type 2 (saddleback) pattern', patch: { age: 38, brugada: 2 }, physiology: 'Saddleback STE in V1–V2 — suggestive, not diagnostic; may convert to type 1 with Na⁺-channel blockers or fever.' },
  hypothermia: { label: 'Hypothermia (Osborn waves)', patch: { hypothermia: 0.8, noise: 0.35, rhythm: { sinusRate: 82 } }, physiology: 'Cold augments the epicardial Ito notch → J (Osborn) waves; slowed conduction and repolarisation → bradycardia, PR/QRS/QT prolongation.' },
};

export const PRESET_IDS = Object.keys(PRESETS);
